- src/firefly/js/ui/InputField.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/util/Validate.js
Not attached to a UI, yet.  The usage for this component is listed below.
Usage:
```
import {InputField} from 'firefly/ui/InputField.jsx';
import {IntValidator} from 'firefly/util/Validate.js';
<InputField
validator = {IntValidator(0,5)}
tooltip = {'Number of bands'}
label = {'Bands:'}
value = {4}
onChange = {(v) => console.log(v)}
/>
```
> DM-5129: Create InputField for generic use cases.

- src/firefly/js/drawingLayers/StatsPoint.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/ui/ImageSelectPanel.css
- src/firefly/js/visualize/ui/ImageSelectPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanelProp.js
- src/firefly/js/visualize/ui/ImageStatsPopup.jsx
- src/firefly/js/visualize/ui/TestImagePanel.jsx
More updates will be added after tab is made as one member in the field group.
> Dm 5361 imgselpan

- src/firefly/js/visualize/XYPlotCntlr.js
When zooming decimated data, a request should go to the server to fetch zoomed data. If the result is not decimated, further zoom does not require server call, but restoring the original does. Hence we need to remember if the unzoomed data were decimated or not.
> DM-4584 Zoom support for density plot

- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/java/edu/caltech/ipac/util/FileUtil.java
- src/firefly/js/fieldGroup/FieldGroupUtils.js
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanelProp.js
While file is being uploaded, a spinning icon will appears on the right end of the file to indicate it is busy uploading.  This should happen right after you submit the form.
This pull request also fixes the problem where fits file are different once uploaded onto the server.
The upload files will be stored at: /hydra/workarea/fftools/visualize/fits-cache/upload_*
> DM-5638: file upload should display feedback while it's busy uploading.

- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/TableDef.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java
- src/firefly/js/tables/SortInfo.js
- src/firefly/js/tables/TableStore.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/BasicTable.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
You can see this in TablePanel options and fits header dialog.
> DM-5722: Add table client-side sorting

- src/fftools/js/fftools.js
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/visualize/ChartsContainer.jsx
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/XYPlot.jsx
Support expanded view for charts (histogram and plot)
(expand button in the right upper corner of the chart area)
> DM-5760 Charts need to be expandable

- src/firefly/html/css/global.css
- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
Tabs are now resizable.
If not enough space is available ellipsis character will be added at the end.
The tooltip with full name will come up when pointing to the tab.
I have experimented with making Mac style mid string truncation, as discussed [here](http://stackoverflow.com/questions/831552/ellipsis-in-the-middle-of-a-text-mac-style). Unfortunately, the most promising [solution](http://jsfiddle.net/r96vB/1/)  breaks in Firefox (resulting in overlap). It looks like purely CSS solution will ether have partial characters or uneven sizing due to truncated characters. To look good, the original string needs to be manipulated, which requires iterating on it because we can not tell in advance many pixels a string it will take.
> DM-5800 Tab titles need to shrink to accommodate long names

- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
We've been trying to fix it for a while. Still in the latest build, loading table, showing XY plot options, and getting XY data result in 3 base catalog requests. This is an attempt to cure it - only one base catalog request should be made.
- Same key is returned even if the order of the parameters is different
- DECIMATE_INFO is included into SYS_PARAMS
- Also cleaned warnings in the classes I have touched
> DM-6050 table caching optimizations

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/js/api/ApiBuild.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/core/History.js
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableResultsReducer.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/util/WebUtil.js
created TABLE_SORT action to distinguish sorting from filtering.  sorting should not reload xyplot nor catalog overlay.
Also:
- disable history when in api mode.
- ensure tableMeta.source reflects the file on the server.
- fix TablePanelOptions not resetting columns selection.
- remove 'Fits Data' tab when no images available.
- fix 'Coverage' appearing when it should.
> DM-6026: distinguish table sort from filter.

- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/drawingLayers/MarkerToolUI.jsx
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/draw/DrawOp.js
- src/firefly/js/visualize/draw/MarkerObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/draw/ShapeToRegion.js
- src/firefly/js/visualize/iv/ImageViewerLayout.jsx
- src/firefly/js/visualize/region/RegionTask.js
- src/firefly/js/visualize/ui/MarkerDropDownView.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
The implementation includes:
- DrawObj for marker
- Marker dropdown list under the marker icon to show the marker and footprint items (will be added later). 
- Marker drawing layer rendering and operation including action creator and action dispatch functions.
- Marker UI component shown in Drawing Layers popup. 
The implementation set up some work which can be similarly expanded to footprints in the future. 
Maker drawing layer operation:
- select 'Add Marker' from dropdown list to add a  new drawing layer
- click anywhere to locate the newly added marker
- click and drag the mouse  to relocate or resize the marker: 
for relocation: click and drag inside the circle, then drag the mouse.
for resize: click inside the circle, then click and drag the handler to resize 
- label and its …
> Dm 4484 marker tool - create drawing layer for marker tool

- src/firefly/html/css/global.css
- src/firefly/java/edu/caltech/ipac/firefly/data/Alert.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AlertsMonitor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/ui/DropDownContainer.jsx
ticket: https://jira.lsstcorp.org/browse/DM-4591
to test:
rebuild firefly.  restart tomcat.
http://localhost:8080/firefly/
mkdir -p /hydra/alerts/
echo 'some message you want users to see' > /hydra/alerts/notice.txt
within 10 seconds, you should see the notice appears on the drop down menu.
remove the file, and it'll go away.
> DM-4591: GWT conversion: System notifications

- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/XYPlot.jsx
- src/firefly/js/visualize/XYPlotCntlr.js
- src/firefly/js/visualize/XYPlotOptions.jsx
- src/firefly/js/visualize/saga/ChartsSync.js
- Added decimation options to XYPlot options panel when numpoints exceed decimation limit of 5000
- Changed selected series to be on top of data series to speed up selection change in Firefox
- Added legend to decimated plot
- Updated syncCharts saga to ignore sort action when refetching table statistics and histogram data
> DM-5763: XYPlot decimation options

- buildScript/loadScript.js
- buildScript/webpack.config.js
- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/html/firefly.html
- src/firefly/java/edu/caltech/ipac/firefly/server/AlertsMonitor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/core/JsonUtils.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/util/WebUtil.js
- default table cell to render html content as html. 
- fix firefly_loader.js to take into consideration the location of from where it is loaded.
- paging bar show non-ascii characters in irsa's html
> firefly api related issues due to irsa integration.

- src/firefly/config/web.xml
- src/firefly/js/core/FireflyViewer.js
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/InputAreaField.jsx
- src/firefly/js/ui/InputAreaFieldView.jsx
- src/firefly/js/ui/InputField.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/TriViewPanel.jsx
https://jira.lsstcorp.org/browse/DM-5387
- display column's units and descriptions
- add single column filter with auto-correction
- add free-hand filters field with validation and auto-correction
- reset, clear filters as well.
- 'Column' is sticky... scrolling left/right will not affect it.
to test: search catalog, open table options.
> DM-5387: Filter Editor

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiUtilChart.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/visualize/ChartUtil.js
- src/firefly/js/visualize/ChartsCntlr.js
- src/firefly/js/visualize/ChartsContainer.jsx
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/HistogramCntlr.js
- src/firefly/js/visualize/HistogramOptions.jsx
- src/firefly/js/visualize/XYPlotCntlr.js
- src/firefly/js/visualize/XYPlotOptions.jsx
- src/firefly/js/visualize/saga/ChartsSync.js
- Removed chart selection from chart area
- Dropdown for chart selection (can be omitted if single chart type is used)
- Populate current values in chart options
- Support Clear and Reset in chart options
- For tables, connected to charts, if no default parameters are specified, default chart id XY plot with center columns for catalogs or two first numeric columns for other tables.
- Label, matching column expression, and unit, matching table model, are default parameters for both app and api now.
- Cleaned chart API a bit
> DM-6726 Default chart and other optimizations

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiUtilChart.jsx
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/ui/VoSearchPanel.jsx
- src/firefly/js/visualize/ChartUtil.js
- src/firefly/js/visualize/ChartsCntlr.js
- src/firefly/js/visualize/ChartsContainer.jsx
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/HistogramCntlr.js
- src/firefly/js/visualize/HistogramOptions.jsx
- src/firefly/js/visualize/XYPlotCntlr.js
- src/firefly/js/visualize/XYPlotOptions.jsx
- src/firefly/js/visualize/saga/ChartsSync.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
Please, review this branch and let me know. VO search panel will be found in the last right-hand tab on the 'Catalog' search dropdown panel and can be tested by using VO URL value as:  
http://vizier.u-strasbg.fr/viz-bin/votable/-A?-source=J/A+A/402/549
and 'ngc3293' as target.
> DM-6135: vo search simplified panel

- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/visualize/ChartUtil.js
- src/firefly/js/visualize/ChartsCntlr.js
- src/firefly/js/visualize/ChartsContainer.jsx
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/HistogramCntlr.js
- src/firefly/js/visualize/TableStatsCntlr.js
- src/firefly/js/visualize/XYPlot.jsx
- src/firefly/js/visualize/XYPlotCntlr.js
- src/firefly/js/visualize/saga/ChartsSync.js
- Introduced CHART_MOUNTED/CHART_UNMOUNTED actions, deleted SETUP_TBL_TRACKING.
- Reworked the logic for chart related controllers. Chart data are updated only if a chart is mounted, no updates on unmounted charts.
- Now checking if connected table or server parameters have changed before placing server request for data
- Fixed setState calls on unmounted component in ChartContainer.
- Fixed delete button being shown in expanded mode.
> DM-6022 Lazy load related chart data on table data update

- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/TextButton.jsx
- src/firefly/js/visualize/ChartPanel.css
- src/firefly/js/visualize/ChartsCntlr.js
- src/firefly/js/visualize/ChartsTableViewPanel.jsx
- src/firefly/js/visualize/Histogram.jsx
- src/firefly/js/visualize/HistogramOptions.jsx
- src/firefly/js/visualize/XYPlot.jsx
- src/firefly/js/visualize/XYPlotOptions.jsx
This ticket is about making chart options (and chart) display more consistent with that of the table. Chart Options will be displayed over the right side of the table. Overall look of the chart is more similar to the table.
> DM-6288 Chart Options Display

- src/firefly/html/css/global.css
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupWriter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/TableDef.java
- src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java
- src/firefly/js/charts/HistogramCntlr.js
- src/firefly/js/charts/XYPlotCntlr.js
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/core/layout/FireflyLayoutManager.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/saga/ChartsSync.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
https://jira.lsstcorp.org/browse/DM-6909
- fixed above ticket
- added close ('x') button to table options and xyplot options
- fixed table's fixed column's transparency issue
> DM-6909: Filtering from expanded mode cancels expanded mode

- src/fftools/python/display/FireflyClient.py
- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/FireflyViewer.js
- src/firefly/js/core/layout/FireflyLayoutManager.js
- src/firefly/js/drawingLayers/ComputeWebGridData.js
- src/firefly/js/drawingLayers/WebGrid.js
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/PlotImageTask.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
- src/firefly/js/visualize/ui/MouseReadout.jsx
- src/firefly/js/visualize/ui/ThumbnailView.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- src/firefly/js/visualize/ui/VisHeaderView.jsx
- There is no panner for the image (is it missing from the API or is it a bug in calling it?)
- No readout value from thumbnail image
- The top bar readout doesn't include units for the pixel flux
- Clicking on the expand icon deletes the image (in API only)
- Clicking on the expand icon diabled the expand mode of table and xy plot (in API only)
- Image button ask you for a position and displays that, wiping out whatever image brought you to IRSA Viewer in the first place. It should give another tile of the same field, drawn from the selected data set. (IRSAVIewer only)
- grid with label off
- Made loading images from remote consistent
- Started conversion of python API
- fixed range values serialization issue
> DM-6953: fixed mutliple image issues

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupFilter.java
- src/firefly/js/charts/HistogramCntlr.js
- src/firefly/js/charts/XYPlotCntlr.js
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
- src/firefly/js/charts/ui/Histogram.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/ui/ToolbarButton.css
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/ChartsSync.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- Added filter editor to the charts toolbar
- When filtering returns empty data set, server side will return header. Before, it was returning  \Loading-Status = COMPLETED, and TablesCntlr:265 would never activate a new table callback.
- Charts are cleared when table data are being fetched. 
- Label and unit in XYPlotOptions will now get cleared whenever x or y changes
- removed tbl_id from CatalogWatcher and CoverageWatcher's server requests to prevent interference with the table
- changed the order of lat,lon->lon,lat in CoverageWatcher's server request (just for consistency: it was dec, ra before)
> DM-6908 Add filter editor to the chart toolbar

- buildScript/publish-to-github.js
- src/firefly/pom.xml
- create firefly-standalone build, similar to fftools-standalone
> DM-7019: Setup standalone Firefly.

- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupFilter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupReader.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableParser.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/TableDef.java
- src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
https://jira.lsstcorp.org/browse/DM-6952
Table component has couple of problems:
- Scrambled table values after column selection and saving the table, then reset mess up the table. Saving the table and reset makes the table comes back.
- table display no longer redefines column names in the table based on the column label, e.g. "Field Size" instead of "s_fov".
- Downloaded file is not a valid IPAC table.
- Filtering table does not change image overlay or plot until table is saved. At that point, the filtering works, but the plot symbol changes (happens when result is decimated, datapoints > 5000?)
- In Edit Table Options, it's unclear what the reset button resets to.
> DM-6952: Table problems

- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/visualize/PlotImageTask.js
- src/firefly/js/visualize/draw/DrawerComponent.jsx
- src/firefly/js/visualize/iv/EventLayer.jsx
- src/firefly/js/visualize/iv/ImageViewerLayout.jsx
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/ui/DrawLayerPanel.jsx
- Image is coming with one draw layer. (I can delete this draw layer and nothing changes on the image)
- When draw layer is deleted, and no more layers are present, the layers dialog should be closed. (It stays with nothing to
display, you have to click x to close it.)
- After selecting an area in one viewer, I select an area in another viewer, then move the mouse to the first one: 147
ImageViewerLayout.jsx:314 Uncaught TypeError: Cannot read property 'x' of null at ImageViewerLayout.jsx:314 Nothing works after
that. I have to reload.
- Selection appears with an offset, if the page, which contains the viewer is scrolled. (Load the attached script, press
'Start selection tracking' click to select a point, then scroll page a bit down, then click to select another point - it shows
down from …
> DM-7029: fixed some api bugs

- src/firefly/js/api/ApiExpandedView.jsx
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/ui/PopupPanel.jsx
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- Toolbar icon not showing up
- If only one point that is no coverage image (or one table with many records but has the same ra,dec values)
- In laptop screen size, the toolbar is not fully visible, scrolling from left to right only move the background but not the expanded panel.
- Readout is sometimes off the screen
- Expanded then return to normal: zoom is not adjusted correctly
> DM-7001: Gator related bugs and region bug

- src/firefly/js/core/layout/FireflyLayoutManager.js
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
- includes a fix to Target Panel, the automatic active target was not working correctly
> DM-7016: Image loading feedback

- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/ui/DropDownMenu.jsx
- src/firefly/js/ui/PopupPanelHelper.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/PlotImageTask.js
- src/firefly/js/visualize/draw/DrawOp.js
- src/firefly/js/visualize/iv/ImageViewerLayout.jsx
- src/firefly/js/visualize/projection/Projection.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- src/firefly/js/visualize/ui/VisToolbarView.jsx
- image select now comes up a dialog in API mode, coverage update not yet working, see DM-7088
- readded FooprintObj into DrawOp.js
- fixed Multi-table coverage issues: projection not working in utility routines
- dialogs position and mouse move bugs - (In API, it is not possible to drag dialogs)
- The highlight should of catalog or coverage overlay should just change if you are close to the point. For now I am setting it to 20 pixels
-  if marker/footprint overlay is clicked, that doesn't activate the image viewer and doesn't update the layer dialog either.  Fixed problem of Large drawing layers kept plot from becomming active on click
> DM-7068: bug list

- buildScript/depends.gincl
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableParser.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/util/DataGroup.java
- src/firefly/js/charts/HistogramCntlr.js
- src/firefly/js/charts/TableStatsCntlr.js
- src/firefly/js/charts/XYPlotCntlr.js
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/core/layout/FireflyLayoutManager.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableDataReducer.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/ChartsSync.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- disable sorting when content is html
- table options: auto-adjust all column width based on content
- table refractoring..
- renamed a few actions to better reflect what it's doing.
- added TABLE_FILTER
- document sequence of actions where applicable.
- update build script to skip buildClient when possible.
> DM-7055: fix miscellaneous table issues

- README.md
- docs/firefly-api-code-examples.md
- docs/firefly-api-overview.md
- src/firefly/html/demo/ffapi-2images.html
- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiUtilImage.jsx
You can view the documentation in this branch.
> DM-7017 Firefly documentation for Camera team

- src/firefly/html/css/global.css
- src/firefly/js/charts/ui/ColSelectView.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/drawingLayers/DistanceToolUI.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/ui/VoSearchPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/DrawLayerPanel.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/ImageSelectPanel.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
This PR contains the following fix:
- words/label fixed
- links to online-help fixed and icon added.
- order of the icon in the image toolbar to be as before migration
Let me know if you find any inconsistency.
> DM-6947: fixing word typos and help links

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotResultSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResult.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResultParser.java
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/core/layout/FireflyLayoutManager.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/PlotImageTask.js
- src/firefly/js/visualize/iv/ExpandedModeDisplay.jsx
- src/firefly/js/visualize/iv/ImageViewer.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
- src/firefly/js/visualize/ui/MultiImageViewer.jsx
- src/firefly/js/visualize/ui/MultiImageViewerView.jsx
- src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- images cannot be remove, but in expanded mode, it can.
- plot group fails are not failing correctly, no message shown
- When a non-meta table is selected, images are shown, but not the toolbar.
- After table is removed, images are still there and other problem with removing tables.
- Firefly viewer uses 'triViewImages’ viewer_id while api has no viewer_id. as a result, images loaded by api will be lost once table or other searched data are returned. (I think this is fixed, but I may not understand it)
- Catalog or Grid overlay are drawn outside of the images.
> DM-6473: Fixes mostly related to image view of the meta data via table

- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
https://jira.lsstcorp.org/browse/DM-7155
from ticket:
> Sort a table first. Then using image selection tool, select an area, then filter: the filter fails. Points are outside the selected area.
PS.. Title of ticket mentioned that is was wrong for XyPlot as well.  That is NOT true.  XyPlot works fine.
> DM-7155: Filtering from image is wrong on sorted tables.

- src/firefly/java/edu/caltech/ipac/astro/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/astro/IpacTableReader.java
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupReader.java
- src/firefly/java/edu/caltech/ipac/util/DataGroup.java
- src/firefly/java/edu/caltech/ipac/util/DataType.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/ui/SearchPanel.jsx
- Add tbl_index to table request indicate which table to display if it's a multi-table file.
- Add default behavior for column with array type to display the array's data-type and length.
https://jira.lsstcorp.org/browse/DM-7149
To test:
Follow above link to download table.fits file.
Using Firefly's "Data Sets..." sample dialog, upload the sample file to view fits table data.
Use the Table Index field to select which table to view.  There should be 4 tables in this file.
> DM-7149: Add more support for FITS table display

- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/util/DataObjectUtil.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
Use the original data whenever available.
For expressions, calculate precision based on min-max difference.
> DM-6920 Yellow dot highlight precision

- src/firefly/html/demo/ffapi-2images.html
- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/drawingLayers/RegionPlot.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/draw/ShapeHighlight.js
- src/firefly/js/visualize/region/RegionDrawer.js
- src/firefly/js/visualize/region/RegionFactory.js
- src/firefly/test/edu/caltech/ipac/visualize/test5.reg
fix the following region bugs, 
1. set the default coordinate system to be 'PHYSICAL' (fixed in DM-5192-PyAPI)
2. region defined with 'PHYSICAL' or  'IMAGE' is treated as 'IMAGE' coordinate
3 . create region layer after the image with plotId finishes loading  - changing the region description parsing which needs plotId info to be done after after the region layer is created (fixed in DM-7088)
4. select the region from any region layer
5. log region parsing error in the console. 
test: 
start firefly demo file, 
localhost:8080/firefly/demo/ffapi-highlevel-test.html
- click on 'test open' to get the Firefly app
- go to the page bottom for 'region test'
- test for bug 1, click on 'Create Region Layer' (for layer Region_Plot_1), the top two regions with no coordinate system specified  shown …
> DM-7147: fix region bugs as listed in DM-7147.

- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
Made resizable tabs an option (most cases, we don't need tabs to resize)
When tabs are resizable, multiple tabs will have the same size.
> DM-6910 Tab panel issues

- src/firefly/js/drawingLayers/NorthUpCompass.js
- src/firefly/js/visualize/draw/DirectionArrowDrawObj.js
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
I've removed white background on the text labels and and made color the same as the overlay itself.
Please check that it is the case for the overlays in general (grid, markers, distance tool, compass).
Thanks!
> DM-6950: improve overlay labels

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/saga/ImagePlotter.js
- always does single mode when the is only one plot
- better use of expanded mode toolbar space using flex layout
- fixed: color change failing when mask is plotted
> DM-7275: fixed expanded modes display issues

- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/visualize/saga/CoverageWatcher.js
- reset options based on original settings.
- do not reload document unless it is needed.
- do not redraw coverage with table is sorted
Reset should work like it did before.
Show units, show filters, column selections, and filters will be reset to what it was originally when table was loaded.  On table sort, coverage image will not reset.  However, it will be reset on filters changed.  This is how it is in production as well.
> DM-7239: Table reset does not reset to original settings.

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/XYPlotCntlr.js
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- Fixed log scale issue (when minimum value is close to 0
- Added more support for error conditions (still no way to catch errors in render)
- More validation for log scale in XYOptions
- Trey's changes for MULTI_VALUE_CHANGE - field reducer is now called once on form submit
> DM-7317 Log scale doesn't work with sample table attached

- src/firefly/html/css/global.css
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
- fix hidden column problem
- TabPanel
- fix annoying gap between tabs and content
- fix cursor shows click-able at edges, but nothing happens when clicked
> DM-7280: display wrong data when 'hidden' columns are in front of visible ones

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/StatisticsProcessor.java
- src/firefly/js/api/ApiUtilChart.jsx
- src/firefly/js/charts/HistogramCntlr.js
- src/firefly/js/charts/XYPlotCntlr.js
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/visualize/saga/ChartsSync.js
- Fixed truncated columns in table statistics processor (when col name is long)
- Fixed NaN related issues in histogram processor
- Reset in xyplot or histogram options resets options to the default.
How do we know the options are the default?
- Chart is created from the menu drop down, options selected there are "the default"
- Default chart, created with the default parameters
- Chart is created via API, options passed via the API function are "the default"
> DM-6289 Chart options - reset to default

- src/firefly/python/display/FireflyClient.py
Document Python API in 'docstrings' by following 'LSST DM Developer Guide' for documenting Python code. 
A simple Sphinx setup has been used to convert the implementation to HTML page. More detail format verification will be made after LSST documentation tool for Python is released.
> DM-7223: Python API using reStructured and numpydoc format.

- src/firefly/js/charts/ui/ColSelectView.jsx
Please, review and let me know.
I've hidden the description column in xy-plot selecting column dialog (same behavior as in table component) when no description available.
This is the case in Gator/Atlas, which both use upload table mechanism in the API. In OPS, before migration, no description is shown in the table/xy-plot component.
To test, upload any ipac table catalog, this is not getting any description from the ipac table header, so nothing should be shown.
> DM-7277: complete commit and fix

- src/firefly/html/lc.html
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/core/FireflyViewer.js
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/templates/fireflyviewer/FireflyLayoutManager.js
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/ImageSelectDropdown.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/ui/panel/DockLayoutPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- introduce template into firefly entry point.
- create light curve as a template.
- create viewer, controller, and results component for light curve.
- these components are place holders and are not fully implemented.
- create upload form for use during development.
To view light curver viewer use lc.html:  ie. http://localhost:8080/firefly/lc.html
Upload a table to see the results.
> DM-7406: Create Light curve skeleton app

- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablesContainer.jsx
https://jira.lsstcorp.org/browse/DM-7448
Reset button does not work when options are set explicitly.
This the demo page below, the first table has showUnits and showFilters set to true.  It used to work reset properly.  
http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
> DM-7448: Table reset unset option 'Show unit' initially set

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
Provide help_id option to define help anchor string.
If firefly is built locally, an example can be found in the first chart at
http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
> DM-7460 No help link/anchor option for XY-Plot

- buildScript/depends.gincl
- buildScript/gwt.gincl
- buildScript/gwt_webapp.gincl
- src/firefly/config/web.xml
- src/firefly/jsdoc_config.json
https://jira.lsstcorp.org/browse/DM-7511
- Added buildJsDoc task to gradle build system to generate JS docs.
- Changed theme to match firefly's L&F.
- This is open for discussion.  I am not adamant about this.
To build war plus JS docs and deploy it, use
`gradle :firefly:buildAllAndDeploy`  or `gradle :fi:bAA`
To see deployed JS docs, http://localhost:8080/firefly/jsdoc/
> DM-7511: add JSDoc generation into build system.

- .eslintrc
- package.json
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/DrawLayerCntlr.js
Please take a look at .eslintrc file.  It lists a set of rules.  Only parameter is required, the rest rules are set to warning (0:off, 1:warning, 2:true).
> Dm 7508 eslint rules

- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/iv/PlotTitle.css
Please, have a look to this change. The ticket suppose to solve the consistency with the rest of the color to be more consistent and readable. Blue is not consistent with the rest (grey) and the zoom level is not readable. Sometimes the inline tool icons (top right-hand side) are not apparent enough.
This is step 1 change: making the background to be the same grey color on image viewer left and right, and plot title black, zoom level label red.
Another proposed solution is step 2:  black font on white background if step 1 doesn't solve the issue.
Thanks.
> DM-7543: color backgrnd image viewer inline tool change

- buildScript/webpack.config.js
- package.json
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/SelectInfo.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/ui/panel/TabPanel.jsx
https://jira.lsstcorp.org/browse/DM-7520
See ticket for steps to duplicate bug.
- fixed TabPanel onSelect called after tab has been removed.
also:  minor jsdoc errors and build script updates.
> DM-7520: XY plot is not shown after closing one of the catalog tab

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/drawingLayers/RegionPlot.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/draw/DrawOp.js
- src/firefly/js/visualize/draw/Drawer.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/draw/ShapeHighlight.js
- src/firefly/js/visualize/region/RegionFactory.js
- src/firefly/js/visualize/region/RegionFileUploadView.jsx
- src/firefly/js/visualize/region/RegionTask.js
- src/firefly/js/visualize/region/RegionUtil.js
- src/firefly/jsdoc_config.json
Implementation: 
- create region selection dispatch function, dispatchSelectRegion.
- create status to record the text description of selected region and provide function to access the status. 
- add selectMode parameter into dispatchCreateRegionLayer & dispatchAddRegionEntry functions which defines the rendering style, rendering color and line width for the selected region. 5 types of rendering styles are defined, 'UprightBox', 'DottedOverlay', 'SolidOverlay', 'DottedReplace' and 'SolidReplace'. 
Testing: 
- from localhost:8080/firefly/demo/ffapi-highlevel-test.html, 
1. click 'test open'
2. find color,  line width text boxes and rendering style dropdown list next to 'Create Region Layer' to set the display features for showing the selected region, then click 'Create Region Layer' to …
> DM-7462: create dispatch function, rendering style and stored status  for region selection

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedCurveProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedLightCurve.java
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/test/edu/caltech/ipac/firefly/server/query/LightCurveProcessorTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/PhaseFoldedLightCurveTest.java
Please review this PR which make use of the phase folded code, updating phase folded processor and tests.
To see in action, go to 
http://localhost:8080/firefly/firefly-dev.html
And click 'compute periodogram' tab.
Change period and phase fold.
The phase folded request built can be seen here: js/ui/TestQueriesPanel.jsx:142
The phase column displays '0.0' which is not enough (see ticket [DM-7593])
> DM-7593: use phase folded code in processor and update test

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/drawingLayers/ActiveTarget.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/draw/DrawLayerFactory.js
- src/firefly/js/visualize/draw/DrawingDef.js
- src/firefly/js/visualize/draw/PointDataObj.js
Now the api should be able to set the size, color, shape of the active target and catalog via api.
- only CATALOG_TYPE and ACTIVE_TARGET_TYPE are currently supported.
- jsdocs in ApiUtilImage.jsx, line 63
- framework can be used to add more options, just have to be supported by the drawing layer.
To test uncomment `ffapi-highlevel-test.html`, line 198 and 199.
> DM-6656: give options to set the color, symbol and size of some draw layers thorough the api

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedLightCurve.java
https://jira.lsstcorp.org/browse/DM-7594
Also, add description meta to that column.
> DM-7594: Display phase column with 8 decimal places precision

- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/DefaultApiReadout.jsx
- src/firefly/js/visualize/ui/MouseReadout.jsx
- src/firefly/js/visualize/ui/PopupMouseReadoutFull.jsx
- src/firefly/js/visualize/ui/PopupMouseReadoutMinimal.jsx
- Mouse readout not longer will randomly switch to the bigger one.
- The mouse readout will not blink as you go in and out of an image
- Clean up flow of mouse readout saga
- MouseReadoutWatch includes description of empty flux fields
- Readout ui layout has been cleaned up: minimal is smaller, three color is tighter, standard api is cleaner
- Readout now correctly shows empty flux display
_Test with_: gator, firefly viewer and ffapi-highlevel-test.html
> DM-7273: Mouse readout cleanup and bug fixes

- src/firefly/js/ui/CatalogSearchMethodType.jsx
Pre-calculated polygon area when this spatial search method is selected in the catalog search.
It will take part of the image and calculate the x,y pairs from active plot.
Please review it.
> DM-7487: add polygon values from active image in catalog search

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PlotServUtils.java
- src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/draw/DirectionArrowDrawObj.js
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
- src/firefly/js/visualize/region/RegionFactory.js
Fixing method: 
Marker size is represented by a small pure number (magnitude of thousandth) in term of world coordinate (J2000). World coordinate is a hint to set the size value with 'degree' unit, otherwise the size value was treated with 'pixel' unit, too small to be shown in the PNG.
> DM-6980:  Fix PNG creation for marker

- src/firefly/js/visualize/ui/DrawLayerPanel.jsx
Make the tile on the drawing layer dialog to be the same as the image title from either image or catalog search.
> DM-7116: change the title of drawing layer dialog based on the title of the active image

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
- src/firefly/js/visualize/region/RegionFactory.js
Fixed the parsing errors which happen when 
- semicolon, space, or '#' is contained in the values of text property.
- the text (or font) property is not properly quoted with " or ' or {}. 
Test sample, 
upload firefly_test_data/region-test-files/regionText.reg
or 
visit localhost:8080/demo/ffapi-highlevel-test.html by clicking 'test-open' and 'create_region_layer'
> DM-7665: fixed the region parsing issue regarding region used separators contained in some property values

- .eslintrc
- src/firefly/java/edu/caltech/ipac/visualize/plot/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/FlipXY.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageMask.java
- src/firefly/js/visualize/ui/StretchDropDownView.jsx
Please test it and let me know if there is still anything wrong.
Thanks!
> Dm 4127 mask over lay

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx
- src/firefly/js/visualize/WebPlotRequest.js
- Add ibe server request retrieve the images.
- Fixed the makeProcessorRequest bug and few eslint errors in WebPLotRequest.
> DM-7164-LCviewer-ibe-preprocessor

- src/firefly/html/css/global.css
- src/firefly/js/charts/ui/ChartPanel.css
- src/firefly/js/charts/ui/ChartsTableViewPanel.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
https://jira.lsstcorp.org/browse/DM-7700
This is only a problem in Atlas which makes it a little harder to test.
Build locally then deploy it on irsawebdev1 or proxy irsawebdev1 to your localhost if you want to test it.
> DM-7700: Atlas table filtering doesn't work properly

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/RegionPng.java
- src/firefly/java/edu/caltech/ipac/visualize/draw/StringShape.java
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/visualize/draw/DirectionArrowDrawObj.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/draw/ShapeToRegion.js
- src/firefly/js/visualize/region/Region.js
- src/firefly/js/visualize/region/RegionDescription.js
The rendering of the region associated text was missing in the PNG. 
This issue is fixed by creating a separate text region  with the location calculated at JS parts, the text value and font defined in the original region, and sending the created text regions as well as the original regions to the server for producing the PNG.
> DM-7765 Render the text defined as the 'text' property value of a region on PNG

- src/firefly/java/edu/caltech/ipac/visualize/plot/Geom.java
Emmanuel,
Can you please take a look and let me know if you still see problems?
Thanks!
> DM-7336:fixed the algorithm bug in Geom.java

- docs/firefly-api-overview.md
- src/firefly/html/demo/ffapi-2images.html
- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiBuild.js
- src/firefly/js/charts/ui/Histogram.jsx
Exposed histogram to API, added documentation, fixed histogram bugs:
- y log scale
- tooltip misaligned with bin boundaries
Testing:
http://localhost:8080/firefly/demo/ffapi-highlevel-charttest.html
http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
http://localhost:8080/firefly/jsdoc/firefly.ui.Histogram.html
> Histogram doc and bug fixes

- src/firefly/java/edu/caltech/ipac/firefly/core/ClientEventQueue.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/js/core/messaging/WebSocketClient.js
- src/firefly/js/util/WebUtil.js
- src/firefly/python/display/firefly_client.py
https://jira.lsstcorp.org/browse/DM-7825
We were using cookies to pass websocket connection info to the server.  This approach does not work in and embedded mode, ie. Gator.
I've converted to use custom http headers instead.  This also affects python api.  I've modified the code to reflect the changes.
The above url describe how to reproduce the problem.  This change fixed the above problem and should not have any regression issue.  Please confirm.
> DM-7825: Use custom http headers to pass ws connection info

- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/js/charts/ui/Histogram.jsx
Display multiple histograms (not connected to table). 
Test URL: http://localhost:8080/firefly/demo/ffapi-highlevel-charttest.html
> [DM-7921] Multiple series histogram display (not connected to table)

- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/InputField.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
Fixed the bugs for catalog search constraints, the bugs are: 
- the constraint rendering became empty when 'enter' key is pressed or the focus on the cell is moved away. 
- the state regarding the search constraints is not updated when the constraint changes. 
Note:
If any entered column constraint is checked to be invalid, the error message will be shown in a popup box when the 'search' button is clicked and the search will stop.
> DM-7918 Constraint column render error and the state update error when column constraint changes 

- src/firefly/html/firefly.html
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/ui/ImageSelectPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanelProp.js
- src/firefly/js/visualize/ui/ImageSelectPanelReducer.js
fixing the circles was trivial and did not really need a ticket.  Most of this ticket has the code to reorder the images tabs in the image select panel
> DM-7986: fix circles connecting & add way to reorder image tabs

- src/firefly/html/firefly.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/InputField.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
Build LSST catalog search panel including two tabs, 'Search Catalogs' and 'Load Catalog'
- add 'LSST Catalogs' to the firefly menu. 
- create LSST catalog search panel, 
. reuse 'CatalogConstraintPanel' (used by IRSA catalog search form) component.
. making improvement on 'CatalogConstraintPanel' including 
validation of column search constraints. 
storing and restoring of column selection and constraint string. 
. incorporating catalog spatial search features made in DM-7995.
. For 'Load Catalog', redisplay the filename of last uploaded file by button 'Choose File'. 
(this feature is applied to all cases which use FileUpload and keep the uploaded filename) 
Test: 
- start firefly localhost:8080/firefly
- select 'LSST Catalogs' and the search panel is started
- select LSST catalog, either …
> DM-7761 Build LSST Catalog search form using the components from IRSA catalog search form

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/java/edu/caltech/ipac/util/download/FileData.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/core/MasterSaga.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/fieldGroup/FieldGroupUtils.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/iv/TileDrawer.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ZoomButton.jsx
To test it,
Check it out and build. 
Start firefly view, then enter the following info based on the method:
Cone search:  
UserTargetPt: 9.49,-1.24
Radius: 0.01 degree
Box Search:
UserTargetPt: 9.49,-1.24
Radius: 0.01 degree
Elliptical Search:
9.49, -1.24
Radius: 0.01 degree
Polygon Search:
9.5  -1.2, 9.6 -1.24, 9.4 -1.24
Known issue:
When the degree unit is selected, it still passed as arcsec 
When all columns are selected by default, it passed null
Suggest:
UI passes the unit, the server side handles the conversion based on the search methods.
Thanks for reviewing it.
[11/1/16 at 5:37PM]
After discussing with Cindy and after her changes, the following changes are made:
1.  If the UI sends a null for selcol, all columns are selected.
2.  For radius UI, he "degree" unit is used  The …
> DM-8010: Add LSSTMetaSearch and LSSTCatalogSearch processors

- src/firefly/test/edu/caltech/ipac/visualize/plot/CropTest.java
This is the unit test class for Crop.java.  The testing data is located in the firefly_test_data/package.
The end to end test is added.  The header and data are examined.  To test it, please check this branch out and also go to https://github.com/lsst/firefly_test_data to checkout the data branch 
"DM-7782-UnitTestForCrop".
The coverage is about 60%.  The low coverage is due to the fact that Crop.java is dealing with different bitpix. The current test only has bitpix=-32.
> DM-7782: add unit test for Crop class

- src/firefly/html/firefly-dev.html
- src/firefly/html/firefly.html
- src/firefly/html/lc.html
- src/firefly/html/lsst-api-triview.html
- src/firefly/html/lsst-pdac-triview.html
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/MenuItemKeys.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanelProp.js
- src/firefly/js/visualize/ui/ImageSelectPanelReducer.js
- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
- added lsst-api-triview.html for api launch with afw.display
- added lsst-pdac-triview.html for pdac entry point
- PROCESS_SCROLL action now has a way to turn off bounds checking
The html files might eventually be moved to an lsst repository
> DM-8176: tweeks for lsst entry points and options

- src/firefly/config/web.xml
- src/firefly/js/core/History.js
- src/firefly/js/visualize/task/PlotImageTask.js
https://jira.lsstcorp.org/browse/DM-8162
As described by the title, allow plotImage to be called via url.
In the above link, you'll find more information on how to construct the url with one sample test url.
This PR is to merge into 'rc' branch.  Once it's in rc, we will merge rc back into dev.
> DM-8162: Call IRSAViewer to display images directly via URL

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
the development includes: 
- add image tables, Science_Ccd_Exposure, DeepCoadd into LSST catalog search panel. 
- search and display DD table for image tables on LSSTMetaSearch 
- show image tables on tri-view on LSSTCatalogSearch
- fix spatial data unit shown in catalog search title. 
- fix the bug in generating query parameters for LSSTMetaSearch.
> DM-8245 Add image tables into LSST catalog search panel.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/js/charts/dataTypes/HistogramCDT.js
- src/firefly/js/charts/ui/Histogram.jsx
- pass 14 sig digits, when creating histogram
- collapse bins if overlapping bins are passed to the client because of precision loss
- use column chart if all bins are of 0 width
- cleanup most warnings in HistogramProcessor.java
- use long to store number of points in a bin
To test, use firefly_test_data/DAXTestData/RunDeepForcedSource_limit100.csv
The following columns are long: id, coordHtmId20, objectId, exposureId.
(The display should be fine – compared to dev version – even though the precision can be reduced with respect to the original.) 
The inherent limitation is that Javascript numbers are 64-bit float point, so the 63 bits in Long are converted to 52 bits of Double, hence the precision is inevitably lost if a number is long enough. Even if we find a way to handle arbitrary …
> dm-8216 Histogram for long values

- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
Although offset seems to work, minor issues have been fixed in this PR.
Fix min/max period for the slider and phase axis max to 2.
Another bug has been raised DM-8261 to be fixed.
> DM-7969: Offset time input field already introduced. 

- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
Fixed the URL parsing when relative URL is found in master catalog table. In order to test, you need to build FF and  redeploy the branch built. 
Then go to 'catalog' search and check that 'info' and inner link in description are ok.
> DM-6617: fix parsing info link

- src/firefly/java/edu/caltech/ipac/firefly/core/background/BackgroundStatus.java
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerEvent.java
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/FluxAction.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventQueue.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/BackgroundEnv.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PushCommands.java
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/AppDataReducers.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableResultsReducer.js
- src/firefly/js/ui/panel/TabPanel.jsx
https://jira.lsstcorp.org/browse/DM-8179
Also, refactor AppDataCntlr.js
Background jobs are saved based on a userKey cookie which remained the same unless inactive for more than 2 weeks.
To test this, starts one or more downloads.
The downloads should be visible in other firefly instances of the same browser.
It should also remain after you reload the application or quit and come back some time later.
Also, cancel and remove are reflected in all instances as well.
> DM-8179: Preserve background jobs and statuses beyond a browser session.

- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/RangeSliderView.jsx
- src/firefly/js/ui/rc-slider.css
The implementation mainly, 
- add 2D chart on the client side phase folding dialog and the plot changes as any of the phase folding parameters (time column, flux column, zero time point, period) changes.
- update the parameter items in the parameter setting dialog. 
Test:
- localhost:8080/firefly/lc.html
- open 'lc_raw.tbl' from 'Raw Table', click 'search'
- select tab 'Upload/Phase folding' and click button 'Phase Folding'
- experiment the setting of all entries and move slider to set 'period', the plot will be updated as any of the parameter (except Flux error column)  changes 
- click button 'Phase Folded Table' to close the dialog and a table with phase column is created (or updated) based on current setting of period, time column and zero point time. 
Note:
- The time and flux column …
> DM-8006 Add xy chart to phase folding parameter setting panel using Highcharts

- src/firefly/html/lsst-api-triview.html
- src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/URLFileRetriever.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/data/ServerRequest.js
- src/firefly/js/metaConvert/ConverterFactory.js
- src/firefly/js/metaConvert/LsstSdssRequestList.js
- src/firefly/js/metaConvert/TwoMassRequestList.js
- src/firefly/js/metaConvert/WiseRequestList.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/iv/ImageViewerStatus.jsx
- src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- Now show LSST SDSS images for ccd (coadd does not yet work)
- added a little more logging and URLDownload and fixed logging bug
- add more control of URL downloads in WebPlotRequest
> DM-8288: Add support to show LSST SDSS images in triview

- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx
In LC viewer application, magnitudes should look flipped automatically when they get plotted. Please, check that when raw and phase folded table are displayed, the fluxes are in reverse order Y-axis. thanks.
> DM-7967: reverse axis for magnitude

- config/mail.prop
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerEvent.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackageMaster.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/Packager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingController.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/BackgroundEnv.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/rpc/SearchServicesJson.js
https://jira.lsstcorp.org/browse/DM-8182
- email notification is working properly
- it should also resend email when the email field has changed.
To test:
- goto: firefly/lc.html
- download something.
- when email is given, you should receive email notification when job completes.  you should also see 'Email notification sent' in the job status as well.
- bring up background monitor and enter a different email.  you should get email notifications for all completed jobs.
> DM-8182:  send email when package successfully completed.

- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
I've added a saga that will listen to table_highlight on peak and periodogram table. Every time a user click on the plot or table, the saga will get the period out of the table and pre-filled the period input field in phase folded panel.
> DM-7964: get period from table/plot

- src/firefly/js/charts/ChartDataType.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/HistogramCDT.js
- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/charts/ui/ChartPanel.jsx
This pull request is for handling server error in a chart. Prior to it, loading message would not disappear when an error occurred.
The test relies on a bug in 'Clear' options behavior for histogram. When 'Clear' is pressed, all fields histogram options are cleared, including 'Column or expression value'. If options are applied at this point, an empty column is sent to the server, resulting in an error.
> DM-8214 - handling server errors in charts

- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
The development fixed the following issues:
1.Catalog polygon search doesn't work (wrong parameters passed)
2.Can not switch to catalog search after image search fails on creating the plot.
3.update the title of searched image table
> DM-8449 resolve LSST catalog search panel running bugs

- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/ui/MultiImageViewer.jsx
This development intends to solve the issue that no image is highlighted on the coverage map and FITS data panel while clicking back and forth among the image tabs on the triview. The image handling toolbar is  shown properly based on the selected image tab and its associated active image. 
test: 
localhost:8080/firefly/lsst-pdac-triview.html
image->deep source->target: 0, -1, search type: enclosed, search region size: 3600 arcsec
click 'External images' on top of the triview to get two images rendered in FITS Data panel, 
external images -> wise, create new plot, target: m31, search, 
external images ->wise, create new plot, target:  m51, search
click among all three image tabs, and test.
> DM-8543 Activate the image inside the multi-image viewer without clicking the image iteself

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
DM-7784-7963
* LC image retrieve use url instead of ibe for general purpose LCViewer
* Add user input image cutout size in Phase Fold Panel.
> DM-7784-7963

- config/app.config
- config/log4j-test.properties
- config/logging-test.properties
- src/firefly/config/app-test.prop
- src/firefly/config/app.prop
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/LightCurveProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PeriodogramAPIRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedCurveProcessor.java
- src/firefly/java/edu/caltech/ipac/util/AppProperties.java
- src/firefly/java/edu/caltech/ipac/util/ClientLog.java
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/LightCurveProcessorTest.java
- src/firefly/test/edu/caltech/ipac/firefly/util/PostDownloadTest.java
- src/firefly/test/edu/caltech/ipac/firefly/util/VoUtilsTest.java
- src/firefly/test/edu/caltech/ipac/visualize/FootprintFactoryTest.java
- src/firefly/test/edu/caltech/ipac/visualize/RegionLoaderTest.java
- src/firefly/test/edu/caltech/ipac/visualize/plot/HistogramTest.java
This PR is about hooking up the IRSA API and adapt the UI form to get the information and compute the periodogram. I have included also 2 more properties in `app.config` that control the exposed API parameters and the url.
I've also changed couple of classes to be able to control the level of the log4j and logging when running unit test. Unit test that extends from a `ConfigTest` class will load properties to set log levels and app configuration properties in runtime.
See more detail in the ticket for the API reference.
In order to test: bring the LC app and load a raw table. Then go to periodogram tab and play around. Every change should give different periodogram profile.
> DM-7829: adapt LC viewer to use IRSA api

- package.json
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchRequestUtils.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYWithErrorsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/chartTypes/ScatterTblView.jsx
- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/charts/highcharts/XYErrorBars.js
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
In this ticket, the option is provided to enter a symmetric error  for X and Y column. Asymmetric errors will be handled by a separate ticket.
A column or an expression can be entered next to X and Y field in plot options.
Good test is WISE color-color plots: use w[1,2,3,4]sigmpro as an uncertainty for w[1,2,3,4]mpro. 
If less than 20 points are displayed, the error bar will have whiskers, otherwise no whiskers.
To test, bring up a catalog search in Firefly, choose WISE. After the default chart comes up, open the options, choose w1mpro for X, w1sigmpro for X Err, w2mpro for Y, w2sigmpro for Y Err. Do the search, zoom to see error bars, check tooltip to see the uncertainty, when available. (If not available, the corresponding cell in the table should show null.)
> DM-3612 scatter plot errorbars

- src/firefly/js/tables/SortInfo.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx
https://jira.lsstcorp.org/browse/DM-7966 
- set default sorting on raw, phase, and peak tables
also:
- allow for raw table upload only, but added option to specify time and flux column
- code cleanup
- fix table index out-of-bound when navigate via arrow keys
- change popup phase folded values from 3 decimal places to 8 to match the server-side version
Use /firefly/lc.html to test.
> DM-7966: Default table sorting in LC viewer

- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/ui/ColorPicker.jsx
- src/firefly/js/ui/InputFieldLabel.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/PointShapeSizePicker.jsx
- src/firefly/js/util/Color.js
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/draw/SimpleCanvas.jsx
- src/firefly/js/visualize/ui/DrawLayerItemView.jsx
- src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
The development mainly adds support for the user to change the symbol and its size when overlaying a catalog on an image including the features: 
- catalog default symbol is square and size 3 to 20, size means the size shown on UI. 
- add shape options for the symbol, 
x, square, cross, diamond, circle, arrow, boxcircle, and dot. 
- create a dialog for changing the symbol and its size, each drawing layer has its own dialog. 
- the change in color will update symbol content in symbol dialog and drawing layer panel in real time. 
- the change in symbol, size, and color will update the catalog symbol overlaying the image in real time.
> DM-8542 Add support for changing draw layer symbol and the size

- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/task/WcsMatchTask.js
- WCS target match on by default.
- The image stretch and color is saved as preference
- object position should be centered in the display by default.
- object is overlaid
To test: just read in the raw table.  The changes are visible.
> DM-7970: Image settings for Light curve

- src/firefly/js/charts/ui/Histogram.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/visualize/draw/DrawingDef.js
This ticket is for making highlight and selection colors consistent in tri-view. (Highlight matching orange image border color, selection is yellow.)
> DM-7965 make consistent highlight and selection colors

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
To test it, 
1.  login JIRA and download the 1250p4106_1342188754_SpirePhoto_L20_PMP500_SPG14.0.fits file in DM-8648 and store somewhere in your locally.
2. check out this branch and build the firefly
3. start your tomcat server and then start the Image viewer in the browser by    http://localhost:8080/firefly/
4. open the fits file and check the flux unit.
Thanks!
> DM-8648:fixed the flux unit bug

- src/firefly/js/metaConvert/LsstSdssRequestList.js
For ScienceCCD, its scienceCCDExposureId is the base id which does not contain the filterId, but for DeepCoaddId, it is the baseId + filterId.    For both, I used 
title = id +'_'+filterName.
To test it, please
1. check it out and build
2. connect vpn 
3. start tomcat and then open this the http://localhost:8080/firefly/lsst-pdac-triview.htm
4. select image, then table name
5 enter 9.469,-1.152 at the Name or Position text box 
Thanks,
> DM-8548 fixed the wrong deepCoaddId in the image title

- src/firefly/js/charts/chartTypes/HistogramTblView.jsx
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/Histogram.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
Separated reversed and opposite ("top" for X, "right" for Y) axis options.
Refactored code to use ColumnOrExpression field in histogram or other charts.
https://jira.lsstcorp.org/browse/DM-8302
To test, open chart options and play with axis options in collapsible for X or Y axes.
> DM-8302 options for opposite axis location: X on top, Y on right

- src/firefly/html/css/global.css
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/FormPanel.jsx
https://jira.lsstcorp.org/browse/DM-8833
- create download dialog with extendable options
- create download button that connects to single table or active table of a named group
- update LcResults.jsx to use this new download dialog as an example
To test:
http://localhost:8080/firefly/lc.html
upper right corner 'Prepare Download' button is tied to active table.
select one or more rows, then click 'Prepare Download' to show the dialog.
> DM-8833: Creates a basic download dialog based on selected rows

- build.gradle
- buildScript/depends.gincl
- buildScript/gwt.gincl
- buildScript/gwt_webapp.gincl
- buildScript/init.gincl
- buildScript/utils.gincl
https://jira.lsstcorp.org/browse/DM-8566
- Fix duplicate nom.tam.fits classes during build
- Add preferIPv4Stack to tomcat env.
- Add firefly.war to Firefly Standalone release page
Temporarily added this branch to jenkin's build to test the Firefly Standalone fix.
preferIPv4Stack=true is added to setenv.sh in ife-env repo
> DM-8566: build related fixes

- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/templates/lightcurve/LcManager.js
https://jira.lsstcorp.org/browse/DM-8706
also fixed:
- DM-8602: Cols link does not work when launched from "Charts" popup.
- when no image available, remove fits data tabs
- drop down menu when there’s nothing in the results after the last component has been removed.
Test:
use firefly-dev.html page for testing for additional functions, ie.  image meta search
> DM-8706: catalog search mistakingly brings up an image tab

- src/firefly/html/lc.html
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseFoldingPopup.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/FieldGroup.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/RangeSlider.jsx
- src/firefly/js/ui/RangeSliderView.jsx
- period finding layout before and after periodogram which contains the panels 
(LcPeriods.jsx)
. to enter values of period finding parameters
. to show phase folding preview of xy plot
. to show periodogram and peak tables and XT plots (after periodogram)
- Find periodogram dialog  which inherits some parameters from period finding panel
(LcPeriodogram.jsx)
- Revamp LcManager to work with period finding and periodogram finding flow 
(LcManager.js)
- add 'keepMounted' property to FieldGroup component which allows the parameters under the field group to be kept mounted while the component is unmounted. 
- update 'RangeSlider' component by removing the text input field attached to the slider. 
Test:
- localhost:8080/firefly/lc.html. 
- choose file - lc_raw.tbl …
> DM-8668 lc period finder

- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYWithErrorsProcessor.java
- src/firefly/js/charts/ChartDataType.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
Added support for line plot
- added plotStyle ('points' and 'line', defaults to 'points') and sortColOrExpr (defaults to x.colOrExpr) to XY plot parameters. For smaller (<5000 rows) tables, plotStyle shows in options; 
- added support for sortColOrExpr to XYWithErrorsProcessor;
- improved the logic to see if server fetch is needed, the function now has access to the server call parameters, with which the data were obtained 
To test, load a catalog less then 5000. Open options and select 'Line' as a plot style.
https://jira.lsstcorp.org/browse/DM-8367
> DM-8367: Line chart

- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYWithErrorsProcessor.java
- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/charts/ui/XYPlot.jsx
This is a fix for a bug described in https://jira.lsstcorp.org/browse/DM-9206
Test procedure and test table are in the ticket.
Set precision for expression columns to 14 seg digits. 
Tooltip will include 4 sig digits in the difference between min and max of the plot.
> DM-9206 - XY Plot: set precision for expression columns

- src/firefly/js/charts/ui/HistogramOptions.jsx
https://jira.lsstcorp.org/browse/DM-8309
Added fixedAlgorithm prop to HistogramOptions.  Set it to true for IRSA.
to test:
- checkout branch in firefly AND ife:
- build irsaviewer in ife
- any catalog search, then clicks on 'Charts' top menu.
- under Histogram, there should only be one option for Algorithm.
> DM-8309: Enable histogram in IRSAViewer

- src/firefly/html/lc.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/LightCurveFileGroupsProcessor.java
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
I've completed and adapted the server and client side for downloading WISE images (cutout or original) single exposure (product level 1b) from Time Series viewer. 
Selected images are downloaded in a zip file previous packaging in the server.
Downloading selected row from raw table should work the same way as from the phase folded table.
To test, upload lc raw table and phase fold, select rows and check that the images have a name that match the row frameid and cutout size, size that match the cutout IBE call as well as original images.
> Dm 7195 lc download images

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
To test it,
1.  In catalog search, select "allSky"
2. Enter the constrains at the field:
For deep source at the id field enter
=3219370314566605
For forced deep source at the id field enter:
=225486482582800165
Each search returns only one finding.
Thanks!
>  DM-9247: Implement search processor(s) to support All Sky mode

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
https://jira.lsstcorp.org/browse/DM-7798
Added 'Launch WISE LcViewer'  link into demo page to demonstrate how to launch an external viewer to display time series data.
To test:
goto http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
In Tables from API calls section, click on 'Launch WISE LcViewer' to launch an external viewer showing wise light curve data.
> DM-7798: Add remote launch capabilities to the Time Series viewer

- src/firefly/js/tables/TablesCntlr.js
https://jira.lsstcorp.org/browse/DM-8571
Switch to the search result tab immediately even though data have not returned.
Minor code change.  Please confirm it did not break anything else, i.e. external viewer, lightcurve, etc.
> DM-8571: The current search result table tab should be shown immediately

- src/firefly/html/demo/ffapi-coverage-test.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/drawingLayers/ActiveTarget.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/ImagePlotter.js
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- Now can set overlay position
- Symbol, symbol size and color can be set per table
- Active Target bug fixed
- Initlization of CoverageWatch sega moved to templates and api
- triview: fixed coverage disappearing in a certain case
**To Test**
- build and try http://localhost:8080/firefly/demo/ffapi-coverage-test.html
- modify options on lines 72-80, then copy file to `/hydra/server/tomcatwebapps/firefly/demo/` and reload
> DM-9165: fixing coverage issues

- config/log4j-test.properties
- src/firefly/test/edu/caltech/ipac/astro/IpacTableReaderTest.java
Please review the Junit test for IPACTableRead.
Need to use the branch, DM-8916-JUnitTestForIPACTableRead, on firefly_test_data.
This test is mainly to test if IPACTableReader.java reads the IPAC table correctly. The IRSA IPAC table reader requirements are in
http://irsa.ipac.caltech.edu/applications/DDGEN/Doc/ipac_tbl.html
An IPAC table is composed by three parts: Attributes which includes keywords and comments; header which includes column names, data types, data units, and null values; and data rows.
The test cases below test if the reader can parse all parts in a table correctly and also if the reader can throw exceptions correctly when a table violate the requirements.
In this version, there are several known issues:
1) So far all the data comparison is done to compare strings …
> DM 8916: Junit Test on IPACTableReader.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTImageSpatialType.jsx
Development includes
[CW DM-9248]
- the 'all sky' feature was built in the LSST spatial search component. 
- fixed some code syntax errors issued by IntelliJ. 
- fixed the setting of some spatial search parameters from float to string format prior to building the table search request. 
[LZ DM-9247]
- Add the AllSky search in Catalog search
- Add the allSky search in Image Catalog search
- Add the guard to prevent from allSky search without constraints.
test for 'AllSky': 
- localhost:8080/firefly/lsst-pdac-triview.html
- In catalog search, select "allSky"
Enter the constrains at the field:
For deep source at the id field enter
=3219370314566605
For forced deep source at the id field enter:
=225486482582800165
- in image search
for Deep coadd: 
deepCoaddId =1610612744
for ccd …
> DM-9248 Implement 'All Sky' mode in LSST catalog and image search catalogs

- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/FilterHanlder.java
https://jira.lsstcorp.org/browse/DM-9349
In Firfefly (+IRSAVIewer) development version, when the user select table rows and filter them out, the result table is not matching the selected rows before applying the filter.
OPS is fine though.
Steps to reproduce:
do a catalog search i.e., 2mass, 100". From the result table, select a row and apply filter. Then check that the resulting row is not the one you selected.
TG 02/10/2017 The row returned is actually the previous row. 
The related issue is filtering a point from an image. A previous row is returned as a result.
> DM-9349: filtering by ROWID is off by 1

- src/firefly/js/ui/PointShapeSizePicker.jsx
The ticket request was to raise the shape size limit to 100 pixels and change checkboxes to radio buttons for the choice selection.
By raising the size, i had to take out the current canvas. If you find a better way to adjust the window with the canvas, let me know, i couldn't.
Fixing the window width or any other style/css approach is not worth the effort because it could change again if the max size is not yet enough for future cases.
Maybe @robyww or @Caltech-IPAC/firefly developers might have a better solution. Come to me to discuss it if you want or feel free to commit directly to my branch. 
Thanks.
> DM-9340: raise size limit to 100 and use radio buttons instead of checkboxes

- src/firefly/java/edu/caltech/ipac/visualize/plot/CentralPoint.java
- src/firefly/test/edu/caltech/ipac/visualize/plot/CentralPointTest.java
Add unit test for CentralPoint class
Change posdis to private since it is only used inside the class
While I was working on this test, I found that the CentralPoint class did not use the Elzinga-Hearn Algorithm as described at the beginning of the class. There are no further document about the
algorithm.
> DM-7946: Unit test for CentralPoint

- src/firefly/js/tables/TableUtil.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
fix the following phase folded table creation issues:
- derive the phase folded table from raw table with full data set by adding a phase column and doubling the row numbers of the raw table. 
- update the time column ('mjd')  value of the added rows to be the same as that in the raw table. 
- update and validate the period value (text field and the period slider)  when the selection of periodogram table and peak table or the highlight on those tables changes.
> DM-9382 Fix phase folded table content

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/core/ExternalAccessCntlr.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/data/MetaConst.js
- src/firefly/js/drawingLayers/PointSelection.js
- src/firefly/js/metaConvert/ConverterFactory.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/PlotCmdExtension.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/test/python/demo-notebook.ipynb
- src/firefly/test/python/lsst2015-demo.ipynb
- cleaned up ExternalAccessCntlr
- fixed point selection improperly turning on and off
- fixed extension added.  It will now update if the extension id already exist
- extension response data sent to server now contains selected table row information
if a table is associated with an image.
- new plots are active by default, it was not defaulting correctly with remote actions
- improve image meta data table uploads a little, made DataSource work correctly
Notes:
- this is really going to be hard to test until we get it on  the pdac.  I would sugest that the code review just look over the code the David S. and I will test it with his python code.
- ignore the python notebook file in the review
> DM-9425: several python interface issues

- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorQuery.java
Please, check that it doesn't break anything else (Gator queries). Need to encode the constraint parameter passed in the request so it can cope with for example:
all-sky search with SQL constraint such as: `objid like '%Themis'`
Test: do a catalog search in NEOWISER Reactivation db, with the text search sql `objid like '%Themis'` in the SQL constraint text area on bottom of the catalog search panel.
Result should come back with 75 result same as if you are doing it from Gator page.
> DM-8989: SQL constraint encoded

- src/firefly/js/templates/lightcurve/LcPeriod.jsx
Phase folded chart preview had the magnitude Yaxis shown in increasing order, astronomers wants to see the magnitude value in reversed. This fix the issue for that component in the "Period finding" layout.
> DM-9162: magnitude should be plotted in reversed order Yaxis

- src/firefly/js/drawingLayers/NorthUpCompass.js
- src/firefly/js/util/Color.js
- src/firefly/js/visualize/draw/DirectionArrowDrawObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/projection/Projection.js
the development includes
- Locate the compass at the left corner of the image when the image is scrolled, zoomed, re-centered, rotated, flipped, etc. 
test: 
- find a image by using 'Images' panel.
- click 'compass' button from the image tool bar
- apply image processing related buttons and see how the compass is rendered.
> DM-9430 Fix Compass Layout 

- src/firefly/html/css/global.css
- src/firefly/js/templates/lightcurve/LCPanels.css
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/ui/panel/DockLayoutPanel.jsx
https://jira.lsstcorp.org/browse/DM-9272
- fix SplitPane resizes beyond browser's width/height
- fix Periodogram expanded mode sizing issue.  Content is larger the window's size causing scrollbars to appear
- removing multiple redundant SplitPanels
- remove 'SplitPanel' based styling when components are not resizable.
To test:
http://localhost:8080/firefly/ts.html
> DM-9272: Clean up IRSA Time series viewer to prepare RC

- src/firefly/js/charts/dataTypes/XYColsCDT.js
Bug fixed in rc.  Please review.
> DM-9543: calling showXYPlot API without xcol/ycol name fails

- src/firefly/js/fieldGroup/FieldGroupUtils.js
- src/firefly/js/templates/lightcurve/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/ui/RadioGroupInputField.jsx
The related ticket: [https://jira.lsstcorp.org/browse/DM-9348](https://jira.lsstcorp.org/browse/DM-9348)
Sample raw table for LSST_SDSS is attached to the ticket.
Refactored the code to support multiple missions (currently WISE and LSST SDSS)
- LcConverterFactory.js defines properties storing mission specific information
- It is assumed that each raw table contains time and at least one periodic column (we call it flux, but it can be anything)
- Each mission can have different UI to define those columns (upper part of result view)
- For LSST SDSS, the uploaded table contains all the bands, raw table is always filtered: band selection triggers table filter. It would be nice to have hidden filter for this case, which user can not remove. Currently, user can remove the filter, and band …
> DM-9348 LSST - time series viewer results (part 2)

- src/firefly/js/ui/InputFieldView.jsx
- even with valid data if the mouse is covering the warning icon
_to test:_
- bring up firefly and go to a input field such as a target input field
- enter an invalid target
- place mouse over warning icon so that you see the message
- with out moving the mouse, then enter a valid target (such as `m31`)
- the warning icon and the popup message should go away.
> DM-9578: warning message does not disappear

- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
I've added the help links as discussed during the review. Luisa has been writing the docs that can be found in the wiki. See ticket in JIRA.
To test, checkout and build the branch. Then go to .../firefly/ts.html.
> Dm 9164 add lc help links

- src/firefly/js/visualize/ImagePlotCntlr.js
_To test, just follow the ticket description._
When doing a catalog search, the result tri-view shows image, table and xy-plot.
The image is called 'Coverage'.  Using the selection tool and cropping part of the image, the result is a smaller image which is correct.
Then when trying to go back and restore to default image (click the "Restore" button on the toolbar), the result is 2 tabs, one with the coverage restored correctly and another one called 'FITS data' empty and active.
> DM-9359: Fixed: Restoring coverage image after cropping it shows an empty tab entitled 'FITS data

- src/firefly/js/templates/lightcurve/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/DownloadDialog.jsx
Labels have been updated according to the ticket.
Please, make sure that nothing is broken and labels are changed.
> DM-9467: changed labels accordingly to the reviewers feedback

- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
Fixed bug after zoom
Pease check:
1.  If the bug is fixed.
2. If the way of fixing is appropriate.
Thanks!
> DM-9343:scatter and line chart zoom changed when changing between "points" and "connected points"

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java
- src/firefly/js/metaConvert/LsstSdssRequestList.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssPlotRequests.js
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/util/MathUtil.js
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTImageSpatialType.jsx
https://jira.lsstcorp.org/browse/DM-9371
- Display image cutouts in LSST TS viewer 
To test, http://localhost:8080/firefly/ts.html, use LSST_SDSS and raw file attached to DM-9348
- Enable option to return cutouts on image search (at the moment, DAX supports cutouts image cutouts only Science CCD Exposure table, not yet for Deep Coadd) 
To test, http://localhost:8080/firefly/lsst-pdac-triview.html, select Images, set Return Image Size or leave it blank for full image.
- Updated SizeInputField to allow empty values.
> DM-9371 Display cutouts in LSST timeseries viewer

- src/firefly/js/data/MetaConst.js
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/generic/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/generic/DefaultPlotRequests.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- src/firefly/js/ui/PopupUtil.jsx
- make UI for generic time series table, metadata tags for time column (ts_timeCName), flux column (ts_fluxCName) , image url(datasource)  and error column (ts_errorCName) can be specified in either table file or the UI. 
- add 'generic' category into the convert factory to cover the default setting for generic table in addition to WISE and LSST missions. 
- Create 'generic' directory to contain the development for generic table specific UI, table load query and plot query. Move 'WISE' relevant development to be under 'wise' directory.
- Fix periodogram table/peak table calculation error. (there was no periodogram table created for LSST). 
- clean the field values in the viewer group when a new raw table is uploaded. 
- period min/max on the periodogram …
> DM-9491 Add support for generic time series tables in the TS viewer

- src/firefly/java/edu/caltech/ipac/visualize/plot/FitsRead.java
The reason that the rotation is wrong is that the incoming coordinate in m16 is galactic. But the out image created by rotation is in EQ_2000.  I think the rotation should be done in the same coordinate as the original image.  However, I maybe wrong since I don't know the reason why the EQ_2000 is hard coded there. 
But the bug is fixed after I changed the coordinate.  I also tried other rotation related function and seemed to me all are well.
Please review this and let me know if I am doing the wrong way.  Thanks!
To test the bug,
1.  In image search, enter target "m16"
2. Select MSX tab
3. Search
4. Click rotation icon and enter 180
> DM-9581:MSX image rotation not computed correctly.

- src/firefly/js/ui/PopupPanel.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/region/RegionFileUploadView.jsx
The development fixes: 
- letter bottom cutoff on tab header and popup panel title
- add missing popup panel title 
test:
try the following entry to see tab group and popup panel
localhost:8080/firefly/
enter a target and search, try click tool button for loading region file, fits download, or overlay editor+color picker to get various popup panel. 
select 'catalogs' to get group of tabs
> DM-9080-LabelCutoff Fix label cutoff on the tab header and popup panel title

- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/ui/ActiveTableButton.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/generic/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssPlotRequests.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
https://jira.lsstcorp.org/browse/DM-7803
On LSST PDAC, when searching for 'Deep Forced Source' data, there should be a button to view the time series data for the highlighted objectId.
If you upload a table with time series's metadata, there should be a button to view the table as time series.
To Test:
- Check out 'DM-7803_triview_timeseries' branch in both firefly and suit repo.
- Build suit and then goto http://localhost:8080/suit/
- Search for "Deep Forced Source", then click on 'View Time Series' button at upper right corner to view the data in a separate window.
- When uploading a table with time series metadata, i.e. 'timeCName', there should also be a 'View as Time Series' button at the same location
> DM-7803: add time series launch capability to suit app.

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/visualize/iv/ImageViewerLayout.jsx
- src/firefly/js/visualize/task/ImageOverlayTask.js
- src/firefly/js/visualize/task/WcsMatchTask.js
- src/firefly/js/visualize/ui/MultiItemViewerView.jsx
- expanded mode problem fixed (flex layout issue)
- image zoom levels sizes stay correctly syncronized
- images reset when new data is loaded
- images reset when cutout size changes and stay synced
- when rotation happens on images, target match is turned off. Therefore new
images will not come in at the same rotation.  The target match
must be turned back on. This is the expected behavior we can consider
whether is is the desired behavior.
> DM-9691: time series image problems fixed

- src/firefly/js/templates/lightcurve/LCPanels.css
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
error column input field removed from setting box. Please check that this is the case.
> DM-9471: remove error flux column input field in setting box area

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/charts/dataTypes/HistogramCDT.js
- src/firefly/js/charts/dataTypes/XYColsCDT.js
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
https://jira.lsstcorp.org/browse/DM-9590
To test, place test.html  attached to the ticket (with non-existent x and y) into firefly/demo deployment directory.
> DM-9590 XY plot is unrecoverable after it fails

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/js/charts/ui/ColSelectView.jsx
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
This development is to
- Remove unexpected image tab and not unmount the column select ion popup after a column for Histogram is selected.
- skip to check if the table used for selecting the column is a catalog table or an image meta table after the table is loaded.
test: 
- start a catalog search (or lsst catalog search from lsst-pdac-triview.html)
- click 'Charts' (or 'Add Charts' for lsst)
- click 'Histogram' or 'Scattered plot' radio button.  click 'Cols' and select a column from the popup table. 
- the select column name is shown in the field for columns in chart select panel.
> DM-9638 Remove unexpected image tab after a column for histogram is selected

- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/basic/BasicMissionOptions.js
- src/firefly/js/templates/lightcurve/basic/BasicPlotRequests.js
- src/firefly/js/templates/lightcurve/generic/errorMsg.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WisePlotRequests.js
This is a fix for the basic case and neowise tables.
I've introduced a basic case which suppose to handle all numerical column of a general table uploaded in order to allow user to find the period and phase fold, with no images to be displayed.
I have added to the converter cases, 2 new functions, one about the images layout and another one to validate the table uploaded.
The case for WISE is trickier because we need to support tables that contains either frame_id or source_id or scanId and frame_num to be able to display WISE single exposure images. I've changed the WISE plot request and add specific function to validate the table. If the table doesn't have those column, the viewer will bailout in a message (the current message will be reviewed and is not definitive) to let the user know …
> DM-9589: Fixed WISE case and add basic case with no images

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcViewer.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-174
To test:
git checkout this branch on both firefly and ife.
build irsaviewer in ife.
goto http://localhost:8080/irsaviewer/timeseries to verify that only WISE and Basic option in dropdown.
> IRSA-174: TSV mission list should display only WISE and Basic for now

- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/basic/BasicMissionOptions.js
- src/firefly/js/templates/lightcurve/generic/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- add time column name field to LSST setting box. 
-update the response when the user change the time column name. This update is applied to all table cases (wise, last, generic and basic tables) including
. update raw table  
. remove phase folded table if there is
. update the chart and the images accordingly
. restart phase folded table calculation.
- fix the following bugs: 
. table highlight sync between raw table, phase folded table and the images => Loi contributed and updated code regarding highlight sync. 
. field validation for generic (and basic) tables
. ensure the table reloaded with sort information for generic table which has no time column name info when the table is uploaded at first time.
. remove cutout option for generic table on image …
> DM-9743 Time column name handling for Time Series Viewer

- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotOptions.jsx
https://jira.lsstcorp.org/browse/DM-8685
To test: 
1. WISE catalog search (ex. m31, 100 arcsec)
2. Chart dropdown -> Scatter plot -> set "Error" options (can be const or col expressions)
3. Check on chart
> xyplot: support asymmetric errors

- src/firefly/java/edu/caltech/ipac/visualize/plot/Rotate.java
- src/firefly/test/edu/caltech/ipac/visualize/plot/RotateTest.java
DM-8854:
Add unit test for Rotate class
Add the algorithm descriptions
The coverage is 80%.  There is a main program inside which made the coverage lowered.  To 
test it, please run:
gradle :firefly:test
Thanks!
>  DM-8854:Create a Unit test for Rotate class

- src/firefly/js/ui/DownloadDialog.jsx
`Cancel` button was not hiding the download dialog in LC, the button was doing anything. The `id `was the wrong one passed to the dispatch.
This is the fix. Please test.
> IRSA-323: fix cancel button to dispatch id correctly to hide dialog

- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
Change the order of the dispatch so the periodgoram is the first table from left to right.
Test: run periodogram from TSViewer and check that periodogram table is the first from the left, peaks the second.
> IRSA-336: reorder periodogram tables

- src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/util/VoTableUtil.java
I've set a default min precision for VOTable converter to data group, plus added the reading of a precision attribute from VOTable if it exists.
The guessing part of the format is only made in the first row. We need to improve that also for the IPAC table reader which is related to ticket raised during GOODS data-set release ([IRSA-128](https://caltech-ipac.atlassian.net/browse/IRSA-128)).
Please check that this make sense and doesn't affect other things.
To test: do a periodogram calculation with period min=1, period max=2, rest as default for example, the first value of the VOTAble from the API is `1`, the second is 1.000... 
This value should appear  in the table/xy plot view with at least `8` digit which is the default minimum precision.
> IRSA-327: fix rounding problem

- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
To test it,
1. build firefly
2. build irsaviewer in ife
3. Please follow the procedures in the video Louisa created (https://youtu.be/B-DfHOtWFGo)
For some reason, the image  from irsaviewer is not the same as the one from the irsatest.  I attached the old image in the ticket. 
Thanks for testing!
> Irsa 142-WCS match behavior is odd

- src/firefly/html/firefly.html
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/ui/ChartSelectDropdown.jsx
This development fixes the following: 
- If the external viewer shows charts only, 'Charts' drop-down button is not working to make another histogram since there is no active table from the viewer. 
- the 'close' button is removed from the external viewer if only charts are on the external viewer. 
the 'close' button exists when the chart is expanded from an external viewer with table, image and charts. Clicking the 'close' button, the page will go back to the original external viewer. 
test:
go to the demo page: 
http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
click on 'show histogram'. an external viewer opens a new tab with a histogram chart on the page.
> DM-9395 Showing histogram on external viewer 

- src/firefly/html/firefly.html
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
the development includes:
- fixes the phase value range on the phase folded curve to be [0, 2)
- plotly based phase folded chart doesn't react properly as the periodogram table is highlighted on a row with invalid period value. 
test:
- start time series upload page, i.e. localhost:8080/firefly/ts.html
- load a time series file
- select 'find period' in the result page, go to period page
- make the zero point time value bigger by adding a couple of digit '0' before the decimal point
- slide the slider to see if the phase falls between 0 and 2
- click 'calculate periodogram'
- select some period value which is either valid or invalid
- check if the period entry and the phase folded chart react correctly. 
(valid period shows a phase folded chart, invalid period shows no chart).
> DM-10149 fix the phase value range of phase folded chart

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
This PR is removing the constraint of updating the period value every time the user switch from one active table to another. Plus, it also set no default value for the period.
Check that when you go to calculate periodogram in LC viewer, switching from one table to another back and forth doesn't change the value of the period, only if you click on the plot or the table.
Also noticed that no value is pre-filled in the period input field.
Let me know if you find any problem.
> Irsa 320 disable period change on table active

- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/FootprintToolUI.jsx
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/drawingLayers/MarkerToolUI.jsx
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
The development includes 
- fixing the bug regarding footprint rotation handles off while rotating
- fixing the bug regarding marker resize handles off while resizing
- rendering the footprints, markers and regions based on the rotation angle of the image. 
- updating footprint and marker rendering on multiple plots. 
test:
do image search 
add footprint or marker onto the image
operate the footprint or marker (rotate/move the footprint or resize/move the marker)
rotate the image before or while operating on the footprint/marker
> DM-10188 Fix drawing related issues on markers and footprints with new rotation scheme

- src/firefly/js/drawingLayers/NorthUpCompass.js
- src/firefly/js/visualize/ui/ThumbnailView.jsx
This development fixes the rendering of the East arrow line in the North/East compass, making the direction of the East arrow perpendicular to the North arrow line.
test: 
please refer to the compass on DS9 for the following image search,. 
- from Firefly, get image by setting RA=45, DEC=89 and selecting IRAS with 5 degree cutout,
add grid and the North/East Compass. 
- download the fits image, and open it from DS9.
- add grid and compasses at various locations  in DS9
- move the image in Firefly to see the compass shown on various locations and compared the compass to that shown on DS9.
> Dm-10241 Fix the rendering of east arrow in the North/East compass

- src/firefly/js/charts/ui/HistogramOptions.jsx
Option in histogram setting panel has been removed for now. See detail in the ticket.
I have kept the code for the (near) future.
Please, confirm that the option is no longer available.
> IRSA-399 remove x-log options from histogram

- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
As requested, accept button in periodogram form has been renamed to 'Calculate'.
Build and check that it is the case.
> IRSA-359: renamed accept button label in periodogram form

- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
This development fixes the following issues after starting a new catalog search: 
- The column selection dropdown shows column stats of previous active table
- the added chart shows the content relevant to the previous active table, not current active table. 
test: 
- start a catalog search
- add a chart by clicking 'Charts' button, selecting chart type (Histogram or scatter) and selecting the column name from column select form.
- check if the added chart reflects the selected column and its stats.
- start another catalog search
- repeat the column selection steps to add the chart
- check if the added chart reflects the selected column and its stats from the second catalog search
> DM-10115 Reset the column select dropdown and column stats on new catalog search

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/chartTypes/HistogramTblView.jsx
- src/firefly/js/charts/chartTypes/ScatterTblView.jsx
- src/firefly/js/charts/ui/Histogram.jsx
- src/firefly/js/charts/ui/HistogramPlotly.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotPlotly.jsx
Added save icon to download plotly chart as a png image. 
The size of the images will match the size on display.
Known issue: in Safari, an image is not downloaded, but opened in the browser, it can be saved from there. Plotly team says it behaves this way because download attribute is not supported in Safari (http://caniuse.com/#feat=download) and they open the link instead.
Link to the ticket:
https://jira.lsstcorp.org/browse/DM-10275
(As discussed at SUIT meeting, we want to save PNG without an extra dialog and we prefer png to jpeg because it is lossless.)
> download plotly image as PNG

- config/app.config
- src/fftools/build.gradle
- src/fftools/config/configurable/spitzer.xml
- src/firefly/build.gradle
- src/firefly/config/app-test.prop
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/TwoMassIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatScanQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatSummaryQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/Query2MassSIA.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/inventory/InventorySearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/inventory/InventorySummary.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/ui/table/TablePanel.java
- src/firefly/java/edu/caltech/ipac/util/download/NetworkManager.java
- src/firefly/java/edu/caltech/ipac/visualize/net/IrsaImageGetter.java
- src/firefly/js/templates/lightcurve/wise/WisePlotRequests.js
- src/firefly/js/ui/IrsaFooter.jsx
- src/firefly/js/ui/VoSearchPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/test/edu/caltech/ipac/firefly/util/PostDownloadTest.java
https://caltech-ipac.atlassian.net/browse/IRSA-401
- add new env: ops_int
- ops to use default config
- switch IRSA’s service URLs to https
- map IRSA’s services based on deployment mapped out here: https://ipacwiki.ipac.caltech.edu/Projects/IRSA/IRSA_Systems/IRSA_Server_Info/IRSA_Software_Deployment_map
- remove all custom ports, i.e. 5001, 9200, etc
- apply changes to both rc and gwt branches
Changes are in firefly and ife under branch 'IRSA-401_add_ops-int_env'.
Checkout branch from both repositories to test different build combinations.
Notice added ops_int env settings.
To build config files without a full build, use  `gradle clean jar prepareWebapp`
- inspect build/<app_name>/../*{.prop,.xml}  for generated prop files
One exception:  all heritage's services are pointed to ops.  dev …
> IRSA-401: Add ops internal environment to IFE apps

- src/firefly/js/templates/lightcurve/LCPanels.css
- src/firefly/js/templates/lightcurve/LcPeriod.jsx
I have added an overflow property and change couple of CSS property in order to make visible the scroll bar when the form panel is shrink. 
Please, check that is ok in different browser and device screens.
> IRSA-396 period finder panel resized

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/rpc/PlotServiceJson.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheProvider.java
- src/firefly/java/edu/caltech/ipac/firefly/server/cache/ObjectSizeEngineWrapper.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/PlotServiceImpl.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/CtxControl.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ModFileWriter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotReader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/HistogramOps.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageDataGroup.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/RangeValues.java
- src/firefly/js/data/ServerParams.js
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/ui/CompleteButton.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/ImageSelectDropdown.jsx
- src/firefly/js/visualize/ImageBoundsData.js
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/iv/CanvasTileDrawer.js
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
- src/firefly/js/visualize/ui/ImageSelectPanel.jsx
DM-10370: Optimize server memory usage for fits images
- Server memory size cut in half
- Optimized drawing so that user sees working message
- Optimized scrolling so the it does not block when loading images
- beta value (used for asinh strech) now only computed when required
- added a getBetaValue service call
- Uploading fits files now show masking while uploading
- removed addColorBand call from server (not used)
- Added way to push out memory in cache before large data is read in
- Fixed bug in computing in CsysConvert.pointInPlot with rectangular images
This is a very difficult test it requires jconsole to monitor the memory with large fits images. It could take awhile just to get set up.  Mostly the review should just look over the code.
_Target code to look at:_
- FitsCacher.java …
> DM-10370: Optimize server memory usage for fits images

- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/task/WcsMatchTask.js
_To Test_
- keep you browser window fairly small
- read in m81: 2mass, wise, dss, sdss
- do wcs match.
- put up grid
- grid should look parallel
> DM-10461: Fixed: wcs match a little off for almost north plots

- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/basic/BasicMissionOptions.js
- src/firefly/js/templates/lightcurve/generic/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssPlotRequests.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WisePlotRequests.js
What changed:
1. the default cutout size is set to 5 arcmin for all missons
2. added  cutout size conversion from arcmin to deg before sending WebPlotRequest
To Test
* upload a WISE/LSST time series table, the upper left form panel should have the default 5arcmin cutout size, the lower image panel will show size in arcmin unit in title
> IRSA-331:  update default cutout size units in TST

- src/firefly/js/drawingLayers/ComputeWebGridData.js
It seemed no one recalls why the algorithm was used in WegGrid.java.  It could be some special case.  That algorithm caused line missing in several cases.  I changed to the simple, and correct algorithm.  There is no more missing lines.
The other way to fix the missing lines is to do the forced regrid.  But since the cause is the algorithm, I chose to change the algorithm.
To test:
ra=45, dec=0, it has a missing line at the right side of the image before.  Now it is there.
ra=45, dec=90, it has a missing line in the bottom of the image before, it is there now.
> DM-10491:WebGrid has missing lines

- src/firefly/js/charts/ui/XYPlotPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
The pull request take care of a version left over from RC and include it in the plotly recently created in dev.
The period finder layout has changed according to the feedback during the test campaign and the version needed to be merged in the plotly version.
Test: bring the LC tool, and go to period finder. The button of the form are now under the control panel, no period value is set by default and title have been added to the plots.
> DM-10523: period finder layout up to date with plotly version

- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/iv/CanvasTileDrawer.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/task/WcsMatchTask.js
DM-10477: wcs match reset images when it turns off
Including bug fixes:
- Fixed a rotation issue: clicking rotate north on north up images fliped them south
- Fixed: when north is up, clicking north up makes the image rotate south.
_To test:_
- load m81 - 2mass, wise 1a, dss, sdss
- click on any image turn wcs-match on then turn off
- click on another image and do the same things
- image should rotation to match then unrotated
- Also, while WCS matched, rotate an image, they should rotate together and stay matched
_To test North up bug:_
- load 2mass click on rotate north - nothing should happen
> DM-10477: wcs match reset images when it turns off

- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/HistogramPlotly.jsx
- src/firefly/js/charts/ui/PlotlyChartPanel.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/charts/ui/XYPlot.jsx
- src/firefly/js/charts/ui/XYPlotPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
DM-10543: improved plotly performance during resize and add masking 
- react component not has properties to control how it renders during resize
- react component will now mask during slower work
- moved all the resize debouncing to the PlotlyWrapper, Firefox is debounced more
- LcPeriodPlotly will debounce the regen data for Firefox
> DM-10543: improved plotly performance during resize and add masking

- src/firefly/js/FFEntryPoint.js
- src/firefly/js/Firefly.js
- src/firefly/js/util/BrowserInfo.js
This development: 
-  import 'babel-polyfill' in Firefly.js to fix the fallback of some string functions on IE11. 
Test, 
you may install Windows on your Mac using VirtualBox to run IE11. You need, 
- Oracle VirtualBox(with extensions), 
https://www.virtualbox.org/
- Windows 10 ISO 
https://www.microsoft.com/en-us/software-download/windows10ISO
To do:
- download VirtualBox (and extensions), and create virtual machine with Windows 10. 
(if you need more detail about installation, please let me know). 
- Starts IE11 from the created virtual machine and launch Firefly by using "http://10.0.2.2/firefly" (this is relevant to Firefly from your local machine, localhost:8080/firefly)
> DM-9254 Make Firefly to work on Windows browser IE11

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
Change the default behavior of Histogram to show all the bins including the empty bins
This is a minor change to avoid confusion to the users.  As I commented in the ticket the reserveEmptyBins can be added to the UI and the parameter.
>  IRSA-371-histogram - numbins sometimes ignored

- src/firefly/java/edu/caltech/ipac/firefly/resources/LSSTMetaInfo.json
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMultiObjectSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java
- src/firefly/js/metaConvert/ConverterFactory.js
- src/firefly/js/metaConvert/LsstSdssRequestList.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- add WISE data search capability to LSST search UI. 
- This search includes catalog and image metadata table search. 
- For image metadata search, the metadata table is sent back from LSST catalog search processor, and the image retrieval is sent back from IBE WISE image search. 
- add WISE catalog and image metadata table search capability to LSST catalog search processor 
- the LSST meta search and catalog search processors are updated to work for multiple databases including those for SDSS and WISE dataset.  
PS. this commit resolves the work for both DM-9947 & DM-9948. 
Test: 
- start by localhost:8080/lsst-pdac-triview.html
- search WISE catalog or image metadata table by selecting project either 'wise_00' or 'wise_ext_00'. 
- select the table from …
> DM-9947 Add capabilities to LSST UI and LSST catalog search processor for searching WISE data

- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ProcessorFileRetriever.java
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/iv/CanvasTileDrawer.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotChangeTask.js
DM-7192: Fixed: User image of the coverage is gone after expand mode
Also includes:
- Bug fix: if a zoom ends after a replot then abort the zoom, also apply to color and stretch change
- A little code clean up and documentation
_Original Bug explanation:_
Do a catalog search, then do an image search to replace coverage image by another image (say WISE), then go in expand mode and back, the image is replaced back to the initial coverage image
_Fix:_
After expanded mode the user image should still be there.
> DM-7192: Fixed:  image of the coverage is gone after expand mode

- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/dataTypes/FireflyScatter.js
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
- src/firefly/js/charts/ui/options/HistogramOptions.jsx
- src/firefly/js/charts/ui/options/NewTracePanel.jsx
- src/firefly/js/charts/ui/options/PlotlyHistogramOptions.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
This PR is for supporting Firefly Histogram chart (with the column data aggregated into bins on the server) in multi-trace plotly chart. (Currently, multi-trace chart is only available in API.)
I've changed histograms to solid color to make multiple histograms look good together, and so that the trace color can be changed easily.
For comparison, I have added options for Plotly histogram (client side histogram calculation). Firefly histogram (backed by Plotly bar chart) and Plotly histogram do not work well together, but it's good to see what options are available and see if we can support both charts with one set of options.
Ticket:
https://jira.lsstcorp.org/browse/DM-10831
Test:
http://localhost:8080/firefly/demo/ffapi-highlevel-charttest.html
Check the first chart, try to change …
> DM-10831 Histogram multi-trace chart

- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYWithErrorsProcessor.java
- src/firefly/js/charts/dataTypes/FireflyScatter.js
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/Errors.jsx
- src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx
- src/firefly/js/charts/ui/options/NewTracePanel.jsx
- src/firefly/js/charts/ui/options/PlotlyHistogramOptions.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- Added options for plot boundaries, color map, and xyratio/stretch (for all chart types) 
- Added color picker to Color field. (Later we should have color input field.)
- Added field validation for boundary fields and logic to clear the fields on x and y changes.
- Color map and Size map can be column expressions. 
(If Size map evaluates to a constant, it won't be connected to the table.) 
The issues that need to be resolved in the future tickets:
- Color input field
- Color bar display when color map is specified. (There is a number of issues with display: two tick sets, no update when color scale changes. We also need to make sure it's on the opposite side of yaxis.)
- Size map scaling: to make sure all points are visible, we might need to scale point size in pixels so that it falls …
> DM-8707: scatter options in multi-trace charts

- src/firefly/java/edu/caltech/ipac/util/expr/Expr.java
- src/firefly/java/edu/caltech/ipac/util/expr/Parser.java
- src/firefly/java/edu/caltech/ipac/util/expr/expressions.html
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/dataTypes/HistogramCDT.js
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/util/expr/Expr.js
- src/firefly/js/util/expr/Parser.js
https://jira.lsstcorp.org/browse/DM-10349
Use the following functions for logarithms in Firefly column expressions: 
log, ln – for natural logarithm
log10, lg – for common logarithm
(The meaning of 'log' has changed from lg to ln to match definitions in JS or Python.)
Added documentation for expressions to both code and tooltips.
Reduced the number of suggest box updates to avoid flickering.
> DM-10349 Chart expression logarithm to be the same as other languages

- src/firefly/java/edu/caltech/ipac/util/VoTableUtil.java
Very small change for big impact. I've fixed the UCD parser by checking the UCD pattern for each column ra,dec so we can make use of SCS result VOTable with this information to overlay catalog.
To test:
Checkout branch `IRSA-289-fix-overlay-votable-ucd`
Bring VO search catalog panel in tri-view and use this URL (SCS from IRSA) `https://irsa.ipac.caltech.edu/SCS?table=allsky_4band_p3as_psd&`
Currently SCS with this UCDs is in dev, not sure if it's already in ops.
You should see the image overlay with catalog result.
You can also try with a sample VOTable with meta UCDs.
> IRSA-289: fix and make use of SCS VO table ucd meta ra/dec

- buildScript/depends.gincl
- buildScript/gwt.gincl
- buildScript/gwt_webapp.gincl
- buildScript/init.gincl
- buildScript/utils.gincl
- buildScript/webpack.config.js
https://jira.lsstcorp.org/browse/DM-11122
DM-11122: gradle task for docker
2 tasks created: dockerImage, dockerPublish
dockerImage is a prerequisite for dockerPublish
they will accept these params:
```
docker_repo = "ipac/firefly”
docker_registry = ''
docker_tag = ‘latest’
```
`docker_user, docker_passwd` may be passed as parameter.  This is used to log into docker hub.
`docker_registry `may be set to a local registry.  You can test it by running a local registry and setting `docker_registry` as parameter or via personal build.config file.
`docker_tag` will be set to branch name during auto-build setup.  This will be useful for ‘dev’ as well as PR’s instances.
To test:
- install docker
- checkout this branch
- gradle :firefly:dockerImage
- in terminal type: docker images
- ipac/firefly …
> DM-11122: create gradle tasks for docker related functions

- src/firefly/js/charts/ui/HistogramPlotly.jsx
- src/firefly/js/charts/ui/XYPlotPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
I've changed the default axis label format to be exponential instead of defualt k/M/B suffix notation.
To test:
Bring any plot and plot an axis either with high values or multiply by 1000 so you can see the difference. Before it was k/M/B format, now it should be raw or exponent notation.
> IRSA-595: set default axis format to exponential.

- src/firefly/js/charts/ui/XYPlotOptions.jsx
- src/firefly/js/charts/ui/options/Errors.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
Labels for error bars option have changed.
X Err -> Error
Sym -> Symm
I took the opportunity to cleanup the code and remove duplicated constant.
Please, confirm change in UI and check that i didn't mess up the code. Thanks.
> IRSA-601: labels change in error bars options

- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/java/edu/caltech/ipac/firefly/data/DecimateInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyScatter.js
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/HeatmapOptions.jsx
- src/firefly/js/charts/ui/options/NewTracePanel.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- src/firefly/js/tables/Decimate.js
- src/firefly/js/ui/ListBoxInputField.jsx
https://jira.lsstcorp.org/browse/DM-10832
Added heatmap trace type to multitrace chart with options and server side connection.
Known limitations:
- The only way to recalculate  heatmap is to change table, filter from the plot, or change heatmap parameters. The map is not recalculated on zoom or when axis limits change
- Table highlight is not shown - it's not clear if we should support this connection
colorbar can overlap.
- It's not possible to set from UI which heatmap trace is on top. (Usually the last trace in the data array is the one on top.) We might need a separate ticket for placing active trace (of the same type) on top of the others.
- Colorbar can overlap with the legend, other colorbar ticks. It's not easy to position it perfectly in generic case, when multiple colorbars …
> Heatmap (density) plot in multitrace chart

- src/firefly/js/tables/TableUtil.js
- src/firefly/js/templates/hydra/HydraManager.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/PTF/PTFMissionOptions.js
- src/firefly/js/templates/lightcurve/PTF/PTFPlotRequests.js
- src/firefly/js/templates/lightcurve/SettingBox.jsx
- src/firefly/js/templates/lightcurve/basic/BasicMissionOptions.js
- src/firefly/js/templates/lightcurve/generic/DefaultMissionOptions.js
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsListTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsTest.java
Two tickets were implemented together.  A new PTF form is created and added. Corresponding actions in the form were implemented.
> IRSA-540, IRSA-541:Add PTF case to Time Series Tool

- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
After using plotly, the period is no longer displayed.
Thie reason is that  LcPeriodPlotly failed to save the period value to the store.
To test:
1. check out this branch and build firefly
2. There is no change in ife.  In ife, check out dev and build irsaviewer.
3. run localhost:8080/irsaviewer/ts.html and then changes period, press "Accept".
> IRSA-611:Period value isn't display anymore in result view

- src/firefly/html/css/global.css
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackageMaster.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/BackgroundEnv.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableResultsReducer.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/ui/FormPanel.jsx
https://jira.lsstcorp.org/browse/DM-10345
Normally, when a search is submitted, a table will appears masked with a loading icon.
The masked panel will be replaced with table data when the search results returned.
With this PR, when a search is backgroundable, a 'send to background' button will be added to the bottom of the loading icon.    If pressed, it will close the masked table and send the search to the background.  The job will appear in the Background Monitor. 
Per Xiuqin request, backgroundable is set to true by default.
This feature will be available to all Firefly's derived projects, ie /irsaviewr, /suit.
To test:
http://localhost:8080/firefly/
- Catalogs search with a larger radius
- While loading, click 'send to background'
- If button is not clicked, it will load when results …
> DM-10345: provide management for long running searches

- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/HistogramProcessorTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/StatisticsProcessorTest.java
Updated and added unit test after HistogramProcessor changed showEmptyBin's default
Add and update the HistogramProcessor unit tests
> IRSA-371:numbins sometimes ignored

- src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoCheckFilter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoVerifyServlet.java
https://jira.lsstcorp.org/browse/DM-11308
Setup PDAC to only allow access to users with 'lsst_pdac' or 'lsst_users' group.
Make sure to select "National Center for Supercomputing Applications" identity provider.
A pull request was also created for code changes in https://github.com/lsst/suit/pull/4
You cannot deploy a version locally.  However, you can test it here: https://facade.ipac.caltech.edu/suit/
> DM-11308: setup PDAC to only allow access to user with 'lsst_pdac' role

- src/firefly/js/templates/lightcurve/LcViewer.jsx
when appTitle is undefined or empty string
https://jira.lsstcorp.org/browse/DM-11094
To test, start Time Series Viewer from SUIT application:
LSST WISE Target: 9.6 -1.1, radius 100,
Check the title. It should not be empty or start with ':'
> DM-11094: use default 'Time Series Tool' title 

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableParser.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/TableDef.java
- src/firefly/java/edu/caltech/ipac/util/DataType.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/js/api/ApiUtilTable.jsx
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
https://caltech-ipac.atlassian.net/browse/IRSA-581
Exposes table selection information to public Firefly API.
Test:  http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
To the right of the 2 table panels, there's a 'show selected' button.
Once clicked, it will display selected 'crval1' and 'crval2' values of the table to the left(http://we..)
Use view source to see code sample.
Here is the added function:
```
/**
* returns an array of all the values for a columns
* @param {string} tbl_id
* @param {string[]} columnNames  defaults to all columns
* @return {Promise.<TableModel>}
* @func getSelectedData
* @public
* @memberof firefly.util.table
*/
export function getSelectedData(tbl_id, columnNames=[])
```
> IRSA-581: Expose to public Firefly API table selection info.

- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/BackgroundStatus.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/WiseLightCurveFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfFileRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfIbeResolver.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfProcimsFileRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfRefimsFileRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundStatus.js
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js
- src/firefly/js/templates/lightcurve/ptf/PTFPlotRequests.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
- src/firefly/js/ui/ScriptDownloadDialog.jsx
- src/firefly/test/edu/caltech/ipac/firefly/server/query/PtfIbeTest.java
This pull request combined 2 tickets IRSA-629 and 630.
One (IRSA-629) causes other one (IRSA-630): in order to get a different download processor (other than the current fixed one for WISE), i have introduced a function to deal with it in the UI form the converter factory.
Then i have added a specific server-side processor to package the files to be downloaded with the help of Wei's ticket (IRSA-514). Firefly has IBE for PTF included now. 
There is a current issue with the background monitor (@loi will fix it soon), once is fixed, the test should be going to the Timeseries tool and upload a LC for PTF, then select any row of the table and download the file(s) to test.
> IRSA-629 and IRSA-630: add generic way to get downloader in time series tool

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java
- src/firefly/js/metaConvert/LsstSdssRequestList.js
- src/firefly/js/metaConvert/WiseRequestList.js
- src/firefly/js/templates/lightcurve/wise/WisePlotRequests.js
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTImageSpatialType.jsx
https://jira.lsstcorp.org/browse/DM-11299
This is continuation of Cindy's work on WISE cutouts
- when subsize is present in request, we assume that the image is cutout for both WISE and LSST.
- When cutouts are requested for LSST deepCoadd images, I_16 of [ImageServ API](https://confluence.lsstcorp.org/pages/viewpage.action?pageId=54854064) is called.
Unfortunately, the code should be fixed on DAX side. At the moment we get HTTP 404 Not Found for band 'r' and HTTP 502 Bad Gateway fro other bands. Test target 9.6 -1.1 
Known issues:
- I_16 of [ImageServ API](https://confluence.lsstcorp.org/pages/viewpage.action?pageId=54854064) produces error (LDSS SDSS deepCoadd image cutouts)
- Spinning wheel on table fetch error (addressed in another …
> DM-11299 Coadded images displayed ignoring cutout size

- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/ui/ColorDialog.jsx
Fixed color stretch issue:
This pull request  implemented two tickets, IRSA-572 and IRSA-586.  
1. On the client side, when the specific color tab is selected for doing stretch, only this band's data is stored in the stretch data and dispatched to the server.
1. On the server side, when the recompute stretch is performed, its update the range values and the band index.  Thus, only the corresponding band's data is stretched with the new range values.
To test,
Please check out this branch and search a color images with one, two and three bands.  And then do the color stretch at each band.
> IRSA-572:Color stretch for three color does not work

- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcUtil.jsx
- src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js
- src/firefly/js/templates/lightcurve/ptf/PTFPlotRequests.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
Simple changes to disable band selection for PTF (which is not needed in PTF case).
> IRSA-636 Disable the band selection for PTF

- src/firefly/js/visualize/saga/CoverageWatcher.js
- fixed: IRSA-642: coverage not showing
- fixed: DM-11250: losing color and shape changes
> IRSA-642-DM-11250: fixed two bugs

- README.md
- src/firefly/java/edu/caltech/ipac/firefly/public/generic_footer_minimal.html
- src/firefly/java/edu/caltech/ipac/firefly/public/irsa_footer_minimal.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
- on fail search, mask panel remained without error messages.
- API should have backgroundable set to false, since background monitor may not be available.
https://jira.lsstcorp.org/browse/DM-11376
use ticket to duplicate a search which will produce error.
use http://localhost:8080/firefly/demo/ffapi-highlevel-test.html to see that api searches are not backgroundable.
> DM-11376: backgrounding job bug

- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfIbeResolver.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/PtfIbeTest.java
I've added the logged in cookies to IBE in Firefly/TimeSeries tool. Also updated a test.
> IRSA-257: add cookies to PTF ibe LC for loggedin user

- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/SimpleComponent.jsx
https://jira.lsstcorp.org/browse/DM-11458
Fixes what's described in the ticket.
Also, fixes finderchart multi-position table not showing.
> DM-11458: Periodogram table rows are no longer selectable and highlighted

- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- when a image is clicked on, it will not longer jump to the center
- when the number of images are changeed then the images will
recenter
_to test:_
- bring a time series up and change the number of images, they should recenter.
- click on an image, it should not jump to the center. However, everything else should work as before.
> DM-11398: fixes some time series display issues

- src/firefly/html/demo/ffapi-slate-test2.html
the update includes the content and the cosmetic stuffs of the charts on ffapi-slate-test2.html, 
The content of the charts based on the WISE search is updated as follows, 
2D scatter: w1-w2 and w2-w3 for x and y
heatmap: 3 sets, w1 vs. w2, w1 vs. w3, and w1 vs. w34.
histogram: 2 sets, w1, w2.
3D scatter: w1, w2, w3 for x, y, z.
All updates are in sync with the grid view demo sample in firefly_client,
https://github.com/Caltech-IPAC/firefly_client/pull/15
> DM-11556 Update chart content of grid-view sample, ffapi-slate-test2.html

- src/firefly/js/templates/hydra/HydraViewer.jsx
Part of the branch implementation was about fixing a bug in HydraViewer.jsx.  The closable is not defined in the layout mode. Thus, the closable is always no defined.
However it is used in all three contaniners as closable={closeable}.  Since the closeable is always undefined, it caused the
the xyPlot's, imagePlots, the close button was gone.
The other part is done in IFE.
> IRSA-503:Migrated Finderchart needs a control button to switch from table view to chart view and vice-versa

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
- src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js
- src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
https://caltech-ipac.atlassian.net/browse/IRSA-689
To test:
- build irsaviewer then goto http://localhost:8080/irsaviewer/timeseries
- use a wise time series file or the ptf file in the ticket.
- select all then download.
wise should work.  ptf fail for me.  I got an unhandled exception.
But, both were added to background monitor as it should be.
@ejoliet, you should have someone look at the exception below.  It should not happen.
```
java.lang.ArrayIndexOutOfBoundsException: 0
at edu.caltech.ipac.firefly.server.query.lc.PtfFileGroupsProcessor.computeFileGroup(PtfFileGroupsProcessor.java:87)
at edu.caltech.ipac.firefly.server.query.lc.PtfFileGroupsProcessor.loadData(PtfFileGroupsProcessor.java:41)
at edu.caltech.ipac.firefly.server.query.FileGroupsProcessor.getData(FileGroupsProcessor.java …
```
> IRSA-689: Time Series Viewer Prepare Download doesn’t send to Background Monitor

- src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
Tile reordered fixed. See IRSA-685. This is a fix in RC.
Please, have a look by testing demo/ffapi-highlevel-test.html to open a couple of images in tri-view and see that when bringing the list of images, the order doesn't change. 
Thanks!
> IRSA-685 img tile reorder

- src/firefly/js/drawingLayers/PointSelection.js
- src/firefly/js/visualize/draw/DrawLayer.js
- src/firefly/js/visualize/ui/DrawLayerItemView.jsx
this development includes:
- disallow the user to delete the PointSelect overlay from the overlay dialog. 
- adjust the layout of 'color', 'symbol' and 'delete' link on the overlay dialog. 
Test:
- get an image from firefly or time series tool
- check 'Lock on click', the 'Overlay display' icon is shown with '2' on the corner, 
- add a PointSelect marker on the image, and click the 'Overlay display' icon, the PointSelect is not deletable from the overlay manipulation dialog. 
- add other overlay layers to see the arrangement of 'color', 'symbol', and 'Delete'  on the overlay dialog. 
- delete the PointSelect overlay by un-checking 'Lock by click'
> DM-11350 PointSelect Marker can not be added after the overlay layer is deleted

- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
_to test_: 
ticket description: https://caltech-ipac.atlassian.net/browse/IRSA-701
also- confirm time series stays in alignment which which between 1-3-5-7
_Note 8-25-17_: fixed server more bugs:
- found more much in wcs match and target match   
- Target match being lost in certain cases   
- Selection showing image bounds in unrotated case   
- Expanded view not sizing to fit when more plots are added   
- In certain cases deleting a plot was causing an exception
> IRSA-701: fixed wcs match getting out of aligement when multi image viewer goes from single to multi

- src/firefly/js/visualize/iv/PlotTitle.css
Improve image title label by changing the line height (css). 
This is also solving the problem that in smaller screen, the zoom level wasn't shown. 
Check that it doesn't break anything.
> IRSA_672: improve image lable for plot title inline

- src/firefly/html/demo/ffapi-slate-test3.html
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/tables/TableUtil.js
This development includes:
- render plotly charts by giving any plotly data and layout JSON description. 
- put Firefly like tool bar for each plotly chart either recognized or unrecognized by Firefly. The tool bar rendering is classified into the following groups, 
1. basic tool bar with buttons for 
download chart as PNG + show/edit filter + chart options and tools + Expand panel (for Pie) 
2.  1 + buttons for 
Zoom to the original range + Zoom + Pan (for Histogram, bar, box)
3.  2 + buttons for  select (for each trace with x, y data directly mapped to table  numerical columns, like scatter, histogram2d, histogram2dcontour, heatmap)
4.  2 + buttons for orbital rotation + turntable rotation
(for 3D-like charts, such as scatter3d, surface, mesh3d) 
- update the chart options and tools …
> DM-11477 Make plot.ly plotting API to handle Firefly unrecognized charts types cleanly

- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/NedSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/ui/NedSearchPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
I've added a NED panel and a processor to postprocess the result VOTable.
The panel has been added to the main component used in IRSA: CatalogSelectView.jsx
To test: go to irsaviewer, bring catalog search and go to NED tab. Enter favorite extragalactic object. The result should be a table with a object name column clickable that goes to NED with more details. 
Please, have a look and let me know.
> IRSA-670: adding NED search

- buildScript/depends.gincl
- buildScript/gwt.gincl
- buildScript/gwt_webapp.gincl
- config/common.prop
- docker/proxy-dev/Dockerfile
- docker/proxy-dev/build.gradle
- docker/proxy-dev/others/openid.conf
- docker/proxy-dev/others/proxy.conf
- docker/proxy-dev/others/site.conf
- docker/proxy-dev/proxyctl.sh
- docker/proxy/Dockerfile
- docker/proxy/build.gradle
- docker/proxy/others/proxy.conf
- docker/proxy/proxyctl.sh
- settings.gradle
- src/fftools/build.gradle
- src/firefly/java/edu/caltech/ipac/firefly/server/security/AuthOpenidcMod.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoCheckFilter.java
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/util/WebUtil.js
- use letsencrypt for public site, and self-signed for development
- add support for authentication via mod_auth_openidc
- expand build script to exposes configurable global variables to javascript
**self-signed https proxy locally.**
cd ./firefly; docker/proxy-dev/proxyctl.sh update
this will create and run the apache proxy in docker.  access it on port 80 or 443.  i.e.  http://localhost/
**javascript global variables**
to make any configuration property a javascript global variable, append '__$' to it.  i.e.  __$help.base.url
> DM-11547: dockerize apache https proxy.

- src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
Added the cookies to the download URL for IBE when a user is logged in via SSO for example.
This fixed the previous change https://github.com/Caltech-IPAC/firefly/pull/430 which was made on the FileInfo but the file was already fetched by then. The set of the cookie has to happen elsewhere. The issue was partially fixed in the PtfIbeResolver which was using the authentication cookies but the images were not.
> IRSA-257 (amended): added cookies when getting IBE url download

- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/html/demo/ffapi-slate-test2.html
- src/firefly/html/demo/ffapi-slate-test3.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyScatter.js
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/charts/ui/XYPlotPlotly.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
https://jira.lsstcorp.org/browse/DM-11601
- Renamed API function showPlot to showChart and removed fireflyData and fireflyLayout from its parameters.
- Firefly specific options are now under firefly property of data and layout, trace type can be fireflyScatter, fireflyHistogram, and fireflyHeatmap for Firefly extended charts.
- Updated addChart action creator to take care of this change and split plotly and firefly info on the fly.
- Added a workaround for hover text appearing without background in Firefox.
> DM-11601 showChart API changes

- src/firefly/html/demo/ffapi-slate-test3.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYGenericProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/XYWithErrorsProcessor.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyScatter.js
This development includes
- a generic search processor to handle column expression which is  related to at least on numeric column or one 'text' column from the searched table.  
- a generic chart data handler to create table source entries to get plotly chart data from the server when the trace data is defined on table columns, like x: 'tables:w1mpro+w2mpro'. The data related keyword is not limited to be like 'x' or 'y' only in the JSON description. It varies based on the chart type, ex. pie chart has data defined on 'labels' and 'values'. 
Test: 
try  to run ffpai-slate-test3.html in which the data of some charts is defined in column expression style.
> DM-11603 Make column expression to work for all plotly charts 

- src/firefly/html/demo/ffapi-slate-test3.html
- src/firefly/html/demo/ffapi-slate-test4.html
- src/firefly/html/demo/ffapi-slate-test5.html
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- reorder the traces before plotly rendering such that the active chart is rendered on top of others. 
- assign the name and color relevant values to the trace in case those are not assigned initially. 
- create 2 demo apps, one is to render charts with multiple traces of the same type (ffapi-slate-test4.html) and the orher is to render charts with traces of mixed types (ffapi-slate-test5.html). 
test: 
run demo/ffapi-slate-test4.html to test the selection of active trace 
run  demo/ffapi-slate-test5.html to test the selection of active trace on the chart with mixed types. 
note: the chart rendering is based on the selection of active trace and the following rendering priority among different chart types (observation from the samples): 
pie -> scatter -> …
> DM-11604 Support showing the active chart trace

- src/firefly/js/Firefly.js
_to test:_
Load firefly.  It should work.
> DM-12208: Check if the document is loaded before rendering firefly

- src/firefly/html/firefly-dev.html
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ExternalMasterDataSource.java
- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/ImageSelect.css
- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/ui/NewImageSearchPanel.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-924
- add select/deselect all at the dataproduct(project) level
- fix mission filter now that mission info is available
- make count returns the number of dataproducts instead of dataset(images)
- make CollapsiblePanel's header takes a string or a component.
- make ImageSelect requires a way to register changeListener
- add option to FormPanel to allow unmounted fields in the request
- set NewImageSearchPanel to take unmounted fields
- fix firefly-dev.html not showing images after embedded db merge
- fix NewSearchPanel not submitting search after previous PR merge.
To test:
http://localhost:8080/firefly/firefly-dev.html
- Image Concept
- enter position, select dataset(s), then click search.
> IRSA-924: fix issues found in new image search

- config/app-test.prop
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/data/WspaceMeta.java
- src/firefly/java/edu/caltech/ipac/firefly/server/LocalFSWorkspace.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/LocalWorkspaceHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WebDAVWorkspaceHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WorkspaceFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/Workspaces.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsCredentials.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
- src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsIrsaTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsListTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsPropTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsPutGetTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsServerCommandTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsTest.java
I’ve added the server side commands. Please have a look and we can discuss it.
I’ve left out the region files and packaging because it totally different path and I have doubt on how to do it, we probably need to in particular.
The ticket has more details on the JSON format and the server parameters expected.
I’ve also added tests, just ask me the password for running them or debug. Remember that the implementation used is defined in the properties and currently we support only authenticated workspace. The commands rely on a util class that uses a workspace manager, that can be switch to other implementation. The vospace protocol is behaving differently so i’m not sure if the classes will need adjustment in the future for different protocol.
> Irsa 729 add ws commands

- src/firefly/java/edu/caltech/ipac/firefly/data/FinderChartRequestUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/data/fuse/provider/FinderChartDataSetInfoConverter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/Packager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceDesc.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
I've added the files download for SEIP (and AKARI when IRSA-820 is done on client side) on server for Finderchart. There is same branch name in IFE.
Build from there Finderchart, and test searching for SEIP/WISE, try to download pdf, html png and fits.
I've also fixed a rounding problem for small size (<1MB) displayed in background monitor status.
Let me know.
> IRSA-870: added PDF, HTML, PNG and FITS files download for seip and akari

- buildScript/depends.gincl
- buildScript/webpack.config.js
- config/app.config
- config/common.prop
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/util/BrowserUtil.js
- src/firefly/js/util/WebUtil.js
https://jira.lsstcorp.org/browse/DM-11856
- define '__$' as a prefix to indicate client property
- added getProp() to WebUtil.js to access the property on the client
See `help.base.url` in config/app.config as an example.
Everything should work as before.  More changes under the sam branch in ife and suit as well.
> DM-11856: framework for client properties defined at build time

- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-810
Also:
- added flow:horizontal option to SearchPanel to display search items horizontally on top
- clean up FinderChart's form layout
More changes are in ife under the same branch
To Test:
- build finderchart in ife
- goto http://localhost:8080/applications/finderchart/
You should see that the left navigation panel is now replaced by a top tab-style navigation.
I've also removed borders, margin and padding to have a cleaner look.
Let me know what you think.
> IRSA-810: Replace left hand options links to top left hand tabs (FinderChart)

- buildScript/gwt_webapp.gincl
- config/app-test.prop
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/download/DynFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/StatisticsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/TableFunctionProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/WiseLightCurveFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTFileGroupProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/util/DataObject.java
- src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/EmbeddedDbUtilTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableTest.java
- Converted code relying on an ipac table file as source of the table data.
- Added unit testing for EmbeddedDbUtil
https://caltech-ipac.atlassian.net/browse/IRSA-964
Additional changes are in ife and firefly_test_data under the same branch.
To test:
http://localhost:8080/firefly/ts.html
- upload a file to view its time series data.
- select multiple rows then select "Prepare Download"
- the images from the selected rows should be downloaded.
This was not working prior to this PR.
> IRSA-964: TimeSeries tool: downloading images from selected rows is broken

- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/ui/NewImageSearchPanel.css
- src/firefly/js/ui/NewImageSearchPanel.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
Add source and type options
Changed the RadioGroupInputField and RadioGroupInputFieldView to allow a customized label style
Combine two .css file to one as NewImageSearch.css
Note:  
For three color images, only irsa works.  You have to check both missionId and band.  More work is needed to get three color images work.
> IRSA-793 IRSA-798-add image type option to main panel add image source panel option

- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/dataTypes/HistogramCDT.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
https://jira.lsstcorp.org/browse/DM-12616
- To make sure all data are sent, set pageSize to MAX_ROW when creating when creating a request on the client.
- Also fixed sticky error
To test 
- cd firefly_client/examples 
- jupyter notebook
- http://localhost:8888/notebooks/slate-demo-explicit2.ipynb
- run the last cell twice
> DM-12616 Partial decimated data returned by a duplicate request

- buildScript/gwt_webapp.gincl
- src/firefly/js/charts/PlotlyConfig.js
- src/firefly/js/util/WebUtil.js
Jira ticket: https://jira.lsstcorp.org/browse/DM-11341
This is the firefly part of DM-11341: exception when creating Jupyter widgets. The exception is caused by unsuccessful loading of the minified plotly script ([plotly-1.28.2.min.js](http://irsa.ipac.caltech.edu:80/irsaviewer/plotly-1.28.2.min.js))
Since jupyter widgets are defined as AMD modules, plotly assumes that we are loading it in AMD/RequireJS context: if("function"==typeof define&&define.amd)define([],t), which results in anonymous define error and Plotly not being loaded. According to webpack docs, the bundle with undefined library name, like this, "will not work as expected, or not work at all (in the case of the almond loader) if loaded directly with a <script> tag." (See Module Definition Systems …
> DM-11341: exception creating firefly Jupyter widget

- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
- Include col 'pos' for catalog master table, only 'all sky' is searched in case the catalog/table has no position information. (value at column 'pos' is 'n' instead of 'y')
- replace the select/option tag for spatial search with 'All Sky' text at the spatial selection panel for the catalog/table without position information.  
test:
go to localhost:8080/firefly and do catalog search 
If a table with position information is selected,  the position search method option list is shown at position search area and ready for selection. 
If a table without position information is selected (i.e. Select Project: 'Gaia', Select Catalog: 'Gaia DR1 Database', table: 'Gaia G-band Time Series of Variable Sources'), the position search is disabled and only 'All sky' is …
> DM-11374 Disable position search on catalogs/tables without position information

- .eslintrc
- src/firefly/html/firefly-dev.html
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterData.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterDataEntry.java
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/ImageSelect.css
- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/reducer/PlotTitle.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.css
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-748
Also includes:
- https://caltech-ipac.atlassian.net/browse/IRSA-955
- https://caltech-ipac.atlassian.net/browse/IRSA-956
- fix TargetPanel resolution in API demo pages
- fix API showImage and showCoverage not setting the right viewer's option
Build firefly and irsaviewer on this branch
Anywhere image search/load is available, the new ImageSearchPanel will appears.
This includes API, Gator, and elsewhere in firefly.
When updating current image, then panel allow for only 1 image to be selected.
Otherwise, you can select more than one, and have them all loaded at once.
@cwang2016 , will you help check to see if any features missing in this new panel.
@robyww , will you do the same.  Also, you want to look over the small changes I made to …
> IRSA-748: Replace image search with new ImageSearchPanelV2

- src/firefly/js/visualize/draw/MarkerFootprintObj.js
- src/firefly/js/visualize/region/RegionDescription.js
This development fixed the code on saving PNG or region files for the image with marker or footprint objects and the associated text labels. 
test: 
- go to firefly, do image search
- add marker or footprint onto the image
- save the image to PNG and region files 
- check the content of the saved PNG 
- repeat the same image search, upload the saved region file and compare the plot to the original image rendering with the markers or footprints.
> DM-10925 Fix the method to save PNG or region files for the image with marker or footprint objects

- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
The development fixes the error when adding marker or footprint to the drawing layer containing the plot without image, 
- skip adding the marker or footprint to the plot that is attached to the marker/footprint drawing layer and has no image. 
- disable the buttons on the toolbar in case the selected plot containing no image. 
test case 1:
go to firefly do image search, 
target: m31, 
select all images under  'SDSS' and 'WISE All-Sky Altas'
result: No image found for SDSS, and  buttons on the tool bar for those plots are disabled. 
test case 2:
go to finderchart do multiple positions search. 
upload file 'forirsa_ref1.tbl' as attached in https://jira.lsstcorp.org/browse/DM-12940
Marker tool can be added to all plots with images with no error.
> DM-12940 Fix the error while adding marker or footprint to the plot without image

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java
- src/firefly/java/edu/caltech/ipac/util/expr/Parser.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/util/expr/Parser.js
- fixed filter from chart when column expressions are used
- use db to calculate column expression values for general charts
- allow same columns to be used for x and y
What is not done:
- I might need to update DecimationProcessor and HistogramProcessor as a part of this PR.
- Expression validation is still done using old Expression parser. Column expression input field tooltip is updated with the operators and functions that are common for both java/js expressions and h2 db. A separate ticket will address column expression validation issues. 
- XYGenericProcessor and XYWithErrorProcessor can not be removed while we are using old single-trace chart architecture. After we finally switch to multi-trace charts, we should remove the code supporting old charts.
> DM-12949 column expression issues in charts

- src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
https://caltech-ipac.atlassian.net/browse/IRSA-1283
also:
- allow more robust string filtering using '%' wildcard
- string comparison is set to case-insensitive
- added filter for null in both numeric and text columns
- numeric column defaults to '=' when not entered
sample filters:
```
like 'j%425%.1'
is null
is not null
```
can be tested in any table.
> IRSA-1283: Fixed string column filtering

- src/firefly/java/edu/caltech/ipac/firefly/resources/LSSTMetaInfo.json
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
https://jira.lsstcorp.org/browse/DM-12993
- added NEOWISE data to PDAC search panel, 
- suit is now using multitrace charts, 
- fixed chart display for columns of type 'long' (was getting error before)
- when columns are used to create scatter, tooltips should show the same data we see in table cells
Please, check out the corresponding branch in suit to test:
To test
1. Build both firefly and suit:
`cd ../firefly; gradle :firefly:clean; gradle :firefly:bAAD; cd ../suit; gradle :suit:bAAD`
2. Connect to ncsa vpn
3. http://localhost:8080/suit
Choose NeoWISE from project list (there is only a single catalog table)
Working samples from DM-12992:
```
curl -o neowy1.json -d 'query=SELECT+*+FROM+neowiser_yr1_00.neowiser_yr1_p1bs_psd+WHERE+qserv_areaspec_circle(9.469,-1.152,0.01);' …
```
> DM-12993 Add NEOWISE data

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessorWrapper.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTFileGroupProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMultiObjectSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/test/edu/caltech/ipac/firefly/server/query/LSSTDbServTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/query/LSSTImgServTest.java
https://jira.lsstcorp.org/browse/DM-13192
The purpose of this PR is to convert from [DAX ImageServ v0](https://confluence.lsstcorp.org/display/DM/Update+for+ImageServ+API+-+v0) to [DAX ImageServ v1](https://confluence.lsstcorp.org/display/DM/ImageServ+API+-+v1)
- converted URLs to work with ImageServ v1
- added unit tests to check for successful HTTP status when retrieving table and images from DAX (when DAX services are available)
- bug fix: applications with no workspace, should not initialize it
- bug fix: catalog watcher should not throw exception when center cols are missing and only corner cols are present
- bug fix: filter syntax should be `"filterName" LIKE 'u'`
- avoid unnecessary wrapping of DataAccessException
To run tests:
gradle -Dtest.single=LSSTDbServ :firefly:test
gradle …
> DM-13192 ImageServAPI v1

- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/HiPSCntlr.js
this development includes, 
- fix client table filtering by using 'like' and 'in' expression styles. 
- convert 'like' condition into regular expression match for client table filtering. 
test:
use firefly-dev.html
select tab 'Test Searches' and then tab 'HiPS'
uncheck 'Popular HiPS' to get more table content, this is a client table. 
try filtering examples: 
type: in (cube), in ('cube') or in ("cube")
like cube, like 'cube' or like "cube"
title: like 2mass
url: like spit%.caltech or spit\%.caltech
> DM-13241 Fix client table filtering issues on 'LIKE' and 'IN' conditions

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/drawingLayers/Artifact.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/tables/TableInfoUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
https://jira.lsstcorp.org/browse/DM-12864
If the table with no positional info is the first rendered in firefly, no coverage or chart area will show.
If other tables are added, the coverage and chart areas will not disappear, when changing the active table. This is intentional behavior to avoid confusing layout changes.
An example of a table with no position info WISE -> AllWISE Inventory Table 
Other bugs fixed:
- non-returning search
- removed chart hanging in the store
- empty result area with no drop down, when all tables are deleted
- missing layout updates
> DM-12864 Coverage and chart rendering on Tri-View when a catalog without position information is searched

- config/app.config
- config/ehcache.xml
- docker/base/setenv.sh
- docker/k8s/dashboard-users.yaml
- docker/k8s/firefly.yaml
- docker/k8s/kubernetes_setup.md
- docker/k8s/misc/busybox.yaml
- docker/k8s/nginx-controller.yaml
- docker/k8s/nginx-svc.yaml
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
Setup Kubernetes on 3 machines; one master and 2 nodes.
```
VMs: irsawebdev9,10,11
Debian 8
irsawebdev9 -> master
others -> nodes (workers)
Kubernetes: v1.8.5
Docker: v17.03.2
Pod Network: Weave Net
```
NGINX Ingress Controller
- load balancing
- cookie-based session sticky
- self-signed ssl certificate
Firefly
- from DockerHub with tag "k8s"
- Debian 9, Tomcat 8
- Dashboard
-recommended setup with an admin-user account.
Unresolved Issues:
- cache replication not working (multicast)
- setup authentication module
- setup Let's Encrypt, or use a CA issued cert.
> DM-12950: Experiment with setting up kubernetes at IPAC for SUIT firefly deployment

- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/data/table/SelectionInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/TableDef.java
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/SelectInfo.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableRequestUtil.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableDataReducer.js
- src/firefly/js/tables/ui/TablePanel.jsx
https://jira.lsstcorp.org/browse/DM-11457
As described in the ticket, selection info should be kept after sorting and filtering.
In the case of filtering, when a selected row is removed due to a filter, it will be removed from selection info as well.  This is to ensure that the selection info is valid for the current view.
For example:
- select all, apply a filter.
- all rows are still selected.
- clear filters
- only the previously selected rows are selected.
Also in this ticket, `null` values are sorted to top for ascending and to the bottom on descending.
This ticket can be tested on any table.
> DM-11457: Selected table rows should be kept after sorting

- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/drawingLayers/ImageOutline.js
- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/SelectBox.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/task/PlotAdminTask.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/ui/DrawLayerItemView.jsx
- src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
The development is made per ticket of 
https://jira.lsstcorp.org/browse/DM-13326
- remove the select area layer after the selected area is cropped or zoomed (to fit selected area)
- for circular selection, a circular region in red is shown on the top of cropped or zoomed (to fit selected area) image in order to indicate the selected (elliptical) area. This is done by using ImageOutline drawing layer, and ImageOutline drawing layer is updated to be generic to contain any Firefly defined drawing object. 
- the image is re-centered at the center of the selected area in case 'recenter image to selected area' is clicked after 'select an area'. 
- Fix the select area help text shown in overlay display menu. 
test:
do image search on Firefly, 
click 'select area' button and make 'Elliptical …
> DM-13326 Fixed issues on circular selection per feedback from IRSA tester

- src/firefly/js/api/ApiBuild.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/api/ApiUtil.js
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/MasterSaga.js
- src/firefly/js/core/ReduxFlux.js
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/templates/fireflyslate/FireflySlateManager.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/ChartsSync.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
https://jira.lsstcorp.org/browse/DM-13265
- Use spawn when using dispatchAddSaga. This prevents the unhandled exceptions in one saga to cancel all the siblings.
- Use fork with dispatchAddActionWatcher, because we are catching the unhandled exceptions. If an exception occurs in the callback, it won't cancel the saga.
- Added documentation for actionWatcherCallback
- Fixed a bug preventing remote charts on the test page 
- converted some dispatchAddSaga to dispatchAddActionWatcher, including coverage and image metadata watchers and firfely.utl.addActionListener API method. 
Test case:  http://localhost:8080/firefly/demo/ffapi-highlevel-test.html  Open console to view the output, "Start selection extensions", "Track mouth readout". Before, you would get an error when switching readout from …
> DM-13265 Saga error handling

- src/firefly/html/firefly-dev.html
- src/firefly/html/firefly.html
- src/firefly/js/Firefly.js
- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/HiPSCntlr.js
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
This development is for 
https://jira.lsstcorp.org/browse/DM-13489
- add app option to turn on or off HiPS image from the image search panel. 
- add HiPS selection to the search panel:
section 1: add HiPS button
section 2: image sources includes 'search' and 'url'
section 3: entries for target and field of view
section 4: entries for url in case image source is from url, or a table showing list of HiPS surveys for HiPS search in the image source is from 'search'
- Support HiPS loading with a URL via API as described in 
https://jira.lsstcorp.org/browse/DM-13286
test:
do HiPS image search by choosing the following items on Image Search panel, 
- section 1, image type, HiPS, 
- section 2, image source, 'Search' or 'URL',
- section 3, target (optional) and field of view (default is 180 …
> DM-13489 Modify image dropdown to support HiPS and modify HiPS loading with a URL via API

- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/TwoMassIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/firefly/data/FinderChartRequestUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceDesc.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
- src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java
- src/firefly/java/edu/caltech/ipac/visualize/net/TwoMassImageParams.java
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/saga/CoverageChooser.js
- src/firefly/js/visualize/ui/ImageSelectPanelResult.js
I've updated the function that make the 2mass request image from the client side. This was a change needed after IRSA-1447.
Please, check that 2mass image are back in Finder Chart (same branch name in IFE) and when coverage 2mass image is chosen.
I saw already a problem that i couldn't figure it out in Safari. Chrome is fine.
> IRSA-1581: 2mass image request fix when survey was implicitly value asky

- config/app.config
- src/firefly/config/app.prop
- src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-hips-master-table.csv
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/CDSHiPSListSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/IrsaHiPSListSource.java
- src/firefly/js/drawingLayers/HiPSGrid.js
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/HiPSListUtil.js
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/MenuItemKeys.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/VisToolbarView.jsx
- Remove HiPS grid icon from the toolbar, Add HiPS grid layer with the checkbox turned off (the layer is hidden by default) when a new HiPS is added. 
- Add support for calling IRSA hips list,
. Update App config file by adding information related to IRSA HiPS map service 
. Each item in the HiPS list has unique value for HiPS property creator_did. 
. Extract title value from property creator_id for IRSA HiPS list
Note: please checkout ife with the same branch name 'DM-13797-rmHiPSGridIconIrsaHiPSList'. 
test:
do HiPS image search. 
For this PR, HiPS map list is formed by sending request to IRSA HiPS map service, 
https://irsadev.ipac.caltech.edu/data/hips/list
> DM-13797 remove HiPS grid on and support to IRSA HiPS list

- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/ZoomUtil.js
This development:
Add arcminute-scale range to HiPS image FOV display in the image title. 
- The FOV display will be changed from degree to arcminute if the value in degree is less than 1.0, and changed from arcminute to arcsecond if the value in arcminute is less than 1.0. 
- The value is display in two significant digits. 
Test:
do HiPS image search by selecting a HiPS from the HiPS map list. 
zoom in the image to see that FOV number dropps and the unit changes from deg to arcminute and then to arcsecond if the zooming is not beyond the limit.
> DM-13919 add arcminute-scale rage to HiPS image FOV display

- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/ui/ZoomButton.jsx
-  fixed image recenter problem
- also fixed the max zoom message show zoom level with HiPS
_to test:_
- recenter: bring in 4 images, then bring image a hips.  The image should stay centered.
- zoom: bring in a HiPS and zoom it all the way.  The message should not show a zoom level.
> DM-13780: fixed image recenter problem

- src/firefly/html/demo/ffapi-coverage-test.html
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Do the following:
- Cube: fixed the bugs related to moving between HiPS cubes and regular hips
- Cube: honor the data_cube_* properties and show information about the 3rd dimension
- Use: `value = crval3 + (cubeIdx - crpix3 ) * cdelt3`
- Make field of view and target optional
- Use the HiPS properties if they are not specified.
- If neither are specified show 180 degrees at 0,0
_To Test:_
- bring up a cube and switch to a regular images, there should be no issues
- bring up a cube, by the controller should be information about the 3rd dimension
- bring a up HiPS without enter fov or target, (DSS is a good example). It the properties are specified it will set the FOV and the target
> DM-13989: FOV and cube issues

- docs/firefly-api-overview.md
- src/firefly/html/demo/ffapi-sed.html
- src/firefly/html/demo/sedSample.xml
- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/mapper/DataGroupUtil.java
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/ChartSelectPanel.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/util/expr/Expr.js
- src/firefly/js/util/expr/Parser.js
https://irsawebdev9.ipac.caltech.edu/dm-7991/firefly/
https://jira.lsstcorp.org/browse/DM-7991
To test, use firefly/demo/ffapi-sed.html 
(Note the use of chart options there: `{singleTraceUI: true, upperLimitUI: true}` - the default values for both options are false.)
- Upper limit column or expression is stored in fireflyData[traceNum].yMax, using the same notation as for other mapped columns.
- Upper Limits are represented by annotations (arrows pointing down).
- Since Plotly stores annotations in the layout, trace annotations needed to be implemented.
Per trace annotations are stored in fireflyData, and are constructed when the data arrive. 
The annotations in plotly layout are constructed from the original annotations (moved to fireflyLayout.annotations) and trace annotations before …
> DM-7991: handling upper limits

- src/firefly/html/demo/ffapi-hips-test.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/visualize/task/PlotHipsTask.js
The development 
- adds 'showImageOrHiPS' into Firefly API. 
- for showImageOrHiPS, either HiPS or regular image will be rendered based on certain criteria including that HiPS request will take the priority in case image request doesn't have target position specified. 
test: 
start firefly/demo/ffapi-hips-test.html
> DM-12973 add showImageOrHiPS to API and update demo app

- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/CDSHiPSListSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/IrsaHiPSListSource.java
- update the method to retrieveHiPSData in which the target file path is modified to contain the path portion plus some extra string in case the url contains query portion. 
test:
- clean the work area relevant to HiPS data 
- do HiPS search on IRSA, CDS, check the produced HiPS data produced 
- repeat firefly and HiPS search and the search is resulted faster than earlier search.
> DM-14046 Cache HiPS list and properties search result

- src/firefly/html/demo/ffapi-coverage-test.html
- src/firefly/html/demo/ffapi-hips-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterListEntry.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/AppDataReducers.js
- src/firefly/js/drawingLayers/HiPSGrid.js
- src/firefly/js/drawingLayers/HiPSGridlUI.jsx
- src/firefly/js/ui/PopupUtil.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/visualize/HiPSListUtil.js
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/iv/HiPSTileDrawer.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/ui/ZoomButton.jsx
Fixed various small HiPS issues
- async ivo resolve and coverage tweeks (DM-14018)
- allows and empty target after a valid target (DM-14018)
- title issues fixed (DM-14018)
- catch potential hips_initial_fov errors (DM-14018))
- Layer control grid lock level maxes out at 14 (DM-14016)
- HiPS zoom can go down to 14 (DM-14016)
- HiPS grid is now `HEALPix (HiPS) Grid` (DM-14016)
- Better error messages (see IRSA-1663)
_to test:_
Test #:
1. in ffapi-hips-test.html set `hipsRootUrl` to a ivo id and see it if works.
1. in the image query panel set a target, load a  hips, uncheck the lock, go back to the query panel, delete the target so it is empty, load another hips, they should load at the same place
1. zoom way in to a hips.  It should go to level 14
1. It is hard to test all the error …
> DM-14018, DM-14016, IRSA-1663 : Fixed various small HiPS issues

- src/firefly/js/data/form/PositionFieldDef.js
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/util/PositionParser.js
- src/firefly/js/visualize/CoordUtil.js
This development includes:
- Better error messages for position input in more specific description by creating the method to show the existing parsing error messages already in the codes, such as (-34, 23) or (123, -91) in which ra or dec is out of range. 
- fix the position input parsing bug for the following input style
<ra>, <dec> <coordinate system>  (ex. '12.3, 23.4 gal' or '18.0, -23.0 Equ J2000’)
- fix the interpretation bug for the position input in HMS format, like ’12 34 56.89 -23 45 16.56’
Test:
Start Firefly image search
Enter the position input examples as follows, read the position description or the error message if there is, 
(-34, 23)
12.3, 23.4 gal
'18.0, -23.0 Equ J2000’
’12 34 56.89 -23 45 16.56’
> DM-10465 Fix position input parsing bugs or better position input error messages

- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheProvider.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/H2DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupReader.java
- src/firefly/js/tables/tables-typedefs.jsdoc
https://jira.lsstcorp.org/browse/DM-13866
Update status page to include more details on EmbeddedDB.
http://localhost:8080/firefly/admin/status
Add cache eviction strategy for VIS_SHARE_MEM
- cached data expires after 60 minute of inactivity
- force eviction check once every 1 minute.
Add cleanup strategy for EmbeddedDB
There are two stages of clean-up; compact(remove all temp tables), then shutdown(remove from memory)
- Compact DB once it has idled longer than CLEANUP_INTVL
- Shutdown DB once it has expired; idle longer than MAX_IDLE_TIME
- Shutdown DB based on LRU(Least Recently Used) once the total rows have exceeded MAX_MEMORY_ROWS
Current settings:
- CLEANUP_INTVL:  1 minutes
- MAX_IDLE_TIME: 15 minutes
- MAX_MEMORY_ROWS:  250k rows for every 1GB of max heap, between the range of 1-10 …
> DM-13866: Optimize server memory usage

- src/firefly/html/demo/ffapi-highlevel-test.html
- src/firefly/html/slate.html
- src/firefly/js/Firefly.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/HistogramPlotly.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/templates/fireflyslate/FireflySlate.jsx
- src/firefly/js/templates/fireflyslate/FireflySlateManager.js
https://jira.lsstcorp.org/browse/DM-14230
To test
- cd firefly_client/firefly_client
-  jupyter notebook ../examples/
- Use slate-demo-explicit2.ipynb, after creating FireflyClient (fc) and launching browser, add a cell `status = fc.show_chart(data=[dict(x=[1,2,3])])` - make sure the chart shows up and expand works. 
Also added code to remove cell on chart delete, fixed a bug preventing text columns in chart data, and a few other.
> DM-14230 Python API show_chart failure with FireflySlate template

- src/firefly/js/FFEntryPoint.js
- src/firefly/js/ui/ButtonGroup.css
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/ui/ZoomOptionsPopup.jsx
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/PlotTransformUtils.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/iv/PlotTitle.css
- src/firefly/js/visualize/iv/PlotTitle.jsx
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/task/ZoomTask.js
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- src/firefly/js/visualize/ui/ZoomButton.jsx
- buttons to move between hips/fits/aitoff
- zoom switching now includes allsky in algorithm
- auto check box to switch on zoom
- zoom level switch to field of view
- fixed: FOV when image zoomed level is really small
- fixed: order of buttons
- fixed: context toolbar going away when in different context modes
- ButtonGroup option for RadioGroupInputFieldView
_to test:_
- do catalog search, then switch between hips and fits
- try the auto button and zoom
- do a catalog search with m4, then m1
- switch between hips, fits, aitoff
- try auto button and zoom
- try tooltip over field of view for both hips and fits
- notice that there is only field of view, not zoom level
> DM-14157: hips/fits/aitoff switching

- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
https://jira.ipac.caltech.edu/browse/IRSA-1790
Download stopped working for irsaviewer and finderchart.  This is because finderchart created usrkey cookie with path '/'.  When frontpage and finderchart or irsaviewer are running on the same page, usrkey for frontpage was also sent to finderchart causing confusion.
The fix is made to FrontPage.  usrkey for frontpage will have a path of '/frontpage'.
I will deploy the changes to frontpage on irsabannertest1&2.  This should fix the download problem on irsadev.
> IRSA-1790: Download for irsaviewer and finderchart stopped working.

- docker/base/Dockerfile
- docker/base/launchTomcat.sh
- docker/base/setenv.sh
https://jira.lsstcorp.org/browse/DM-12705
It turns out to be a trivial fix.  Firefly's docker template was passing `-Djava.rmi.server.hostname=` property to the jvm, setting RMI host name to blank.  This causes ehcache's RMI replication code to fail during lookup.  
As part of this PR, I was able to confirm that replication is working in k8s environment.
I added some println into CacheEventWorker to monitor replicated cache's event and was able to confirm that data did get replicated between 2 instances of Firefly in a k8s deployment.
For testing purposes, I have a deployment of 2 firefly instances under the url:  https://irsawebdev9.ipac.caltech.edu/loi/firefly/
If you have kubectl installed, you can do the following to see that event messages are replicated between the pods.
`$ kubectl …
> DM-12705: cache replication not working in kubernetes

- buildScript/gwt_webapp.gincl
- config/app.config
https://jira.lsstcorp.org/browse/DM-13776
Add option to build and deploy onlinehelp along with the application.
Changes were made directly in master branch of ife-onlinehelp as well.
To build onlinehelp along with firefly:
`gradle :firefly:onlinehelp :firefly:war`
Deployed to k8s: https://irsawebdev9.ipac.caltech.edu/dm-13776/firefly/
> DM-13776: Add option to include firefly's onlinehelp when building firefly

- src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
- src/firefly/js/visualize/region/RegionFactory.js
Per ds9 documentation, the 'text' region could be defined like
text x y {Your Text Here}
text x y # text={Your Text Here}
text (x,y) {Your Text Here}
text (x y) {Your Text Here}
text string may be quoted with " or ' or {}. 
this development fixes parsing error for text defined with region description (before '#'), like
`image;text 100 200 "My label"`
this fixing is made on both javascript & java sides. 
test (javascript side): 
start demo/ffapi-footprint-test.html
add  the region description into the region editing area like, 
'image;text 700 700 "My text"' 
and click 'Create Footprint Layer'
test (server side):
start a image search, 
upload a region file containing region description like 
`'image;text 200 200 "My text"`
> dm-14758 fixed text display error for region text

- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/draw/ShapeHighlight.js
This development fixes the following issues, 
- when the marker/footprint is moved towards the edge of the display area, the label for the marker/footprint disappears.
fixing: showing the label when the marker/footprint is moved out of plot area and showing the label in alternate corner location in case the label is being moved out of plot area. 
- when the marker/footprint is relocated farther from the center or the target of the HiPS, the footprint  is shown out of shape as the image is zoomed. 
fixing: instead of translating each region component on image domain as regular image, each component is re-rendered in world coordinate after relocating the footprint center first per original region description. 
test:
start image search 
add a marker or footprint overlay
move the …
> DM-14673 Label for marker disappears when it is moved to the edge and footprint translation is out of shape on HiPS

- buildScript/depends.gincl
- buildScript/gwt_webapp.gincl
- buildScript/init.gincl
- config/common.prop
- src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiUtil.js
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/util/WebUtil.js
https://jira.lsstcorp.org/browse/DM-14779
https://irsawebdev9.ipac.caltech.edu/dm-14779/firefly/
Add git commit info into Firefly build.
Show a detail view of the version info when the shorten version is clicked.
- click on the version info on the lower-right corner to see the details
Exposes the same information via the JS API as well as from Java server-side environment.
- In JS, open a demo page, open console.  In console, enter `> window.firefly.util.getVersion()`
Jsdoc added:
```
/**
* Version information
* @typedef {Object} VersionInfo
* @prop {string} BuildMajor    major version number
* @prop {string} BuildMinor    minor version number
* @prop {string} BuildRev      revision version number
* @prop {string} BuildType     one of Final, Development, Alpha, Beta, or RC
* @prop …
```
> DM-14779: make last Git commit ID available in Firefly build

- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
https://jira.lsstcorp.org/browse/DM-14045
https://jira.ipac.caltech.edu/browse/IRSA-1710
Since `showPaging` is already an option, use it as the flag for turning paging on/off.
Update jsdoc to reflect the changes.
It's a small change.  No k8s build were made.  Use /firefly/demo/ffapi-table-test.html to test this option if built locally.
> DM-14045: TablePanel should also support no paging option.

- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
https://jira.lsstcorp.org/browse/DM-13382
Add option to show/hide column's data type.  Option is added to option panel and exposed through API as well.  
I took the liberty of adding some style to the data type because it looks pretty bad without it.  
If you don't like it, I have not problem changing it to something people agree to.
A couple of things you should be aware of.
- Sorting is triggered by clicking anywhere on the column header, not just the column's label.
- Cursor's is change to a 'pointer' icon when hover over the column's header.
Deployed to k8s:
https://irsawebdev9.ipac.caltech.edu/dm-13382/firefly/
> DM-13382: In TablePanel, allow option to show data type

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/HistogramOps.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageDataGroup.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/RangeValues.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/Zscale.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretch.java
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/ui/RangeSlider.jsx
- src/firefly/js/ui/RangeSliderView.jsx
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
- src/firefly/js/visualize/ui/StretchDropDownView.jsx
https://jira.lsstcorp.org/browse/DM-14778
- Improved algorithm to calculate asinh stretch using Q parameter
- Added slider for Q parameter (with image refresh on slider change pause)
- Autofill range option (for non z-scale case) for cases when full data range can be used. This option works well for small images, but might not be appropriate for large images. 
Deployment to test: https://irsawebdev9.ipac.caltech.edu/dm-14778/firefly/
> DM-14778: fix asinh stretch

- src/firefly/html/demo/ffapi-region-test.html
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/region/RegionFactory.js
Firefly intends to silently skip the bad region description with wrong format while parsing the region strings and render the region with good description.
This development fixes
-  the bugs in the region description parser at JS side. 
-  display of text for region 'circle'. 
test:
please try the region test page, demo/ffapi-region-test.html
- click 'Load sample image' to load an image to Firefly
- click 'create region layer' to create a region layer with the regions in the text area shown below.
- click 'add region entry' to add more regions shown in the text area shown below. 
Some regions with wrong description shown in the text area are not displayed.
> DM-15213 Fix region description parsing bug

- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java
- src/firefly/js/visualize/CoordSys.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/task/PlotImageTask.js
Loan an image with an initial position
_to test:_
This must be tested from python using the slate.html entry point.  I loaded the `firefly_client/demo/basic-demo` jupyter notebook.
I modified the two cells the first to start slate.html
`fc = FireflyClient('http://127.0.0.1:8080/firefly', html_file='slate.html')`
then later when I loaded an image.
`status = fc.show_fits(file_on_server=imval, plot_id="wise-cutout", title='WISE Cuteout', InitialCenterPosition='5;5;PIXEL', InitZoomLevel='5', ZoomType='STANDARD')`
The `InitialCenterPosition` should be in the middle of the screen.
> DM-15215: support an initial scroll position for the images

- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
this development fixed the MOC display bugs in Galactic coordinate system by converting the world point with the same coordinate system as that of the project center while finding some pixel alongside the great circle passing the given projection center and a world point. 
test: 
do hips image search and get moc display in galactic coordinate system.
> DM-15399 Fix the MOC display in Galatic coordinate system

- src/firefly/java/edu/caltech/ipac/firefly/server/query/BaseFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/FileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
https://jira.ipac.caltech.edu/browse/IRSA-2067
To test, using irsadev Gator, download a light curve table.
-> login as someone with ztf access -> click example link -> To Time Series Tool -> Download Light Curve Table
Goto https://irsawebdev9.ipac.caltech.edu/irsa-2067/irsaviewer/timeseries
You should be logged in as the same user.
-> upload previously downloaded file -> select ztf -> upload 
-> navigate through table rows to load protected images -> logout
-> as guest user -> upload same file -> select ztf -> upload 
the images are no longer loading because they are protected and cannot be view by user without privileges
Doing the same test in IRSA ops will reveal the security breach.
@robyww, when you have time next week, it would be nice if you can take a look at the changes to ensure …
> IRSA-2067: FileInfoProcessor need to take into consideration login status when caching

- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/visualize/HiPSMocUtil.js
- src/firefly/js/visualize/draw/MocObj.js
This development fixes the MOC display bug by using 'division' instead of 'right shift' to calculate 'npix' of lower tile where the higher order tile is nested in. This change is due to the fact that Javascript bitwise operation treats the operands as a sequence of 32 bits, the result will become inaccurate if doing bit shift on 'npix' of some higher order tile. 
test:
searching HiPS 'HST/NICMOS - all bands' by un-checking 'IRSA Featured' and selecting the only HiPS image with order 16. 
check up 'MOC' layer
zoom in the image 
the MOC of all levels (up to order 16) will be shown as image is zoomed in from large fov to small fov.
> DM-15498 MOC display hangs when HiPS image is zoomed in on fov around 1 degree or less

- src/firefly/html/demo/ffapi-region-test.html
- src/firefly/js/drawingLayers/RegionPlot.js
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/visualize/region/RegionFileUploadView.jsx
- src/firefly/js/visualize/region/RegionTask.js
- src/firefly/js/visualize/ui/DrawLayerItemView.jsx
This development includes, 
- use the file name of the uploaded ds9 region file as the label in the layer dialog if file is the source of the regions. 
- if the file name is lengthy, the file name is shown in shorter style shorten with '...' at the end. The full file name is shown as tooltip when the mouse is over it. 
- the API has a parameter field for the caller to provide the title (label) to create a new region layer. 
- if no title is provided by the caller, a string like 'ds9 region overlay-{N}', N=1, 2, ... is created as the title in default. 
- File upload panel is also updated to show the long file name of the uploaded file in shorter style as that shown in the layer dialog. 
test:
- start firefly test page, demo/ffapi-region-test.html
- click 'Load sample image' to get Firefly …
> Dm 14512 Use the file name of uploaded ds9 region file as the label in the layer dialog

- docker/base/Dockerfile
- docker/base/launchTomcat.sh
- docker/base/setupSharedCacheJars.sh
https://jira.lsstcorp.org/browse/DM-15225
- Update dockerfile to run as tomcat(91:91) by default.
- Using CATALINA_BASE inside the container to separate files owned by tomcat vs root.
- Use docker run parameter `--user=[user:group | uid:gid] ` to override default tomcat user.
This image is current deployed on irsawebdev5: http://irsawebdev5.ipac.caltech.edu:8888/firefly/
The way verify this is to ssh in to irsawebdev5;
`ps -ef | grep docker ` to see that the tomcat process is now owed by a uid other then root.
You may also want to modify stop/start scripts under /home/irsadmin directory to test the `--user` parameter or anything else.
> DM-15225: docker container should not run as root by default

- src/firefly/java/edu/caltech/ipac/astro/net/NedNameResolver.java
- src/firefly/java/edu/caltech/ipac/astro/net/Simbad4Client.java
- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/util/WebUtil.js
Ticket: https://jira.lsstcorp.org/browse/DM-13491
When name is being resolved and Search button is clicked, the search is not started until all fields are validated. Validation can not be completed until target resolution promise is resolved. If the service is unresponsive, name resolution might not return for a long time.
Enforce timeouts on name resolution calls both on client and server side.
If name resolution times out or fails for another reason, the target field should be shown as invalid, and the search should not continue.
> DM-13491 handle name resolution failures

- src/firefly/html/demo/ffapi-sed.html
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/charts/ui/options/Errors.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/util/expr/Expr.js
- src/firefly/js/util/expr/Expression.js
- src/firefly/js/util/expr/Parser.js
- src/firefly/js/util/expr/SyntaxException.js
https://jira.lsstcorp.org/browse/DM-15219
https://jira.lsstcorp.org/browse/DM-14886
Test deployment: https://irsawebdev9.ipac.caltech.edu/dm-15219/firefly/
This PR addresses multiple chart and filter related bugs, found in NED:
- Fixed filter bug, described in DM-15148: error when chart is filtered after another table filter is applied (for example on Units)
- Quoted columns should be considered valid in chart options 
- Error type in chart options should match the data
- When error is empty, no error bar should not be displayed (0 length bar was displayed before) 
- FilterEditor should allow filters update without clearing expression-based filters.
- Allow filter update by changing free-form filter in FilterEditor
To test, use http://localhost:8080/firefly/demo/ffapi-sed.html
- apply …
> DM-15219: chart bug fixes, found in NED 

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
The development includes, 
- modify FITS header display to use local headers instead of calling the server
- the content of FITS header dialog is updated as the user clicks on the image displayed or goes through the extensions. 
test: 
start Firefly
- get multiple images, open FITS header dialog, change the active image and check the content change of FITS header dialog. 
- upload a FITS image with multiple extensions, get FITS header dialog, change the extensions and check the content change of FITS header dialog.
> Dm 12636 Modify FITS header display to use local headers 

- src/firefly/html/demo/ffapi-region-test.html
- src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
- src/firefly/java/edu/caltech/ipac/util/dd/RegionOptions.java
- src/firefly/js/util/Color.js
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/MocObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/region/Region.js
- src/firefly/js/visualize/region/RegionDrawer.js
- src/firefly/js/visualize/region/RegionFactory.js
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
The development includes
- allow 'textangle' to be provided in the property of region description, like
`text 1074 110 "Text" # color=yellow textangle=45.0`
text of  region 'text' is shown to be rotated if the region description is with 'textangle'. 
- the development is made at both javascript and server sides.
- a test sample in Python for region text with 'textangle' is added into firefly_client. 
https://github.com/Caltech-IPAC/firefly_client/pull/29
also includes some extra fixing for MOC display - set a upper limit on the order for  generating visible tiles per display field of view to filter out invisible tiles defined in MOC file.
To test: 
- for the sever side, get region 'text' from uploaded region file,
start firefly, upload region file from …
> DM-15248 add 'textangle' to text region per DS9 documentation.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/TableFunctionProcessor.java
- src/firefly/js/Firefly.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/Colorscale.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/ui/ChartSelectPanel.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/HeatmapOptions.jsx
- src/firefly/js/charts/ui/options/NewTracePanel.jsx
- src/firefly/js/charts/ui/options/ScatterOptions.jsx
- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/util/Color.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
Ticket: https://jira.lsstcorp.org/browse/DM-15490
Test deployment: https://irsawebdev9.ipac.caltech.edu/dm-15490/firefly/
- Modified Firefly behavior of scatter charts to move between scatter and heatmap representation depending on whether the number of table rows exceeds the threshold stored in charts.maxRowsForScatter application option. 
- Introduced custom (non-plotly) color scales, see Colorscale.js so that the color of the first 8 traces does not change dramatically, when switching between scatter and heatmap. 
- Fixed a  bug, preventing TableFunctionProcessor from refetching the table data after session timeout has passed.
- Fixed bugs related to trace removal.
> DM-15490 Modify behavior of 2D-histogram (heatmap) fallback

- src/firefly/html/demo/ffapi-footprint-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/FootprintToolUI.jsx
- src/firefly/js/drawingLayers/RegionPlot.js
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/draw/FootprintFactory.js
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/region/RegionFactory.js
- src/firefly/js/visualize/region/RegionFileUploadView.jsx
- src/firefly/js/visualize/region/RegionTask.js
- src/firefly/js/visualize/ui/MarkerDropDownView.jsx
This development provides, 
- UI to upload 'instrument footprints' file: 
. 'instrument footprints' file upload is treated like region file upload and the uploaded region file is set to be relocatable,  the origin (at either world coordinate or image coordinate system) of the footprint is initially replaced to the search position of the image. 
. UI dialog:  using the same dialog for region file upload and a checkbox, 'treat as relocatable' is added to the dialog specifically  for 'instrument footprints' file upload. 
- API for creating 'instrument footprint' layer from a footprint file or an array of region description. 
- Each footprint entity is in default 'rotatable' and can be defined to be non-rotatable in region description. 
test:
for UI, upload the footprint file samples from …
> DM-14514 provide UI for uploading 'instrument footprints' in region description

- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/mapper/IpacTableExtractor.java
- src/firefly/java/edu/caltech/ipac/table/DataObject.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
Fixed failing table loads when a table contains quoted column name or a control characters in a cell.
https://jira.lsstcorp.org/browse/DM-16012 Firefly fails to load a table with '\n' and '\r' characters in a cell
https://jira.lsstcorp.org/browse/DM-15982 Firefly fails to load a table with a quoted column
Test deploy: https://irsawebdev9.ipac.caltech.edu/dm-16012/firefly
The solution was to remove quotes from column names and to escape/unescape control characters when writing and reading IPAC table to/from file. 
HSQLDB does not accept quotes in table column names. Even though DataGroup can handle quoted columns, we are removing quotes from column name in  DataType constructor rather than during DataGroup ingest into db, because it could result in inconsistent column names before and …
> DM-16012: table load failures

- src/firefly/js/ui/panel/TabPanel.jsx
https://jira.lsstcorp.org/browse/DM-16034
test deployment: https://irsawebdev9.ipac.caltech.edu/dm-16034/applications/sofia/
`selectedIdx` is a state kept by TabPanel.  It's possible that `selectedIdx` is greater than the number of tabs due to adding and removing tab dynamically.
Currently, this condition is handled in the render function of the component.  This visually appears correct, but the state is out of sync.
This bug is found in the Sofia app.  You can use Sofia to test.
https://irsawebdev9.ipac.caltech.edu/dm-16034/applications/sofia/
- search all-sky 
- select FIFI-LS
- select coverage
- select AOR..
Should see `Details` selected with rendered info.
> DM-16034: TabPanel's state may get out-of-sync when tabs are removed

- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/GroupInfo.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/LinkInfo.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
This PR includes Improvement on reading VOTable by processing more elements and the attributes from TABLE and FIELD elements  in votable file, 
- Using Starlink votable-aware DOM parser to traverse the xml elements in the votable file and collect more details from TABLE element including info. from TABLE's attributes (ID, name, ucd, utype, ref) and from TABLE's children elements (DESCRIPTION, LINK, GROUP, PARAM, INFO, LINK, FIELD). 
- collect more details from FIELD element including info. from FIELD's attributes such as  ID, name, datatype, unit, precision, width, ref, ucd, utype  and from FIELD's children elements including DESCRIPTION, LINK, and VALUES. 
- The JAVA class implementation regarding the table (DataGroup) and table column (DatType)  are updated accordingly. 
Test:
Run …
> DM-15826 Improvements on reading VOTable in Firefly 

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
ticket: https://jira.ipac.caltech.edu/browse/IRSA-2152
test deployment: https://irsawebdev9.ipac.caltech.edu/irsa-2152/applications/sofia/
Ticket provide steps to reproduce bug.  Please use that to confirm that bug is fixed.
> IRSA-2152: Firelfy table filter fails when underscore '_' is in filter

- src/firefly/config/app.prop
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
https://jira.ipac.caltech.edu/browse/IRSA-2261
Test deployments: 
https://irsawebdev9.ipac.caltech.edu/irsa-2261/applications/finderchart/, https://irsawebdev9.ipac.caltech.edu/irsa-2261/firefly/ 
Delay setting firefly `isReady` until after the promise from firefly.bootstrap is fulfilled.  This enable application to do additional initialization before normal processing.
See ticket for testing for testing instructions.  I built `firefly` as well for the convenience of regression testing.
NOTE:  This PR is for merging into `rc`.  It will be merged back into `dev` at a later time.
> IRSA-2261: Finder Chart URL API in irsatest fails

- src/firefly/html/css/global.css
- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.css
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.ipac.caltech.edu/browse/IRSA-2211
Test deploy: https://irsawebdev9.ipac.caltech.edu/irsa-2211/firefly/
To test:
- Image Search with multiple images returned
- From toobar, select "Choose which plot to show" icon.. 3rd one in the 3 icon set.
This dialog should be resizable now.
Also, Image Search drop-down and pop-up is also resizable.
To test:
- select Image Search from menu
The panel is resizable by dragging the bottom-right corner
To test popup:
- firefly/demo/ffapi-coverage-test.html
- mouse-over image -> select toolbar
- select New Image from toolbar, 2nd icon from left.
> IRSA-2211: Make popup image list resizable

- src/firefly/html/demo/ffapi-LSSTfootprint-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/drawingLayers/ImageLineBasedFootprint.js
- src/firefly/js/drawingLayers/ImageLineFootPrintUI.jsx
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/draw/Drawer.js
- src/firefly/js/visualize/draw/ImageLineBasedObj.js
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/task/LSSTFootprintTask.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
the PR links LSST source and footprint overlay including the following functions, 
- source table and footprint overlay can be highlighted, selected, and filtered in sync.
- the API can take either footprint source and data file  or footprint data in json format.
test:
test samples,
-download image file from https://caltech.app.box.com/s/91itmkiz0s68b14qy3nnj7sriqh80mxg
-download votable, combined_sources_and_footprints.xml, containing more than 34K footprints, from https://caltech.app.box.com/s/kob0ri00fai75eruyspfbobs3lxx9gzs 
- get votable files with 500, 2000, 5000 footprint data extracted from above votable sample from firefly_test_data.
test steps:
start firefly, 
upload the image file and search the first image 
upload one of the footprint votable file (try the one with smaller set …
> DM-16035 link LSST source and footprint overlay.

- config/test/app-test.prop
- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTableFromExternalTask.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UserCatalogQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
- src/firefly/test/edu/caltech/ipac/table/IpacTableFromSourceTest.java
This PR was closed but a bug was found and needed to be re-opened.
After conversion, a couple of the SearchProcessors no longer take `table index` into consideration when loading table.  This was spotted by @tgoldina .
Also in this PR, I've fixed a condition in which Table wrongly marked as completed even though `data` hasn't returned.  This was spotted by @cwang2016 
Also added a unit-test to test IpacTableFromSource.
`gradle :fi:test -x jsTest --tests *IpacTableFromSourceTest`
Will you two help review the code to see if it addresses the problem you raised?
Thank you.
> DM-16273: fix search processors from saving as ipac table first

- src/firefly/js/visualize/saga/CatalogWatcher.js
This PR recenter the hips image projection center based on the search target when
- doing catalog search 
- changing the active table
test:
- do hips image search with/without entering a target
- do catalogs search on different position or polygon method
the hips image is re-centered as the active table changes
> DM-15449 recenter the hips image based on catalog search target

- src/firefly/html/demo/ffapi-region-test.html
- src/firefly/java/edu/caltech/ipac/util/RegionFactory.java
- src/firefly/js/visualize/draw/ShapeToRegion.js
- src/firefly/js/visualize/region/Region.js
- src/firefly/js/visualize/region/RegionDescription.js
- src/firefly/js/visualize/region/RegionFactory.js
This PR support
- support global statement on coordinate system in  form of 'global coordsys <coordinate_specifier>', where coordinate_specifier could be FK4, B1950, FK5, J2000, ICRS, GALACTIC, or ECLIPTIC.
- multiple global lines (for coordsys and region property) may be used within  a region file. 
(server side only allows the global lines defined before the region description).  
test,
from the client side:  
start the page on firefly/demo/ffapi-region-test.html
click 'Load sample image' and the 'Create Region Layer' for the regions defined  in the first text area in which multiple global lines for properties and coordsys are included. 
from the server side: 
start firefly, do image search on m51, 
upload region test file at firefly_test_data/region-test-files/test5_global.reg
> DM-15233 support global statement on coordsys for DS9 region 

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableDef.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/table/query/DataGroupQuery.java
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/test/edu/caltech/ipac/astro/IpacTableReaderTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/IpacTableTest.java
- src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
- src/firefly/test/edu/caltech/ipac/table/VotableTest.java
https://jira.ipac.caltech.edu/browse/IRSA-2274
test deploy: https://irsawebdev9.ipac.caltech.edu/irsa-2274/firefly/
Additional changes in firefly_test_data under the same branch name; updated test file.
This change is to preserve the original meta information from the source for later use.
One usage is when exporting.  It should only export the original meta, not any that were added by Firefly during processing.
In the future, we should have an option where the original meta information is displayed in the UI.
This behavior applies to all table, including FITS, IPAC, and VOTABLE.
Design Notes:
TableMeta now contains 2 types of meta; attributes and keywords.
`keywords` is a list of the original meta info, which may contains comments and duplicate keys.
`attributes` is a map containing all …
> IRSA-2274: export only the original meta

- src/firefly/js/visualize/projection/ProjectionInfo.js
- src/firefly/js/visualize/ui/ThumbnailView.jsx
fixed 2 issues:
- ThumbnailViewer does a undefined check it should have been doing, this protects the `render()`
- A plate projection sets up the coordinate system correctly
_To test:_
Load the fits file attached to the ticket. It should load OK and have a working readout.
https://jira.lsstcorp.org/browse/DM-16522
> DM-16522: fixed bug in eval of plate projection parameters

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedCurveProcessor.java
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
https://jira.lsstcorp.org/browse/DM-16656
k8s: https://irsawebdev9.ipac.caltech.edu/dm-16656/irsaviewer/
Light Curve viewer was dependence on 'original_table ' meta that is no longer supported. 
This PR replace that logic with something that is supported.
> Dm 16656 lc periodogram peak error

- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
https://jira.ipac.caltech.edu/browse/IRSA-2424
The bug was caused by java escaping, which included quote character
Updated behavior: when saving ipac table, replace control characters only with a replacement character (currently inverted question mark)
To test: 
1. NED target search, save as IPAC table, check Details field url. Quotes should be unchanged.
2. To test the replacement of control chars, search for `gaia` tables in `public` schema at 
http://localhost:8080/firefly/demo/ffapi-tap-test.html, save tables (second table) as IPAC table. Description field has control characters.
> irsa-2424: Link in tables are not saved correctly in ipactable

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/js/tables/TablesCntlr.js
https://jira.lsstcorp.org/browse/DM-16661
k8s: https://irsawebdev9.ipac.caltech.edu/dm-16661/firefly/
According to the ticket, column's properties when sent via META-INFO is lost when filter is applied.
You can test this on our nightly build: http://irsawebdev5:8100/view/k8s/job/k8s_firefly/demo/ffapi-table-test.html.
- clear META-INFO
- click show table
- enter `{"col.ra.FmtDisp": "%.2f"}` into META-INFO
- click show table again
- should see `ra` is formatted with only 2 decimal places
- open column filter bar
- enter `> 0` into a numeric column, i.e `sigdec`
- `ra` is back to its original precision.
Doing the same on this PR's k8s build should yield the expected results.
> DM-16661: Firefly tableviewer column does not apply column formatting on user filter attempt	

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/CropFile.java
Fixed the  bug for cropping the multi-extension 2-d images
Fixed the bug for the cropping cubes image data
Two issues noticed:
1. For sofia cube, the cropped images are not inside the cropped frame
2. In Firefly, when I  do a search in one mission, a group images are displayed. By default, all images are locked as a group.  The selection tool applies on all images, but crop tool only applies to the selected image. Is this a designed behavior?  
Test URL:
URL: https://irsawebdev9.ipac.caltech.edu/irsa-2367/applications/sofia/
> IRSA-2367-Issue Priority 2. SOFIA crop fails on a cube

- src/firefly/js/ui/DropDownContainer.css
https://jira.ipac.caltech.edu/browse/IRSA-1316
k8s: https://irsawebdev9.ipac.caltech.edu/irsa-1316/irsaviewer/
Additional changes here:  https://github.com/IPAC-SW/irsa-ife/pull/40
Catalog search panel is pushing into the footer, causes footer to rendered badly as well as links not working correctly.
The test deploy is for irsaviewer, but this will fix finderchart, sofia, and firefly as well.
> IRSA-1316: adjust footer so that it does not shrink

- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/tables/Decimate.js
This development includes, 
- fixing the bug regarding changing binning value on the plot parameter dialog of Heatmap chart
- the numbers (including the defaults for the plot in the beginning)  for x-bins & y-bins fields are  shown in plot parameters setting dialog. 
test:
start catalog search on cone search with large radius and that will result in a table more than 5000 rows. (default setting in Firefly.js), ex: m31 & radius=1600"
open up charts options and tools dialog,  change  the number of xbins or ybins or both and apply the change.
> DM-13099 set binning value of any axis on decimated plot 

- src/firefly/html/demo/ffapi-footprint-test.html
- src/firefly/js/visualize/region/RegionFactory.js
The development fixed the bug in region parser at client side regarding the region size with the unit like  arcmin or arcsec, ex, image;box(100, 150, 1.0', 1.2', 0) # color=red
test:
Go to firefly/demo/ffapi-footprint-test.html or firefly/demo/ffapi-region-test.html 
Add some region description including a size with unit arcmin or arcsec into the text area for creating footprint or region layer and check the overlay.
> DM-16922 fixing parsing bug on regions with size unit in arcmin or arcsec

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/TableSelectViewPanel.jsx
Ticket: https://jira.lsstcorp.org/browse/DM-16707
Test deployment (TAP Searches dropdown under firefly-dev.html)
https://irsawebdev9.ipac.caltech.edu/dm-16707/firefly/firefly-dev.html?__action=layout.showDropDown&visible=true&view=TestTAPSearch
Create a panel (TableSelectViewPanel), which would allow to browse TAP schema and submit queries to the selected TAP service. The page provides means to browse a selected TAP schema (from a predefined list) and construct simple ADQL queries on a selected table using column constraints. The resulting query is displayed to the user. User can modify the query before submitting. The result is displayed in Firefly triview.
This is a starting point for our TAP searches. The UI by no means is complete. Table selector is a list box, no support for spatial, …
> DM-16707 TAP search prototype

- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/StatedInputfield.jsx
- src/firefly/js/visualize/BandState.js
- src/firefly/js/visualize/PlotState.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Improve the cube and multi-image FITS display controls
- Added individual cube readout display for cases with multiple cubes
- Show the HDU number if more than one or not the 0 HDU (simple FITS)
- Added: for HiPS/FITS cubes and multi image FITS text entry field to jump directly to the plane
- show show the text entry field if more than 8 planes
- Created a text entry StatedInputField for text input outside of a field group
- Fixed bug: a plot id not being created correctly for upload and URL
- add a set of PlotViewUtil functions to get cube and multi-image FITS info
- cleaned up of unused BandState and PlotState functions
_To Test:_
- load any of the multi image fits or cubes in `firefly_test_data/multi-ext-fits`
- observe the control area of the cube / multi image FITS
- this will also …
> DM-14350: Improve the cube and multi-image FITS display controls

- src/firefly/js/drawingLayers/DistanceTool.js
- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/drawingLayers/MarkerToolUI.jsx
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/draw/DrawLayer.js
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
This development mainly fixes the issues when footprint/marker layer is attached to both HiPS and FITS images: 
- the point distance (how close to the center of the footprint or marker) on screen
pixel coordinate is adjusted per plot  (HiPS plot or FITS plot) that the footprint/marker layer attached to. 
- Scale the size of the marker according to the primary image while a new plot is created. 
Every new marker is added with fixed screen pixel size no matter if the primary image is HIPS or FITS and the plot created later should have the marker scaled in world coordinate by looking at that in the primary image. 
- fix bugs to show the fake outline box when the outline box surrounding the footprint/marker is out of view. (this may happen when you move the marker/footprint on HiPS image and …
> DM-15378 Scale the size and synchronize the movement of footprint/marker on both HiPS and fits display

- src/firefly/js/ui/ImageSelect.jsx
ticket: https://jira.ipac.caltech.edu/browse/IRSA-2488
k8s:    https://irsawebdev9.ipac.caltech.edu/IRSA-2488_missing_info_link/firefly/
As described in ticket...  test using above k8s url.
> In Gator or in any tri-view catalog search, after a coverage image is displayed, if the user wants to change the image and brign the image search panel, the information icon and links are not shown in this mode (single selection mode)
> IRSA-2488: Image search is not showing info link icon in single select mode

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
Without it, charts were ignoring values smaller than 1.0e-6 due to the default %.6f set on all decimal numbers.
> IRSA-2506: bring back default format when reading from DB resultset.

- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.css
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/util/VOAnalyzer.js
This PR is made on
https://jira.lsstcorp.org/browse/DM-17213
The development includes, 
- fill in the top right box in TAP search panel for entering spatial/temporal/wavelength constraints. 
- set up the widget and layout for spatial, temporal and wavelength search.
- implement the spatial search panel on cone, polygon and all sky search
- compose the statement for ADQL where clause on entered spatial search numbers
test: 
https://irsawebdev9.ipac.caltech.edu/dm-17213/firefly/firefly-dev.html
do TAP searches,
- the position columns are shown in default based on the TAP table and 'columns table'. It is The column_name of the first two rows in 'columns table' with ucd column value as 'pos.eq.ra' and 'pos.eq.dec'. 
compare the following test  with regular catalog search,
TAP schema, …
> Dm 17213 TAP spatial and temporal search

- src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
- src/firefly/js/templates/lightcurve/LcManager.js
Fixed the ztf image direction issue
Fixed the ra/dec format issue in IBE.java
Test URL:  https://irsawebdev9.ipac.caltech.edu/irsa-1991/irsaviewer/ts.html
Please use the ztf_tbl attached in the ticket IRSA-1991.  This is the most recently table saved from IBE gator searching result.
> IRSA-1991-ZTF:ZTF time series: North up not applied

- src/firefly/js/ui/ExampleDialog.jsx
- src/firefly/js/ui/TargetFeedback.jsx
- src/firefly/js/ui/TargetPanel.jsx
This pr consist of making the examples custom to a particular target panel by making them a prop of the target panel view.
An example has been used in ExampleDialog.js. 
Go to localhost:8080/firefly/firefly-dev.html and open Example dialog popup. See the examples are different and are taken from SOFIA request.
This PR has been triggered and is associated with SOFIA request change in irsatest and can be seen by building SOFIA in IFE repos with same branch name.
> IRSA-2578: make target examples a prop

- src/firefly/js/visualize/saga/CoverageWatcher.js
Coverage now does a more rigorous check to validate and show coverage.
- For box coverage a least 10% of the rows must have non-empty data
- All empty data rows are thrown out (box or point)
- Before empty data was creating 0,0 j2000 points.
_To test:_
- load sofia
- search m17
- look at coverage
> IRSA-2568: Coverage now does a more rigorous check for validate coverage

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
Fixed the wrong title in larger table (row count >5000).
When a searched table has more than 5000 rows, the function changed the title by hard coded "updates".  
To produce it: 
1.  clean your browser cache, in your workarea remove sofia folder
2. run https://irsadev.ipac.caltech.edu/applications/sofia/
3. do an allsky search, then select "FIFI-LS", and see the image in Data tab, the image label is "updates FOV: angle". 
Clean cache and workarea, and then run the URL for this pull request, the image label is "FIFI-LS FOV:angle".  
The issue only happens for table's row count> 5000 and the first time the table is load.
> IRSA-2556:SOFIA: image title label is wrong

- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
https://irsawebdev9.ipac.caltech.edu/tabpanel/firefly/
In the past, border was applied to the tabs, but not the tab's content.  It leaves an `unfinished` feel to the UI.  It's only noticeable if you pay attention.   Please compare and see if you agree with the changes.
> Minor tweak to TabPanel so that the Tab's border is uniformly applied to the Tab's content as well.

- src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
- src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/Packager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IbeTemplateProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/ZtfLCFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCatalogSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ptf/PtfIbeResolver.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/AuthOpenidcMod.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoCheckFilter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoVerifyServlet.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/test/edu/caltech/ipac/firefly/server/query/PtfIbeTest.java
https://jira.lsstcorp.org/browse/DM-14501
Add authentication hook for LSST portal to CILogon.
Additional changes in these repositories: 
https://github.com/lsst/suit/pull/10
https://github.com/IPAC-SW/irsa-ife/pull/44
- Cleanup SsoAdapter interface
- Allow custom adapter by class name
- Improve mechanism for handling requests to external services on behalf of the user.
- Converted LSSTQuery to be subclass of DbProcessor
Test:  https://lsst-lsp-int.ncsa.illinois.edu/portal/suit/
Known Bug:  Cannot log in when using NCSA as an identify provider.
You must use your external linked ID, like github or google.
If you go here:
https://identity.lsst.org/manage
... You can login with your NCSA credentials.
You should see, if you linked a provider to your (e.g. Caltech, Google) with your account, an …
> Dm 14501 add lsst auth adapter

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/AuthOpenidcMod.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
Ticket: https://jira.lsstcorp.org/browse/DM-17499
Needs to be built locally for test, because only LSST is producing plain text error docs, and LSST services require VPN.
"AsyncTapQuery" search processor now handles both formats of errors: VOTable and plain text.
Bugs fixed:
- LSST result queries (when using URLDownload with GET method) were not following redirects
- Single char datatype in VOTable was not converted to the right hsqldb type, which was causing table load failure: "Invalid Statement". 
To test:
1. Build locally, use NCSA VPN to run:
http://localhost:8080/firefly/firefly-dev.html?__action=layout.showDropDown&visible=true&view=TestTAPSearch
2. Use ADQL tab to modify ADQL query to make it invalid. Search.
3. Switch between services (sample query should change). Try both valid …
> DM-17499 Support error docs in plain text

- src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/IrsaHiPSListSource.java
- src/firefly/js/Firefly.js
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/visualize/iv/ImageRender.jsx
- src/firefly/js/visualize/saga/CoverageWatcher.js
Improve caching and reading of HiPS images 
_Ticket issues:_
- HiPS retrieve now check status and only serves good files
- HiPS retrieve validates image and hips property files
- HiPS retrieve change of caching parameters, also now supports 304, If-Modified-Since
- refactor of AnyFileDownload.java
bulk of ticket work in `AnyFileDownload.java` and `HiPSRetrieve.java`
_Other issues found and fixed:_
- fixed regression issue if CoverageWatcher (`CoverageWatcher.js`)
- fixed sometimes bad file naming with download region files (`FitsDownloadDialog.jsx`)
- fixed HiPS option not showing in jupyter slate. (`Firefly.js`)
- fixed a regression scrolling issue (`ImageRender.jsx`)
> DM-17740: improve caching and reading of HiPS images

- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
This PR is about fixing the problem of the peridogram tool (period finder) in TimeSeries when sending the table from Gator. 
Gator send the table (light-curve) with a URL source input file that contains '&' and other characters and get passed to the tool and period finder use it without encoding before calling the API and fails.
To test, you will need to use this branch with Gator in irsadev - go to WISE multiepoch photometry catalog and do a search, then click on 'Time Series tool' button in the result page and then click on 'period finder' on the time series tool and calculate the peirodogram with default value.
Another way is to replace the test 'LightCurveProcessorTest' with a sample URL (from Gator search test) which contains '&' and overwrite …
> IRSA-2637: URL value encoded and passed to api

- README.md
- buildScript/webpack.config.js
- package.json
- src/firefly/js/core/AppDataReducers.js
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- yarn.lock
https://irsawebdev9.ipac.caltech.edu/dm-17758-supported-browsers/firefly/
DM-17758: update supported browsers List & update webpack to version 4
- webpack 4
- Safari 9 => 10  (current: 12)
- Chrome 62 => 67  (current: 71)
- Firefly 56 => 60 (current: 65)
- Edge  14 => 16 (current: 18)
Webpack Notes:
- Updating the browsers so that more ran natively seemed to reveal a bug in uglify
- Updating to webpack 4 uses a new uglify and fixes the problem
- the uglify plugin is now packaged with webpack so we don't need to specify it in package.json
- webpack now will use some standard plugins. I enabled this feature see: https://webpack.js.org/migrate/4/
- Using standard plugins does not disable being able to add more.
> DM-17758: update supported browsers List & update webpack to version 4

- src/firefly/js/visualize/reducer/HandlePlotChange.js
Fixed bug: flip fail when there is a fail image plot in the group
_to test:_
https://irsawebdev9.ipac.caltech.edu/dm-13630-dist-tool/firefly/
Make image plots with m34 on SEIP. Four images should come up and one should fail- then do a flip. It if works and there are not errors in the console the bug is fixed.
> DM-13630: Fixed bug: flip fail when there is a fail image plot in the group

- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-2562
The tooltip for the free-form `Filters:` input is wrong.  Without clear instruction in the ticket, I changed it to what I think is correct.  Feel free to request changes.
To test:   https://irsawebdev9.ipac.caltech.edu/IRSA-2562_filters_tooltips/irsaviewer/
- Any search that produce a table, i.e. Catalog search.
- Click on options (gears icon)
- mouse over `Filters:` input to see tooltips.
> IRSA-2562: modify filter tooltips to reflect current support format.

- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.lsstcorp.org/browse/DM-18330
test: https://irsawebdev9.ipac.caltech.edu/dm-18330/firefly/firefly-dev.html
Depending on its layout, a dropdown panel may behave differently to window resizing.
In this PR:
- TAP Searches will be fully expanded when window resizes.
- Image Search will be fully expanded up to 1600px.  This is about the width of a `default` retina display.
- Others remain fixed width.
> DM-18330: Make DropDownContainer support optional layout. 

- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/ui/DateTimePickerField.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/ui/TimePanel.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
This PR includes development for https://jira.lsstcorp.org/browse/DM-18122 
- add checkbox to the disclosure bar on the spatial/temporal search panels
- fix the size of the search panel while moving the resizer in the 'Select Constraints' area. 
- remove all-sky from spatial search method 
- validate the field entries depending on the entered value and the checkbox status of the search panel (empty value is allowed in case the search panel is not checked)
- add feedback regarding field validation on the disclosure bar when the search panel is checked.
- merge the change regarding column fields in spatial/temporal search panel from dev. 
test: 
start  https://irsawebdev9.ipac.caltech.edu/dm-18122/firefly/firefly-dev.html
for styling,
- check the size and layout of each panel in 4.Select …
> DM-18122 update Spatial/temporal search panels

- src/firefly/html/css/global.css
https://jira.lsstcorp.org/browse/DM-18409
test: https://irsawebdev9.ipac.caltech.edu/dm-18409/firefly/
As reported in ticket, `mask` css style uses z-index and therefore interfere with the natural stacking order of the other components.
In this PR, z-index is removed.  Please verify everything is working as before.
> DM-18409: Loading mask z-index is breaking natural stacking order of the components

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterListEntry.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/LinkInfo.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/visualize/VisConstants.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/util/__tests__/VOAnalyzer-test.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
https://jira.ipac.caltech.edu/browse/IRSA-2420
http://www.ivoa.net/documents/VOTable/20130920/REC-VOTable-1.3-20130920.html#ToC54
- implements VOTable LINK substitution A.1
- implements VOTable FIELDs as Data Pointers A.4
- increase ImageSearch panel's max-width to 1200 from 900
- move `Properties` column between `Type` and `Title`
- added test for link substitution function
To test:
- https://irsawebdev9.ipac.caltech.edu/irsa-2420/firefly/
- from Image Search, select `View HiPS Images`
- the 2nd column `Pr...` is the new Properties column, with an `info` icon instead of long url string
- position of the column is moved to between `Type` and `Title` as requested in ticket.
There's also a test file attached to the ticket to demonstrate other usage of LINKs.
As usual, ran `gradle …
> IRSA-2420: Make HiPS table "Properties" column show links

- buildScript/webpack.config.js
- package.json
- src/firefly/js/util/WebUtil.js
- yarn.lock
Replace the deprecated library react-addons-update with immutability-helper, also upgrade immutability-helper to the most recent version (3.0).
Note- We have been using immutability-helper for 2 years but did not replace it in WebUtil.js because it had a bug in certain use cases. This bug appears to have been fixed a while back so I think it is safe to replace. This will fix the bug we were seeing with Atmos when they added Prototype.js.
https://irsawebdev9.ipac.caltech.edu/firefly-50-immutability-helper/firefly/
> Firefly-50: update immutability-helper and replace react-addon-update

- src/firefly/html/css/global.css
https://jira.ipac.caltech.edu/browse/IRSA-1093
Problem:  
See the attached image in the ticket.
Solution:
Add style to rootStyle to remove `center` tag affect.
Test:  https://irsadev.ipac.caltech.edu:9201/
Note: There's a side effect to this solution.  Although, this remove the unwanted vertical line, it also remove the `center` affect as well.  
In general, we do not want external style to affect our firefly component.  This is the reason why rootStyle were introduced.  
But, since IRTF is already in production.  I just wanted to point out the visual differences after this PR.
There's a ticket created already to provide more styling to a table.
> IRSA-1093: vertical line appears due to an external outer <center> tag.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
https://jira.lsstcorp.org/browse/DM-18591
Test deployment: https://lsst-lsp-int.ncsa.illinois.edu/portal/suit/
The following bugs are fixed in this branch or in bug fix commits:
- Table info button does not show up.
- Legacy PDAC does not show up.
- Image metadata do not show up.
- Failed authorization on getting column metadata or images.
Broken chart options and suggest box not accepting input when switching to a different chart type were fixed in https://jira.ipac.caltech.edu/browse/FIREFLY-46 and should be working in the test deployment.
> DM-18591 Bugs found in TAP demo

- config/app.config
- config/common.prop
- src/firefly/html/demo/ffapi-table-test.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/tap/Select.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
https://jira.lsstcorp.org/browse/DM-18690
Test build: https://irsawebdev9.ipac.caltech.edu/dm-18690_maxrec/firefly/firefly-dev.html?__action=layout.showDropDown&visible=true&view=TAPSearch
"Row Limit"  field is displayed at the bottom of the TAP Search, along with "Search" and "Cancel" buttons. It is propagated to the server and is translated into MAXREC parameter of the search request. We allow to disable it by clearing.
tap.maxrec.hardlimit property (default 10000000) is a config property. If MAXREC is set, it can not exceed this value.
defaultMaxrec is an application property (default 50000 for Firefly). It is the default value for MAXREC parameter.
Other changes:
- Filters are now shown by default in the TAP result tables
- Removed 'tables.showInfoButton' app property and made it a …
> DM-18690: implement maximum record limit in TAP query screens

- src/firefly/js/templates/lightcurve/ztf/ZTFPlotRequests.js
Add ZTF filtercode to the image display title.
To test, upload the attached ztf lightcurve table in jira IRSA-2015 (login on irsadev first for ZTF image retrieve):
https://irsawebdev9.ipac.caltech.edu/irsa-2015/irsaviewer/ts.html
> IRSA-2015 Add ZTF filtercode to the image display title.

- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/DateTimePickerField.jsx
- src/firefly/js/ui/ExampleDialog.jsx
- src/firefly/js/ui/FieldGroupConnector.jsx
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/InputAreaField.jsx
- src/firefly/js/ui/InputField.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/ui/NaifidPanel.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/RangeSlider.jsx
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/ui/TimePanel.jsx
- src/firefly/js/ui/ValidationField.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/ui/tap/Select.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/CatalogTableListField.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
Firefly-51: Make FieldGroupConnector use function components with hooks
- Created a new field group connector hook
- converted all `FieldGroup` related components to be functions with hooks
- updated and cleaned up `NaifidPanel`, it needed a little work
- updated many propTypes to include shape of initialState
- removed value from some components props, replaced with initialState:{value}
- a attempt to better define what should be in initial state
- hook give a warning is value is passed as prop
_Code to look at_:
- Look at `FieldGroupConnect.jsx`, look at the hook `useFieldGroupConnector`. Don't bother looking at the differences, just look at the new file.
- All other files are pretty straight forward. You might want to look at a couple of files or focus on the components that you wrote. …
> Firefly-51: Make FieldGroupConnector use function components with hooks

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/util/FileUtil.java
- src/firefly/java/edu/caltech/ipac/util/download/Downloader.java
- src/firefly/js/core/MasterSaga.js
- src/firefly/js/metaConvert/ConverterFactory.js
- src/firefly/js/metaConvert/ObsCoreConverter.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/ImageMetaDataWatcher.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
Firefly-44: Make data product display work with ObsCore
- Recognize ObsCore tables
- Show products if it is a FITS image and less than 1 GIG
- Put in simple support for data link: only access_url so far
- Data link tries show the #this semantics image if available
- Give option to show grid of images when filtered down to image and/or cube
_To test:_
https://irsawebdev9.ipac.caltech.edu/firefly-44-obs-core-meta/firefly/firefly-dev.html
Load a ObsCore table: 
- TAP Searches => **Tap Service**: CDAC or MAST => **Schema**: ivoa => **Table**: ivoa.obscore
- Spacial search around small area e.g. 200 arcsec
What happens:
- When you click on a row with the data produce image or a cube it will attempt to load the image
- For CDAC it will do a Data Link indirection and if possible load the `#this` …
> Firefly-44: Make data product display work with ObsCore

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotBuilder.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotReader.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotResultSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/BandState.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/ClientFitsHeader.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/CreatorResults.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/PlotState.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotHeaderInitializer.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotInitializer.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResult.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/output/PlotOutput.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/BandState.js
- src/firefly/js/visualize/PlotState.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/ProjectionInfo.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
Firefly-61: Headers are not passed for every cube plane, show correct cube headers
- pass the correct cube headers
- optimize size of returns
- fixed crop file mouse readout bug
- better feedback
- large cube significantly faster
- cube result json much smaller
- standard result json a little smaller
_To Test:_
https://irsawebdev9.ipac.caltech.edu/firefly-61-cube-loading/firefly/
go to `firefly_test_data/multi-ext-fits` and read some file.
- `sofia-10_ext-10130_images.fits` is the best test case since this file highlighted the bug.
- read others such as `F0202_FI_IFS_0300595_RED_WXY-10-hdu-69-plane-cube.fits`
- read other fits files.
Performance should be good.
> Firefly-61: Headers are not passed for every cube plane, show correct cube headers

- src/firefly/java/edu/caltech/ipac/table/PrimitiveList.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
This PR contains developments for  https://jira.ipac.caltech.edu/browse/FIREFLY-22 
- fix fits table reader and votable reader to handle the fields of type 'byte' or 'short' 
- fix the missing label on upload panel when URL is selected.
test 
start Firefly
upload the FITS sample from URL
http://web.ipac.caltech.edu/staff/ejoliet/gaia/query-sels/result.fits
k8s: https://irsawebdev9.ipac.caltech.edu/firefly-22/firefly/
> FIREFLY-22 Fix the reader for FITS table or VOTable with fields of 'byte' or 'short' type

- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/ExampleDialog.jsx
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/SimpleComponent.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-67
Tests:  
https://irsawebdev9.ipac.caltech.edu/FIREFLY-67/firefly/
https://irsawebdev9.ipac.caltech.edu/FIREFLY-67/applications/sofia/
Additional changes:  https://github.com/IPAC-SW/irsa-ife/pull/63
TabPanel was not working in some cases.  It was also very complex in the way it handles its multiple use cases.
Changes:
- Refactor TabPanel
- separate the different tab types using composition.
-  convert to functional components with hooks
- Fixes Example Js Dialog 'third' tab prop validation error.
- Create replacement for SimplePanel using hooks.
Also:
I think `useFieldGroupConnector` relies on the view not getting unmounted.  When I use StatelessTabs for its view, onChange was not called.  Not a big deal, switching to Tabs(internal state) …
> FIREFLY-67: Fixes TabPanel

- src/firefly/html/demo/ffapi-highlevel-charttest.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/charts/ui/ChartPanel.css
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/ChartSelectPanel.jsx
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/ui/CloseButton.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-33
Test: https://irsawebdev9.ipac.caltech.edu/firefly-33_notoolbar_chart/firefly/demo/ffapi-highlevel-charttest.html
- Added noChartToolbar to showChart parameters. When set to true, the chart toolbar will not be displayed and the chart area will be "under the glass", not reacting to any DOM events. If connected to a table, it will update when the table updates.
- Refactored some of the chart code to remove UNSAFE__* methods.
> FIREFLY-33: no chart toolbar option in API

- package.json
- yarn.lock
https://jira.ipac.caltech.edu/browse/IRSA-2825
chrome update causes error messages to appear in console when mouse wheel is used  for scrolling on any table. (https://www.chromestatus.com/features/6662647093133312)
Update `fixed-data-table-2` to latest(v0.8.22) fixes the problem.
Test:  https://irsawebdev9.ipac.caltech.edu/IRSA-2825/applications/sofia/
On any table with data, use mouse wheel to scroll the view.  With this fix, there should not be any error messages in the console.
> IRSA-2825: Console error msg on mouse wheel on any table

- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/saga/UrlLinkWatcher.js
This PR is for https://jira.ipac.caltech.edu/browse/FIREFLY-43, includes development:
- add a watcher to find the qualified table which has 'access_url' column 
- display the column as a link and enable the link to be used for a download of the associated data file.
test
https://irsawebdev9.ipac.caltech.edu/firefly-43/firefly/firefly-dev.html
do TAP search on MAST->ivoa->ivoa.obscore & spatial search 
get a table in which each cell of access_url column is shown as a link
> FIREFLY-43 Recognize the "access_url" column in a table and display it as a link

- src/firefly/js/ui/PopupPanel.jsx
This small change is to allow user to select and copy text from a popup panel and dialog which was requested in those other tickets:
IRSA-1613 (marker coordinates not copyable) and FIREFLY-65 (hips properties info dialog).
Please test that any dialog or popup text can be selected and copied and confirm.
> FIREFLY-31: make any popup panel text selectable and copyable

- __jest__/InitTest.js
- src/firefly/html/demo/ffapi-table-test.html
- src/firefly/html/test/styles.css
- src/firefly/html/test/template.html
- src/firefly/html/test/template_loader.js
- src/firefly/html/test/tests-main.html
- src/firefly/html/test/tests-viewer.html
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/js/data/MetaConst.js
- src/firefly/js/metaConvert/DataProductsFactory.js
- src/firefly/js/metaConvert/ObsCoreConverter.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/__tests__/TableUtil-test.js
- src/firefly/js/tables/reducer/TableDataReducer.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/util/VOAnalyzer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-30
Adds ability to handle table with proprietary data.
- introduced DATARIGHTS_COL and RELEASE_DATE_COL column metas.
- When one of these columns exists, table contains proprietary data.
- has access is when DATARIGHTS_COL resolved to `true` or RELEASE_DATE_COL is less than today's date
- renders table row with pink when user does not have access
- added warning to DownloadDialog when a table with proprietary data is selected for download
- added additional JS unit tests to` TableUtil-Test.js`
- added Firefly API test: #7-Test Proprietary Data Display
Also:
Added Links to META-INFO API
- You can inject `links` into a column via API's META-INFO.
- added Firefly API test: 6 - Column links via API
- you can also use …
> FIREFLY-30: Add support for proprietary data display in table

- src/firefly/js/ui/FieldGroupConnector.jsx
- src/firefly/js/ui/ListBoxInputField.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/TargetPanel.jsx
This radio and List box fields need to be able to confirm that the current value is in the list when the options change.  This is a behavior that is already there but only when it initializes. If will now do it on every render if enabled.
https://irsawebdev9.ipac.caltech.edu/firefly-98-useFieldGroupConnector/firefly/
> firefly-98: useFieldGroupConnector needs optionally  confirm value for every render

- src/firefly/html/demo/ffapi-table-test.html
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
This ticket is about removing "Units" from FITS header table options.
Jira: https://jira.ipac.caltech.edu/browse/IRSA-2441 
To test:
1- Goto: https://irsawebdev9.ipac.caltech.edu/irsa-2441/irsaviewer/
2- Select an image ex:(object: m17, mission: akari)
3- Click on "Show Fits Header" from the top menu (located all the way to the right).
4- Click on "Edit Table Options" (on the top right).
5- There should be no more "Units" column, or checkbox.
> IRSA-2441_irsaviewer_fits_header_table_popup_should'nt_have_units

- src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
https://jira.ipac.caltech.edu/browse/FIREFLY-78
Added support for file_format to WsServerCommands.WsPutTableFile
Test deployment: https://irsawebdev9.ipac.caltech.edu/ff78_tblSaveToWorkspace/irsaviewer/
- Log into workspace at https://irsadev.ipac.caltech.edu
- Catalog search m31, 100''
- Save table with various file formats
- The file is saved as an IPAC table in all cases.
> FIREFLY-78: tbl save to workspace should respect file format selection

- src/firefly/html/demo/ffapi-table-test.html
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/js/charts/ui/FilterEditorWrapper.jsx
- src/firefly/js/data/MetaConst.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableDataReducer.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/SimpleComponent.jsx
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-2421
Test: https://irsawebdev9.ipac.caltech.edu/IRSA-2421/firefly/
copied from ticket:
> This applies both to client-side and server-backed tables
> In Firefly tables, sorting, filtering, or removing a column resets all of the following:
> horizontal scroll
> vertical scroll
> column widths
> None of these extra things should happen.
> 
Also:
- Convert BasicTableView into a React function component with hooks.
- Remove the use of `UNSAFE_componentWillReceiveProps`
Things to test for:
Make sure table works as before beside scroll position and column widths.
Scroll position and column widths should remain the same between table updates.  This includes sort, filter, show/hide columns, mount, and unmount.
> IRSA-2421: retain table states between updates including mount/unmount

- src/firefly/java/edu/caltech/ipac/visualize/plot/PlotGroup.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/js/charts/ChartUtil.js
Tickets:
https://jira.ipac.caltech.edu/browse/FIREFLY-69
https://jira.ipac.caltech.edu/browse/FIREFLY-70
Test deployment: https://irsawebdev9.ipac.caltech.edu/ff69_70-edge_case_fits/firefly/
- Fixed the bug preventing the display of very thin or very long FITS images.
- Improved error message when only one dimension is available in a FITS file.
- Fixed default chart bug: when picking numeric columns for plotting, 'long_string' was taken for a numeric column and plotting failed.
Used FITS images, referenced in the ticket to test. (Please, not that 2017-05-12_HA_F394_001_CAL_unk_HAWE_HWPE_RAW.fits is 324MB and takes long time to upload.) Here is the result:
> FIREFLY-69,70: handling edge case FITS from SOFIA pipelines

- src/firefly/js/visualize/region/RegionFileUploadView.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-96
- fix the styling of file information on 'Load DS9 Region File' dialog, including the position of the file name display and  the characters of the file name  is displayed with no cut-off
test:
https://irsawebdev9.ipac.caltech.edu/firefly-96/firefly/
do image search
click button 'Load a DS9 region file' to bring up 'Load DS9 Region File' dialog
'No file chosen' before file upalod or a file name after file upload should be located by the right side  'Choose File' button.
> FIREFLY-96 fix the misplaced file information on DS9 region file upload dialog

- src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/FitsEvaluation.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/MaskEval.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotHeaderInitializer.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotInitializer.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadFactory.java
- src/firefly/js/ui/StatedInputfield.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/visualize/FitsHeaderUtil.js
- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/MouseReadout.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- src/firefly/js/visualize/ui/VisHeaderView.jsx
Firefly-73: Added improved cube, wavelength and spectral info support
- Added zero header passed and managed by client
- converted wavelength projection type parsing to client
- client now maintains both projections and wavelength data
- Updated readout to show Wavelength info
- Improved cube paging controls to page though HDU's and cubes
- Show wave length in cube paging controls
_To test:_
https://irsawebdev9.ipac.caltech.edu/firefly-73-cube-updates/firefly/
Read in cube:
- Notice cube controls.
- Read in multi-HDU cubes, notice  cube controls
- read in cube with wavelength information should show in mouse readout and navigation controls
@lznakano  - can you pay attentions to:
- `Wavelength.js` - This file contains the algorithms
- `WavelengthInfo.js` - This file analyzes the headers …
> firefly-73: Added improved cube, wavelength and spectral info support

- src/firefly/js/visualize/ui/MarkerDropDownView.jsx
Remove the "all" entry in the SPITZER footprint menu.
URL: https://irsawebdev9.ipac.caltech.edu/FIREFLY-115/irsaviewer/
> FIREFLY-115:Spitzer footprint option 'All' doesn't appear to work

- src/firefly/html/test/tests-main.html
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/util/WebUtil.js
https://jira.ipac.caltech.edu/browse/FIREFLY-136
Changes:
- right-align columns with numeric types.  This is based on the column's type and not its values.
- for links:
- when there's only one link, align it based on its link `text`.
- When there's more than one, left align.
To test:
https://irsawebdev9.ipac.caltech.edu/FIREFLY-136/
Make sure all tables are behaving this way.  For links, look at test #6 of this page.
https://irsawebdev9.ipac.caltech.edu/FIREFLY-136/firefly/test/tests-main.html#test-6
> FIREFLY-136: Support right justification of numeric columns in Firefly table

- src/firefly/java/edu/caltech/ipac/visualize/plot/projection/TpvProjection.java
- src/firefly/js/visualize/projection/ProjectionInfo.js
- src/firefly/js/visualize/projection/TpvProjection.js
- src/firefly/test/edu/caltech/ipac/visualize/plot/projection/ProjectionTest.java
This PR fixes the offset seen in the overlay projection when FITS image is using TPV type (from ZTF dataset for example).
I had to force push this branch because of a bad merge beginning this week in dev. 
But the fix was made by @stargaser.
I've made the same changes in Java. (Still need to do it in gwt, will make another branch for ZTF GUI itself).
I've also updated the json sample header/data and java side with the updated tests.
NOTE:
To run `gradle test` (js or java), please use together with `firefly_test-data/IRSA-2895-debug-test-tpv` branch.
Test the UI: use the IRSAViewer deployed version here:
https://irsawebdev9.ipac.caltech.edu/irsa-2895/irsaviewer/
And upload the image with `ztf-` prefix in the repos/branch (`firefly_test_data/edu/caltech/ipac/visualize/plot/projection`) …
> IRSA 2895: TPV projection fixed in JS/Java

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisContext.java
- src/firefly/js/visualize/draw/FootprintFactory.js
- src/firefly/js/visualize/ui/MarkerDropDownView.jsx
- src/firefly_data/footprint/Footprint_SOFIA.reg
Footprints are added for three Sofia instruments.  
Please test it using URL: https://irsawebdev9.ipac.caltech.edu/firefly-106-sofiaFootprint/irsaviewer/
>  FIREFLY-106:Add more instrument footprint

- src/firefly/js/ui/TargetPanelWorker.js
- src/firefly/js/util/PositionParser.js
- src/firefly/js/util/StringUtils.js
https://jira.ipac.caltech.edu/browse/FIREFLY-29
Test build: https://irsawebdev9.ipac.caltech.edu/firefly-29_tgtresolver/firefly/?__action=layout.showDropDown&visible=true&view=IrsaCatalogDropDown
- Objects with the names starting with a number are now resolved
- Names with long-dash are now resolved (they were previously causing "TypeError: Cannot assign to read only property ..." and "Invariant Violation" warnings in React.
- Show unencoded name for failed name resolutions. (They were previously shown encoded.)
Previously failing, now resolving target names:
61 Ursae Majoris
41 Ara
12 Ophiuchi
39 Leonis
SCR J0630–7643
Known issues:
- The greek symbols are not converted into English equivalent.
- Degree symbol is not stripped.
These are the names resolved by …
> FIREFLY-29: inadequate interpretation of the target field value

- src/firefly/js/drawingLayers/NorthUpCompass.js
- src/firefly/js/visualize/ui/ThumbnailView.jsx
ZTF images are mirror-reversed with respect to the sky, with North down and East to the left. Account for this case by computing the cross product of local North and East vectors, and taking the sign to know when to flip the compass.
Link to ticket in JIRA: https://jira.ipac.caltech.edu/browse/IRSA-2894
> IRSA-2894: ZTF images flipped east-west in time series tool

- src/firefly/java/edu/caltech/ipac/firefly/data/WspaceMeta.java
- src/firefly/java/edu/caltech/ipac/firefly/server/LocalFSWorkspace.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManagerBase.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/UserServicesImpl.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WebDAVWorkspaceHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/Workspaces.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsException.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/visualize/WorkspaceCntlr.js
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsPropTest.java
- src/firefly/test/edu/caltech/ipac/firefly/ws/WsPutGetTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-94
https://jira.lsstcorp.org/browse/DM-13112 (firefly part)
Test builds:
IrsaViewer with the unchanged behavior:
https://irsawebdev9.ipac.caltech.edu/firefly-94_ws_irsa/irsaviewer/ 
IrsaViewer as it would be if WebDAV server did not support depth-'infinity'
https://irsawebdev9.ipac.caltech.edu/firefly-94_ws_noInfinity/irsaviewer/
The behavior is controlled by application property workspace.propfind.infinity (server and client, must be '__$workspace.propfind.infinity' in config). If this property is not specified, we assume that WebDAV server supports depth='infinity'. In this case the whole file tree is retrieved at once and passed to the client.
If workspace.propfind.infinity=false, only one level of workspace file tree is retrieved at a time. …
> Firefly-94 Workspace with WebDAV servers not supporting depth 'Infinity'

- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/Wavelength.java
- src/firefly/js/visualize/FitsHeaderUtil.js
- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
The wavelength implementation is carefully evaluated based on algorithm described in three reference papers.  Default values are enforced.  Three bugs are fixed.   Please see ticket https://jira.ipac.caltech.edu/browse/FIREFLY-116 for more information. 
Test URL: https://irsawebdev9.ipac.caltech.edu/FIREFLY-116/firefly/
> FIREFLY-116:Evaluate the wavelength readouts from various types of FITS and fix any Errors

- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/js/tables/FilterInfo.js
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/IpacTableTest.java
ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-59
test:    https://irsawebdev9.ipac.caltech.edu/FIREFLY-59/firefly/firefly-dev.html
As reported, filtering fail when the value contains semicolon.  Because we were using semicolon to separate conditions, this messes up the underlying query statement.
Instead of just fixing the problem, I went ahead and allow the conditions delimiter to be either `AND` or `OR`.  Although this added a useful requested feature, it also may require updates to our online help.  Please coordinate with the appropriate people after merging.
Sample conditions:
`> 0 and < 50 or is NULL`
`< 0 or > 100`
`in ('m31', 'm41') or is NULL`
> FIREFLY-59: Filtering fail when value contains semicolon

- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/util/WebUtil.js
https://jira.ipac.caltech.edu/browse/FIREFLY-53
As described in the ticket, when the URL length exceed its limit, table save will get a `Bad Request` error.  In this PR, the logic is to switch to a HTTP `post` method to avoid the limit constraint.  I've also refactored Image's PNG save to make use of common code.
Please include that in your testing as well.
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-53_bad_request/firefly/
Things affected:  tables and images save/download.
> FIREFLY-53: Saving a table with large number of columns results in HTTP 400 (Bad Request)

- src/firefly/html/css/global.css
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.css
https://jira.ipac.caltech.edu/browse/FIREFLY-162
Test link: https://irsawebdev9.ipac.caltech.edu/FIREFLY-162_save_firefox_safari/firefly/
As reported in ticket, downloading is no longer working in Firefox and Safari.
This is due to a recent chance in the code where the `<A>` tag was not added to the HTML document before triggering a click event.  Not testing it in Firefox and Safari was an oversight.
You should definitely test the fix in all browsers.  :)
- also, minor tweaked to File Upload layout
> FIREFLY-162: fixed download feature not working in firefox and safari

- src/firefly/js/templates/lightcurve/LcViewer.jsx
The buttons in the upload panel were down to the bottom in Time Series application.
Jira: https://jira.ipac.caltech.edu/browse/FIREFLY-158
K8s: https://irsawebdev9.ipac.caltech.edu/firefly-158/irsaviewer/timeseries
> FIREFLY-158_uplaod_panel_buttons_are_too_down_in_ts

- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManagerBase.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/WorkspaceCntlr.js
Follow-up for FIREFLY-94: fixes for bugs discovered while testing LSST workspace.
https://jira.lsstcorp.org/browse/DM-13112
See SUIT pull request at https://github.com/lsst/suit/pull/15 for the info how to test.
> Ff94 webdav bug

- config/logging.properties
- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
https://jira.ipac.caltech.edu/browse/FIREFLY-172
Test:  https://irsawebdev9.ipac.caltech.edu/FIREFLY-172_sofia_table_stopped_working/applications/sofia/
Additional changes here: https://github.com/IPAC-SW/irsa-ife/pull/78
- put back the ability to read VOTable from URL.
- revert changes to SofiaQuery made as a workaround to previous changes
Also
- set higher logging level for starlink to avoid repetitive warning messages
> FIREFLY-172: put back read from URL in VoTableReader

- src/firefly/html/test/tests-chart.html
- src/firefly/js/charts/ChartsCntlr.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-114
To test, check case 4 (Chart errors: non-existing column):
https://irsawebdev9.ipac.caltech.edu/firefly-114_apiErr/firefly/test/tests-chart.html
These are minimum changes to help API user to find a problem, when an error happens because of a non-existent column. Basically, in "column not found" case, an error from db is passed to the user. 
The limitations of this implementation are the following:
- If multiple columns are misspelled, only the first one is mentioned
- Non-existing column name is shown in lower case
> FIREFLY-114: improved message for an API user on non-existent column

- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-3009
In tables with proprietary data, it failed to interpret row access beyond first page.  This is due to `startIdx` not being passed to the table rendering logic.
To test, follow the instructions from the ticket.
Test build:  https://irsawebdev9.ipac.caltech.edu/IRSA-3009_sort_proprietary_rows/applications/sofia/
> IRSA-3009: Table sort wrongly interpret proprietary data

- src/firefly/js/util/VOAnalyzer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-166
When VOTable Link contains bad column reference, table should not fail to load.
This fix applies to both `href` and `value` substitution.  When the substitution fail to resolve, it will use what is given.
To test:
https://irsawebdev9.ipac.caltech.edu/FIREFLY-166_link_substitution_error_handling/firefly/
- upload the attached file in the ticket.  In the 4th column, the 5th links should say 
`info-${non-existing-column}-NGC6543`, because `non-existing-column` is not a valid column in this table.
> FIREFLY-166: fixed condition when Link Substitution fails, table fail to load.

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/drawingLayers/Catalog.js
https://jira.ipac.caltech.edu/browse/FIREFLY-259
Test build: https://irsawebdev9.ipac.caltech.edu/firefly-259_filterBug/firefly/
- Fixed a bug which was indirectly introduced by firefly-88: a list of drawing drawing objects for a catalog overlay now can have extra objects (like search center), which do not correspond to catalog table rows. These objects should be excluded when filter by ROW_IDX is constructed. 
To test, select on image a subset of points that includes search center and use filter button.
- Also fixed non-returning spinning wheel in charts when there are no data. To test, select an empty area on image and filter or filter from the table with such constraints that no data are left. An error message "No data available" should show up for the related charts.
> Firefly 259 filter bug

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotFactory.java
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-185
Test deployment: https://irsawebdev9.ipac.caltech.edu/firefly-185-3color/firefly/
Fixed two bugs related to 3-color: 
1) exception described in the ticket (when less than 3 bands are used) 
2) no image (server-side) failure when red band is not used
Two test, create a 3-color image with 1 or 2 bands, with and without red.
> FIREFLY-185: 3-image composition doesn't work

- src/firefly/js/ui/ImageSelect.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-113
test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-113_image_filtering_band/firefly/
The behavior should be as follow:
- Filtering should only affect the view of the panel.  So when images are selected, it will remained selected even though it is no longer visible by filtering.
- The collapsible level checkbox are based on the currently filtered view.  It is checked when all of its filtered checkboxes are checked.  Action(check/uncheck) performed on this checkbox will only affect the filtered image checkboxes.
- Selected images are shown in brown under Selection: at the top of the panel.
> FIREFLY-113: Filtering images by BAND doesn't filter properly the sub selection

- src/firefly/js/data/ServerRequest.js
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/ui/StatedInputfield.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/task/PlotAdminTask.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/task/WcsMatchTask.js
- src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
Firefly-179: Fixed right-east align and align w/rotation issues
- right-east image align now work
- fixed issue with aligning to rotated images
- fixed align left-east with right-east image
- clean up of rotation dialog: (fixes some issues in FIREFLY-146)
- fixed multiple issues with rotation dialog and improved it.
- now does immediate results
- operates on active image.
- has a north up button
- show active images's rotation
- Added slider
- rotation dialog hides when all image removed
https://jira.ipac.caltech.edu/browse/FIREFLY-179
_To Test:_
https://irsawebdev9.ipac.caltech.edu/firefly-179-wcs-match-bug/firefly/
- load two images at same target (i.e. 2mass, wise), rotate one then match the other to it. Check that they scroll around together
- load two east-right images …
> Firefly-179: Fixed right-east align and align w/rotation issues

- config/ehcache.xml
- src/firefly/java/edu/caltech/ipac/firefly/server/cache/resources/ehcache.xml
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
- src/firefly/js/visualize/ui/WorldPtFormat.jsx
IRSA-3044: fixed image bugs found in SOFIA
- Will now load 60,000 images from cube
- Fixed: fail of big image after a good load showing the fail message
- Fixed: later cube screen size not getting initialized in certain cases
- Changed ImageCenterDropDown "center on target" with coverage (Firefly-180)
- If all the catalogs have the same target I will enable it
(sofia case or case where you search m31 with multiple catalogs).
If the catalogs don’t have the same target
I will disable it and the use will use the layer control
https://jira.ipac.caltech.edu/browse/IRSA-3044
_to test:_
https://irsawebdev9.ipac.caltech.edu/irsa-3044-various-sofia-issues/firefly/
https://irsawebdev9.ipac.caltech.edu/irsa-3044-various-sofia-issues/applications/sofia/
> IRSA-3044: fixed image bugs found in SOFIA
