Caltech-IPAC/firefly

src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/ui/RadioGroupInputField.jsx, src/firefly/js/ui/panel/CollapsiblePanel.css, src/firefly/js/ui/panel/CollapsiblePanel.jsx, src/firefly/js/visualize/XYPlot.jsx, src/firefly/js/visualize/XYPlotCntlr.js, src/firefly/js/visualize/XYPlotOptions.jsx, src/firefly/js/visualize/XYPlotTableViewPanel.jsx
The implementation of XY Plot options.
Includes updates to CollapsiblePanel to allow picking up values from the collapsed fields
and updated RadioGroupInputField to correctly display vertical or horizontal alignment.
(Does not include the options for Density Plot.)
=> DM-4577 XYPlot options

src/firefly/js/tables/SelectInfo.js, src/firefly/js/visualize/ChartsTableViewPanel.jsx, src/firefly/js/visualize/HistogramTableViewPanel.jsx, src/firefly/js/visualize/XYPlot.jsx, src/firefly/js/visualize/XYPlotCntlr.js
Added selection support to XY Plot view of a table
=> DM4582: XY Plot view of a table - selection support

src/firefly/js/tables/TablesCntlr.js, src/firefly/js/visualize/ChartsTableViewPanel.jsx, src/firefly/js/visualize/XYPlot.jsx, src/firefly/js/visualize/XYPlotCntlr.js
Added filtering from XYPlot view
Fixed bug in dispatchTableHighlight of TablesCntrl which was omitting highlightedRow from action payload, when highlightedRow was 0.
=> DM-5274 filtering from XYPlot table view

src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TableRenderer.js
- Fixed scrollToRow bug.
- Added renderers option to table
- Created several common renderers
=> DM-5552: Add renderer option to js table

src/fftools/js/fftools.js, src/firefly/js/Firefly.js, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/core/History.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/core/ReduxFlux.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/TablesUiCntlr.js, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/SearchPanel.jsx, src/firefly/js/util/WebUtil.js
an early implementation of history and routing.  it's based on the old framework with placeholder for additional features.
=> DM-4595: first pass at history and routing.

src/firefly/js/core/History.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/ui/InputField.jsx, src/firefly/js/ui/InputFieldView.jsx, src/firefly/js/ui/SearchPanel.jsx, src/firefly/js/util/WebUtil.js
A FileUpload field is added to the SearchPanel.
To test, select a file to upload.  Click search, then monitor this directory for uploaded file:
/hydra/workarea/fftools/temp_files/
File should start with 'upload_'.
=> DM-5584: create reusable file_upload component

src/firefly/js/drawingLayers/ActiveTarget.js, src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/drawingLayers/SelectArea.js, src/firefly/js/ui/TestCatalog.jsx, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/draw/CanvasWrapper.jsx, src/firefly/js/visualize/draw/DrawLayer.js, src/firefly/js/visualize/draw/Drawer.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/reducer/DrawLayerReducer.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Includes:
- Select, Unselect, Filter
- Drawer support the selected layer
- Handling decimation
- VisUtil function to get all points in a selected area
- Highlighted point fix
=> DM-4503: ImageViewer: Select, Unselect, Filter

src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanelOptions.jsx
Just minor tweak to table container components to make it play well with other container types.
Not much to test.  Table should still appears correctly after changes.
=> DM-5723: table fail to resize in some cases

src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/ui/SuggestBoxInputField.css, src/firefly/js/ui/SuggestBoxInputField.jsx, src/firefly/js/visualize/XYPlotOptions.jsx
Created suggest box input field.
Modified ExampleDialog to show an example and XYPlotOptions to use it for column selection. 
(In future it should assist creating column expressions.)
=> DM-4571-suggestbox

src/firefly/js/ui/panel/TabPanel.css, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/visualize/ui/FitsHeaderView.jsx
The table sorting and popup's resizing are both working in this branch.  Please take a look and let me know your comments. 
Thanks!
=> DM-5757, DM-5775:make the resize work in 3-color bands

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java, src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/ui/ImageSelectDropdown.jsx, src/firefly/js/ui/panel/CollapsiblePanel.css, src/firefly/js/ui/panel/CollapsiblePanel.jsx, src/firefly/js/ui/sizeInputFields.jsx, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/ui/ImageSelectPanel.css, src/firefly/js/visualize/ui/ImageSelectPanel.jsx, src/firefly/js/visualize/ui/ImageSelectPanelProp.js, src/firefly/js/visualize/ui/ImageSelectPanelReducer.js, src/firefly/js/visualize/ui/ImageSelectPanelResult.js, src/firefly/js/visualize/ui/ImageSelectPanelState.js
Add 3 colors support to image selection dropdown, disclosure component is used for r, g, b field group tabs. 
For SizeInpuFiield component, fixed validation, add props 'showFeedback' for feedback display and add valid range in error message popup. 
Some Issues: 
- should 'disclosure' component's status be kept? 
- image creation doesn't work if any of r, g, b is disabled.
=> DM-5363-ImgSel3Colors

src/firefly/js/ui/ImageSelectDropdown.jsx, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/ui/RadioGroupInputField.jsx, src/firefly/js/ui/RadioGroupInputFieldView.jsx, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/ui/ImageSelectPanel.jsx, src/firefly/js/visualize/ui/ImageSelectPanelResult.js
The image select panel provides the options to replace or modify the plot in either 3 colors or not. The option is  based on if  any plot  is selected before opening the dropdown  or if the viewer of the selected plot can receive new plot.
=> DM-5364-ImgSelAddPlot replace or modify the plot based on if there is  highlighted plot or if the highlighted plot is 3-colors.

src/firefly/java/edu/caltech/ipac/util/StringUtils.java, src/firefly/js/core/JsonUtils.js, src/firefly/js/core/ReduxFlux.js, src/firefly/js/rpc/PlotServicesJson.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/ChartsTableViewPanel.jsx
- Change 'post' to use 'form-urlencoded' instead of 'multipart/form-data'.
- Add 'file-upload'.  It should use 'multipart/form-data'.
- Switch plot and table request method to 'post'.
=> DM-5803: fetchUrl is not handling post requests correctly.

src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java, src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java, src/firefly/js/core/messaging/WebSocketClient.js, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReduer.js, src/firefly/js/tables/reducer/TableResultsReducer.js, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/PagingBar.jsx, src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/TableStatsCntlr.js, src/firefly/js/visualize/XYPlotCntlr.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/ImageMetaDataWatcher.js, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
Added paging bar to image full grid mode.
=> Dm 5806 image pagebar

src/fftools/js/fftools.js, src/firefly/html/css/global.css, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReducer.js, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/PagingBar.jsx, src/firefly/js/ui/ResultsPanel.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
please see jira ticket for details.
=> DM-5859: Table: Add keyboard navigation

src/firefly/js/core/ReduxFlux.js, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/region/Region.js, src/firefly/js/visualize/region/RegionFactory.js, src/firefly/js/visualize/ui/ImageSelectPanelResult.js
- create Region class to contain various types of region data
- build parser to parse region JSON generated by region file upload.
- some accessory update: change the label of 3 color image to be '3-Color Image'.
=> build parser to parse DS9 region JSON resulted by region file upload and region objects to contain data and properties of all types of regions

src/firefly/java/edu/caltech/ipac/util/DataObjectUtil.java, src/firefly/java/edu/caltech/ipac/util/expr/Expression.java, src/firefly/js/util/expr/Expr.js, src/firefly/js/util/expr/Expression.js, src/firefly/js/util/expr/Parser.js, src/firefly/js/util/expr/Scanner.js, src/firefly/js/util/expr/SyntaxException.js, src/firefly/js/util/expr/Token.js, src/firefly/js/util/expr/Variable.js, src/firefly/js/util/expr/__test__/Expression-test.js, src/firefly/js/visualize/ChartUtil.js, src/firefly/js/visualize/XYPlotCntlr.js, src/firefly/js/visualize/XYPlotOptions.jsx
Converted GWT expression library to JS.
Wrote a unit test for its functions and operators.
Added expression support to XY plot column selection.
=> DM-4573 expression support (converted expression parsing library to JS)

src/firefly/java/edu/caltech/ipac/firefly/server/servlets/CommandService.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerCommands.java, src/firefly/js/visualize/HistogramCntlr.js, src/firefly/js/visualize/TableStatsCntlr.js, src/firefly/js/visualize/ui/FitsHeaderView.jsx, src/firefly/js/visualize/ui/MouseReadout.jsx, src/firefly/js/visualize/ui/VisHeaderView.jsx
Please check and let me know if both FitsHeader and MouseReadout look OK.  Thanks!
=> DM-5283:fixed 2-color flux readout  layout issue and FitsHeader's issues

src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/ui/VisToolbarView.jsx
Write a button on the toolbar that monitors the active plot view's group and shows the locked or unlocked icons
Add an action and reducer functions the will toggle the lock state of the group.
p.s. pardon the commit comments
=> DM-5185 add a group lock icon

src/firefly/js/core/ReduxFlux.js, src/firefly/js/drawingLayers/RegionPlot.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/draw/DrawUtil.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/PointDataObj.js, src/firefly/js/visualize/draw/ShapeDataObj.js, src/firefly/js/visualize/region/Region.js, src/firefly/js/visualize/region/RegionDrawer.js, src/firefly/js/visualize/region/RegionFactory.js, src/firefly/js/visualize/region/RegionFileUploadView.jsx, src/firefly/js/visualize/ui/VisToolbarView.jsx
region drawing for the following regions, 
circle, ellipse, box, polygon, point (circle, box, diamond, cross, x, arrow, boxcircle), line, text, annulus, box annulus, ellipse annulus.  (annulus is made for the case with at least two repeated regions of the same type). 
add the following functions to file ShapeDataObj.js
- makeRectangleByCenter, makeEllipse
- drawEllipse, 
- makeTextLocationRectangle, makeTextLocationEllipse
- update drawRectangle by adding the case which is given the rotating angle and rectangle center.
=> Dm 4485 region drawing

src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PlotPngCreator.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerCommands.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java, src/firefly/js/data/ServerParams.js, src/firefly/js/rpc/PlotServicesJson.js
This is the new server call for making a hard copy for image with the drawing layers
=> DM-6139: server call for region on images

src/firefly/js/ui/CatalogSearchMethodType.css, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/visualize/ui/CatalogSelectViewPanel.css, src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx, src/firefly/js/visualize/ui/CatalogTableListField.css, src/firefly/js/visualize/ui/CatalogTableListField.jsx
This PR is about fixing the style for the catalog panel dialog (part 2). Please review it. I did my best to match the OPS one.
=> DM-6134: fix style

src/firefly/js/core/ReduxFlux.js, src/firefly/js/drawingLayers/DistanceTool.js, src/firefly/js/drawingLayers/SelectArea.js, src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/CsysConverter.js, src/firefly/js/visualize/DrawLayerCntlr.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/draw/DrawLayer.js, src/firefly/js/visualize/iv/ImageViewerLayout.jsx, src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- mouse selection should now work the way it is expected to
- includes bug fixes with distance tool and select area editing
- includes layer fixes, the most active should be on top
=> DM-6141: improve the mouse control with the drawing layers

.eslintrc, src/firefly/js/core/MasterSaga.js, src/firefly/js/core/ReduxFlux.js, src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/fieldGroup/FieldGroupUtils.js, src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/util/Validate.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/RangeValues.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/draw/DrawLayer.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/PointDataObj.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/ui/ColorDialog.jsx, src/firefly/js/visualize/ui/ColorPanelReducer.js
- added a sega to handle side effect problem with color dialog
- field groups need a sega to more effective respond to out side actions
- the dispatchChangeFieldGroup needs better, more documented parameters
- update multiple fields at the same time.
- now can has a nullAllowed, default to false
- will revalidate everything on complete
- will revalidate on mount
- has restore initial values
- Also: in started playing with JSDocs @typedef, so some file unrelated to this ticket have more documentaion
=> DM-6136 update to field group

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java, src/firefly/js/astro/conv/CoordConv.js, src/firefly/js/astro/conv/Ecleqx.js, src/firefly/js/astro/conv/Fk5prc.js, src/firefly/js/astro/conv/Galeqd.js, src/firefly/js/astro/conv/Gtjpa.js, src/firefly/js/astro/conv/Gtjul2.js, src/firefly/js/astro/conv/Jbdist.js, src/firefly/js/astro/conv/Jbposa.js, src/firefly/js/astro/conv/Jcnvc2.js, src/firefly/js/astro/conv/Jcnvp2.js, src/firefly/js/astro/conv/Jgtfkc.js, src/firefly/js/astro/conv/Nwcprc.js, src/firefly/js/visualize/Projection.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/projection/ARCProjection.js, src/firefly/js/visualize/projection/AitoffProjection.js, src/firefly/js/visualize/projection/CartesianProjection.js, src/firefly/js/visualize/projection/CylindricalProjection.js, src/firefly/js/visualize/projection/GnomonicProjection.js, src/firefly/js/visualize/projection/LinearProjection.js, src/firefly/js/visualize/projection/NCPProjection.js, src/firefly/js/visualize/projection/OrthographicProjection.js, src/firefly/js/visualize/projection/PlateProjection.js, src/firefly/js/visualize/projection/Projection.js, src/firefly/js/visualize/projection/ProjectionUtil.js, src/firefly/js/visualize/projection/SansonFlamsteedProjection.js
- Conversion of the coordinate system routines
- convert the GWT projection to JavaScript
- Server now sends projection info in JSON as well, old way not yet removed
- VisUtil.USE_GWT will control if the new is used or the old.
=> DM-6437: Convert GWT java algorithmic to JavaScript

buildScript/depends.gincl, buildScript/gwt.gincl, buildScript/webpack.config.js, package.json, src/fftools/package.json, src/firefly/js/Firefly.js, src/firefly/js/api/ApiExpandedView.jsx, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/core/FireflyViewer.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/metaConvert/ConverterFactory.js, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/tables/SortInfo.js, src/firefly/js/tables/TableConnector.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/tables/ui/TablesContainer.jsx, src/firefly/js/ui/ResultsPanel.jsx, src/firefly/js/ui/TriViewPanel.jsx, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx, src/firefly/package.json
The details of this commit is in this ticket:  https://jira.lsstcorp.org/browse/DM-6108
Also..
- fix local table sorting
- fix online help link not working
- fix progress not updating while using gradle :firefly:dev
=> DM-6108: firefly viewer layout manager

src/firefly/html/demo/ffapi-highlevel-test.html, src/firefly/html/demo/ffapi-lowlevel-expanded-demo.html, src/firefly/js/api/ApiBuild.js, src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/api/ApiUtilImage.jsx, src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/PlotImageTask.js, src/firefly/js/visualize/Point.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/draw/DrawLayerFactory.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/FootprintObj.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/projection/Projection.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageChooser.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/saga/ImageMetaDataWatcher.js, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- Coverage
- Fixed FootprintObj, is was ported but never tested
- Currently, coverage is forced on in TriViewImageSelection.
- Ported CoverageChooser to determine which images to plot, we still should add wise to this.
- a little clean up in VisUtil.js
- rearranged test file a little for coverage demo
- More documentation in DrawLayerFactory (not related to the ticket)
=> DM-5191: Coverage - support coverage in application and API

src/firefly/js/drawingLayers/ComputeWebGridData.js
Xiuqin,
Please check a few maps and let me know if  you spot any issues. 
Thanks!
=> DM-6239:fixed the label's issue when the coordinate is Ecliptic

src/firefly/js/tables/ui/BasicTable.jsx, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/SizeInputField.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx, src/firefly/js/visualize/ui/CatalogSelectViewPanel.css, src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx, src/firefly/js/visualize/ui/CatalogTableListField.css, src/firefly/js/visualize/ui/CatalogTableListField.jsx
Please, review this PR:
- added table with customized cell renderers, 
+ on the column 'name' a link cell has been defined, 
+ an extra contains the url definition of that link info
+ an extra column input field for the constraints and connected to a filter  (same as the filter used for the column headers)
+ SQL text area ( no validation yet added, see other ticket DM-6136) added
- Catalog search is now a Gator request built from the constraint input, selected columns and sql text if any
- redesign the current OPS panel following a 3-steps flow from left to right-down (catalog set, spatial method defined and constraints added)
=> dm-6137: added irsa catalog panel with constraints table and sql textarea

src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryByConeSearchURL.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java, src/firefly/java/edu/caltech/ipac/firefly/ui/searchui/LoadCatalogFromVOSearchUI.java
...when required ucds are present.
This solution is to rely on "use" parameter in QueryVOTable based search processors to set the necessary meta attributes.
Example of access URL (wise_allsky, but not from ipac):
http://wfaudata.roe.ac.uk/wise-dsa/DirectCone?DSACAT=WISE&DSATAB=wise_allskysc&
=> DM-6902 - possible solution for VO catalog coverage 

src/firefly/html/css/global.css, src/firefly/js/api/ApiUtilTable.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/ToolbarButton.css, src/firefly/python/firefly_widgets/examples/firefly_widgets.ipynb, src/firefly/python/firefly_widgets/examples/test.ipynb
firefly:
prerequisites: gradle, tomcat, and node.js
`gradle :firefly:buildAndDeploy`
test:
goto http://localhost:8080/firefly/
firefly_widgets
prerequisites:
install latest Anaconda with Python 3.5 from https://www.continuum.io/downloads
install latest ipywidgets
`conda install -c conda-forge ipywidgets`
test:
```
cd ./firefly/src/firefly/python/firefly_widgets/examples
jupyter notebook test.ipynb
```
=> DM-6942: Explore and experiment the process of creating a Jupyter widgets

src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/Point.js, src/firefly/js/visualize/draw/DrawOp.js, src/firefly/js/visualize/ui/ImageSelectPanel.jsx, src/firefly/js/visualize/ui/ImageSelectPanelResult.js, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- update the plot container to be able to create a new plot, replace an existing plot or neither while doing image select.
=> DM-7088 make the image select work with coverage correctly

.eslintrc, src/firefly/html/demo/ffapi-highlevel-test.html, src/firefly/js/api/ApiBuild.js, src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/api/ApiUtilChart.jsx, src/firefly/js/api/ApiViewer.js, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/HistogramCntlr.js, src/firefly/js/charts/XYPlotCntlr.js, src/firefly/js/charts/ui/ChartsContainer.jsx, src/firefly/js/charts/ui/HistogramOptions.jsx, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/jsdoc_config.json
External API for XYPlot and Histogram
- Added showHistogram
- added showXYPlot and showHistogram to external viewer interface
- the external charts can be tested from ffapi-highlevel-test (Show XYPlot and Show Histogram links)
- Also updated JSDoc, only public methods are included
=> DM-6282 Chart API: external API and the API for histogram

src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/visualize/saga/CoverageWatcher.js
DM-7521: gator coverage now allows you to add more plots. This fixes the core issue of the ticket
- to test: bring up gator and you should be able to add more plots.
=> DM-7521: gator coverage now allows you to add more plots. 

src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/TargetFeedback.jsx, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/TargetPanelWorker.js, src/firefly/js/ui/VoSearchPanel.jsx, src/firefly/js/visualize/ui/ImageSelectPanel.jsx
Target panel resolve selection now working
- can choose 'Ned or Simbad' or Simbad or Ned'
- the dummy ui elements removed from image and catalog panel
- feedback is now centered
=> DM-7610: Target panel resolve selection now working

src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/js/visualize/saga/CoverageWatcher.js
=> DM-7470: Tri-view coverage now working more like the GWT version

src/firefly/js/charts/ui/ColSelectView.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/PagingBar.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx, src/firefly/js/visualize/ui/FitsHeaderView.jsx
https://jira.lsstcorp.org/browse/DM-7547
Also:
- re-sizes the column selection panel when description is not available.
- fix usage of TablePanel so that only 1 table ui state is created for each table model.
=> DM-7547: Remove the extra column on far right-hand side of a table

src/firefly/js/visualize/task/WcsMatchTask.js
Ticket can be tested by following the ticket description:
- https://jira.lsstcorp.org/browse/DM-7760
and using the following two images.
- http://irsa.ipac.caltech.edu/data/SPITZER/Enhanced/SEIP/images/6/0095/60095931/9/60095931-19/60095931.60095931-19.MIPS.1.median_mosaic.fits
- http://irsa.ipac.caltech.edu/data/SPITZER/Enhanced/SEIP/images/6/0095/60095931/9/60095931-19/60095931.60095931-19.MIPS.1.mosaic.fits
=> DM-7760: Fixed: WCS Match not working correctly if image starts out unlocked

src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/firefly/util/DataSetParser.java, src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/FilterEditor.jsx, src/firefly/js/tables/ui/TableRenderer.js
- show column's label in 'Text View' if it exists.
- disable filter when content of the column contains html
=> DM-7488: Text View does not show column's label, only name.

src/firefly/js/charts/ui/XYPlotOptions.jsx
This is the fix fo DM-7805:
Changing column to plot doesn't reset the 'flip' option to unchecked state
In this implementation, X or Y column change would result in the reset of the corresponding options (excluding 'grid').
=> DM-7805 reset column options on column change

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PlotServUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/WebPlotReader.java, src/firefly/java/edu/caltech/ipac/visualize/plot/FitsRead.java, src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/fieldGroup/FieldGroupUtils.js, src/firefly/js/templates/lightcurve/LcImageToolbar.jsx, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/ui/RadioGroupInputFieldView.jsx, src/firefly/js/visualize/DrawLayerCntlr.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/reducer/HandlePlotCreation.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/task/WcsMatchTask.js, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/ImagePager.jsx, src/firefly/js/visualize/ui/MultiImageViewerContainer.jsx, src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
- mutliple plots coming in with table selection
- plots comming in as wcs matched
- wcs functionallity expanded to support new plots, matching zoom and rotation
- scroll together
- preference for zoom and stretch
- rotation will stay wcs matched
- set number of images (1,3,5,7)
=> DM-7767 Make Multi image viewer support light curve type layout

src/firefly/js/core/LayoutCntlr.js, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/visualize/ImageOverlayTask.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/ZoomUtil.js, src/firefly/js/visualize/iv/ExpandedModeDisplay.jsx, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/iv/ImageViewerLayout.jsx, src/firefly/js/visualize/reducer/OverlayPlotView.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/saga/ImageMetaDataWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/ImagePager.jsx, src/firefly/js/visualize/ui/ImageSelectPanel.jsx, src/firefly/js/visualize/ui/ImageSelectPanelResult.js, src/firefly/js/visualize/ui/MaskAddPanel.jsx, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- MultiViewCntlr refactored, will work with 2d plots and charts
- a little code cleanup
=> DM-7912: refactor MultiViewCntlr to work with more than just images

src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/visualize/ui/ImageSelectPanel.jsx, src/firefly/js/visualize/ui/VisToolbarView.jsx
1. Fixed problem with extra help icon on select a new image panel.
2. Updated some help links per Luisa's feedback.
3. Updated the LC viewer panels.
=> DM-7948 bug fixes and upadtes for irsaviewer/LC viewer

src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcViewer.jsx
https://jira.lsstcorp.org/browse/DM-7830
- Also show xyPlot on Peak Table.
=> DM-7830: Hook image display into raw table as well.

src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
The development adds catalog fetch error handling into catalog constraint panel: 
- Create table object with error information  when catalog fetch error occurs. 
- add generic error display into BasicTableView
- move the table with error creator from TableCntlr into TableUtil
=> DM-8189 handling fetch error for the catalog constraint panel.

src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java
For catalog search (RunDeepSource and RunDeepFourcedSource), qserv functions are used in all four type of searches.  For the image meta search, the scisql functions are still used.  They will be changed in the ticket DM-8334.  
To test this branch:
1. check it out
2. build and deploy
3. connect vpn
4.  use the value below to run the search:
position: 9.469,-1.152,
radius = 0.01
For ellipse:
semi-major-axis = 58 arcsec
ratio = 0.62
Thanks!
=> DM-8303:Use replace scisql functions by qserv functions

src/firefly/js/core/JsonUtils.js, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx, src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx, src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx, src/firefly/js/visualize/ui/LSSTImageSpatialType.jsx
- re-style UI for selecting  LSST image tables and catalog tables.
- create spatial search component for LSST image table search.
- fix DD table constraint column data entry bugs. 
- store the search panel status for the selection of every table. 
- fix table fetch query to be sent by 'POST' method.
=> DM-8308 Update LSST search panel to work for both catalog and image searches

src/firefly/html/demo/ffapi-highlevel-test.html, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/saga/ImageMetaDataWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js
- dispatchPlotImage now requires viewerId or it will default the defaul
viewer.  This is a change in original behavior, before there was not
defaulting.
- cleaned up ffapi-highlevel-test.html to remove old api examples
=> DM-8376: url will now work for image plot

src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/rpc/SearchServicesJson.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/js/core/JsonUtils.js, src/firefly/js/core/background/BackgroundMonitor.jsx, src/firefly/js/data/ServerParams.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/ui/ScriptDownloadDialog.jsx, src/firefly/js/util/BrowserUtil.js, src/firefly/js/util/WebUtil.js, src/firefly/python/firefly_widgets/examples/test.ipynb
https://jira.lsstcorp.org/browse/DM-8181
To test:
- launch /firefly/lc.html
- upload a raw table
- click download on top right corner
- enter at least 20 images, so that more than one download parts appear in the background monitor
- when package completes, click on "Get Download Script"
- play around with the different parameters to make sure it's working as intended
=> DM-8181: Add script download dialog

src/firefly/test/edu/caltech/ipac/visualize/plot/CircleTest.java
To test it, 
1. check out this branch
2. build Firefly:
gradle :firefly:war
gradle :firefly:deploy
3. run the unit test
gradle :firefly:test
Thanks!
=> DM-7947:Add unit test for Circle class

buildScript/webpack.config.js, package.json, src/firefly/js/FFEntryPoint.js, src/firefly/js/Firefly.js, src/firefly/js/core/ReduxFlux.js, src/firefly/js/ui/Banner.css
https://jira.lsstcorp.org/browse/DM-8385
- setup LSST/suit repo
- added lsst logo onto the banner
- make sure build scripts are fully functional
- minor code refactoring
setup:
git clone https://github.com/lsst/suit
ensure both repos (firefly and suit) are in branch 'DM-8385_pdac_v1'
Things to test:
- able to build and deploy suit
`gradle :suit:buildAndDeploy`
- ensure dev mode works.  webpack should monitor firefly's source code as well as suit.
`gradle :suit:dev` 
- verify that LSST logo is used and that suit application is working as expected.  This require vpn into ncsa.
=> DM-8385: PDAC v1 deployment

src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableResultsReducer.js, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/visualize/saga/ChartsSync.js
https://jira.lsstcorp.org/browse/DM-8598
see ticket for details.
=> DM-8598: Dispatch TBL_RESULTS_ACTIVE when table is removed

src/firefly/js/templates/lightcurve/LcImageToolbar.jsx, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/templates/lightcurve/LcImageViewerContainer.jsx, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/iv/ExpandedModeDisplay.jsx, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/iv/ImageViewerLayout.jsx, src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/MultiImageViewerView.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- Light curve viewer now has it own expanded mode
=> DM-8684: allow for others types of image expanded mode

src/firefly/html/css/global.css, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTFileGroupProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java, src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/core/History.js, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
Please test it while I am away.  To test it,
1. check out this branch
2. start vpn 
3. select LSST Data/Images
4. enter 9.469,-1.152
5. highlight one or more columns and then select "Prepare Download"
The current external file name conversion is
DeepCoadd/deepCoaddId-filter.fits
ScienceCCD/scienceCcdId-filter.fits
Thanks!
=> DM-7827:add file group search processor

src/firefly/js/templates/lightcurve/LcPeriodogram.jsx, src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx
Note: change the periodogram calculation options for now.
=> Update the periodogram panel option so there is only LS algorithm in use 

src/firefly/java/edu/caltech/ipac/visualize/plot/GeomTestMain.java, src/firefly/test/edu/caltech/ipac/visualize/plot/GeomTest.java
Please check out the data branch at firefly_test_data with the same branch name to run the tests.
The coverage of this unit test is 85% of the method and 57% of lines. There are still more room to improve.  But for now, I think it is sufficient.
=> DM-8660: add unit test for Geom class

src/firefly/js/ui/DownloadDialog.jsx
https://jira.lsstcorp.org/browse/DM-9196
Use lc.html for testing.  No visible changes.  
You will be able to verify the passed parameter if you set a breakpoint in the debugger in LightCurveFileGroupsProcessor.java
=> DM-9196: fix cutout size parameter is not passed to server

src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/templates/lightcurve/LCPanels.css, src/firefly/js/templates/lightcurve/LcImageToolbar.jsx, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/templates/lightcurve/LcImageViewerContainer.jsx, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcPeriod.jsx, src/firefly/js/templates/lightcurve/LcPeriodogram.jsx, src/firefly/js/templates/lightcurve/LcPhaseFoldingPanel.jsx, src/firefly/js/templates/lightcurve/LcPhaseTable.js, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/templates/lightcurve/PeriodogramOptionsPanel.jsx, src/firefly/js/ui/Banner.css, src/firefly/js/ui/RangeSliderView.jsx
- revamp result area including finder panel, chart, table and image areas
. finder panel includes entries which are mission related and non-related. 
. synchronize among table highlight, image selection, chart highlight and entries changes. 
. add 'Period finding' button in the finder panel to move to period area to find period and the phase folding table. 
. Reorder the phase folding table by moving phase related columns to the left side of the table. 
. add indication regarding table sort columns and sort order. 
- update period area according to the feedback to the flow and the layout of DM-8668 
. show the time and flux field as read only data (as set in result area). 
. put period min and max entries to the end of the period slider. 
. highlight the period …
=> DM-8670 change LC result area as new UI design for time series viewer and update period/periodogram area based on the review feedback.

src/firefly/test/edu/caltech/ipac/visualize/plot/ImageDataTest.java
Add unit test for ImageData class
To test it, please check out the data in firefy_test_data with the same branch name.
=> DM-8661:Create a Unit Test for ImageData class

src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
Please, review the periodogram form and let me know if you find any problem.
=> DM-9141: cleanup periodogram form

src/firefly/js/ui/CatalogSearchMethodType.jsx
Label name and position of the radio button choice changed to top. 
Please check and let me know.
=> DM-9339: lables name changes

package.json, src/firefly/html/demo/ffapi-highlevel-test.html, src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableParser.java, src/firefly/java/edu/caltech/ipac/util/CollectionUtil.java, src/firefly/java/edu/caltech/ipac/util/DataGroupQuery.java, src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java, src/firefly/js/data/ServerParams.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/tables/FilterInfo.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcPeriod.jsx, src/firefly/js/templates/lightcurve/LcPhaseTable.js, yarn.lock
https://jira.lsstcorp.org/browse/DM-7971
also:
- fix missing rows.
- fix phase folded table sort issue
To test:
- Using ts.html, upload a raw table.
- add a phase-folded table.
- the highlighted row of the two tables should be in synced.
Note:  when going from raw to phase-folded, it will highlight the first occurrence.
=> DM-7971: Sync highlighted row for raw and phase-folded tables.

src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/charts/ui/Histogram.jsx, src/firefly/js/ui/ChartSelectDropdown.jsx
Check that column selection dialog has 'OK' button instead. And 'Chart' dropdown dialog has 'OK' instead of Search submit button.
=> DM-9346: change label to OK

src/firefly/test/edu/caltech/ipac/firefly/util/FitsGenerator.java, src/firefly/test/edu/caltech/ipac/firefly/util/FitsValidation.java, src/firefly/test/edu/caltech/ipac/visualize/plot/FlipXYTest.java
1.  Add unit test for FlipXY class
2.  Add a utility class to generate a FITs file for unit test
3.  Modified the FitsValidation.class to test each values when the HeaderCard contains numberical values
=> DM-7780:JUnit Test for image flip (FlipXY)

src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/ui/Banner.css, src/firefly/js/ui/Banner.jsx
https://jira.lsstcorp.org/browse/DM-9327
Add Time Series Viewer into IFE as a feature of irsaviewer.
To test:
- checkout this branch on both firefly and ife.
- build irsaviewer from ife.
- goto http://localhost:8080/irsaviewer/timeseries
=> DM-9327: Create IFE app for Time series viewer

src/firefly/java/edu/caltech/ipac/visualize/plot/ImagePlot.java, src/firefly/test/edu/caltech/ipac/visualize/plot/ImagePlotTest.java
Add unit test for ImagePlot class
Fixed typo error in ImagePlot.java
To test,
Please check out the testing data at firefly_test_data with the same branch name.
Thanks!
=> DM-8845:Create a Unit test for ImagePlot class

src/firefly/js/visualize/iv/EventLayer.jsx
_to test-_ choose lock by click option and click on the image symbol should be (within a pixel) of centered on the mouse
=> DM-9552: Fixed: Reported mouse position on mouse click is a couple of pixels off

src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchRequestUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java, src/firefly/js/templates/lightcurve/lsst_sdss/LsstSdssMissionOptions.js
https://jira.lsstcorp.org/browse/DM-9565
Sometimes, we don't want users to change the filters applied to the table. (For example, when user selects a band in the LSST time series viewer, we want user to see the table filtered by band, but no choice to remove band filter.)
=> DM-9565 - support for hidden filters

src/firefly/js/drawingLayers/DistanceToolUI.jsx, src/firefly/js/drawingLayers/NorthUpCompassUI.jsx, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/ui/PointShapeSizePicker.jsx, src/firefly/js/ui/RadioGroupInputFieldView.jsx
Fixed the bug in RadioGroupInputView.jsx
=> DM-9594:The default radio button (point) in scatter plot is not selected after line style changes

src/firefly/js/tables/TableUtil.js
https://jira.lsstcorp.org/browse/DM-9271
Please read ticket for reported bug and how to duplicate it.
=> DM-9271: fix unselected columns appearing in downloaded tables.

src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java, src/firefly/js/charts/dataTypes/HistogramCDT.js, src/firefly/js/charts/ui/HistogramOptions.jsx, src/firefly/js/ui/InputFieldView.jsx
DM-9342:
Add the bin width,min and max options
Please check the UI and let me if they look OK with you or need more changes.
=> DM-9342:histogram option input dialog

src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/HelpText.jsx
Based on the feedback input in IRSA-310, i've changed the upload panel in LC viewer.
I took also the chance to fix the overlapping `No file chosen` on the `Browse...` button in Firefox.
Please, check that the upload looks ok in different browser and devices sizes
=> IRSA-310 improve upload lc panel

src/firefly/js/templates/lightcurve/LcPeriod.jsx, src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
See ticket for detail of the changes. The 'Accept' form buttons moved to the period control panel. Instructions added and title in plots added.
=> IRSA-312: imprive period finder layout.

src/firefly/js/charts/ui/HistogramOptions.jsx, src/firefly/js/util/Validate.js
This implementation fixed the following issues:
1. User changes Bin width. Number of bins changes. 
2. User changes Min or Max. Number of bins changes. Bin width does not. 
3. Fixed bug in Validate to validate the integer at the given range.
=> IRSA-395:fix linkage between histogram params: Number of bins, bin width, min, max

src/firefly/js/ui/CatalogSearchMethodType.jsx
=> DM-10379: fixed: After a catalog search with a globe coverage map, the catalog search doesn't work anymore.

src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/LightCurveFileGroupsProcessor.java
Please check that when you upload a neowise table, images can be downloaded.
I have added a logic to check if frame_id is missing, to fall back and build the IBE url based on source id, or scan id and frame_num.
BTW, this file should really be called WISE file search processor. No time now but we probably need to clean this up, and maybe put this under IFE.
=> IRSA-418: fix download when frame_id is not present: newowise tables

src/firefly/js/drawingLayers/ComputeWebGridData.js, src/firefly/js/drawingLayers/WebGrid.js, src/firefly/js/util/Interp/LinearInterpolator.js, src/firefly/js/util/Interp/Regrid.js, src/firefly/js/visualize/draw/DrawUtil.js, src/firefly/js/visualize/draw/ShapeDataObj.js
1. Refactor codes to impove the performance.
2. Add LinearInterpolator.js
3. Add Regrid.js
4. Use Regrid to make more gride lines and more points in a line
5. Rotate the label direction according to the angle of the line
Label location is calcualted at the time when the line angle is calculated.
6. Re-orgainze and clean up the codes
7. add the jsdoc info
=>  DM-6501:Regrid needed  for WebGrid (coordinate grid overlay on image)

src/firefly/js/drawingLayers/ActiveTarget.js, src/firefly/js/visualize/draw/DrawUtil.js, src/firefly/js/visualize/draw/Drawer.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/PointDataObj.js
Changed the default  overlay color to red
=> IRSA-438:Make IRSA Viewer default overlay color be more visible

buildScript/gwt.gincl, buildScript/webpack.config.js, src/firefly/html/css/global.css, src/firefly/html/hydra.html, src/firefly/js/FFEntryPoint.js, src/firefly/js/Firefly.js, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/core/AppDataReducers.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/core/core-typedefs.jsdoc, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/js/templates/hydra/HydraManager.js, src/firefly/js/templates/hydra/HydraViewer.jsx, src/firefly/js/templates/hydra/SampleHydra.jsx, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/ui/DropDownContainer.css, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/ui/Menu.css, src/firefly/js/ui/SearchPanel.jsx, src/firefly/js/ui/TestSearchPanel.jsx, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/ui/TriViewImageSection.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-253
A placeholder app for the new migrated FinderChart.  This pull request includes a base implementation of the Hydra template.
To Test:
- check out 'IRSA-253_hydra_template' from both firefly and ife
- in ife, build finderchart, ie.  gradle :finderchart:buildAndDeploy
- on your browser, goto http://localhost:8080/applications/finderchart/
=> IRSA-253: create a hydra template as a starting point to migrate FinderChart

src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java, src/firefly/js/tables/tables-typedefs.jsdoc
https://caltech-ipac.atlassian.net/browse/IRSA-333
The null values in the input table appears as empty space in the phase folded table.  They should be made consistent.
To test:
- build irsaviewer from this branch (use 'dev' in ife.. no changes were needed)
- upload a file with 'null' values.. use sample file from ticket if you do not have one.
- go to period finder, select a period, then 'accept'.  phase folded table should contains 'null' values like ones in input table.
=> IRSA-333: Time Series Tool - inconsistent handling of nulls

src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/PlotViewUtil.js
To Test:
goto: http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
bring up one image, the bring up a second.  They should both show up.
=> IRSA-533: fixed bug.  The second image now shows up

src/firefly/js/visualize/saga/CoverageWatcher.js
https://caltech-ipac.atlassian.net/browse/IRSA-270
Gator result table sort breaks overlay clicking
See ticket for instructions on how to duplicate bug.
=> IRSA-270: Gator result table sort breaks overlay clicking

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java, src/firefly/js/templates/lightcurve/LcConverterFactory.js, src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js, src/firefly/js/templates/lightcurve/ptf/PTFPlotRequests.js
This is part 1 of the ticket, to setup PTF for IBE file retrieve which is also needed for PTF file package download (EJ is working on)
=> Irsa 514 add ptf image tsv

src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/BackgroundEnv.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTFileGroupProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTLightCurveQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java, src/firefly/java/edu/caltech/ipac/util/download/ResponseMessage.java, src/firefly/js/core/background/BackgroundUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.lsstcorp.org/browse/DM-11013
To test
localhost:8080/suit without being connected to VPN - check error messages
load invalid catalog or introduce errors in queries 
Loi, please check TablePanel and the behavior on backgrounded search failures
Cindy, please check SUIT
=> DM-11013 More meaningful errors

src/firefly/js/templates/lightcurve/ptf/PTFPlotRequests.js
RSA-667-Add-band-in-PTF-label: get fid from table and turn it into band name
=> RSA-667 Add band name in PTF image label

src/firefly/java/edu/caltech/ipac/firefly/server/query/IpacTablePartProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/FilterHanlder.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/IpacTableParser.java, src/firefly/java/edu/caltech/ipac/util/DataGroup.java
https://jira.lsstcorp.org/browse/DM-11424
To test:
- build firefly on this branch
- bring up a table, sort one of the columns
- select a few rows, then filter on the selected rows.
Something else to test is the 'show selected' button on http://localhost:8080/firefly/demo/ffapi-highlevel-test.html
- selecting a few rows then click the button
=> DM-11424: filter on selected row fails on sorted table.

src/firefly/html/demo/ffapi-slate-test2.html, src/firefly/js/api/ApiViewer.js, src/firefly/js/charts/TableStatsCntlr.js, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/core/MasterSaga.js, src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/templates/fireflyslate/FireflySlate.jsx, src/firefly/js/templates/fireflyslate/FireflySlateManager.js, src/firefly/js/visualize/DrawLayerCntlr.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/MultiViewCntlr.js
- demo file: ffapi-slate-test2.html
= added a REINIT_APP actions to force firefly to completly reinit
- added support for plot.ly direct plots
_to test:_
http://localhost:8080/firefly/demo/ffapi-slate-test.html
=> DM:11475: add second demo and support plot.ly general charts

src/firefly/html/demo/ffapi-highlevel-test.html, src/firefly/html/demo/ffapi-slate-test.html, src/firefly/html/demo/ffapi-slate-test2.html, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/CtxControl.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/LocalFileRetriever.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java, src/firefly/js/api/ApiViewer.js, src/firefly/js/core/ComponentCntlr.js, src/firefly/js/templates/fireflyslate/FireflySlateManager.js, src/firefly/js/visualize/ui/ColorPanelReducer.js
- http code that starts with "file://" now goes through LocalFileRetriever, better security this way.
- fixed layout issues with charts
- fixed issues with initial plot returning the wrong RangeValues
- reinit now hides all dialogs
_To Test:_
- all dialogs should go away on reinit
- there should not longer any layout issues with location of charts.  grid layout should work any any order of clicking (try ffapi-slate-test.html and ffapi-slate-test2.html)
- other issues are a little hard to test.
=> DM-11563: bug several small bugs

src/firefly/js/charts/ui/XYPlotPlotly.jsx
Fixed the axis range bug when restyle to grid
=> IRSA-688:IRSAViewer xyplot settings grid resets ymin

src/firefly/js/templates/lightcurve/LcPeriodogram.jsx, src/firefly/js/ui/TestQueriesPanel.jsx
Column removed.
Please check that this column is not available to be displayed in table and chart.
=> IRSA-690: remove frequency column for now

src/firefly/html/demo/ffapi-highlevel-charttest.html, src/firefly/html/demo/ffapi-slate-test2.html, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/charts/ui/options/HeatmapOptions.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx
https://jira.lsstcorp.org/browse/DM-11602
from tables::<tbl id>,<col expression>
to tables::<col expression>
with tbl_id added to top level data structure.
build branch then test with these 2 demo pages.
everything should work like it did before.  pay particular attention to chart options.
http://localhost:8080/firefly/demo/ffapi-highlevel-charttest.html
http://localhost:8080/firefly/demo/ffapi-slate-test2.html
=> DM-11602: change syntax for table column data identification

src/firefly/js/ui/FileUpload.jsx
This development fixes the URL input field editing problem, losing focus while entering the URL, from Upload tab.
test:
start firefly (localhost:8080/firefly)
select 'Upload'
select 'Upload from URL'
enter URL into the field 'Enter URL of a file'
=> DM-11609 fix File Upload out of focus issue while editing the url input field

src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcResult.jsx
Fixed the bugs for period finder
=> IRSA-464:LC phase folded table doesn't get updated after the LC table is filtered out the first time

src/firefly/html/firefly-dev.html, src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-data.json, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ExternalMasterDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterData.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterDataEntry.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ImageMasterDataSourceType.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/IrsaMasterDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/LsstMasterDataSource.java, src/firefly/js/FFEntryPoint.js, src/firefly/js/Firefly.js, src/firefly/js/charts/PlotlyConfig.js, src/firefly/js/data/ImageMasterData.js, src/firefly/js/data/ServerParams.js, src/firefly/js/rpc/PlotServicesJson.js, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/FieldGroupConnector.jsx, src/firefly/js/ui/NewImageSearchPanel.jsx, src/firefly/js/visualize/RequestType.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/ui/AllImageSearchConfig.js
- Server side: frame work for returning a json array from multiple master sources
- Client side: a concept search panel the uses image master data framework
and starts image searches
- image master data is a array of object to UI information and information
on how to retrieve the image
_to test:_
1. http://localhost:8080/firefly/firefly-dev.html
2. Choose "Image Concept" option
3. Choose multiple images and search
=> DM-12011: Implement framework for new image search panel

src/firefly/js/ui/ImageSelect.css, src/firefly/js/ui/ImageSelect.jsx, src/firefly/js/ui/NewImageSearchPanel.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-794
To test:
- http://localhost:8080/firefly/firefly-dev.html
- then Image Concept
Looking for feedbacks.
=> RSA-794: Panel 4: image set panel selection

src/firefly/js/visualize/ui/MouseReadout.jsx
Please test it using the attached fits file in IRSA-737.  The values should be displayed using the exponent expression instead.
=> IRSA-737:IRSA Viewer multi-extension pixel value bug

src/firefly/js/visualize/task/WcsMatchTask.js, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/MultiItemViewerView.jsx, src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
- toolbar is now correct with only one images
- for not images found- fixed exception and shows correct display
_note:_
you must checkout the same branch in ife to test.
=> IRSA-909-927: fixed 2 issues

src/firefly/js/ui/ImageSelect.jsx, src/firefly/js/ui/NewImageSearchPanel.jsx, src/firefly/js/ui/RadioGroupInputField.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-1008
Added MultiSelect property to ImageSelect panel.  This component now able to operate at single or multi select mode.
Changes in firefly only.
To Test:
http://localhost:8080/firefly/firefly-dev.html
- Image Concept
=> IRSA-1008: New image search needs a single selection mode

src/firefly/js/core/background/BackgroundUtil.js
https://caltech-ipac.atlassian.net/browse/IRSA-944
Also, fixed working mask not showing during download.
Additional changes in ife under same branch.
To test:
- build finderchart
- select 'no'  for 'search corresponding catalog'.
=> IRSA-944: FinderChart fail to recognize when search catalog is set to 'no'

src/firefly/js/templates/hydra/HydraViewer.jsx, src/firefly/js/templates/hydra/SampleHydra.jsx
- Also change the HydraViewer search key from `results` to `renderStandardView`
_note:_ must build ife with same branch
=> IRSA-1061: Fixed expanded view not showing

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imagesources/ExternalMasterDataSource.java, src/firefly/js/ui/ImageSelect.jsx
=> IRSA-1055:New image search: Waveband filter is missing some bands value

src/firefly/js/visualize/ui/FitsHeaderView.jsx, src/firefly/js/visualize/ui/HiPSPropertyView.jsx, src/firefly/js/visualize/ui/VisToolbar.jsx, src/firefly/js/visualize/ui/VisToolbarView.jsx
The development includes,
- update the state for VisToolBar in case HiPS image is rendered. 
- popup viewer to show HiPS image properties.
test: 
go to firefly-dev.html do HiPS search (Test Searches ->HiPs-> select a plot) 
click 'Show HiPS properties' button.
=> DM-12552 Update info toolbar button to show the properties info for HiPS image

src/firefly/js/templates/hydra/HydraManager.js
Set the image object to "undefined" for every new table search to make the smartMerge work in the LayoutCntlr.js
The ife branch has the same name.  Please check out both branches to test.  Thanks!
=> IRSA-1108:Finderchart displays "No data available" error message for the de-selected image sources

buildScript/depends.gincl, buildScript/gwt.gincl
https://caltech-ipac.atlassian.net/browse/IRSA-1126
also:
- fixed 'hidden' message mentioned in IRSA-1108's PR
- fixed warning message "title of type function" when loading finderchart
To Test:
- build finderchart in this branch, both ife and firefly
- click on help or '?' icon.  url should be /onlinehelp/finderchart/
=> IRSA-1126: FinderChart online help url is wrong

src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://caltech-ipac.atlassian.net/browse/IRSA-1220
- value set-able via app.options 'ImageSearch.archiveName'
- fix FinderChart layout issue in multi-position mode.
Build irsaviewer and finderchart in this branch.
Changes are in both ife and firefly.
=> IRSA-1220: Change 'Archive' to 'Search' in ImageSearchPanel

src/firefly/js/core/LayoutCntlr.js, src/firefly/js/templates/hydra/HydraManager.js, src/firefly/js/ui/SearchSummary.jsx, src/firefly/js/visualize/ui/SearchSummary.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
Please review this PR to be merged in RC asap. 
The idea is to put back the search summary text in Finderchart. One component has been added to FF, and used in IFE.
Build Finderchart and check the summary in different search that will come up as in OPS, red text between image toolbar and images grid.
=> IRSA-1163: add component for search summary

src/firefly/js/core/LayoutCntlr.js, src/firefly/js/templates/lightcurve/LcManager.js
There is nothing changed in IFE.  The change is minor and fixed the problem.
Please test it.  Thanks!
=> Irsa 623: Time series has wrong uploaded table column names

src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java, src/firefly/js/tables/TableUtil.js
https://caltech-ipac.atlassian.net/browse/IRSA-1293
- Move catalog search logic into the manager so that it get processed as an effect of a finderchart search.  This make the UI flow a bit smoother, and it is essential when we implement direct URL link to finderchart.
also:
- Prior to the change, while finderchart API is running, performance in interactive mode is severely affected.  This change should helped in that regard. 
- clean up old finderchart code.
=> IRSA-1293: do catalog search after the initial finderchart search returned

src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java, src/firefly/js/charts/dataTypes/XYColsCDT.js
This is fixing single trace chart errors, when trying to plot decimated expressions. 
(The issue is described in https://caltech-ipac.atlassian.net/browse/IRSA-1178)
=> IRSA-1178 FinderChart plotting with math and decimations fails

src/firefly/js/ui/TargetFeedback.jsx
Fixed the Finderchat example bugs.  No IFE changes.
=> IRSA-1284:Finder Chart example does not work

src/firefly/js/templates/lightcurve/LcViewer.jsx
Fix the source upload inconsistence.
The changes are only in Firefly.  There is no change in IFE.
=> IRSA-1238:TimeSeries tool: source upload option selected is not consistent

src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java, src/firefly/js/core/History.js, src/firefly/js/tables/TablesCntlr.js
https://caltech-ipac.atlassian.net/browse/IRSA-1290
Allow finderchart UI to be launched by a URL.  The method used to construct the URL is described in the ticket above.
Changes are in firefly as well as ife.
=> IRSA-1290: Finder Chart URL construction feature broken

src/firefly/js/visualize/iv/HiPSTileCache.js, src/firefly/js/visualize/iv/HiPSTileDrawer.js
For tiles the are not yet loaded, the drawing should show a higher level tile
for the area. In other words, there should be a blurry image until the
sharper image is loaded.
_To Test_:
Go to http://localhost:8080/firefly/firefly-dev.html
Test Searches -> HiPS
- Load the a HiPS and try zooming.  If the hi-resolution tile is not there you should see a lower resolution tile. 
- Scroll around, you should see a low resolution tile until the high resolution tile is loaded.
=> DM-13315: HiPS drawing cleanup

src/firefly/java/edu/caltech/ipac/firefly/resources/LSSTMetaInfo.json, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTCataLogSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTLightCurveQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMultiObjectSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java, src/firefly/js/tables/TableRequestUtil.js, src/firefly/js/visualize/ui/LSSTCatalogSelectViewPanel.jsx
https://jira.lsstcorp.org/browse/DM-13309
=> DM-13309 Update PDAC Portal for WISE single-epoch source data

src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/iv/HiPSRenderer.js, src/firefly/js/visualize/iv/HiPSTileCache.js, src/firefly/js/visualize/iv/HiPSTileDrawer.js, src/firefly/js/visualize/iv/ImageProcessor.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
_to test:_
- in chrome bring up the dev tools and choose network.
- bring up a HiPS image, zoom in to a level greater than 5, scroll around a lot.
- you should see chrome marking images can canceled (it will be in read)
=> DM-13400: cancel image tile download

docker/base/context.xml, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
https://jira.lsstcorp.org/browse/DM-13538
I've also committed a couple of files directly into `ife-env:master`.
http://irsawebdev5:8100/view/active/
login -> click on `play` icon left of `k8s_firefly`
Enter a branch or commit hash
Enter a version label.  This will be used as part of the URL to access this deployment in k8s.  Defaults to BRANCH input.
After build successfully completes, goto:  https://irsawebdev9.ipac.caltech.edu/<VERSION_INPUT_FROM_ABOVE>/firefly/
You can do the same for `k8s_irsaviewer`.  Replace `firefly` with `irsaviewer` in the URL above.
NOTE: Only context.xml was modified for this PR.  The other 2 is code refactoring.
=> DM-13538: Add a Jenkins job to build and deploy Firefly's app to a local k8s cluster

src/firefly/js/core/background/BackgroundMonitor.css, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js, src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js, src/firefly/js/ui/DownloadDialog.jsx
Changed the downloaded file name to meaningful name
Fixed the bug in DownloadDialog.jsx
Adjust the BackgroundMonitor.css's BGMon's size
Removed the reduanant codes in time series
Adjust the fields in the download dialog size
Add a labelWidth property in DownloadDialog.jsx
To test:
1.  Check out this branch and build firefly
2. There is no IFE changes, use ife in dev is fine and build irsaviewer
3. Run time series
=> IRSA-663:TimeSeries tool: Make it easier for users to find the right entry in the Background Monitor

docker/base/context.xml, src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/mapper/IpacTableExtractor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/BgIpacTableHandler.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/DataGroupWriter.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ipactable/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/util/DataGroup.java, src/firefly/java/edu/caltech/ipac/util/IpacTableUtil.java, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/tables/FilterInfo.js, src/firefly/js/tables/ui/FilterEditor.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/ui/InputField.jsx, src/firefly/js/ui/InputFieldView.jsx
these 2 are duplicate of #13420
https://jira.lsstcorp.org/browse/DM-13591
https://jira.lsstcorp.org/browse/DM-13591
also fixed:
https://jira.lsstcorp.org/browse/DM-13592
- tooltips missing for votable
https://jira.lsstcorp.org/browse/DM-13594
- in embedded mode, the `reset` button in table options submits enclosed form when clicked.
https://jira.lsstcorp.org/browse/DM-13595
- in embedded mode, input fields may trigger form submit if used within a `form` tag.
https://jira.lsstcorp.org/browse/DM-13597
- same as #13595
The changes are not big.  But, it's a bit hard to review.  
The error messages, you'll be able to see in any table.
For the embedded mode, I've deployed this version into k8s at:
https://irsawebdev9.ipac.caltech.edu/dm-13420/firefly/ 
I'll ask Jeff to use this instance in his …
=> Dm 13420 table error message

src/firefly/java/edu/caltech/ipac/firefly/server/db/DbCustomFunctions.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/dataTypes/FireflyGenericData.js, src/firefly/js/charts/dataTypes/FireflyHeatmap.js, src/firefly/js/charts/dataTypes/FireflyHistogram.js, src/firefly/js/charts/ui/ColSelectView.jsx, src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/util/expr/Expression.js, src/firefly/js/util/expr/Parser.js, src/firefly/js/util/expr/Scanner.js, src/firefly/js/util/expr/Variable.js
https://jira.lsstcorp.org/browse/DM-13038
This ticket takes care of the client-side validation for column expressions with columns that are not alphanumeric. Non-alphanumeric column names must be quoted. To test use a NED table, and try to plot a scatter, using column expressions.
https://irsawebdev9.ipac.caltech.edu/dm-13038/firefly
Database supports quoted column expressions, however heatmap and histogram processors do not at the moment. (DM-13036 will address server side.)
Also made a db function for lg (log10) instead of substituting log10 for lg.
=> DM-13038 Column expressions for column names that are not alphanumeric

src/firefly/html/firefly-dev.html, src/firefly/html/firefly.html, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/CDSHiPSListSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterListEntry.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/IrsaHiPSListSource.java, src/firefly/js/Firefly.js, src/firefly/js/data/ServerParams.js, src/firefly/js/ui/HiPSImageSelect.jsx, src/firefly/js/ui/HiPSSurveyListDisplay.jsx, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/visualize/HiPSListUtil.js, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
This development includes: 
- create methods for application to configure the creation of HiPS-selection list.
Two app option parameters are used for the configuration, 
- hips.hipsSources: defining the available HiPS sources, like 'cds,irsa', 'all'. if not specified, all available sources are assumed. 
- hips.defHipsSources: defining default HiPS sources selected from the available sources. The creation of HiPS-selection list is based on the selection. If not specified, the first item of the available sources is assumed. 
- For UI, a set of checkboxes is used to present the available HiPS sources and the selection. 
- update the columns of HiPS-selection list per proposal from https://jira.lsstcorp.org/browse/DM-13855
test:
localhost:8080/firefly
in firefly.html, the creation of …
=> DM-13172 Create method for application to configure the creation of HiPS list and update the columns in HiPS list

src/firefly/js/externalSource/FilePicker/react-keyed-file-browser/base-file.js, src/firefly/js/externalSource/FilePicker/react-keyed-file-browser/base-folder.js, src/firefly/js/externalSource/FilePicker/react-keyed-file-browser/browser.js, src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/ui/DownloadOptionsDialog.jsx, src/firefly/js/ui/UploadOptionsDialog.jsx, src/firefly/js/visualize/ui/WorkspaceViewPanel.jsx
I've fixed the setState problem where we used it and in the FilePicker.
Please, check the features where workspace is involved. This is broken currently in dev and this PR fixed all those problem related.
I'm building IRSAViewer with this fix will appear soon for testing in https://caltech-ipac.slack.com/messages/C9SDXRAHH
=> IRSA-1632 workspace upload option broken

src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/MouseReadoutCntlr.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/saga/MouseReadoutWatch.js, src/firefly/js/visualize/ui/MouseReadout.jsx, src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js, src/firefly/js/visualize/ui/PopupMouseReadoutFull.jsx, src/firefly/js/visualize/ui/PopupMouseReadoutMinimal.jsx, src/firefly/js/visualize/ui/VisHeader.jsx
- pixel now show angular size of the HiPS pixel for the displayed level
- options cleaned up to work better with HiPS
- some code refactoring to make `MouseReadoutUIUtil` for reused among readout code
- general cleanup of readout
_to test:_
- load an image and it should work as before.
-  load image and you should see the image pixel readout change with hips level
- under readout options: HiPS should not have image point as an option
=> IRSA-1605: Readout working with HiPS

src/firefly/js/drawingLayers/DistanceToolUI.jsx, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/HiPSSurveyListDisplay.jsx, src/firefly/js/ui/SizeInputField.jsx, src/firefly/js/visualize/ui/HiPSPropertyView.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
This PR is limiting the pre-filled polygon values for a catalog search to maximum 5 degrees or less depending on the FoV.
Maximum search value is a constant and can be changed easily.
Also changed the initial state for method search if hips to be set to cone search type.
Also fix labels reported here IRSA-1554, 1555, 1607.
For testing purposes, see here:
https://irsawebdev9.ipac.caltech.edu/irsa-1557/irsaviewer/
Please have a look. Thanks.
=> IRSA-1557: limit polygon search

src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/api/ApiViewer.js, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ChartsCntlr.js
Deployment: https://irsawebdev9.ipac.caltech.edu/dm-13972/irsaviewer
Ticket: https://jira.lsstcorp.org/browse/DM-13972
Updated addXYPlot, showXYPlot, showHistogram and remote equivalents to use multi-trace architecture.
=> DM-13972 High-level API updated to use multi-trace architecture

src/firefly/html/css/global.css, src/firefly/java/edu/caltech/ipac/visualize/net/AtlasImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java, src/firefly/js/drawingLayers/FootprintToolUI.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
This PR is allowing the user to display full size images. Please have a look and let me know if it doesn't break other image searches.
=> IRSA-1299: enable full size display

src/firefly/js/ui/HiPSSurveyListDisplay.jsx, src/firefly/js/ui/PopupPanel.jsx, src/firefly/js/visualize/HiPSListUtil.js
This development resolves:
- the stacking order among popup dialogs. 
- update the page size number on the 'edit table options' from Hips list table. 
- change the popup dialog from 'Change HiPS' click to be modal. 
test:
do HiPS search, 
click 'Change HiPS' button
click 'Edit table options' gear
=> DM-14002 fixed HiPS 'Change HiPS' UI display problem 

src/firefly/js/ui/PopupPanel.jsx, src/firefly/js/visualize/ui/DrawLayerPanel.jsx
https://jira.lsstcorp.org/browse/DM-13872
Deployment: https://irsawebdev9.ipac.caltech.edu/dm-13872/irsaviewer/
To test: using Images drop-down load a few images, open layers dialog, change active image, observe dialog title change.
=> DM-13872: Title of layer-selection dialog should change with change of image

src/firefly/java/edu/caltech/ipac/astro/net/Simbad4Client.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java, src/firefly/js/ui/TargetPanelWorker.js
Fixed the object name resolve bug
Please test: https://irsawebdev9.ipac.caltech.edu/irsa-1519/firefly/
There is no change in finderchart and irsaviewer.
=> IRSA-1519:name resolver

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/charts/dataTypes/FireflyGenericData.js, src/firefly/js/charts/ui/ChartPanel.jsx, src/firefly/js/charts/ui/MultiChartViewer.jsx, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/charts/ui/options/BasicOptions.jsx
https://jira.ipac.caltech.edu/browse/IRSA-1644
Items addressed: 8, 9, 13. 
Deployment: https://irsawebdev9.ipac.caltech.edu/irsa-1644/irsaviewer
By default multiple charts in the viewer should be deletable, selecting an area should make the chart active, autorange should not change on chart update unless necessary.
=> Chart bugs, mentioned in IRSA-1644

src/firefly/java/edu/caltech/ipac/firefly/data/FinderChartRequestUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/PlotServUtils.java
This PR fixes the labels that appear in the title of the images when downloading or generating FC documents HTML/PDF.
It also fix the observation date for AKARI. SEIP doesn't have a standard date to extract from so is left out of this PR.
Build FC from ife branch name are the same in ife and firefly.
Check that images band are labelled correctly. See tickets for description of the issue.
=> IRSA-1587 and IRSA-1207: FC labels PDF/HTML fixed

src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-943
A simple change.  Set a fixed width on Search Panel.  Shrink/expand stops.
=> IRSA-943: IRSAViewer Catalog Search active region shrinks/expands with different tabs

src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java, src/firefly/js/tables/FilterInfo.js
https://jira.lsstcorp.org/browse/DM-13037
See ticket for details on how to reproduce.
This can be tested with this demo page as well.
http://localhost:8080/firefly/demo/ffapi-sed.html
=> DM-13037: Second filter fails on column names with spaces (NED)

src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/HistogramProcessor.java, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/charts/dataTypes/FireflyGenericData.js, src/firefly/js/charts/dataTypes/FireflyHeatmap.js, src/firefly/js/charts/dataTypes/FireflyHistogram.js, src/firefly/js/charts/ui/HistogramOptions.jsx, src/firefly/js/tables/Decimate.js, src/firefly/js/util/MathUtil.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js
https://jira.lsstcorp.org/browse/DM-8180
Test link: https://irsawebdev9.ipac.caltech.edu/dm-8180/irsaviewer/
This PR addresses the following issues:
- Flexible histogram tooltip precision based on the bin width. You should not see bin ranges like "0.000000 to 0.000000" when the boundaries are small numbers.
- Histogram and heatmap now handles quoted column names and expressions. (Can be tested with NED - was failing before.) 
- Histogram options will show range for quoted and unquoted columns.
- Expressions for all charts are now handled by database. (There will be a separate ticket for cleanup.)
=> DM-8180 Histogram issues

src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerCommands.java, src/firefly/js/ui/DownloadOptionsDialog.jsx, src/firefly/js/ui/WorkspaceViewer.jsx, src/firefly/js/visualize/WorkspaceCntlr.js
There is the branch in ife with the same branch name. 
In this pull request, the above two tickets were implemented:
- Add workspace option to download dialog for packaging images
- Improve Finder Chart workspace access error message
=> IRSA-1598 and IRSA-1015

src/firefly/js/templates/lightcurve/SettingBox.jsx
Fixed the bug that made time series fail
Please test it based on the instruction in IRSA-1744.
There is no IFE changes.
=> IRSA-1744:Time Series: failed when uploading a LC with different mission case

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ui/HistogramPlotly.jsx
Display hover text information in the empty bins in the histogram.
=> IRSA-364:tooltip should show parameters for empty bins

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/charts/dataTypes/FireflyGenericData.js, src/firefly/js/charts/ui/PlotlyChartArea.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/templates/lightcurve/LcConverterFactory.js, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcPhaseTable.js, src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js, src/firefly/js/util/expr/Expr.js, src/firefly/js/util/expr/Parser.js
https://jira.lsstcorp.org/browse/DM-7950
Use upper/lower limit symbol to show upper limits in raw and phase folded tables when value column is w[1,2,3,4]mpro_ep.
Test table is attached to the ticket.
=> DM-7950 Display WISE upper limits in time series viewer

src/firefly/js/visualize/iv/PlotTitle.jsx, src/firefly/js/visualize/reducer/HandlePlotCreation.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
DM-14695: fixed losing mask when replacing plot
- internally we create new PlotView with all parameter reset
- also fixed FOV showing up when no projection
=> DM-14695: fixed losing mask when replacing plot

src/firefly/js/visualize/CsysConverter.js, src/firefly/js/visualize/region/RegionDescription.js, src/firefly/js/visualize/region/RegionFactory.js, src/firefly/js/visualize/saga/MouseReadoutWatch.js, src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
DM-14694: Changed readout so that it will show the FITS standard Image point
- image pixel show as FITS standard
- includes option to show the lsst image point
- make convert image pixel between fits convention and internal image style while reading in and write out the region description with image coordinates.
=> DM-14694: Changed readout so that it will show the FITS standard Image point

docs/fits-plotting-parameters.md, src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/api/ApiViewer.js, src/firefly/js/charts/ChartDataType.js, src/firefly/js/charts/ChartType.js, src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/charts/dataTypes/HistogramCDT.js, src/firefly/js/data/ImageMasterData.js, src/firefly/js/visualize/CoordSys.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/RequestType.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/ZoomType.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/saga/CoverageWatcher.js
The development
- update markdown file on plotting parameters on 'SurveyKey' and 'SurveyKeyBand'
- update jsdoc mainly by @typedef an object related to plotting parameters defined in WebPlotRequest. 
test:
compile firefly and create jsdoc (gradle :firefly:bAA)
Browse the pages built on on jsdoc from firefly/build/firefly/war/docs/js/
Some issue occurs all over the created pages jsdoc:
open page on global.html, the description line of some members or methods is shown repeatedly.
=> DM-11816: Firefly API document update 

src/firefly/html/slate.html, src/firefly/java/edu/caltech/ipac/visualize/plot/ImageHeader.java, src/firefly/js/Firefly.js, src/firefly/js/visualize/CsysConverter.js, src/firefly/js/visualize/Point.js, src/firefly/js/visualize/saga/MouseReadoutWatch.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
_to test:_
bring the api with slate.html or just load http://localhost:8080/firefly/slate.html.
`O based image point` should be the default.  XY0 support should work.
=> DM-14759: support XY0, default it for slate.html

src/firefly/java/edu/caltech/ipac/visualize/plot/FitsRead.java
Ticket: https://jira.lsstcorp.org/browse/DM-14780
Data values in lower and upper range are not mapped correctly for power law and asinh stretch
To test: use https://irsawebdev9.ipac.caltech.edu/dm-14780/firefly/
- bring an image, 
- open Color Stretch dialog, 
- modify Upper and Lower range
- refresh
- test with Power Law Gamma and Asinh stretch types
=> DM-14780: power law and asinh stretch bug

config/app.config, src/firefly/config/app.prop, src/firefly/html/demo/ffapi-table-test.html, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java, src/firefly/java/edu/caltech/ipac/util/FileUtil.java, src/firefly/js/api/ApiBuild.js, src/firefly/js/api/ApiUtilTable.jsx, src/firefly/js/tables/TableRequestUtil.js, src/firefly/js/ui/DropDownContainer.css, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/FieldGroupConnector.jsx, src/firefly/js/ui/WorkspaceViewer.jsx, src/firefly/js/visualize/WorkspaceCntlr.js, src/firefly/js/visualize/ui/WorkspaceViewPanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-1016
Use table test page to test this feature.  Make sure to use your fully qualify host name in the url.
Log into irsa.ipac.caltech.edu first.
http://facade.ipac.caltech.edu:8080/firefly/demo/ffapi-table-test.html
You'll need to build locally with `ignore.auth=false`.  
You can do this by adding `-Pignore.auth=false` to the gradle command line.
Or, by inserting that line into your `~/.gradle/build.config` file to use that option on every build.
=> IRSA-1016: exposes workspace components to JS API

src/firefly/html/css/global.css, src/firefly/js/ui/DropDownMenu.css, src/firefly/js/ui/DropDownMenu.jsx, src/firefly/js/ui/ToolbarButton.css, src/firefly/js/visualize/draw/FootprintFactory.js, src/firefly/js/visualize/ui/MarkerDropDownView.jsx
https://irsawebdev9.ipac.caltech.edu/dm-6592/firefly/
https://jira.lsstcorp.org/browse/DM-14515
K8s: https://irsawebdev9.ipac.caltech.edu/dm-6592/firefly/
Added submenu capability to drop down menu.  Submenu can be nested to multiple levels.
Also, implemented ticket DM-14515 to place project footprints into submenu.
You can test this by loading any image, then select `Overlay Markers` to see drop down with submenu.
=> DM-6592: Enable subMenu in the menu list

src/firefly/js/templates/lightcurve/LcManager.js
Please test this branch and let me know if any issues.  Thanks!
URL: https://irsawebdev9.ipac.caltech.edu/irsa-673/irsaviewer/
=> IRSA-673: Time Series Tool table/image link breaks after sorting/filtering table

src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
https://jira.lsstcorp.org/browse/DM-15179
Do not send these 2 columns when it's not requested. 
It should still send them when all(*) is requested.
Use debugger to validate that the table sent back contains only the columns requested.
=> DM-15179: Table: Do not send ROW_IDX and ROW_NUM columns when not requested

src/firefly/js/util/Validate.js
Kindly review my changes.
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-2051
Goto: https://irsawebdev9.ipac.caltech.edu/irsa-2051/applications/sofia/
Note: This ticket includes work on IFE also.
=> Irsa 2051 an observation data field should be added

src/firefly/html/firefly.html, src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/visualize/HiPSMocUtil.js, src/firefly/js/visualize/draw/MocObj.js, src/firefly/js/visualize/draw/ShapeDataObj.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
This development mainly provides the method to load MOCs with the upload panel: 
- the MOCs from other sources can be uploaded by file or from URL. 
- the uploaded MOCs can be overlaid on top the image. 
2MASS HiPS ((https://irsa.ipac.caltech.edu/data/hips/CDS/2MASS/Color) ) is set as the default image in case there is no image shown at the viewer.
test: 
start firefly upload panel
the following MOC fits samples and the relevant URLs are provided for test, 
- firefly_test_data/FileUpload-samples/fits/moc/galex.fits,
https://irsa.ipac.caltech.edu/data/hips/CDS/GALEX/GR6-03-2014/AIS-ND/Moc.fits
- firefly_test_data/FileUpload-samples/fits/moc/hershel.fits
https://irsa.ipac.caltech.edu/data/hips/ESAC/PACS-color/Moc.fits
- firefly_test_data/FileUpload-samples/fits/moc/nicmos.fits …
=> DM-14438 Overlay loaded MOCs on the image by using upload panel

src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/fieldGroup/FieldGroupUtils.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/ui/RadioGroupInputField.jsx
https://jira.lsstcorp.org/browse/DM-15693
- Fixed the bug preventing the full update of radio group input field options via reducer function
- Updated ExampleDialog to show how field state can be modified on an action.
To test
https://irsawebdev9.ipac.caltech.edu/dm-15693/firefly/firefly-dev.html,
Change the options in Master Radio Group, observe the changes in Dependent Radio Group.
=> DM-15693: bug applying field reducer function

src/firefly/java/edu/caltech/ipac/firefly/server/WebDAVWorkspaceManager.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorDD.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncJob.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncSearchProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessorWrapper.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/IbeTemplateProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/TableFunctionProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/multipart/MultiPartPostBuilder.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java, src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java, src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java
https://jira.lsstcorp.org/browse/DM-15791
- create a rough implementation of AsyncTapQuery
- refactor EmbeddedDbProcessor
- refactor HttpServices
Please review code.  There's no UI changes.  Pay closer attention to new `AsyncSearchProcessor`, `AsyncJob`, and the roughly implemented `AsyncTapQuery`
Added a simple test:  AsyncTapQueryTest.java
` gradle :fi:test --tests *AsyncTapQueryTest`
Note:  `testError` is ignored.  async TAP error returns a voTable with only INFO tags.  We are unable to parse the returned table.  Not sure if starlink is capable of parsing it.  Also, I think IRSA is returning a 'bad' error doc.  If so, either they fix it, or we'll need to have special cases for it.
Small changes to irsa-ife:  https://github.com/IPAC-SW/irsa-ife/pull/8
=> DM-15791: Creates framework for an async SearchProcessor

src/firefly/js/drawingLayers/ComputeWebGridData.js, src/firefly/js/drawingLayers/WebGrid.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/ui/VisToolbarView.jsx
1.  Please check it out and build firefly. 
2.  Run: http://localhost:8080/firefly/firefly-dev.html
3.  Load a HIPS image from "Test Search" tab
4.  Then click grid icon to add or remove grid lines. 
5.  Then click zoom in/out/fit or change coordinate etc.
=> IRSA-1391:HiPS: make the grid to support hips images

src/firefly/html/demo/ffapi-coverage-test.html, src/firefly/js/api/ApiBuild.js, src/firefly/js/api/ApiUtil.js, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/iv/ImageExpandedMode.jsx, src/firefly/js/visualize/ui/ApiFullDisplay.jsx, src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx, src/firefly/js/visualize/ui/VisHeader.jsx
Changes to support the jupiter lab extension.
see https://github.com/Caltech-IPAC/jupyter_firefly_extensions
=> DM-14218 jupyterlab

src/firefly/html/css/global.css, src/firefly/java/edu/caltech/ipac/firefly/core/background/BackgroundStatus.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java, src/firefly/java/edu/caltech/ipac/firefly/server/cache/EhcacheProvider.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/CacheEventWorker.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/FluxAction.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventQueue.java, src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/table/DataGroup.java, src/firefly/java/edu/caltech/ipac/table/DataType.java, src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java, src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/table/TableDef.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/java/edu/caltech/ipac/table/io/BgIpacTableHandler.java, src/firefly/js/Firefly.js, src/firefly/js/core/messaging/WebSocketClient.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/DialogRootContainer.jsx, src/firefly/js/ui/SimpleComponent.jsx
The option is available when the number of unique values is less than 15.
This feature is only available for columns with string, char, int, long, or boolean data type.
ticket : https://jira.ipac.caltech.edu/browse/IRSA-1940
test deploy: https://irsawebdev9.ipac.caltech.edu/irsa-1940/firefly/
Also in this PR:
- fixed https://jira.lsstcorp.org/browse/DM-15765
- fixed https://jira.ipac.caltech.edu/browse/IRSA-2151
- added support for a 'drop-down' UI
- fixed `FmtDisp`
- ensure onFireflyLoad is not called more than once
To Test, load catalog smaller catalog so there's more chance of columns with a choice UI.
=> Add table column filter using a multiple choice UI

src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java, src/firefly/java/edu/caltech/ipac/table/DataType.java, src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
https://jira.lsstcorp.org/browse/DM-16135
Please test using VOTable with array types.
=> DM-16135: Add long_string type into DataType

src/firefly/java/edu/caltech/ipac/visualize/plot/RangeValues.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretch.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretchUtil.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/RGBIntensity.java, src/firefly/js/visualize/RangeValues.js, src/firefly/js/visualize/ui/ColorBandPanel.jsx, src/firefly/js/visualize/ui/ColorDialog.jsx, src/firefly/js/visualize/ui/ColorPanelReducer.js, src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
https://jira.lsstcorp.org/browse/DM-15725
Test deployment: https://irsawebdev9.ipac.caltech.edu/dm-15725/firefly/
- Added help text and help anchor to hue-preserving 3-color stretch dialog
- Added scaling coefficients for each band (a log slider ranging from 0.1 to 10)
=> DM-15725: hue-preserving dialog changes

src/firefly/js/drawingLayers/ComputeWebGridData.js
Using the centerWpt's lontitude to draw the labels for all latitude lines
For longitude lines, use different algorithm to calculate the angle and the label postion
=> IRSA-2121-At certain fov angle, some labels are mission in HiPs grid

src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
https://jira.ipac.caltech.edu/browse/IRSA-2238
Test deploy: https://irsawebdev9.ipac.caltech.edu/irsa-2238/applications/sofia/
Changes also in https://github.com/IPAC-SW/irsa-ife/pull/26
- possible unsupported cookie format
- switch to using new HttpClient on each request
See ticket for test file.  Although, I think the file produce no results.
=> IRSA-2238: SOFIA multi-position search is broken

src/firefly/js/ui/CatalogSearchMethodType.jsx
Add workspace option for multi-object search
Test URL:https://irsawebdev9.ipac.caltech.edu/irsa-1255/irsaviewer/
=> IRSA-1255: Workspace option is missing when uploading multi-object file for catalog search

config/app.config, src/firefly/build.gradle, src/firefly/js/ui/DropDownContainer.jsx
- only include revision if it's not '0'.
Test deploy: https://irsawebdev9.ipac.caltech.edu/irsa-2269/firefly/
See bottom-right corner for version info.
=> IRSA-2269: Update Firefly's version to 2018.2

src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/Wavelength.java, src/firefly/js/visualize/projection/ProjectionInfo.js
Another approach to fix IRSA-2291 issues
=> IRSA-2291: Another approach to fixed IRSA-2291 issues

src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java, src/firefly/js/charts/ChartUtil.js, src/firefly/js/tables/TableInfoUtil.js, src/firefly/js/templates/lightcurve/wise/WisePlotRequests.js, src/firefly/js/ui/TestTapSearchPanel.jsx, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
This development provides functions to get table center columns by checking 
- table meta ('CatalogCoordColumns' or 'CENTER_COLUMN')
- UCD and ( 'pos.eq.ra;meta.main'/'pos.eq.dec;meta.main'  or  'pos.eq.ra'/'pos.eq.dec') 
- ObsCore columns (check the existence of mandatory columns)  or
- guessing
test: 
case for checking table meta: 
do catalog search
case for checking UCD, 
run firefly/firefly-dev.html
select tab 'TAP searches'  && TAP service URL for IRSA
case for checking ObsCore & guessing, 
firefly/firefly-dev.html
select tab 'TAP searches' && TAP service URL for CASDA
=> DM-16475 Recognize ObsCore, some UCDs for doing catalog overlay

src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/table/DataType.java, src/firefly/java/edu/caltech/ipac/table/IpacTableDef.java, src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java, src/firefly/java/edu/caltech/ipac/table/TableUtil.java, src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java, src/firefly/test/edu/caltech/ipac/astro/IpacTableReaderTest.java
https://jira.lsstcorp.org/browse/DM-15274
k8s: https://irsawebdev9.ipac.caltech.edu/dm-15274/firefly/
To test, follow the instructions in the ticket.
This PR did not address all of the problems.  It at least picks up the correct data.
It did not preserve the exact precision.  
This is because we have a default precision when one is not given.
There are other tickets that will address this issue.
=> DM-15274: file upload bug: the precision of numbers changed

src/firefly/html/demo/ffapi-table-test.html, src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/mapper/IpacTableExtractor.java, src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java, src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/java/edu/caltech/ipac/table/io/BgIpacTableHandler.java, src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java, src/firefly/java/edu/caltech/ipac/table/query/FilterHanlder.java, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/TableTest.java
https://jira.ipac.caltech.edu/browse/IRSA-128
k8s: https://irsawebdev9.ipac.caltech.edu/irsa-128/firefly/
- ensure all column's meta is consistently supported both server and client
- add documentation to reflect the changes
- added unit test to ensure column's meta is preserved throughout the SearchProcessor's cycle
- minor code refactoring 
unit test: `gradle -Dtest.single=TableTest :fi:test -x jsTest`
Live Test: https://irsawebdev9.ipac.caltech.edu/irsa-128/firefly/demo/ffapi-table-test.html
=> IRSA-128: g format issue in Firefly tool

config/app.config, src/firefly/config/app.prop, src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java, src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTImageSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTQuery.java, src/firefly/test/edu/caltech/ipac/firefly/server/query/LSSTDbServTest.java, src/firefly/test/edu/caltech/ipac/firefly/server/query/LSSTImgServTest.java
https://jira.lsstcorp.org/browse/DM-17072
Allow url properties to be relative to host url.
@loitly, I've added resolveUrl method to ServerContext.java Please feel free to change anything you find questionable.
Also, I found that dbserv now fails on 3 of our queries, commented them out for now.
=> DM-17072 re-establish the legacy PDAC portal

src/firefly/js/api/ApiViewer.js
https://jira.ipac.caltech.edu/browse/IRSA-2525
This is fixed.  Code reverted back to when it was working.  
Unfortunately, there's no easy way to test it while it's in a PR.
You can go here: https://irsadev.ipac.caltech.edu:9201/
Assuming my local dev instance(laptop) is running.  Or, you'll have to test it after it's merged into dev.
=> IRSA-2525: Launching time series tool appear to be broken in dev

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/charts/ui/options/HeatmapOptions.jsx
Bug report: https://jira.lsstcorp.org/browse/DM-17265
Test build: https://irsawebdev9.ipac.caltech.edu/dm-17265_heatmapbug/firefly/
Fixed "Default" color scale bug in heatmap charts. 
Default color scale is chosen from color scale list based on trace number.
=> DM-17265 Bug with Default color scale in heatmap chart

src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Display the NaN value instead of blank.
URL to test this PR is here https://irsawebdev9.ipac.caltech.edu/irsa-945/irsaviewer/
=> IRSA-945:IRSAViewer panner shows blank flux for pixels with NaN values

config/ehcache.xml, src/firefly/java/edu/caltech/ipac/firefly/server/cache/resources/ehcache.xml, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/projection/ProjectionInfo.js, src/firefly/js/visualize/reducer/PlotTitle.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
Read in a cube with a large of images. 
Also- this includes some cleanup.
_To test:_
https://irsawebdev9.ipac.caltech.edu/irsa-2623-big-cube/firefly/
Test data is in the `firefly_test_data` repository.
Read in:
`firefly_test_data/multi-ext-fits/sofia-10_ext-10130_images.fits`
_tech note:_
The fix is only in the two `ehcache.xml` files. Everything else is cleanup or small refactoring.
=> IRSA-2623: fixed reading very large cube count, plus some code cleanup

config/ehcache.xml, src/firefly/java/edu/caltech/ipac/firefly/server/cache/resources/ehcache.xml
patch to rc to fix file with over 1000 images bugb
=> IRSA-2623: patch: simple big cube with many extension fix

src/firefly/js/tables/FilterInfo.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReducer.js, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/DialogRootContainer.jsx, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx, src/firefly/js/ui/tap/TableColumnsConstraints.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.lsstcorp.org/browse/DM-17217
Test build:
https://irsawebdev9.ipac.caltech.edu/dm-17217_colConstraints/firefly/firefly-dev.html?__action=layout.showDropDown&visible=true&view=TestTAPSearch
1. Implemented support for preserving selections in client tables.
2. Enabled sorting and filtering of the constraints table itself.
3. Sorting and filtering does not change checkbox states.
4. Principal columns are pre-selected.
5. No switch between All/Principal, removed by Gregory Dubois-Felsmann request.
6. Removed additional constraints. (They can be added in ADQL tab.)
7. Added "Remove column filters" button (since there is no table header).
Bug fixes:
1. Now supporting table ids with . character. (UI state was not stored correctly for such tables.)
2. Enum filter was not shown (hidden …
=> DM-17217 Improve the constraints table for TAP search

src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
DM-18102: fixed 2 regression bugs
- firefly not guessing ra/dec in tables like before
- columns like coord_ra, coord_dec not recognized
- regular expression change
- fix regression undeclared variable bug
=> DM-18102: fixed 2 regression bugs

src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx, src/firefly/js/ui/tap/TableColumnsConstraints.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.css, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapUtil.js
https://jira.lsstcorp.org/browse/DM-18123
Test build: https://irsawebdev9.ipac.caltech.edu/dm-18123/firefly/firefly-dev.html
Change layout according to attached mock-up.
- TAP search panel is now resizable
- Bottom section is expand/shrink when resizing
- Column constraint toolbar is separated and placed on top for better symmetry
- Message added to Advanced ADQL panel to warn user of lost query when switching back to Basic
- Added loading mask to Select Constraints when waiting for data to be loaded
TODOs:
- All labels should be reviewed.
- Submit change request as needed.
Known Issues:
- Left panel of Constraints (spatial/temporal section)
- Has awkward alignment when expanded
- Horizontal scrolling will not appear when shrink
- Minor, collapsible icon and label not aligned
- Service …
=> DM-18123: Change layout of TAP search panel to reflect the new top-down flow

src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.ipac.caltech.edu/browse/IRSA-2553
Fixed `Cancel` button not working.
At the moment, you can test with this url: https://irsadev.ipac.caltech.edu:9201/
Also, noticed that it's a multi-select.  Shouldn't it be single select?
=> IRSA-2553: fixed Add Image Dialog Cancel Button Broken in Gator

config/test/app-test.prop, src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java, src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java, src/firefly/js/data/ServerParams.js, src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/ui/NaifidPanel.jsx, src/firefly/js/ui/NaifidPanelWorker.js, src/firefly/js/ui/SuggestBoxInputField.jsx, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/test/edu/caltech/ipac/firefly/server/rpc/ResolveNaifidNameTest.java
Kindly review:
This ticket is about adding a Naifid Panel to firefly.
Jira: https://jira.ipac.caltech.edu/browse/IRSA-2146
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-2146/firefly/
Note: For testing, please: 
- Go to (https://irsawebdev9.ipac.caltech.edu/irsa-2146/firefly//firefly-dev.html)
- Click on 'Test Searches' button (on the top menu), then click on the 'NAIF-ID' tab (the last tab). 
- Or, click on 'Examples Js Dialog' button.
=> Irsa 2146 add naifid resolver to firefly

src/firefly/js/ui/panel/CollapsiblePanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-1150
Change collapsible panel style to correctly open/close the content.
https://irsawebdev9.ipac.caltech.edu/irsa-1150/applications/finderchart/
=> IRSA-1150: fix collapsible panel extends too far into the search button in Firefox

src/firefly/js/charts/ui/ColSelectView.jsx, src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/tables/TableRequestUtil.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx, src/firefly/js/ui/tap/Select.jsx, src/firefly/js/ui/tap/TableColumnsConstraints.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapUtil.js
https://jira.lsstcorp.org/browse/DM-18121
Test build: https://irsawebdev9.ipac.caltech.edu/dm-18121_colsel/firefly/firefly-dev.html?__action=layout.showDropDown&visible=true&view=TestTAPSearch
- Positional and temporal columns fields now behave similarly to column selection fields in charts
- Made the search for suggestions case-insensitive. (The field value is case-sensitive though, and must match column name exactly to pass validation.)
- Column constraints and selections are now independent of what is visible in column constraints table
- Cleaned column constrains selection, no field is necessary.
- TAP search requests are not cached (per Xiquin's request). New search will produce new asynchronous request.
- Added error reporting, but did not fix filter validation partially working - …
=> DM-18121 TAP search: column field selection, column constraints as a view

src/firefly/js/ui/UploadOptionsDialog.jsx
Kindly review:
Adding the ability to pass style as a prop to uploadOptionsDialog.jsx.
The style was hard-coded before.
ife PR: https://github.com/IPAC-SW/irsa-ife/pull/53
=> IRSA-2657: passing style as a prop in uploadOptionDialog.jsx

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisContext.java, src/firefly/js/visualize/draw/FootprintFactory.js, src/firefly/js/visualize/ui/MarkerDropDownView.jsx, src/firefly_data/footprint/Footprint_SOFIA.reg
Add sofia in the menu and then add submenu for forcast
Add region files
Add sever side codes to process region file and then create Footprints
URL: https://irsawebdev9.ipac.caltech.edu/irsa-2032/applications/sofia/
=> IRSA-2032:SOFIA: Add footprint to viewer

src/firefly/html/css/global.css, src/firefly/html/firefly-dev.html, src/firefly/js/Firefly.js, src/firefly/js/charts/ui/ColSelectView.jsx, src/firefly/js/ui/DateTimePickerField.jsx, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/Select.jsx, src/firefly/js/ui/tap/TableColumnsConstraints.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/util/VOAnalyzer.js
https://jira.lsstcorp.org/browse/DM-16667
A parallel PR is created for SUIT: https://github.com/lsst/suit/pull/13
Please, check it for steps to test.
- Added "LSST TAP" and "Upload" buttons.
- Made the list of TAP services a property.
- Added UCD to the popup with column selections for Spatial and Temporal column fields.
- Removed "schema_name" and "table_name" from columns constraints table, reordered columns into more logical sequence.
- Use ISO time constraint format if time column is not numeric. Even though ISO format is guaranteed to be converted to the native format only for timestamp fields (xtype="timestamp"), it is still more useful than MJD, which would break the query for char time fields.
Bug fixes:
- Schema and table descriptions in select boxes a little bit cut on the …
=> DM-16667 Use TAP provided by DAX team when available

src/firefly/js/charts/ui/MultiChartViewer.jsx, src/firefly/js/ui/FieldGroup.jsx
Firefly-46: fixed field group bug when component mount and unmount
- also applied bug fix in MultiChartViewer that tatiana fixed
This fixes issues found in https://jira.ipac.caltech.edu/browse/FIREFLY-46
https://irsawebdev9.ipac.caltech.edu/firefly-46-field-group-bug/firefly/
=> Firefly-46: fixed field group bug when component mount and unmount

src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/LightCurveHandler.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/LightCurveProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PeriodogramAPIRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PhaseFoldedCurveProcessor.java, src/firefly/js/templates/lightcurve/LcPeriodogram.jsx, src/firefly/test/edu/caltech/ipac/firefly/server/query/LightCurveProcessorTest.java
- Add codes in both js/java to save the filtered table 
- Removed Depercated class IRSA-2099 in IrsaLightCurveHandler.java
To test:
URL: https://irsawebdev9.ipac.caltech.edu/irsa-2099-ts/irsaviewer/ts.html
Here is my irsa build running in my port:
https://irsadev.ipac.caltech.edu:9231/frontpage/
=>  IRSA-2099 save the filtered light-curve table

src/firefly/js/ui/PagingBar.jsx
Making the size of "current page box" dynamic.
Jira: https://jira.ipac.caltech.edu/browse/IRSA-2626
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-2626/applications/sofia/
Testing: 
- Run SOFIA and do an "All-Sky" search, with all levels (1,2,3,4) added. Then click search.
- Select 'Forcast' instrument.
- Navigate back and forth from the first to the last page.
=> IRSA-2626: dynamically computing the size of page number box

src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/drawingLayers/CatalogUI.jsx, src/firefly/js/ui/PopupPanel.css, src/firefly/js/ui/PopupUtil.jsx, src/firefly/js/util/Color.js, src/firefly/js/util/ObsCoreSRegionParser.js, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/draw/CanvasWrapper.jsx, src/firefly/js/visualize/draw/DrawLayer.js, src/firefly/js/visualize/draw/DrawOp.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/MocObj.js, src/firefly/js/visualize/draw/ShapeDataObj.js, src/firefly/js/visualize/reducer/DrawLayerReducer.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/TriViewImageSection.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-42 (this PR is for FIREFLY-42, not 37)
https://jira.lsstcorp.org/browse/DM-18510
this PR includes development on
* create two drawing layers for the table has columns compliant to ObsCore table with s_region column:
* observation center layer contain point objects for s_ra & s_dec column, like normal catalog layer
* observation region layer contain region objects for s_region column
* the layer dialog shows column info for both observation center and region layers.
* the layer dialog shows buttons on 'all' regions, 'selected' regions and 'highlighted' region for the 
observation region layer
* the layer dialog shows an error icon if any of the region for ‘all’, ’selected’ or ‘highlighted’ selection has invalid or unsupported values in the …
=> Firefly 37 recognizing s_region in a table colum

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterListEntry.java
Very simple PR where i follow the request from CCB to update the column tooltip , name and order of the HiPS choice table. Please, confirm that this is correct.
Test can be done here: https://irsawebdev9.ipac.caltech.edu/irsa-2419/firefly/
=> IRSA-2419: hips table choice column name, mouseover and order updated

src/firefly/js/drawingLayers/WebGrid.js, src/firefly/js/visualize/task/PlotHipsTask.js
Fixed HiPs and image match issue
Test URL: https://irsawebdev9.ipac.caltech.edu/irsa-1637/firefly/
=> IRSA-1673:HiPS WCS grid disappears if "Match Image to HiPS" and EQ J2000-->Galactic

src/firefly/js/visualize/iv/HiPSRenderer.js, src/firefly/js/visualize/iv/HiPSTileCache.js, src/firefly/js/visualize/iv/TileDrawHelper.jsx
fixed artifact described in: https://jira.ipac.caltech.edu/browse/IRSA-2128
- note you might see the artifact as you move but when drawing completes it will clear.
https://irsawebdev9.ipac.caltech.edu/irsa-1673-artifact/firefly/
=> IRSA-2128: fixed artifact found in IRSA-2128

src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/js/visualize/projection/Projection.js
Please using the testing data attached in the jira ticket: Firefly-68 to test this pull request.
URL: https://irsawebdev9.ipac.caltech.edu/firefly-68/firefly/
=> Firefly-68:Firefly can't display SOFIA FITS cube (4-d)

src/firefly/js/ui/NaifidPanel.jsx
Adding examples to NAIFID component, along with other enhancements.
Jira: https://jira.ipac.caltech.edu/browse/IRSA-2685
k8s: https://irsawebdev9.ipac.caltech.edu/irsa-2685/applications/sofia/
IFE-PR: https://github.com/IPAC-SW/irsa-ife/pull/64
=> IRSA-2685_sofia_add_example_element_to_naifid_resolver

src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java, src/firefly/js/metaConvert/ObsCoreConverter.js, src/firefly/js/ui/DownloadDialog.jsx
see https://github.com/IPAC-SW/irsa-ife/pull/66 for details
=> IRSA-2883: Update SOFIA with proprietary data enabled

src/firefly/js/drawingLayers/ComputeWebGridData.js, src/firefly/js/visualize/draw/ShapeDataObj.js
In this pull request:
1.  FIREFLY-82:
Changed the algorithm for grid line labels.
2. IRSA-2916:
Bug was found and fixed in HiPs grid levels
I built several times in the past week but none of them is able to search images.  The URL will be added here once the build works. 
URL: https://irsawebdev9.ipac.caltech.edu/firefly-82-grid/irsaviewer/
=> 1. FIREFLY-82

src/firefly/js/ui/NaifidPanel.jsx
Sorting the suggestion list of the moving objects (NAIFID) in descending order. See ticket:
https://jira.ipac.caltech.edu/browse/FIREFLY-83 
K8s:https://irsawebdev9.ipac.caltech.edu/firefly-83/applications/sofia/
To Test:
- Select 'Moving Object'
- Type 2, the suggestions list sorting values from highest to lowest.
=> FIREFLY-83_moving_object_resolver_improvements

src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/projection/WavelengthHeaderParser.js
Fixed bugs in WavelengthHeaderParser and PlotViewUtils
Test URL: https://irsawebdev9.ipac.caltech.edu/Firefly-178-lijun/firefly/
=> Firefly-178:Cubes and MEFS bugs

src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
https://jira.ipac.caltech.edu/browse/FIREFLY-265
Test https://irsawebdev9.ipac.caltech.edu/FIREFLY-265_formatting_issues/irsaviewer/
You can use the attached file in the ticket for testing.  There is also a comment added to the ticket to explain the problem.
=> FIREFLY-265: Check formatting table values

src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
https://jira.ipac.caltech.edu/browse/FIREFLY-99
Test deployment: https://irsawebdev9.ipac.caltech.edu/firefly-99_emptyFloat/firefly/
To test you can use a minimal table attached to the ticket or TAP result tables with float fields.
=> FIREFLY-99: Empty float from VOTable shows as "0.0000000000e+00" 

src/firefly/html/demo/ffapi-sed.html
This is to document the VizieR search cases in the current Radar update.
=> IRSA-2696 Add couple of example for VizieR photometry data retrieval and SED plot

src/firefly/js/visualize/reducer/DrawLayerReducer.js
Fixed the  missing image grid issue after performing wcs align
Test URL: https://irsawebdev9.ipac.caltech.edu/irsa-2998-grid-lijun/irsaviewer/
=> IRSA-2998:WCS HiPS/FITS alignment and coord overlay

src/firefly/js/ui/RadioGroupInputFieldView.jsx
Please review:
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3039
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-3039/applications/sofia/
IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/85
=> IRSA-3039_gray_out_precovery_search_option_in_sofia_applicaiton

docker/base/Dockerfile, src/firefly/js/tables/TableUtil.js, src/firefly/js/visualize/CsysConverter.js, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/MultiImageViewer.jsx
firefly-333,Firefly-334: fixed bug with lsst deployment 
- flashing and infinite loops on render (334)
- better recognition of radians as units (333)
https://irsawebdev9.ipac.caltech.edu/firefly-334-333/firefly/
=> firefly-333,Firefly-334: fixed bug with lsst deployment

src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/task/PlotChangeTask.js, src/firefly/js/visualize/task/PlotImageTask.js
Please use the sofia cube data in the IRSA-2459.  To check what the issue is, please do the same thing in irsadev.ipac.caltech.edu.   
Test URL: https://irsawebdev9.ipac.caltech.edu/irsa-2459-Lijun/firefly/
=>  IRSA-2459-Cropped images are not within the selecting area

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisContext.java, src/firefly/js/visualize/draw/FootprintFactory.js, src/firefly_data/footprint/Footprint_SOFIA.reg
Change the labels
URL: https://irsawebdev9.ipac.caltech.edu/firefly-Lijun-firefly-356/firefly/
=> firefly-356:Ordering and footprint labels

src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java, src/firefly/js/templates/lightcurve/LcPhaseTable.js
Ticket [IRSA-3112](https://jira.ipac.caltech.edu/browse/IRSA-3112?focusedCommentId=230285&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-230285).
Fixed the wrong phase value issue
Test URL: https://irsawebdev9.ipac.caltech.edu/irsa-Lijun-irsa-3112-lc/irsaviewer/ts.html
Please use the attached testing data in irsa-3112 to test it.
=> IRSA-3112:Time Series tool problems on irsadev

src/firefly/js/visualize/HiPSMocUtil.js
https://jira.ipac.caltech.edu/browse/FIREFLY-372
Fix the method to validate the mandatory keywords defined in the MOC fits file. 
test:
compare the PR build and the nightly build on HiPS image search. 
=> no MOC layer (by checking the draw layer dialog) can be found for HiPS image on any of "IRACx survey in Healpix". 
nightly: https://irsawebdev9.ipac.caltech.edu/nightly/firefly/
PR build: https://irsawebdev9.ipac.caltech.edu/firefly-372/firefly/
=> FIREFLY-372 Fix MOC layer displayed issue

src/firefly/js/ui/ImageSelect.jsx
Fixing Expand all/Collapse all in irsaviewer app.
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3071
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-3071/irsaviewer/
=> IRSA-3071_irsaviewer_expand_all_and_collapse_all_behaves_unexpectedly

src/firefly/html/demo/ffapi-sed.html, src/firefly/js/charts/ChartsCntlr.js
IRSA-3117 Radar update UI to show SED error message in chart. Add VizieR SED plot example with calculated column and example with no data error message.
For details see Jira ticket: 
https://jira.ipac.caltech.edu/browse/IRSA-3117
Example on k8s: https://irsawebdev9.ipac.caltech.edu/irsa-3113_update-SED-plot-error-massge/firefly/demo/ffapi-sed.html
=> IRSA-3117 Update error message for Radar SED plot

src/firefly/js/ui/DownloadDialog.jsx
jira: https://jira.ipac.caltech.edu/browse/IRSA-3181
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-3181/applications/sofia/
=> IRSA-3181_disable_download_button_when_row_includes_private_data

src/firefly/html/firefly-dev.html, src/firefly/js/Firefly.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/MenuItemKeys.js, src/firefly/js/visualize/PlotAttribute.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/draw/DrawingDef.js, src/firefly/js/visualize/draw/FootprintObj.js, src/firefly/js/visualize/iv/HiPSTileDrawer.js, src/firefly/js/visualize/iv/ImageRender.jsx, src/firefly/js/visualize/iv/ImageTileDrawer.js, src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/ImageCenterDropDown.jsx, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx, src/firefly/js/visualize/ui/VisToolbarView.jsx
- Coverage: When doing coverage, then switching FITS or HiPS, and the FOV is 15 degrees or greater then it will attempt to center on the active row of the active table.
- Coverage: When 'pan by table row' is on, the coverage is a FITS image not showing the whole table, and another row is clicked and if the row is off the image a new image will be loaded.
- Zooming in auto mode, conversion will continue to center on the center of the zoom
- fixed bug: when moving between an all sky FITS and HiPS. Failed to render.
- fixed bug: with footprints, it did not catch coordinate conversion errors
- the recenter button, when image is off the screen, now always recenters on image and not target
- allow toolbar options to include the 'Pan by table row' button to be turned off
- added …
=> Firefly-390,Firefly-391: Multiple coverage issues fixed.

src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java, src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/drawingLayers/NorthUpCompass.js, src/firefly/js/ui/CompleteButton.jsx, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/visualize/CsysConverter.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Firefly-144,400,388: bug fixes:
- Firefly-144: fixed: compass is not redrawn is certain cases.
- Firefly-400: Compress images show as table in the upload tool
- Firefly-388: fixed image should not select when in decimation mode
- Fixed: image jumping on selection
- also, NorthUpCompass.js code cleanup
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-144-400-388-bug-fixes/firefly/
- load an image and turn on compass: flip, rotate, zoom compass should always redraw
- upload and image with a compress FITS images. It will show and load correctly.
- load catalog m16, 1800 arcsec. This will put the image catalog in decimation mode. It should not show selection.
- In the same case, filter down (with chart) then start clicking on table to show selection on image. It should not jump around.
=> Firefly-144,400,388: bug fixes

buildScript/global.gincl, buildScript/tasks.gincl
https://jira.lsstcorp.org/browse/DM-20931
Add to `suit` a build script that encapsulates the full build process for that package, including its dependency on an explicitly specified version of Caltech-IPAC/firefly.
Added reusable task to firefly common.  
See https://github.com/lsst/suit/pull/18  for more details.
=> DM-20931: Implement pinning of Firefly version in suit repo

src/firefly/js/ui/PagingBar.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-13
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-13_paging_bar_update/firefly/
Toolbar button moves when description changes in size.  This PR ensure the buttons stay at the same place regardless of the description.
To test, create a big table with at least 10 pages.  Use the toolbar buttons to move from page to page.  The buttons should remain in the same position.
=> FIREFLY-13: fix table paging bar grow/shrink when paging

src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/WebsocketConnector.java, src/firefly/js/core/messaging/WebSocketClient.js
https://jira.ipac.caltech.edu/browse/FIREFLY-151
Test deployed as /firefly on irsawebdev{7,8} and proxied by irsadev:9201.
Use this to monitor active connections: https://irsadev.ipac.caltech.edu:9201/server-status
Initial testing indicates the fix is working.  Reviewers may continue to monitor and/or comment on the code change.
Summary of changes:
- add timeout and max session idle time on server-side
- reduce keepalive ping while connected.
=> FIREFLY-151: WS connection stuck on "Sending Reply"

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/ZtfIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/ztf/ZtfRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/ztf/ZtfSciimsFileRetrieve.java, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ZtfRequestList.js, src/firefly/js/templates/lightcurve/ztf/IbeZTFPlotRequests.js, src/firefly/js/ui/IbeSpacialType.jsx
majority code done in ife. 
Related IFE branch/PR: https://github.com/IPAC-SW/irsa-ife/pull/95
Note: There will be more UI redesign, code reorg and cleanups. 
Test url: https://irsawebdev9.ipac.caltech.edu/irsa-2955-ztf-migration/applications/ztf/
=> IRSA-2955 First cut of ztf mirgration

src/firefly/java/edu/caltech/ipac/table/TableUtil.java, src/firefly/js/tables/ui/TableSave.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-370
Updated table save dialog and dowloaded file extension.
See ticket for details.
To test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-370_table_save_option/firefly/
- Catalog Search -> m31
- Click `Save` icon
Examine the dialog to ensure that the options are as described in the ticket.
=> FIREFLY-370: Update table saving option menu

src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/TempTable.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/Query.java
Jira:https://jira.ipac.caltech.edu/browse/IRSA-3147
K8s: https://irsawebdev9.ipac.caltech.edu/irsa-3147/applications/Spitzer/SHA/
IFE PR:https://github.com/IPAC-SW/irsa-ife/pull/102
Testing: use m81, and check Level1, and Level2. Any radius is ok.
=> IRSA-3147_migration_of_searches_for_BCD_and_PBCD

src/firefly/js/visualize/projection/Wavelength.js, src/firefly/js/visualize/projection/WavelengthHeaderParser.js
Firefly-271: https://jira.ipac.caltech.edu/browse/FIREFLY-271
In this pull request, the TAB wavelength was implemented based on the algorithm in the reference paper by E. W. Greisen et al.  The implementation was tested using the simulated data.  I was not able to create good enough simulated data to cover the whole image.  Thus, there will be some NaN.  
Please test it using the simulated data attached in firefly-271.
URL: https://irsawebdev9.ipac.caltech.edu/firefly-271-Wave-TAB/firefly/
=>  firefly-271-Add WCS-TAB support to spectral FITS parser

src/firefly/js/tables/TableUtil.js, src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
**Fixes Firefly-772**
https://jira.ipac.caltech.edu/browse/FIREFLY-472
This fits table is in radians, image center did not recognize it.
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-472-rad/firefly/
- upload file in ticket
- click on a row.  It should stay in place.
=> Firefly-472: image centering was not recognizing that the table was in radians

src/firefly/js/tables/ui/TablesContainer.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
Show the file names on tabs when loaded from the catalog upload.   
- Catalog tab show file name
- fixed a small issue with coverage
_for review:_ also look at `UserCatalogQuery.java:prepareTableMeta`
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-486
_test_: https://irsawebdev9.ipac.caltech.edu/firelfy-486-file-in-tab/firefly/
- upload two file using the catalog upload (not the more general file upload)
- There must be two files, to test the tabs. (you can use the file in the ticket.)
=> Firefly-486: Add file name in tab to catalog upload

docs/release-notes.md, src/firefly/js/visualize/task/PlotChangeTask.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- _fixes:_ https://jira.ipac.caltech.edu/browse/IRSA-1197_
- _to test with finder chart_: follow steps in ticket. The problem should be fixed.
- _URL:_  https://irsawebdev9.ipac.caltech.edu/IRSA-1197-fc-crop-lock/applications/finderchart/
- _to test with firefly_: load a bunch of images, wcs match lock, crop one
-  _URL:_ https://irsawebdev9.ipac.caltech.edu/IRSA-1197-fc-crop-lock/firefly/
=> IRSA-1197: fixed, after crop the incorrect box no lock appear and locking is correct

docs/release-notes.md, src/firefly/html/demo/table-api.html, src/firefly/html/test/tests-table.html, src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/table/DataType.java, src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java, src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/TablePanel.css
https://jira.ipac.caltech.edu/browse/FIREFLY-442
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-442_api_fixed_column/firefly/
> Expose the feature "freeze columns" of the table display in API
Also:
- added `Column Meta` test to /test/tests-table.html
- update jsdoc
- update docs in /demo/table-api.html
=> FIREFLY-442: Add fixed column to table API

src/firefly/html/test/styles.css, src/firefly/html/test/template.html, src/firefly/html/test/tests-table.html, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReducer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-137
From ticket:
> - one or more columns' values or the entire row
> - the "absolute row index" of the row in the table (i.e., an index that refers to the same row no matter how the filter or sort state of the table may have changed)
> - the relative index of the row in the currently displayed content of the table
> - the checkbox state of the row
Also:
- added test case to demonstrate how to listen to table events
- add feature `copy source to clipboard` to integrated test framework
Best to see this in action.  Test case #4
https://irsawebdev9.ipac.caltech.edu/FIREFLY-137_table_highlight_info/firefly/test/tests-table.html#4
=> FIREFLY-137: add additional information into the row highlight action

src/firefly/js/visualize/region/RegionDescription.js
fixes firefly-501.
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-501
_to test:_
- https://irsawebdev9.ipac.caltech.edu/firefly-501-region-save/firefly/
- save a region file
=> Firefly-501: fixes region saving

src/firefly/js/visualize/Point.js, src/firefly/js/visualize/projection/__tests__/Projection-test.js, src/firefly/js/visualize/projection/__tests__/Wavelength-test.js, src/firefly/test/edu/caltech/ipac/firefly/util/FileLoader.java, src/firefly/test/edu/caltech/ipac/firefly/util/FitsHeaderToJson.java, src/firefly/test/edu/caltech/ipac/visualize/plot/ImageHeaderTest.java, src/firefly/test/edu/caltech/ipac/visualize/plot/projection/ProjectionTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-468
1. Add utility methods to load table from a FITS file
2. Add utility methods to read binary table in the FITS
3. Add utility methods to create json files that contains FITs header and the binary table information
4. Create testing data for wavelength unit test
5. Add unit tests for Wavelength.js
NOTE:  The unit test for each algorithm is black box type unit test.  The expected value is calculated either by directly taking from the known data or calculated independently using the known data.  
To test:
1. check out the data branch firefly-468-wavelength-unitTest in firefly_test_data
2. check out this branch
3. gradle :fi:jTest
=> firefly-468-Unit test is needed for Wavelength calculation for different WCS

src/firefly/java/edu/caltech/ipac/visualize/plot/ImageHeader.java, src/firefly/js/visualize/projection/ProjectionHeaderParser.js
https://jira.ipac.caltech.edu/browse/FIREFLY-482
Fixed serval bugs that provent from displaying the mouse readout for ctypei='LINEAR'.
This is a generic issue for the any FITS which has CTYPEi="LINEAR".  For detail explanation, please see the comment in the ticket FIREFLY-482. 
URL: https://irsawebdev9.ipac.caltech.edu/Firefly-482-mouseReadout/firefly/
To test: 
1. download the FITS file attached "pacscube_wcstab.fits"
2. upload this FITS using https://irsadev.ipac.caltech.edu/irsaviewer/, you will see the coordinate values are displayed as EQ-J2000: 0.000000;0.000000
3. upload this file in the URL above and you will see the mouse readouts displayed.
=> Firefly-482-Firefly can not display mouse readout for some Herschel PACS data

src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java, src/firefly/js/drawingLayers/DistanceTool.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/task/PlotChangeTask.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/task/WcsMatchTask.js
Fixes the following to tickets.
- 503: label changes with HiPS change
- 511: ruler unit change fixed
https://jira.ipac.caltech.edu/browse/FIREFLY-503
https://jira.ipac.caltech.edu/browse/FIREFLY-511
_test:_  https://irsawebdev9.ipac.caltech.edu/firefly-503_511/firefly/
=> Firefly-503, firefly-511 - fixed

src/firefly/html/firefly-dev.html, src/firefly/html/ts.html, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/task/PlotAdminTask.js, src/firefly/js/visualize/task/WcsMatchTask.js
Firefly-510  - partial bug fix.
see ticket - https://jira.ipac.caltech.edu/browse/FIREFLY-510 
- fixes #1.
- number #2 already fixed in Firefly-511.
- number #3 may be fixed. Need more clarity on it.
- cleaned up reset to more reset to the applications intension
- wcs match sometimes broke rotation with timeseries.
- fixed target lock not being on
_to test_ - https://irsawebdev9.ipac.caltech.edu/firefly-510-ts/firefly/ts.html
=> Firefly-510  - partial bug fix.

src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
firefly-514: revamped how we use starlink fits table reading so that we can close the FITS file.
_to test:_
-  use the upload to read a table fits file. it should close when it is done.
- I am not making a jenkins build
- the only way to test is to build it on a local machine and stop in the debugger on line 436 and observe the file being closed.
=> firefly-514: revamped how we use starlink fits table reading so that we can close the FITS file.

src/firefly/js/ui/ColorPicker.jsx
Firefly-529: Fixed: Color Picker now update when user changes a value
https://jira.ipac.caltech.edu/browse/FIREFLY-529
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-529-color-picker/firefly/
- Bring up any drawing layer and change the color using the color picker dialog
- dialog should update and the color should change
=> Firefly-529: Fixed: Color Picker now update when user changes a value

package.json, src/firefly/html/demo/table-api.html, src/firefly/js/core/background/BgMaskPanel.jsx, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReducer.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablesContainer.jsx, src/firefly/js/ui/PagingBar.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/util/Logger.js, src/firefly/js/util/WebUtil.js, yarn.lock
https://jira.ipac.caltech.edu/browse/FIREFLY-495
- fix TABLE_LOADED is called after table has been removed
- fix eslint error by updating eslint-plugin-react-hooks
- tidy up table-api.html test page
Test: https://irsakudevlb1.ipac.caltech.edu/firefly-495-expanded-table/applications/sofia/
- search on m17
- select to FIFI-LS and Data tab
- select 3rd row
- should be a 1-row table.
- expand that table.  should work now.
@robyww I created new yarm.lock file and noticed a lot of the sha hash is removed.  Did you purposely put them in there?  If so, I'll figure out how to put them back.
Additional changes after PR review:
- fix Backgrounded searches not cached on activation fetch
@robyww, this was the cause of the long blank table.
It's actually a pretty bad bug, because without cache, it …
=> FIREFLY-495-sofia-expanded-table

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java, src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageParams.java
https://jira.ipac.caltech.edu/browse/IRSA-2673
Fixed the full image issue in SDSS.  Please check IRSA-2673 for the description of the issue and the log about the fix. 
Please note:  There is a branch in ife with the same name.  But all changes were in firefly.
Testing URL:
https://irsakudevlb1.ipac.caltech.edu/irsa-2673-sdss/irsaviewer/
=> irsa-2673:IRSAViewer can't get full SDSS images?

src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FlipXY.java
https://jira.ipac.caltech.edu/browse/IRSA-1530
The issue in IRSA-1530 is originated from Firefly.  There is the PR in the IFE that fixed some issues in IFE.
The fixes are the following:
1. In FlipXY, access the FITs data through the FitsRead instance instead of accessing from the memory.  
2. If the image has a projection=PLATE, doFlipY returns the input FitsRead instance, instead of null.  Thus, the total number of images are not changed.  However, I checked the flipY in Firefly, it does not care about the PLATE projection, it flipped anyway.  I don't know the reason why flipping PLATE is not allowed.  The old code, FlipLR is so.   
To be consistence, should we do the same in Finderchart?   To test, please use the test example in 
https://github.com/IPAC-SW/irsa-ife/pull/121.
=> IRSA-1530:Finder Chart : Orientation keyword in API

src/firefly/test/edu/caltech/ipac/firefly/util/FitsGenerator.java
https://jira.ipac.caltech.edu/browse/FIREFLY-594
Changed the simulated data in FitsGenerator.java to fix the unit test failure in FlipXY.java
=> firefly-594:FlipXY's unit test "FlipXTest" is failed

src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
This is the branch where i've changed the label in the target panel as CCB requested.
https://jira.ipac.caltech.edu/browse/FIREFLY-564
Please confirm and i will merge.
Built here: https://irsakudevlb1.ipac.caltech.edu/firefly-564/irsaviewer/
Thanks!
=> FIREFLY-564: label changed in the target panel

src/firefly/js/data/form/PositionFieldDef.js
Quick fix required by PR:
https://github.com/IPAC-SW/irsa-ife/pull/124
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3541
=> IRSA-3541_add_to_sofia_web_api_search_for_aor_level_planid

src/firefly/js/data/MetaConst.js, src/firefly/js/visualize/ui/PngViewer.jsx
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3476
K8s: https://dean-irsa-3476.irsakudev.ipac.caltech.edu/applications/sofia/
IFE Branch: https://github.com/IPAC-SW/irsa-ife/pull/116
For test:
1- Run a search ex: m17, radius 200.
2- Click on "HAWC+" tab
3- Click on a row with a .png instead of .fits
4- The "Preview" tab should display that image.
=> IRSA-3476_add_preview_of_pngs_to_data_tab

package.json, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/util/WebUtil.js, yarn.lock
- fixed download for chart
- cleaned up FitsDownloadDialog.jsx download for image (LOC more than cut in half)
- added package to create a slug
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-585
- to test: 
- https://fireflydev.ipac.caltech.edu/firefly-585-chart-save/firefly/
- save a chart
- https://fireflydev.ipac.caltech.edu/firefly-585-chart-save/firefly/ts.html
- save a chart
=> Firefly-585: fix download

package.json, src/firefly/html/test/tests-viewer.html, src/firefly/js/FFEntryPoint.js, src/firefly/js/api/ApiViewer.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/core/core-typedefs.jsdoc, src/firefly/js/templates/fireflyslate/FireflySlate.jsx, src/firefly/js/templates/fireflyslate/FireflySlateManager.js, src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/AppInitLoadingMessage.jsx, src/firefly/js/visualize/MultiViewCntlr.js, yarn.lock
- Loading message is settable from API viewer code
- `ApiViewer.js` cleaned up
- ` FireflySlate.jsx` cleaned up, converted to functional component
- `react-grid-layout` package updated, `GridLayoutPanel.jsx` tweeked to support changes
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-505
https://fireflydev.ipac.caltech.edu/firefly-505-starting-message/firefly/test/tests-viewer.html
- Click on any link and you will see the loading message.
- The message might not be there long, but is more obvious with HiPS and MOC and some tables
=> Firefly-505: added support for a loading message

src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java, src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java, src/firefly/java/edu/caltech/ipac/firefly/data/sofia/VOSpectraModel.java, src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
https://jira.ipac.caltech.edu/browse/IRSA-2716
Add the analyzer to analysis the SOFIA GREAT not_scale data. And then display the flux vs frequency table and chart.
To Test:
URL: https://irsa-2716-sofia-v1.irsakudev.ipac.caltech.edu/applications/sofia/
URL: https://irsa-2716-sofia-v2.irsakudev.ipac.caltech.edu/applications/sofia/
1. click the URL above
2. select, allSky, Level4
3. filter the data in file-url field by "not"
4. click "Data" tab
=> irsa-2716:SOFIA GREAT: Level 4 .fits files can be visualized

src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/MultiProductViewer.jsx
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-617
sofia no longer show the file content twice
https://firefly-617-dpviewer.irsakudev.ipac.caltech.edu/applications/sofia/
all sky search on GREAT, the filter for fits files
=> firefly-617: fixed data products viewer showing the File Content dropdown twice

buildScript/tasks.gincl, buildScript/webpack.config.js, package.json, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TableRenderer.js, yarn.lock
https://jira.ipac.caltech.edu/browse/FIREFLY-595
Handle cell with long entries
- show '...' icon when hover over cells with value clipped
- on click, show actions as context popup menu
- Copy to clipboard
- View as plain text:  show full content as text in a dialog
Also:
- fix minor build related script bugs
- update fixed-data-table-2 to latest version
To test: https://fireflydev.ipac.caltech.edu/firefly-595-long-cell-entries/firefly/
=> FIREFLY-595: Handle cell with long entries

src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java, src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-632
This PR fixed some of the issues reported in the ticket above.  
NOTE the following two issues:
GRID:  FF can not add grid for the image without projection, ie. the mapType = unrecognized or unspecified.  I spent quit some effort on this issue, but I did not find a better solution.  
GREAT LEVEL-1: Some of the GREAT LEVEL-1 data has 'Table Load" error. The cause is the FF does not support the FITs that has more than one naxisi>1 where i=1,..naxis.  The failing FITs files have both naxis1>1 and naxis2>1.
Test URL:
https://lijun.irsakudev.ipac.caltech.edu/applications/sofia/
https://lijun1.irsakudev.ipac.caltech.edu/applications/sofia/
To test:
1. allSky
2. Select instrument: GREAT, LEVEL_1
In the first URL, the fourth row will give a "table …
=> firefly-632:More issues found after fixing FIREFLY-629 and 631

src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/PopupPanel.jsx
This PR is suppose to fix the problem described in [FIREFLY-618](https://jira.ipac.caltech.edu/browse/FIREFLY-618) in the table viewer when a String array type is wrongly displayed. It was JSON conversion that needed to be fixed.
We have found also that there is a bug in the STIL library and we fix it locally in Firefly code by writing our own reader for the array size (`getshape()` method).
We have added a formatting option when displayed as text to ease the reading.
Version deployed for testing: https://fireflydev.ipac.caltech.edu/firefly-618-fix-value-array-string/firefly/
=> Firefly 618 fix value array string

src/firefly/js/visualize/reducer/PlotTitle.js
https://jira.ipac.caltech.edu/browse/FIREFLY-279
change the 3-color image's label
Test:
URL: https://lijun.irsakudev.ipac.caltech.edu/irsaviewer/
=>  firefly-279:Update 3-color image labeled incorrectly

src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/IRSA-3708
Fixed the file content menu
To Test:
URL: https://lijun.irsakudev.ipac.caltech.edu/applications/sofia/
=> IRSA-3708:SOFIA HDU menu: "show as or image"

src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java, src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/IRSA-3724
labels are changed.
Test URL:
https://zhang-irsa-3724.irsakudev.ipac.caltech.edu/applications/sofia/
=> IRSA-3724:GREAT level 4 file contents menu

src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/task/PlotChangeTask.js, src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
Fixes firefly-549
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-549
Best test is to look at @lrebull last comment on the ticket.  Before the context toolbar was staying up after the crop.
_build:_ https://fireflydev.ipac.caltech.edu/firefly-549-toolbar-staying-up/firefly/
=> Firefly-549: Fixed Crop and context toolbar not going away.

src/firefly/js/visualize/ui/PngViewer.jsx
Fix png image distortion:
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3703
K8s: https://dean-irsa-3703.irsakudev.ipac.caltech.edu/applications/sofia/
Test: Search moving target "Neptune Barycenter" and click on HAWC+ then see the png's.
=> IRSA-3703_preview_image_can_be_distorted

src/firefly/java/edu/caltech/ipac/firefly/data/sofia/VOSpectraModel.java, src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java, src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/converterUtils.js
https://jira.ipac.caltech.edu/browse/IRSA-3721
This PR is changed the file menu, chart and table titles as requested. 
Test URL
https://lijun-irsa-3721.irsakudev.ipac.caltech.edu/applications/sofia/
=> irsa-3721:original HDU view names

README.md
The branch descriptions were updated to more accurately reflect current practice.
=> Update branch descriptions in master README file

config/web.xml, src/firefly/html/test/tests-table.html, src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java, src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HealthCheck.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java, src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-667
- Firefly 'dev' and 'gwt' need to be modified so that it take header ''X-Forwarded-*' header' when available.  This is because when Firefly is behind a reverse proxy, the proxied host information is stored in these headers.
- Add health check endpoint to all Firefly-based applications.  The check will perform a simple operation, like allocating a small amount of memory to ensure the JVM is healthy.  It will be mapped to `/healthz`.
- Fixed error messages coming from the catalog dialog.
I do not have a test build.  Please review code to ensure it does not break existing functionality.  More testing to come when IRSA UI apps are served by irsakudev.
=> Firefly 667 Firefly related changes needed for irsakubernetes deployment

src/firefly/js/charts/ui/PlotlyChartArea.jsx
Chart is not being updated when expanded.
Jira: https://jira.ipac.caltech.edu/browse/FIREFLY-525
K8s: https://fireflydev.ipac.caltech.edu/dean-firefly-525/firefly/test/tests-main.html
Testing : 
1 - Use the link above. 
2- Click expand on the first search example. 
3- Expand the chart.
4- Click the gears to show options.
5- Click "Layout options" and change the x and y axis labels.
6- Click apply. That should change the labels on the chart immediately.
=> FIREFLY-525_charts_expanded_view_do_not_update

docs/new-release-procedure.md, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-670
Test URL: https://fireflydev.ipac.caltech.edu/firefly-670-fmtdisp-bug/firefly/
To test, edit attached HTML file in the ticket to point to this `Test URL`, then open it in your browser.
Also:
- update releae procedure to include Test and Deployment to IRSA Kubernetes
- update tables-typedefs.jsdoc to include 'resources' meta
=> FIREFLY-670: Table fail to render cell value as HTML when FmtDisp is used

src/firefly/js/core/ComponentCntlr.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/CoveraeViewer.jsx
Irsa-3771: coverage bug
- occures when the tables indicates that is support coverage but coverage cannot be computed
- happening in sofia when some of the corner columns were null
- the fix is general
fixes: https://jira.ipac.caltech.edu/browse/IRSA-3771
To test with sofia: 
- https://irsa-3771-coverage-bug.irsakudev.ipac.caltech.edu/applications/sofia/
- serach m42, 1 degress, EXES only
=> Irsa-3771: coverage bug

src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/ui/Banner.jsx
https://jira.ipac.caltech.edu/browse/IRSA-3729
Decrease Time Series Tool's title font size so it will fit in a smaller screen.
Test: https://irsa-3729-viewer-shrunk.irsakudev.ipac.caltech.edu/irsaviewer/timeseries
=> Irsa 3729 viewer shrunk

config/app.config, docs/release-notes.md, src/firefly/js/charts/ChartsCntlr.js, src/firefly/js/charts/ui/ChartsContainer.jsx, src/firefly/js/charts/ui/PlotlyToolbar.jsx, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/templates/hydra/HydraViewer.jsx
IRSA-3757: fixes chart data viewer expanding wrong chart
Fixes: IRSA-3757
_ticket_: https://jira.ipac.caltech.edu/browse/IRSA-3757
To test: 
Sofia: https://irsa-3757-expand.irsakudev.ipac.caltech.edu/applications/sofia/
Firefly: https://fireflydev.ipac.caltech.edu/irsa-3757-expand/firefly/
=> IRSA-3757: fixes chart data viewer expanding wrong chart

src/firefly/js/ui/tap/TableSelectViewPanel.jsx
This PR migrates BasicUI to be a functional component rather than class-based.
=> Migrate BasicUI to a functional component

src/firefly/js/visualize/ui/CoveraeViewer.jsx
IRSA-3846: fixes: "no coverage available bug"
https://jira.ipac.caltech.edu/browse/IRSA-3846
_to test:_ see ticket
https://irsa-3846-coverage.irsakudev.ipac.caltech.edu/applications/sofia/
=> IRSA-3846: fixes: "no coverage available bug"

src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx
Fixes issues with adql text area being out of sync when service url changes as well as z-index related issues when selecting a new service url
=> ADQL editor fixes when service url changes

src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/WiseFileRetrieve.java
Update iWISE with NEOWISER yr8.
k8 build: https://wmi-iwise-yr8.irsakudev.ipac.caltech.edu/applications/iwise/
=> IRSA-3863 iWISE yr7-yr8 update.

src/firefly/js/drawingLayers/WebGrid.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx
- Fixed: Firefly-695: gridlines not update when HiPS expands
- Fixed: Firefly-696: grid does not come up when API requested with AITOFF coverage
- https://jira.ipac.caltech.edu/browse/FIREFLY-695
- https://jira.ipac.caltech.edu/browse/FIREFLY-696
=> Firefly-695, Firefly-696: fixed two grid issue

src/firefly/js/drawingLayers/WebGridUI.jsx, src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-567
- https://fireflydev.ipac.caltech.edu/firefly-567-ecl/firefly/
- click on the readout dialog, there will the a ecliptic j2000 option
=> Firefly-567: added ecliptic j2000 readout

src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
=> ensure proxy host works for gwt apps

src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java
Update for NEOWISER yr7 public release
=> IRSA-3862 NEOWISER yr7 public release

src/firefly/html/firefly-dev.html, src/firefly/js/tables/TableUtil.js, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/ui/SuggestBoxInputField.jsx, src/firefly/js/ui/tap/ObsCore.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/util/Validate.js
Refactor TableSearchMethods for functional components
Introduces TableSearchHelpers.jsx
There are a lot of changes related to both transitioning to functional components, reducing code interdependency, as well as trying to extract common code across all the new components.
This PR is currently a draft. There are changes I plan to commit in the next several days:
Things I plan to address before this PR comes out of draft
=> Add ObsCore support

docs/new-release-procedure.md, src/firefly/js/charts/ui/ChartPanel.css, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/charts/ui/options/SpectrumOptions.jsx, src/firefly/js/ui/ColorPicker.jsx
Test URL: https://irsa-4042-doubleclick-zoom-reset.irsakudev.ipac.caltech.edu/irsaviewer/
https://jira.ipac.caltech.edu/browse/IRSA-4042
- Disable plotly's "double click to zoom out" feature.  
- Set `yLimitUI` defaults back to `false`.  Chart setting options will not show y-axis upper/lower limit fields unless it is explicitly set.
https://jira.ipac.caltech.edu/browse/FIREFLY-761
- Color picker doesn't update
=> IRSA-4042,FIREFLY-761,FIREFLY-765: Chart multi-trace related change requests

README.md
Updated some of the help to clarify current capabilities, as well.  Regularized the use of MarkDown header levels.
=> FIREFLY-531: Update supported-browser list in the README

src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/ui/ColorPicker.jsx, src/firefly/js/ui/FileUploadDropdown.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- Added support for color swatches with alpha  (firefly-762)
- Added tooltip for whole color dialog (firefly-764)
- Added help icon (firefly-764)
- A little layout cleanup
- Upload panel now has option to only upload tables (irsa-4046)
https://jira.ipac.caltech.edu/browse/FIREFLY-762
https://jira.ipac.caltech.edu/browse/FIREFLY-762
https://jira.ipac.caltech.edu/browse/IRSA-4046
Finder Chart: https://firefly-762-764-irsa-4046.irsakudev.ipac.caltech.edu/applications/finderchart/
Firefly:  https://fireflydev.ipac.caltech.edu/firefly-762-764-irsa-4046/firefly/
See my comments at the bottom of firefly-762 and firefly-762 for details on what we could and could not implement.
=> implement firefly-762, firefly-764, irsa-4046

docs/fftools-api-code-examples.md, docs/fftools-api-overview.md, docs/firefly-python-wrapper.md, docs/fits-plotting-parameters.md
Long-lost commits from a local copy, rebased to current state.
=> Fixes to MarkDown formatting in several help files

src/firefly/js/charts/dataTypes/FireflyGenericData.js
see https://github.com/Caltech-IPAC/firefly/pull/1087
This PR is to fix the above PR's base.  It should've been created in rc-2021.2, not dev.
=> FIREFLY-763: bug in symbol size

src/firefly/js/ui/InputGroup.jsx
Just a small addition to InputField.  The work is done over irsa-ife.
see https://github.com/IPAC-SW/irsa-ife/pull/159
=> IRSA-3156: WISE migration, Position Search

src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
This PR is just to get this commit into the Caltech-IPAC/firefly repo, so that it can be accessed by Jenkins.
Errors from an async TAP call are stored the same way as data
results and thus may return a redirect to an external URL that
does not understand our tokens.  However, they lacked special
redirect handling and the underlying request library would resend
the authentication token for the original request when following
the redirect.  This in turn led to sending authentication tokens
to sites (such as a GCS bucket URL) which did not understand them.
Copy the same code pattern from getData to getErrorMsg: disable
redirects, check the result for a redirect status, and then follow
the redirect manually, re-checking its URL for whether we should
send an authentication token.
I suspect the …
=> Handle redirects when retrieving TAP errors

src/firefly/js/drawingLayers/CatalogUI.jsx, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/PlotTransformUtils.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/draw/CanvasWrapper.jsx, src/firefly/js/visualize/iv/EventLayer.jsx, src/firefly/js/visualize/iv/ImageViewer.jsx, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/task/ZoomTask.js
Fixes mouse wheel / trackpad zoom performance problem.
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-793
=> Firefly-793: fix mouse wheel / trackpad zoom performance problem

src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
Errors from an async TAP call are stored the same way as data
results and thus may return a redirect to an external URL that
does not understand our tokens.  However, they lacked special
redirect handling and the underlying request library would resend
the authentication token for the original request when following
the redirect.  This in turn led to sending authentication tokens
to sites (such as a GCS bucket URL) which did not understand them.
Copy the same code pattern from getData to getErrorMsg: disable
redirects, check the result for a redirect status, and then follow
the redirect manually, re-checking its URL for whether we should
send an authentication token.
I suspect the status of the secondary request may not propagate
back to the outer request for both this and getData, but …
=> DM-30073: Handle redirects when retrieving TAP errors

src/firefly/java/edu/caltech/ipac/astro/net/SimbadNameResolver.java, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/task/ZoomTask.js
Fixes firefly-803, Firefly-797
_Tickets_: 
- https://jira.ipac.caltech.edu/browse/FIREFLY-803
- https://jira.ipac.caltech.edu/browse/FIREFLY-797
_Testing_:  https://fireflydev.ipac.caltech.edu/firefly-803-mouse-zoom/firefly/
=> Firefly-803: fixes mouse wheel/trackpad zoom and Simbad name lookup bug

src/firefly/java/edu/caltech/ipac/firefly/server/query/ztf/ZtfRefimsFileRetrieve.java, src/firefly/js/ui/DownloadDialog.jsx, src/firefly/js/ui/Menu.css
minor change for ZTF file retrieve, more changes are in [ife branch](https://github.com/IPAC-SW/irsa-ife/pull/160).
=> IRSA-4090 ZTF migration add ancillary file download

src/firefly/js/tables/FilterInfo.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/__tests__/TableUtil-test.js, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/FieldGroupConnector.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/util/__tests__/Expression-test.js
https://jira.ipac.caltech.edu/browse/FIREFLY-805
Get exceptions when filtering boolean column:
```
Table Load Error:Invalid statement: 
"w4sigmpro.mask" IN ('true') 
```
Also  fixed a couple of minor errors showing up in the console.
Test: https://fireflydev.ipac.caltech.edu/firefly-805-boolean-col-broken/firefly/
Use attached tables in the ticket to test.
=> FIREFLY-805: Filter does not work on boolean type column

src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java, src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java, src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java, src/firefly/js/metaConvert/MultiProductFileAnalyzer.js, src/firefly/js/metaConvert/PartAnalyzer.js
Jira: https://jira.ipac.caltech.edu/browse/IRSA-3867
K8s: https://irsa-3867.irsakudev.ipac.caltech.edu/applications/sofia/
=> IRSA-3867_show_middle_plane_of_any_sofia_data_cube_by_default

src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java, src/firefly/java/edu/caltech/ipac/util/FileUtil.java, src/firefly/java/edu/caltech/ipac/util/download/BaseNetParams.java, src/firefly/java/edu/caltech/ipac/util/download/Downloader.java, src/firefly/java/edu/caltech/ipac/visualize/net/AtlasImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/DssImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/DssImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/ImageServiceParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/PtfImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/SloanDssImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/TwoMassImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/WiseImageParams.java, src/firefly/java/edu/caltech/ipac/visualize/net/ZtfImageParams.java, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- the parameters `plotId` and `progressKey` were not being passdown down the download
- upload panel now show progress
_note_ - most file changes are just to get the parameters to the lower level.
_ticket_: https://jira.ipac.caltech.edu/browse/FIREFLY-828
_url_: https://fireflydev.ipac.caltech.edu/firefly-828-download-feedback/firefly/
- do a image search, select wise and do full images (these are 64 meg images)
- you might see it with 2MASS Full Survey briefly. Try any image that you know is big
- tap obscore: try CADC - m1 - 10 arcsec, most images here are petty big
- from the images panel choose a url: http://web.ipac.caltech.edu/staff/roby/data-products-test/table-images-single-dim-images.fits
=> Firefly-828: download feedback not working

src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
Jira: https://jira.ipac.caltech.edu/browse/IRSA-4161
K8s: https://irsakutest.ipac.caltech.edu/applications/sofia/
ife PR: https://github.com/IPAC-SW/irsa-ife/pull/167
=> IRSA-4161_limit_the_default_display_of_the_middle_plane_of_a_cube

src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- fixed clear file bug
- fixed a bug where the detail do now show when swtiching between upload and url
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-825
_test url:_  https://fireflydev.ipac.caltech.edu/firefly-825-up/firefly/
- Upload a file, clear it, then upload it again
- Upload a file, then switch to url, load a file via url. You should be able to switch back and forth and clear either one.
=> Firefly-825: fixed clear not working with current file

src/firefly/js/ui/SearchSummary.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-4226
Test   : https://irsa-4226-finderchart-multipos-fail.irsakudev.ipac.caltech.edu/applications/finderchart/
Fixes a bug where a string is requested to be formatted as a decimal number.
Follow ticket's description for testing.
=> IRSA-4226: Finder Chart batch(multi positions) searches fail

src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java, src/firefly/java/edu/caltech/ipac/astro/net/TargetNetwork.java
firefly-277: update moving target name resolution to new horizons api
- Now uses the new api with JSON
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-277
_test in sofiia_ 
- https://firefly-277-horizons-api.irsakudev.ipac.caltech.edu/applications/sofia/
- try the moving target name resolution
=> firefly-277: update moving target name resolution to new horizons api

src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java, src/firefly/java/edu/caltech/ipac/astro/net/TargetNetwork.java, src/firefly/java/edu/caltech/ipac/firefly/messaging/JsonHelper.java
https://jira.ipac.caltech.edu/browse/IRSA-4262
Port the fix in FIREFLY-277 into GWT and roll out SHA, WISE and ZTF with the latest JPL/Horizons name resolution api.
-  FIREFLY-277 PR:  https://github.com/Caltech-IPAC/firefly/pull/1132
Test:  
https://irsa-4262-horizons-api.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
https://irsa-4262-horizons-api.irsakudev.ipac.caltech.edu/applications/wise/
https://irsa-4262-horizons-api.irsakudev.ipac.caltech.edu/applications/ztf/
=> IRSA-4262: Update GWT based app with latest JPL/Horizons name resolution api

src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
Corrected "Cannot not" to "Cannot" in two error messages
=> Correct typos in File Analyzer error messages

src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryIBE.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-876
Test: https://firefly-876-ibe-multi-pos.irsakudev.ipac.caltech.edu/applications/wise/
Add multi-position (file upload) search to QueryIBE (common IBE search processor).  
Also, made migrated WISE multi-postion search working by using this new feature.
This part is in `irsa-ife`'s PR: https://github.com/IPAC-SW/irsa-ife/pull/180
=> FIREFLY-876: add multi-position search into the common ibe search processor

src/firefly/java/edu/caltech/ipac/firefly/core/HipsIndexHtmlGenerator.java, src/firefly/java/edu/caltech/ipac/firefly/resources/index_template-hips.html
The program is generating an html using properties file given a hips url root.
This is to answer the IRSA request IRSA-3475.
Should be a start for making a template HTML to be used for HiPS internally and replace CDS ones.
Should be safe to merge, no collision with other things.
=> IRSA-3475: added template index.html and generator 

src/firefly/js/drawingLayers/NorthUpCompass.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/PlotGroup.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/iv/ImageTileDrawer.js, src/firefly/js/visualize/iv/PlotTitle.css, src/firefly/js/visualize/iv/PlotTitle.jsx, src/firefly/js/visualize/reducer/HandlePlotAdmin.js, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/HandlePlotCreation.js, src/firefly/js/visualize/reducer/PlotView.js
- Flipping and North up sticky
- Title string shows flip
- Compass sticky
- flipY not centering correctly on image creation
- a little cleanup
_ticket:_ 
https://jira.ipac.caltech.edu/browse/FIREFLY-858
- url:  https://firefly-858-sticky.irsakudev.ipac.caltech.edu/applications/ztf/
- flip and/or rotate north the image. The other ones should be that as well.
=> Firefly-858: Sticky flipping and north up

src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/draw/MocObj.js
- When the MOC coordinate sys differs from the HIPS coordinate system the MOC it was drawn incorrectly
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-675
- https://fireflydev.ipac.caltech.edu/firefly-675-moc-coordinate-sys/firefly/
- Test 1: according to the ticket
- Test 2: 
- show an 2 MASS HiPS or AllWise HiPS
- Overlay MOC IRAC1 survey in Healpix
=> Firefly-675: Fixed: incorrect MOC drawing with different coordinate system

src/firefly/js/core/background/BackgroundMonitor.css, src/firefly/js/core/background/BackgroundMonitor.jsx, src/firefly/js/core/background/BackgroundUtil.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/DownloadDialog.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-900
- small downloads don't work
https://jira.ipac.caltech.edu/browse/FIREFLY-901
- email notification cannot be turned off once it's on
NOTE: globally changed
- CheckboxGroupInputField value's label is now vertically centered with the checkbox.
Test: https://firefly-900-901-email-small-download.irsakudev.ipac.caltech.edu/applications/ztf/
=> FIREFLY-900-901: ZTF download related fixes

src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/ui/ExtractionDialog.jsx
Two Tickets: 
- [firefly-909](https://jira.ipac.caltech.edu/browse/FIREFLY-909) : extract shift-click message not shown with one image
- [firefly-910](https://jira.ipac.caltech.edu/browse/FIREFLY-910): units on y axis
Testing:
_IrsaViewer_: https://firefly-909-extract-msg.irsakudev.ipac.caltech.edu/irsaviewer/
_ZTF_: https://firefly-909-extract-msg.irsakudev.ipac.caltech.edu/applications/ztf/
=> Firefly 909,910 

src/firefly/js/Firefly.js
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-916
- https://fireflydev.ipac.caltech.edu/firefly-916-api-load/firefly/
- @cwang2016  will need to test this in a NED environment
=> Firefly-916: fixed: API adding to DOM before page load

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java, src/firefly/java/edu/caltech/ipac/util/download/CacheHelper.java, src/firefly/js/Firefly.js, src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/visualize/saga/MOCWatcher.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/task/PlotImageTask.js
- Also Fixes an occasional but that is hard to duplicate. Once an image request fails it continues to fail until the server is restarted.
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-922
- https://fireflydev.ipac.caltech.edu/firefly-922-moc-on-fits/firefly/
=> Firefly-922: fixed: MOC should just be added to HiPS and not images

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java, src/firefly/js/visualize/FitsHeaderUtil.js, src/firefly/js/visualize/ui/FitsHeaderView.jsx
Firefly-926: now shows all headers, before is was not showing repeating headers
_ticket_: https://jira.ipac.caltech.edu/browse/FIREFLY-926
- https://fireflydev.ipac.caltech.edu/firefly-926-header/firefly/
- Version:    2022.1-DEV:firefly-926-header_4af3
=> Firefly-926: now shows all headers, before is was not showing repeating headers

src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/WiseFileRetrieve.java
k8s build:
https://irsa-4372.irsakudev.ipac.caltech.edu/applications/iwise/
ready for test when yr9 data is setup in ibe
=> IRSA-4372: Update iwise ui for NEOWISER yr8-yr9

src/firefly/js/core/background/BgMaskPanel.jsx, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/ui/DownloadDialog.jsx, src/firefly/js/visualize/PlotState.js, src/firefly/js/visualize/ui/ColorPanelReducer.js
- [Firefly-950](https://jira.ipac.caltech.edu/browse/FIREFLY-950): restore TimeSeries download button
- [Firelfy-139](https://jira.ipac.caltech.edu/browse/FIREFLY-139): fixed color panel showing invalid state when valid
- [IRSA-3170](https://jira.ipac.caltech.edu/browse/IRSA-3170): fixed
- Firefly-139:
- https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/ts.html
- load any time series, The download button will be there.
- Firefly-950:
- https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/
- load any image
- bring up color dialog
- enter and invalid percent then switch to data
- IRSA-3170:
-  https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/ts.html
- start a download and then cancel, or send to background, or let it finish
- in call three cases the download …
=> Firefly-950,Firelfy-139,IRSA-3170: bug fixes

buildScript/webpack.config.js, config/app.config, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/rawData/ManageRawDataThread.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/reducer/HandlePlotCreation.js, src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx, src/firefly/js/visualize/ui/VisMiniToolbar.jsx, src/firefly/js/visualize/ui/ZoomButton.jsx
- [Firefly-956](https://jira.ipac.caltech.edu/browse/FIREFLY-956): improved error handling on retrieve stretch byte data
- [Firefly-957](https://jira.ipac.caltech.edu/browse/FIREFLY-957): Fixed: north up now works
- [Firefly-958](https://jira.ipac.caltech.edu/browse/FIREFLY-958): Fixed: hue preserving now works
- Fixed string: `r` added to zoom message string (Luisa's list 8)
- _Version:_ 2022.1-DEV:firefly-956,957,958_5377
- _URL:_ https://fireflydev.ipac.caltech.edu/firefly-956-957-958/firefly/
=> Fixed multiple issues

src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/ui/panel/TabPanel.css, src/firefly/js/visualize/ui/ExtractionDialog.jsx
-  [Firefly-965](https://jira.ipac.caltech.edu/browse/FIREFLY-965): fixed: extraction tool not completely turning off
-  [Firefly-966](https://jira.ipac.caltech.edu/browse/FIREFLY-966): fixed: tabs losing top 1 pixel border
-  [Firefly-967](https://jira.ipac.caltech.edu/browse/FIREFLY-967): fixed: charts sometime lose title in finderchart
- _Sofia_:  https://firefly-965-966-967.irsakudev.ipac.caltech.edu/applications/sofia/
- _FinderChart_: https://firefly-965-966-967.irsakudev.ipac.caltech.edu/applications/finderchart/
-  Test according to the tickets
- firefly version: 2022.1-DEV:HEAD_7050
**irsa-ife PR**: https://github.com/IPAC-SW/irsa-ife/pull/203
=> firefly-965,966,967: multi bug fixes

config/app.config, package.json, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/metaConvert/MultiProductFileAnalyzer.js, src/firefly/js/templates/hydra/HydraManager.js, src/firefly/js/threadWorker/WorkerAccess.js, src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/iv/EventLayer.jsx, src/firefly/js/visualize/rawData/ManageRawDataThread.js, src/firefly/js/visualize/rawData/RawDataCommon.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/rawData/RawImageTilesGPU.js, src/firefly/js/visualize/ui/FitsHeaderView.jsx, src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx, yarn.lock
- [Firefly-973](https://jira.ipac.caltech.edu/browse/FIREFLY-973) Fixed finder chart performance problem
- updated the revisions of package.json libraries
- optimized getLayouInfo() will not create a new object unless necessary
- workers: when worker deleted it  will now fire a reject for all outstanding promises
- better expired plot checking in RawDataOps
- [Firefly-974](https://jira.ipac.caltech.edu/browse/FIREFLY-974): popout mouse readout not showing flux
- _Bug fix_: FITS Information dialog was not showing file size
- _Bug Fix_: Multi product viewer "All Images" option not showing the correct file when file changed by DataProductAnalyzer
- _Bug Fix_: fixed non-passive event error warning coming from chrome
- _finderchart:_ https://firefly-973-fc-performance.irsakudev.ipac.caltech.edu …
=> Firefly-973, Firefly-974: Fixed Multiple Issues

src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java, src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java, src/firefly/java/edu/caltech/ipac/firefly/core/background/ServCmdJob.java, src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java, src/firefly/test/edu/caltech/ipac/firefly/core/background/JobManagerTest.java
https://jira.ipac.caltech.edu/browse/IRSA-4571
https://jira.ipac.caltech.edu/browse/IRSA-4570
Test: https://irsa-4570-download-proprietary-data.irsakudev.ipac.caltech.edu/applications/sofia/
I think both tickets are related.  I fixed 4571 and 4570 seem to be fixed as well.  Please test.
=> IRSA-4570: SOFIA app: error packaging proprietary data

src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Regression bugs reported after FIREFLY-976 was merged.  Please test and confirmed it's fixed.
https://firefly-976-tablepanel-rerender.irsakudev.ipac.caltech.edu/applications/sofia/
https://fireflydev.ipac.caltech.edu/firefly-976-tablepanel-rerender/firefly/
=> FIREFLY-976: fix bug introduced in useStoreConnector and fix file upload dialog

src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/CtxControl.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/iv/EventLayer.jsx, src/firefly/js/visualize/projection/Wavelength.js, src/firefly/js/visualize/projection/WavelengthHeaderParser.js, src/firefly/js/visualize/task/ImageOverlayTask.js, src/firefly/js/visualize/task/PlotImageTask.js
- search alternate wcs-es for TAB tables
- make sure all TAB tables are read 
- transfer more than one table if necessary
- check parse code to make sure it is getting the correct header data
- _url:_ https://fireflydev.ipac.caltech.edu/firefly-985-wcs-tab/firefly/
- Upload a fits file  with pixel level wavelength info, using TAB, and specified in a alt wcs
- Move mouse around on the image, there will be a wavelength readout
- Note- this does PR is not about the accuracy of the readout (it might be correct). It is about getting the data to to algorythm.
=> Firefly-985: make sure Wavelength TAB tables are read correctly

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/WiseFileRetrieve.java, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/metaConvert/WiseRequestList.js, src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/saga/ImagePlotter.js
This is part of the WISE migration. Updated the sso searches and ui.
k8s build: https://irsa-4202.irsakudev.ipac.caltech.edu/applications/wise/
please see ife [PR ](https://github.com/IPAC-SW/irsa-ife/pull/209) for test instruction.
=> IRSA-4202 Update wise sso(moving object) search and ui.

__jest__/InitTest.js, src/firefly/java/edu/caltech/ipac/firefly/messaging/Messenger.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java, src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventQueue.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java, src/firefly/js/visualize/PlotCompleteMonitor.js
- Messanger information
- Cache replicating information
- Server Event queue information
=> Firefly-992: Improve status page, improve the following

src/firefly/js/Firefly.js, src/firefly/js/api/webApiCommands/TableCommands.js, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/tables/TableRequestUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/FilterEditor.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/visualize/ui/ExtractionDialog.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-478
FIREFLY-478: discrepancy between what's displayed on Table and Table's Column Options
https://jira.ipac.caltech.edu/browse/FIREFLY-787
FIREFLY-787: add 'Copy To Clipboard' action to "Current constraints" field in Table Options
https://jira.ipac.caltech.edu/browse/FIREFLY-812
FIREFLY-812: make default pageSize configurable at the application level
Test: https://fireflydev.ipac.caltech.edu/firefly-494-478-787-812-table-related/firefly/
Follow ticket instructions for testing.
=> Firefly 494 478 787 812 table related

docker/Dockerfile, docker/launchTomcat.sh
Same as https://github.com/Caltech-IPAC/firefly/pull/1222
Added ticket to this PR.  https://jira.ipac.caltech.edu/browse/FIREFLY-996
=> add advanced internal scheme to support secrets, quotes, and spaces in envVar value

src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-739
FIREFLY-739: Don't show more(...) popup for cell with input field.
https://jira.ipac.caltech.edu/browse/FIREFLY-665
FIREFLY-665: Pop up long cell view: formatting enabled by default
Test: https://fireflydev.ipac.caltech.edu/firefly-739-665-cell-popup-ui-validation/firefly/
=> FIREFLY-739_665: table cell rendering related

src/firefly/js/ui/tap/TableSearchMethods.jsx
[Approved](https://jira.ipac.caltech.edu/browse/FIREFLY-990?focusedCommentId=284836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-284836) by @vandesai1 on Jira.
Please include in 2022.2.
=> FIREFLY-990: Change search default to boundary-contains-point

src/firefly/html/test/tests-table.html, src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/js/tables/SortInfo.js
https://jira.ipac.caltech.edu/browse/FIREFLY-1008
- added test to test/tests-table.html
To test feature via API: 
https://fireflydev.ipac.caltech.edu/firefly-1008-sortbycols/firefly/test/tests-table.html?test=Table+sortByCols
From view source, you can see column's meta was added.
To test WISE:
https://firefly-1008-sortbycols.irsakudev.ipac.caltech.edu/applications/wise/
Search: Position -> m51 -> Any pixel overlaps search region -> Search Region=600 arcsec -> Single Exposure -> all bands
Verify that sorting `scan_id` also sorts frame_num and band.
=> FIREFLY-1008: migrate sortByCols feature from GWT

src/firefly/html/test/tests-table.html, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/Query2MassSIA.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css
https://jira.ipac.caltech.edu/browse/IRSA-4688
- change table meta from col.relatedCols to tbl.relatedCols
- add test to tests-table.html
Pretty simple.  See test page to verify that it's working.
Also, see chosen color is appropriate.
Test: https://fireflydev.ipac.caltech.edu/irsa-4688-table-grouped-highlight/firefly/test/tests-table.html?test=Table+related+rows+highlighting
=> IRSA-4688: Migrate the ability to highlight related rows from GWT

src/firefly/java/edu/caltech/ipac/astro/ibe/BaseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorMOS.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/DataGroupHandler.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/metaConvert/WiseRequestList.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/test/edu/caltech/ipac/firefly/server/query/GatorMOSTest.java
Most of the code changes are in ife [here](https://github.com/IPAC-SW/irsa-ife/pull/210) with limited changes in wise ibe search in firefly to support wise source id search etc. 
View ticket [here](https://jira.ipac.caltech.edu/browse/IRSA-4592)
k8s build : https://irsa-4592.irsakudev.ipac.caltech.edu/applications/wise/
=> IRSA-4592 Update for wise searches.

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java, src/firefly/java/edu/caltech/ipac/visualize/net/AtlasIbeImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java, src/firefly/java/edu/caltech/ipac/visualize/net/ImageServiceParams.java, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/visualize/FitsHeaderUtil.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/iv/PlotTitle.jsx, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/PlotTitle.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- [Firefly-959](https://jira.ipac.caltech.edu/browse/FIREFLY-959): Fixed
- [IRSA-4696](https://jira.ipac.caltech.edu/browse/IRSA-4696): Fixed
- [IRSA-4695](https://jira.ipac.caltech.edu/browse/IRSA-4695): Fixed
- A little clean up on the java side
- https://fireflydev.ipac.caltech.edu/firefly-959-timeseries/firefly/ts.html
- Test by uploading a file and trying each tickets issue
=> Firefly-959,IRSA-4696,IRSA-4695: Fixed Timeseries issues

src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java, src/firefly/js/metaConvert/DataLinkProcessor.js, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- clean up HiPS url constructions so no double - /
- better logging of cookies
- clean up service descritor layout
- https://fireflydev.ipac.caltech.edu/firefly-1031-cleanup/firefly/
- Search CACD obcore M1
- choose cutout 
- look at the UI
- Don't do the search since it will probably not work, just look at the UI layout
=> Firefly-1031: clean up

docker-compose.yml, docker/Dockerfile, docker/devMode.sh, docker/launchTomcat.sh, firefly-docker.env, src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/js/tables/ui/BasicTableView.jsx
WiseIbeDataSource was using fits image from filesystem.
This is not reliable.  Remove logic so it will call irsa/ibe instead.
Test: https://fix-scanid-image-failed.irsakudev.ipac.caltech.edu/applications/wise
=> Fixed migrated WISE scan_id image failed to load

docs/release-notes.md, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/ui/VersionInfo.jsx, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- [Firefly-1033](https://jira.ipac.caltech.edu/browse/FIREFLY-1033): fixed: switch between hips and fits
- [Firefly-1035](https://jira.ipac.caltech.edu/browse/FIREFLY-1035): fixed: when no files with coverage show only chage and tables:wq
- [Firefly-1037](https://jira.ipac.caltech.edu/browse/FIREFLY-1037): more updates to acknowledgement
- [IRSA-4722](https://jira.ipac.caltech.edu/browse/IRSA-4722): in data products viewer, three color button will add or remove
- https://fireflydev.ipac.caltech.edu/firefly-1033-firefly-1035/firefly/
- Test Firefly-1033 and Firefly-1035 according to the tickets
=> Firefly-1033, 1035

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
see ife PR: https://github.com/IPAC-SW/irsa-ife/pull/217
=> Irsa 4720 wise full image search with blank image size

src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/util/expr/Parser.js
https://jira.ipac.caltech.edu/browse/FIREFLY-1047
Test: https://fireflydev.ipac.caltech.edu/firefly-1047-more-chart-func/firefly/
Load a table with chart.  Change chart's x/y axis to make use of the added functions.
=> FIREFLY-1047: add radians and degrees into the list of supported functions used by chart

src/firefly/js/ui/DateTimePickerField.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/TimePanel.jsx
- Converted the Menu, TimePanelView and DateTimePicker class components to functional components 
- Made a small change to menu.jsx's makeMenuItem function arguments (set default values for isWorking and badgeCount) 
-  https://fireflydev.ipac.caltech.edu/firefly-1050-class-to-function/firefly/
- go to TAP -> service: CADC -> table collection: ivoa -> table: ivoa.ObsFile or ivoa.ObsPart 
- look at the UI for time field entry and date time picker (click on the calendar icon)
- Functionality should be the same as before, as the only changes made were class components -> functional components
=> Firefly 1050 Converting class based to functional components

docs/development-process.md, docs/tags-and-branches.md
=> Docs: development process

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
This PR fix the WISE source id searches and add a helper anchor in the 3color image popup.
There is also a PR in ife for multiple bug fixes. Test instructions  are in ife PR.
=> IRSA-4756 fix source id searches

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
Fixed them imageset constraints when wise ibe search uses merged table. 
Please test with k8s build:  https://irsa-4789.irsakudev.ipac.caltech.edu/applications/wise/
=> IRSA-4789 Fix the imageset constraints with wise merged table searches.

src/firefly/js/api/WebApi.js
Firefly-1067: added imageSize as a new ReservedParam
=> Firefly-1067: added imageSize as a new ReservedParam

src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
To tset, do a position search using k8s build, hover image icons to see the tooltip and try make 3color image for the error message. 
k8s URL: https://irsa-4753.irsakudev.ipac.caltech.edu/applications/wise/
[View Jira ticket](https://jira.ipac.caltech.edu/browse/IRSA-4753) for details.
=> IRSA-4753 fix few tooltips and error messages.

src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/util/__tests__/VOAnalyzer-test.js, src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/ui/MetaDataMultiProductViewer.jsx, src/firefly/js/visualize/ui/MultProductViewerContainer.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- Also fixes FIREFLY-1066
- https://irsa-4796-toolbar.irsakudev.ipac.caltech.edu/applications/wise/
=> IRSA-4796: Fixed: wise image navigation icons vanish

src/firefly/js/metaConvert/DataProductsFactory.js
Change the default WISE band selection for 3 color images, Red: Band 4, Green: Band 2, Blue: Band 1.
https://irsa-4683.irsakudev.ipac.caltech.edu/applications/wise/
=> IRSA-4793 Change the default three color bands.

src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/task/CreateTaskUtil.js, src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
- user may now use a color band for more than one observation bands
- https://irsa-4807-three-color.irsakudev.ipac.caltech.edu/applications/wise/
- use 3 color setting the same color band to more than one wise band
=> IRSA-4793: allow to use band for more than one color

src/firefly/js/ui/TimePanel.jsx
=> FIREFLY-1050 regression bug in time panel fixed

src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/metaConvert/WiseRequestList.js, src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx, src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/task/PlotImageTask.js, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/MultiImageViewer.jsx
This PR is to add ability to change the image view layout by the data table (tbl_id). 
Most the code change are done by @robyww at the visualization control level. Project level changes are add as well.
To test:
1. do position search with both level 1b and level 3 selected, you should get level 3 data with 4 band view and level 1b data with full grid view. 
2. The moving object search default to full grid view
3. Scan id search: full grid view
4. Coadd id search: 4band view
5. Source id search: depend on product level selected.
ku8 url:  https://irsa-4815.irsakudev.ipac.caltech.edu/applications/wise/
=> Irsa 4815 set default view for wise level1 image

src/firefly/js/ui/CompleteButton.jsx, src/firefly/js/ui/ExampleDialog.jsx, src/firefly/js/ui/FieldGroup.jsx, src/firefly/js/ui/FieldGroupConnector.jsx, src/firefly/js/ui/IbeSpacialType.jsx, src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- Enhance the FieldGroup
- https://fireflydev.ipac.caltech.edu/firefly-1106-fg/firefly/firefly-dev.html
- click on `Example JS Dialog`
- click on the X3 tag
- click ok, you should see the more-info key in the popup
=> Firefly-1106: enhanced field group request

src/firefly/js/tables/ui/TableInfo.jsx, src/firefly/js/ui/panel/CollapsiblePanel.css, src/firefly/js/ui/panel/CollapsiblePanel.jsx, src/firefly/js/ui/tap/ObsCore.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx
Fixes [FIREFLY-1113](https://jira.ipac.caltech.edu/browse/FIREFLY-1113)
- Replaced class component by functional one:
- using setState hook for handling local state 
- and setting local state if it has changed globally [during rendering](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops) to implement getDerivedStateFromProps 
- Used spread syntax in objects and assignments to simplify code, like setting default arguments
https://fireflydev.ipac.caltech.edu/firefly-1113-func-colpan/firefly/
- Click on the collapsible panels throughout the app
- Click on "Expand/Collapse All" on Image Search page (to check if all panels respond to global state changes)
=> FIREFLY-1113: Converted CollapsiblePanel to functional component

src/firefly/js/ui/NaifidPanel.jsx
Fixes [FIREFLY-1120](https://jira.ipac.caltech.edu/browse/FIREFLY-1120)
Besides converting class to functional component, it does cleanup of:
- multiple one-time use functions
- global variables (searchHistory, naifNameValue) using useRef (see [this](https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables))
https://firefly-1120-naif-panel-func.irsakudev.ipac.caltech.edu/applications/sofia
In Sofia Search, select "Solar system target", enter object name or id. 
Similarly in Wise, SHA, etc interfaces.
=> Firefly-1120: Convert NaifidPanel to functional component and cleanup

src/firefly/js/charts/TableStatsCntlr.js, src/firefly/js/charts/ui/ChartPanel.css, src/firefly/js/charts/ui/CombineChart.jsx, src/firefly/js/charts/ui/PinnedChartPanel.jsx, src/firefly/js/core/BootstrapRegistry.js, src/firefly/js/tables/TableUtil.js
https://jira.ipac.caltech.edu/browse/FIREFLY-1122
- Remove Pin Chart 'Add title' popup.  Use default title.
- The buttons at the bottom of the "Combine Charts" dialog should read "OK" and "Cancel"
- Remove 'Show All Charts' check box.
- Fix cannot plot derived columns.  <-- @lrebull 
Test: https://firefly-1122-spectra-chart-cleanup.irsakudev.ipac.caltech.edu/irsaviewer
Catalogs -> M31, radius=100 -> Search
-> `Pin Chart`  ==> no more popup.  Chart's title defaults to the title of the table.
Then, Add a new column ->  (from table's toolbar, 4th icon from the right)
-> Name: mytest, Expression: ra + 2 -> Add Column
-> `Pin Chart` again  ==> there should be 2 charts in the `Pinned Charts` tab
-> modify pinned chart to plot the new `mytest` column on the x axis
Now, `Combine Chart`  ==>  no …
=> FIREFLY-1122: Spectra Chart cleanup

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/ui/CombineChart.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1097
Test: https://fireflydev.ipac.caltech.edu/firefly-1097-combined-chart-color/firefly
Expected chart behavior:
- New chart start with a set of predefined colors
- Each new trace(data series) is assigned the next color in that set
Pin Chart:
Pinning a chart is basically cloning the current chart and placing it into the Pinned Chart panel. 
Therefore, it should have the exact same color as the current chart.
Combine Chart:
- Start by selecting a chart in the Pinned Chart panel.  This is considered the 'base' chart.  We will keep the color of the traces as is.
- New trace(s) created by this combining process will get the next color from the set of predefined colors.  This is to ensure each trace has a good unique color.
=> FIREFLY-1097: Combined chart color enhancement

src/firefly/js/FFEntryPoint.js, src/firefly/js/Firefly.js, src/firefly/js/core/ClickToAction.js, src/firefly/js/drawingLayers/ImageOutline.js, src/firefly/js/drawingLayers/SearchSelectTool.js, src/firefly/js/ui/ActionsDropDownButton.jsx, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/DefaultSearchActions.js, src/firefly/js/ui/ToolbarButton.css, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/SearchRefinementTool.jsx, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
- added to spatial and table: Search NED and Simbad
- circumscribe polygon
- separators in dropdowns
- change some text as requested in the ticket
- fixed TAP "selection type" to be "selection"
- search area showing after search
- https://firefly-1109-click-to-action.irsakudev.ipac.caltech.edu/irsaviewer
- Try NED and Simbad from click to action
=> Firefly-1109: Updates to Click to Action

src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Fixes [FIREFLY-250](https://jira.ipac.caltech.edu/browse/FIREFLY-250)
Stored target position and size in its own field group, such that all channels: red, green, blue (as well as single and hips as suggested by @robyww) use the same values.
https://fireflydev.ipac.caltech.edu/firefly-250-3color-lock-size/firefly/
Make archive selection in all different channels and ensure that target position and size remains same - changing it in one should change it in others too. Although in hips, size is allowed to be set differently.
=> FIREFLY-250: Lock position and size across RGB for 3 color image

src/firefly/js/ui/CatalogSearchMethodType.jsx
Fixes [FIREFLY-1058](https://jira.ipac.caltech.edu/browse/FIREFLY-1058)
https://fireflydev.ipac.caltech.edu/firefly-1058-sync-polygon-img-search/firefly/
Load a table -> open chart grid view -> select catalog search and check polygon coords for selected chart. Now go back to chart grid view and select another chart -> select catalog search, the polygon coords should have updated.
Also check if other related features work fine or not.
=> FIREFLY-1058: Fix synchronization problem with image outlines in target-panel polygon-search  

src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java, src/firefly/js/charts/ChartUtil.js, src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js, src/firefly/js/ui/tap/ObsCore.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/WavelengthPanel.jsx, src/firefly/js/visualize/RelatedDataUtil.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
- Firefly-1133: Remove MP for mask
- Make layers shown as group
- added better support for obscore config
- Fixed subtype bug
- Fixed: table loading status not showing on second load
- Fixed: fits table reading bug when ZIMAGE header is defined but null
- Fixed: x axis is not reversed in data product guessing case
- test on rubin `data-int`
=> Firefly-1133: lsst issues

src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/WiseFileRetrieve.java
Updates for adding year 10 data in  iwise ui.
=> IRSA-4896 setup for iwise year9-year10.

buildScript/init.gincl, docker/Dockerfile, docker/Dockerfile.dockerignore
=> Add checkoutFirefly to gwt branch

src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/VosiCapabilityRetrieve.java, src/firefly/js/data/ServerParams.js, src/firefly/js/fieldGroup/FieldGroupUtils.js, src/firefly/js/rpc/SearchServicesJson.js, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/DropDownMenu.css, src/firefly/js/ui/SuggestBoxInputField.jsx, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/UploadTableChooser.js, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/Constraints.js, src/firefly/js/ui/tap/ObsCore.jsx, src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableColumnsConstraints.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TableSelectViewPanel.jsx, src/firefly/js/ui/tap/TapKnownServices.js, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- Upload in Spatial panel
- ADQL panel fully supports upload
- columns now in disclosure panel, open by default if now columns found
- improved SuggestionBoxInputField
- improved error checking
- Not yet supported (future tickets): 
- upload from existing (loaded) table 
- making column chooser for uploaded files 
- no "by object id" upload panel
- implemented to support /capabilities: [Firefly-1149](https://jira.ipac.caltech.edu/browse/FIREFLY-1149)
- https://fireflydev.ipac.caltech.edu/firefly-1142-tap-upload/firefly/
- Add a upload file to the spacial panel and search IRSA or CADC
- Try using the Advance ADQL panel
=> Firefly-1142: upload from tap

src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ShaRequestList.js
change to MultiProductViewerContainer.
change wrapper for SHA to send file to analyzer first.
P.S. most of the sha changes are in ife, ife PR merged already.
=> change plot request to url file retrieval.

src/firefly/js/metaConvert/ShaRequestList.js
Fixes [IRSA-5112](https://jira.ipac.caltech.edu/browse/IRSA-5112)
Added condition to set different filename when AOR request.
https://irsa-5112-add-data-prev.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
=> IRSA-5112: Add data preview and download button to advanced search types

docs/release-notes.md, src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/js/ui/PagingBar.jsx, src/firefly/js/visualize/saga/DataProductsWatcher.js, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/MultProductViewerContainer.jsx
Test url:
https://wise-yr9-rel.irsakudev.ipac.caltech.edu/applications/wise
Year9 data will be available for test on March 20. 
Included in the build: a minor change for image view icon tooltip,  requested by [ticket](https://jira.ipac.caltech.edu/browse/IRSA-5111)
also fixes: [Firefly-1182](https://jira.ipac.caltech.edu/browse/FIREFLY-1182)
=> updates for NEOWISE year9 data release

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSListUtil.java, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/HiPSImageSelect.jsx, src/firefly/js/ui/RadioGroupInputFieldView.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.css, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/HiPSListUtil.js, src/firefly/js/visualize/HiPSMocUtil.js, src/firefly/js/visualize/PlotCompleteMonitor.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/draw/Drawer.js, src/firefly/js/visualize/iv/HiPSRenderer.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/saga/MOCWatcher.js, src/firefly/js/visualize/task/CreateTaskUtil.js, src/firefly/js/visualize/task/PlotChangeTask.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- fixed: wrongly adding hips grid to image
- fixed: some cases with accessing undefined values
- fixed: a certain case where the collection table was treated data products table
- changed some labels
- made all MOCs default to same color
- https://firefly-1186-atlas-bugs.irsakudev.ipac.caltech.edu/irsaviewer/collections
- See ticket for fixes
=> firefly-1186: fixes some atlas replacement bugs

src/firefly/js/charts/ui/ColSelectView.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx
- added the ability to allow user to choose upload columns when uploading a table
- **Updates 3/23**
- changed UI to add a link to the columns description to launch the column chooser dialog as requested @robyww 
- changed code to keep ColSelectView simple as discussed with @loitly. if multiSelect is true, send back an array of col names, if it's false, then send back the selected col name as before. 
- testing link updated 
- https://fireflydev.ipac.caltech.edu/firefly-1141-column-chooser/firefly
- go the TAP panel, select source as IRSA or CADC 
- Under constraints, select Spatial Type as "**Multi-Object**"
- Either upload a tbl file or load an existing table
- You should see a new button under "**Position Columns**" titled "**Choose Columns**"
- Click on it to make a selection of …
=> FIREFLY-1141: column chooser popup

src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java
Relates https://github.com/IPAC-SW/irsa-ife/pull/250
- Moved out TableServerRequest to CatalogRequest conversion in its' own method so that it can be overidden by subclasses 
see linked PR, gator query should work
=> IRSA-3145: SHA migration: Added result by IRS Enhanced

src/firefly/js/visualize/rawData/RawDataCache.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/task/ZoomTask.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
[Firefly-1190](https://jira.ipac.caltech.edu/browse/FIREFLY-1190): optimize byte data loading based on zoom
- byte data compression size is based on data size and zoom level
- less compress data is not loaded until the user zooms up.
difficult to test. just review the code
=> Firefly-1190: optimize byte data loading based on zoom

src/firefly/js/tables/TableUtil.js
- https://firefly-1194-date.irsakudev.ipac.caltech.edu/irsaviewer/dce
- test according to the ticket
=> Firefly-1194: fixed date parsing in TableUtil.js

src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/templates/common/ttFeatureWatchers.js, src/firefly/js/templates/fireflyviewer/FireflyViewer.js
This PR is only client side work, it can't be tested until [Firefly-1193](https://jira.ipac.caltech.edu/browse/FIREFLY-1193) is completed
=> Firefly-1192: client side obs core packaging

src/firefly/js/drawingLayers/SelectArea.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/iv/PlotTitle.jsx, src/firefly/js/visualize/rawData/RawDataCache.js, src/firefly/js/visualize/rawData/RawDataCommon.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/ui/CtxToolbarFunctions.js, src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx, src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx, src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
- https://firefly-multi-draw-layers.irsakudev.ipac.caltech.edu/irsaviewer/dce
=> Firefly Multi ticket: fix multiple issues

src/firefly/js/metaConvert/ShaRequestList.js
see related ife [PR](https://github.com/IPAC-SW/irsa-ife/pull/251)
=> IRSA-5181 fix data preview for SSC Enhanced Products and SEIP super mosaics

src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/ui/ToolbarButton.jsx, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/DynamicDef.js, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/ui/CtxToolbarFunctions.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx
- Fixed: download original file and other cleanup
- Fixed: coordinate system changes for hips when the HiPS does not change
- Fixed recenter and 
- Added pin badge
- https://firefly-1209-examples.irsakudev.ipac.caltech.edu/irsaviewer/dce
=> Firefly-1209: polygon examples

src/firefly/html/css/global.css, src/firefly/java/edu/caltech/ipac/table/DataGroupPart.java, src/firefly/js/charts/dataTypes/FireflyGenericData.js, src/firefly/js/charts/dataTypes/FireflySpectrum.js, src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js, src/firefly/js/charts/ui/ChartPanel.css, src/firefly/js/charts/ui/ChartPanel.jsx, src/firefly/js/charts/ui/ChartsContainer.jsx, src/firefly/js/charts/ui/CombineChart.jsx, src/firefly/js/charts/ui/MultiChartToolbar.jsx, src/firefly/js/charts/ui/PinnedChartPanel.jsx, src/firefly/js/charts/ui/PlotlyChartArea.jsx, src/firefly/js/charts/ui/PlotlyToolbar.jsx, src/firefly/js/charts/ui/PlotlyWrapper.jsx, src/firefly/js/charts/ui/options/Errors.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/charts/ui/options/SpectrumOptions.jsx, src/firefly/js/core/background/BackgroundCntlr.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/reducer/TableDataReducer.js, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/visualize/ui/ExtractionDialog.jsx
Work ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1183
Design ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1171
Notable changes:
- thumbnail view for charts while in normal grid mode
- add show/hide errors checkbox
- remove side-by-side view
All items from the tickets were implemented except for a couple noted in `Implementation notes:` of the work ticket.
Test: 
https://fireflydev.ipac.caltech.edu/firefly-1183-spectra-cleanup/firefly
https://firefly-1183-spectra-cleanup.irsakudev.ipac.caltech.edu/irsaviewer
Follow design ticket to ensure all items are fixed.
=> FIREFLY-1183: Combine spectra cleanup

src/firefly/js/templates/common/ttFeatureWatchers.js, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- fixed data products not loading on table tab switches (this was only broken with the Download PR)
- fixed obscore packager default title naming
- https://firefly-1220-anaimate.irsakudev.ipac.caltech.edu/irsaviewer/dce
- _Note_- help is now hooked up.
=> Firefly-1220: animate the side bar

src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java, src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSListUtil.java, src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java, src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/visualize/HiPSListUtil.js, src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/iv/EventLayer.jsx, src/firefly/js/visualize/rawData/RawDataCommon.js, src/firefly/js/visualize/rawData/RawDataOps.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/MultiImageViewerView.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js, src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
- Firefly-1225: fixed: image not rendering in safari 16
- Firefly-1226: fixed, sort of: The data products tab no longer show the wrong table title on the third fetch
- Firefly-1224: fixed chart causing crash
- Added: `helpId` as a prop to TargetHiPSPanel
- Fixed: search refinement tool showing wrong radius on repeated uses
- Fixed: readout only shows on image with mouse on it
- Fixed: Remember TAP services showing
- HiPS fetching optimizations. (see commit for details)
- https://firefly-1225-safari.irsakudev.ipac.caltech.edu/irsaviewer/dce
=> Firefly-1225: fixed: multiple issues

src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ShaRequestList.js
see PR:https://github.com/IPAC-SW/irsa-ife/pull/256 for details
=> IRSA-3146 update for SHA Precovery data view.

src/firefly/js/ui/CatalogSearchMethodType.jsx
- _Note_- There was a race condition so I used `setTimeout`, in the future it would be worth looking at a bigger solution.
- https://firefly-1237-polygon.irsakudev.ipac.caltech.edu/irsaviewer
- test according to the ticket
=> Firefly-1237: fixed

docs/release-notes.md, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
- finishes the work from Firefly-1200. I missed a case
- https://firefly-1238-clear-polygon.irsakudev.ipac.caltech.edu/irsaviewer/dce
- test according to the tickets
=> Firefly 1238:  clear polygon

src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java, src/firefly/js/tables/ui/AddOrUpdateColumn.jsx, src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Request to merge this into 2023.1
=> FIREFLY-1156: better SQL error message for added column failure

src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
Fix "Test WAVE-TAB Algorithm" JS Test.
To test: `gradle fi:jsTest`
=> FIREFLY-987 Hot fix for test

src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
- https://firefly-1243-spaces.irsakudev.ipac.caltech.edu/irsaviewer/dce
-  select msx and cut/paste the example into the search box
- _or_ enter some polygon without spaces after the comma, it should work
=> Firefly-1243: make sure the string conversion has spaces between number

src/firefly/java/edu/caltech/ipac/firefly/server/catquery/SDSSQuery.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/ui/ExtractionDialog.jsx, src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- ZTF:https://firefly-1248-bugs.irsakudev.ipac.caltech.edu/applications/ztf
- FinderChart: https://firefly-1248-bugs.irsakudev.ipac.caltech.edu/applications/finderchart
- see ticket for testing.
=> Firefly-1248 bugs

src/firefly/js/visualize/projection/Wavelength.js
=> FIREFLY-1069 Hotfix for JSDoc failure

src/firefly/html/demo/table-api.html, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.jsx
Fixes [IRSA-5099](https://jira.ipac.caltech.edu/browse/IRSA-5099) - linked PR: https://github.com/IPAC-SW/irsa-ife/pull/258
Most of changes are in TablePanel and child components to make it possible to render a data list (single column table)
- Added option to hide header
- Set cell width differently if single column table
- Added option to set row height dynamically (based on cell content)
https://irsa-5099-abstract-search.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA - do abstract search, resize screen width, the table content will wrap correctly for tablet widths too.
Do other searches to make sure table panel is rendering as it used to before (to test if it's not broken for more than one column)
=> IRSA-5099: SHA migration: Add abstract search

src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java, src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TemportalSearch.jsx
- changed the processing of tap.additional.services to better reflex the config orider
- added hide property to tap.additional.services
- temporal column check
- https://fireflydev.ipac.caltech.edu/firefly-1252-spacial-missing/firefly
- test according to the check
- `tap.additional.services` and temporal column check changes are hard to test outside the Rubin environment
=> Firefly-1252: spacial missing

src/firefly/js/ui/ImageSelect.jsx
Fixes [FIREFLY-1242](https://jira.ipac.caltech.edu/browse/FIREFLY-1242)
- When an image with default colors is selected, and filters are present in that color, sets those same filters in other colors' filter field groups too.
- Made sure that this filter field value gets read in initial value
https://firefly-1242-3color-default-filters.irsakudev.ipac.caltech.edu/irsaviewer/
Select "3 color composite" -> red channel -> apply mission filter: wise, project filter: all-sky -> select W4 in "WISE ALLWISE Atlas" -> switch to green channel, filters should be preserved and W2 should be automatically selected; switch to blue channel, filters should be preserved and W1 should be selected.
Similarly you can try filtering 2MASS and then test on "2MASS all sky" (where we have default colors available).
=> FIREFLY-1242: Preserve filters when 3 color default selection is made

src/firefly/js/charts/ui/PlotlyToolbar.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1255
Added a null condition check to avoid uncaught exception.
Test: https://fireflydev.ipac.caltech.edu/firefly-1255-heatmap-failed/firefly/
- IRSA Catalogs -> WISE -> m31, 2000 arcsec
- Charts -> Add New Chart -> Heatmap -> x: ra, y: dec
=> FIREFLY-1255: heatmap failed due to uncaught exception

src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- The goal of this ticket is to get rid of StarTable as the intermediary step when converting a table from a FITS file to a DataGroup one. We can use hdu/TableHDU directly to create a DataGroup object. 
- The most important new methods are `readFitsTable` (to convert table to a DataGroup object), `addRowToDG`. and `convertHDUToDataType`. <s>I have sill kept calls to `getStarTable` and `convertStarTableToDataGroup` for testing purposes. I can remove that code when I convert this into a PR.</s> StarTable code is now all commented out (will be removed in PR). 
- The test build below is ready and stable and should yield expected results (same as on ops when you upload a FITs file and select and load table entries)
- Some of these changes are based on the `FitsStarTable` class from the …
=> FIREFLY-1232: Remove StarTable from FITS Table Reader 

src/firefly/js/api/webApiCommands/DatalinkUICommands.js, src/firefly/js/metaConvert/ObsCoreConverter.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/TargetFeedback.jsx, src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/DynamicDef.js, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/ui/CoveraeViewer.jsx
- support SSA
- spectrum results
- no build yet
=> Firefly 1250 concurrent

docs/new-release-procedure.md, docs/release-page-template.md
Made minor updates to the release procedure doc based on what I observed when following it.
=> Update release procedure docs

src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- Make some simple changes to optimize read very large fits table.
- https://fireflydev.ipac.caltech.edu/firefly-1263-optimize-fits-table-read/firefly
- read a large fits table
=> Firefly-1263: optimize fits table read

src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/converterUtils.js, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/ui/DrawLayerPanelView.jsx, src/firefly/js/visualize/ui/MouseReadout.css, src/firefly/js/visualize/ui/MouseReadout.jsx, src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
- fixed: Overlapping fields in readout display area
- fixed: Mask overlay on incompatible images
- fix client side data analyzer table loading
- https://fireflydev.ipac.caltech.edu/firefly-1276-readout/firefly
- test according to tickets
=> Firefly-1276,Firefly-1277

src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonStringProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1260
Cleanup code.  Updated QueryMOS.
- also, fixed a bug where the database file exists but, there's no data in it this may be caused by a bad tomcat shutdown.
More changes and test URL here: https://github.com/IPAC-SW/irsa-ife/pull/268
=> FIREFLY-1260: Remove multiple copies of QueryMOS

src/firefly/js/visualize/saga/DataProductsWatcher.js
Fixes [IRSA-5359](https://jira.ipac.caltech.edu/browse/IRSA-5359)
This bug also exists in Wise, ZTF, Sofia, besides SHA
SHA: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
Sofia: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/sofia/
Wise: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/wise
ZTF: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/ztf
Firefly: https://fireflydev.ipac.caltech.edu/irsa-5359-dataproductsviewer-fix/firefly
=> IRSA-5359: Fix Data Product Viewer not updating on changing table tabs for the 1st time

src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.css, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/util/VOAnalyzer.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/VisualSearchUtils.js
[Firefly-1286](https://jira.ipac.caltech.edu/browse/FIREFLY-1286): DCE and search features 
- Support Create EmbeddedPositionSearchPanel - the is the panel we will use for Euclid and SpearX
- Support SSA coord_obs
Testing:
- https://firefly-1286-dce.irsakudev.ipac.caltech.edu/irsaviewer/dce
- Choose IRS and do a search
- The coverage should work
- https://fireflydev.ipac.caltech.edu/firefly-1286-dce/firefly/firefly-dev.html
- look at the `Test Searches` tab and then `Inset Example`
- https://fireflydev.ipac.caltech.edu/firefly-1286-dce/firefly/
- you can also test coord_obs on firefly with the following vo table I will include on slack
-
=> Firefly-1286: DCE and search features

src/firefly/js/metaConvert/ObsCoreConverter.js, src/firefly/js/visualize/ui/VisualSearchUtils.js
- https://firefly-1291-search-target.irsakudev.ipac.caltech.edu/irsaviewer/dce
- do a DCE search, the overlay position should be the search target
=> Firefly-1291: obscore data products result should show search target

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/ZtfIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/ztf/ZtfRefimsFileRetrieve.java, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/ZtfRequestList.js, src/firefly/js/templates/lightcurve/ztf/IbeZTFPlotRequests.js
[View Jira ticket](https://jira.ipac.caltech.edu/browse/IRSA-5046)
1. Add ztf deep reference image in the data products.
2. Make grid view default for moving target search
[View ife PR for test info](https://github.com/IPAC-SW/irsa-ife/pull/284)
=> IRSA-5046 Add ztf deep reference image in the data products.

src/firefly/js/ui/tap/TimeRangePanel.jsx
View test instruction in IFE PR:
https://github.com/IPAC-SW/irsa-ife/pull/287
=> Irsa 5396 make timerange examples

docs/release-notes.md, src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/iv/HiPSRenderer.js, src/firefly/js/visualize/iv/HiPSTileDrawer.js
- https://fireflydev.ipac.caltech.edu/firefly-1311-hips-smoothing/firefly
- zoom all the way into a hips images. The lowest level should be blocky
=> Firefly-1311: fixed: hips tile should not be smoothed at highest resolution

src/firefly/js/drawingLayers/HiPSGrid.js, src/firefly/js/visualize/HiPSUtil.js, src/firefly/js/visualize/iv/HiPSCellFinder.js, src/firefly/js/visualize/iv/HiPSSingleTileRender.js, src/firefly/js/visualize/iv/HiPSTileDrawer.js, src/firefly/js/visualize/task/PlotHipsTask.js
- Also: cleaned up rendering a little more on deep zoom
- https://fireflydev.ipac.caltech.edu/firefly-1313-hips-missing/firefly
=> Firefly-1313: fixed HiPS missing tiles on deep zoom

src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- https://firefly-1338-dce-race.irsakudev.ipac.caltech.edu/
- Do a radar search and then, send to DCE
=> Firefly-1338: Fixed: dce search race condition when launched via API

docs/release-notes.md
Perhaps you can add this when you add 2023.2.5 to the release notes?
=> Correct ticket (JOIN support) in release notes to FIREFLY-1257

src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/ui/ValidationField.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/visualize/WebPlotRequest.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx, src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- [Firefly-1336](https://jira.ipac.caltech.edu/browse/FIREFLY-1336) : fixed
- bug fix: regression: dynamic field building not recognizing radius
- https://firefly-1346-image-row-viewer.irsakudev.ipac.caltech.edu/applications/spherex
=> Firefly-1346: Image Table Row Viewer

src/firefly/js/core/AppDataCntlr.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/visualize/ui/VisualSearchUtils.js
- add datatype hint when we know it is spectrum
- https://firefly-1196-pos-selection.irsakudev.ipac.caltech.edu/irsaviewer/dce
=> Firefly-1196: fixed

src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java, src/firefly/java/edu/caltech/ipac/table/io/FITSExtractToTable.java, src/firefly/js/visualize/ui/ExtractionDialog.jsx, src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- https://fireflydev.ipac.caltech.edu/firefly-871-wl/firefly 
- upload wl.fits
- extract line or points
- save to table
- there should be a column for wavelength
- [wl.fits.zip](https://github.com/Caltech-IPAC/firefly/files/13430210/wl.fits.zip)
=> Firefly-871: Add wavelength to "line extract" and "pick points" tools

src/firefly/java/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessor.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/js/tables/TableRequestUtil.js, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/templates/common/ttFeatureWatchers.js, src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
https://jira.ipac.caltech.edu/browse/FIREFLY-1318
Show link to dataset's documentation page in DCE result table.
Test: https://firefly-1318-dce-doclink-in-result.irsakudev.ipac.caltech.edu/irsaviewer/dce
Test with one table as well as multiple tables.
Should also test to see when there's more than one docrows.  (I don't know of a dataset that do).
=> FIREFLY-1318: Add documentation link to DCE result table

src/firefly/js/drawingLayers/HiPSMOCUI.jsx, src/firefly/js/ui/dynamic/ServiceDefTools.js
- [Firefly-1335](https://jira.ipac.caltech.edu/browse/FIREFLY-1335): DCE: sort results 
- [Firefly-1321](https://jira.ipac.caltech.edu/browse/FIREFLY-1321): DCE: hide/show columns
- [Firefly-1361](https://jira.ipac.caltech.edu/browse/FIREFLY-1361): DCE: layers doesn't work on DCE search screen
- https://firefly-1335.irsakudev.ipac.caltech.edu/irsaviewer/dce
- test according to the ticket
- testing dependent on backup dev being updated
=> Firefly Multi ticket: Firefly-1335,Firefly-1321,Firefly-1361

docs/release-notes.md
Fix several ticket numbers that had typos; make formatting more consistent.
=> Fix typos in 2023.3.0 release notes; add 2023.3.1

docs/older-release-notes-2022.md
FIREFLY-968 was the correct ticket reference.
=> Correct ticket reference for Aitoff HiPS projection implementation

src/firefly/js/core/AppDataReducers.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/rpc/CoreServices.js, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/FetchDatalinkTable.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Some changes in order to fix issues found in [FIREFLY-1332](https://jira.ipac.caltech.edu/browse/FIREFLY-1332).
Testing URL: https://firefly-1332-file-upload-bugs.irsakudev.ipac.caltech.edu/irsaviewer
I didn't split changes in several commits per bug so here are some comments about code changes related to found bugs.
Bug 1: this was fixed pretty much by these changes:
https://github.com/Caltech-IPAC/firefly/compare/FIREFLY-1332-file-upload-bugs?expand=1#diff-52137344cb10bca3632e78c1c63a321e058b83573ae7b82663e0dcbbd927bfc6R337
and
https://github.com/Caltech-IPAC/firefly/compare/FIREFLY-1332-file-upload-bugs?expand=1#diff-52137344cb10bca3632e78c1c63a321e058b83573ae7b82663e0dcbbd927bfc6R358
Bug 2: this was fixed by:
https://github.com/Caltech-IPAC/firefly/compare/FIREFLY-1332-file-upload-bugs …
=> several bug fixes, see FIREFLY-1332

src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/WiseFileRetrieve.java
View [Jira ticket](https://jira.ipac.caltech.edu/browse/IRSA-5719).
iWISE UI is updated with the ongoing year11 incoming data.
Dev build is ready, will wait for the new load of year 11 data for testing.
https://irsa-5719-iwise.irsakudev.ipac.caltech.edu/applications/iwise
Related [IFE PR](https://github.com/IPAC-SW/irsa-ife/pull/302)
=> IRSA-5719 update iWISE for year11

src/firefly/js/api/ApiExpandedView.jsx, src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/ui/DropDownMenu.jsx, src/firefly/js/ui/DropDownToolbarButton.jsx, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/FileUploadDropdown.jsx, src/firefly/js/ui/ImageSelect.jsx, src/firefly/js/ui/TargetFeedback.jsx, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/ToolbarButton.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/ui/ApiExpandedDisplay.jsx, src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx, src/firefly/js/visualize/ui/ApiToolbarImageDisplay.jsx, src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/ColorTableDropDownView.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/FitsHeaderView.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx, src/firefly/js/visualize/ui/MatchLockDropDown.jsx, src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx, src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx, src/firefly/js/visualize/ui/TriViewImageSection.jsx, src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- Converted ApiExpandedView and made a fucntional component
- Converted other image js api related components
- Fixed TargetPanel jumping/resizing issues
- Added more mui icons in image toolbar
- fixed Toolbar button issues with handling some cases
- https://fireflydev.ipac.caltech.edu/firefly-1397-jsapi/firefly/test/
- test expanded view looks correct
- https://fireflydev.ipac.caltech.edu/firefly-1397-jsapi/firefly
- do a search and look at image icons
=> FIREFLY-1397: some js api conversion to Joy UI

src/firefly/js/api/ApiBuild.js, src/firefly/js/api/ApiUtilChart.jsx, src/firefly/js/api/ApiUtilTable.jsx
- Added all exported functions and constants from TableUtil and TableRequestUtil
- Added all exported functions and constants from ChartUtil and selected functions from ChartCntlr
Test: https://fireflydev.ipac.caltech.edu/firefly-1398-api-more-util-func/firefly/test/tests-chart.html
Bring up Chrome DevTools, then inspect firefly.util.table and firefly.util.chart.
=> FIREFLY-1398: Export additional functions to JS API

src/firefly/html/css/global.css, src/firefly/js/charts/ui/ChartPanel.jsx, src/firefly/js/charts/ui/ChartSelectPanel.jsx, src/firefly/js/charts/ui/ChartsContainer.jsx, src/firefly/js/charts/ui/MultiChartViewer.jsx, src/firefly/js/charts/ui/PinnedChartContainer.jsx, src/firefly/js/charts/ui/PlotlyToolbar.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/ui/AddOrUpdateColumn.jsx, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/tables/ui/TablePanel.css, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/ui/ActionsDropDownButton.jsx, src/firefly/js/ui/InputField.jsx, src/firefly/js/ui/InputFieldView.jsx, src/firefly/js/visualize/ui/Buttons.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1408
Only the listed bug reports were fixed.  Will rollover the unfinished work to another ticket.
Bug report fixed: https://confluence.ipac.caltech.edu/display/IRSA/Testing+Feb+2024+-+Joy+UI%2C+mostly
21, 36, 38, 39, 40, 41, 42, 45, 47, 49, 50
Notes on specific item:
39: Not exactly sure what this is asking for.  I added a border to Chart’s toolbar.  Is that what you want?
41: IRSA TAP returns columns with a `width` attribute.  Firefly respects this value.  However, this may result in some columns being rendered too narrow for their content.
45: Implemented to retain the previous behavior but with the JoyUI look.
47: Fixed all except for the exact position of the tooltip.  This is generic code.  May need to rethink.
Test: …
=> FIREFLY-1408: JoyUI reported bugs

src/firefly/js/ui/ImageSelect.css, src/firefly/js/ui/ImageSelect.jsx, src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1410
Test: https://fireflydev.ipac.caltech.edu/firefly-1410-image-search-4/firefly/
See changes made to section 4 of the Image Search Panel.
When text overflow, a '...' will appear.  Tooltip will still display the full text.
=> FIREFLY-1410: Clean and compress section 4 of image seach panel

src/firefly/js/api/ApiUtil.js, src/firefly/js/charts/ui/MultiChartToolbar.jsx, src/firefly/js/charts/ui/PlotlyToolbar.jsx, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/templates/fireflyviewer/LayoutChoice.jsx, src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/DropDownToolbarButton.jsx, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/ui/DrawLayerItemView.jsx, src/firefly/js/visualize/ui/ExtraIpacSearches.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
response to doc: https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199
- https://firefly-1421-many-fixes.irsakudev.ipac.caltech.edu/irsaviewer/
=> Firefly-1421: fixed multiple issues

src/firefly/js/tables/ui/TableSave.jsx, src/firefly/js/ui/DownloadOptionsDialog.jsx, src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/ui/WorkspaceViewer.jsx
Convert Firefly workspace viewer.
Go to [Test Url](https://firefly-1400.irsakudev.ipac.caltech.edu/irsaviewer):
1. login into irsadev first
2. from irsaviewer landing page do an image search and/or catalog search, select from image/table toolbar choose `Save Image` or `Save Table`, then select File location "Workspace"
3. from irsaviewer landing page select Upload tab and Upload from workspace, click "Choose Workspace File", inspect the "Read file from workspace" popup panel
=> Firefly 1400 convert workspaceviewer

src/firefly/js/core/LayoutCntlr.js, src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/drawingLayers/SearchTarget.js, src/firefly/js/ui/AppConfigDrawer.jsx, src/firefly/js/ui/InputFieldView.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/SizeInputField.jsx, src/firefly/js/ui/ToolbarButton.jsx, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- Irsa testing round 2: 8, 30, 45
- Rubin - Landing page: 2,4,5,7,8,9,10,11,12 - Table Component: 1
- https://firefly-1422-ui-rubin-irsa.irsakudev.ipac.caltech.edu/irsaviewer/
IRSA testing round 2
https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199
Rubin Landing page, etc
https://confluence.lsstcorp.org/pages/viewpage.action?pageId=250480825
=> FIREFLY-1422-ui-rubin-irsa: Multiple fixes from IRSA and Rubin testing

src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-5873
see https://github.com/IPAC-SW/irsa-ife/pull/309
=> IRSA-5873: Create SpherexForcedPhot processor

src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/MaskEval.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java, src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/js/metaConvert/vo/ObsCoreConverter.js, src/firefly/js/visualize/RelatedDataUtil.js, src/firefly/js/visualize/WebPlot.js, src/firefly/js/visualize/task/CreateTaskUtil.js, src/firefly/js/visualize/ui/DrawLayerPanelView.jsx, src/firefly/js/voAnalyzer/TableAnalysis.js
- [Firefly-1404](https://jira.ipac.caltech.edu/browse/FIREFLY-1404): multiple mask layer fixes, support more then one layer
- [Firefly-1428](https://jira.ipac.caltech.edu/browse/FIREFLY-1428): upload- better compress image feedback - znaxis
- [Firefly-1432](https://jira.ipac.caltech.edu/browse/FIREFLY-1432): messages for data-rights limitations
- https://fireflydev.ipac.caltech.edu/firefly-1404-plus-others/firefly
- [Firefly-1404](https://jira.ipac.caltech.edu/browse/FIREFLY-1404): Test using the FITS file with the mask in ticket
- [Firefly-1428](https://jira.ipac.caltech.edu/browse/FIREFLY-1428): Test by uploading the FITS file in ticket, look at the second HDU
- [Firefly-1432](https://jira.ipac.caltech.edu/browse/FIREFLY-1432): Test by using ADQL in ticket
=> Firefly-1404: multiple mask layer fix and other tickets

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java
Updates for NEOWISE year 10 data release
=> IRSA-5732 UI update for WISE year10 data release

src/firefly/js/charts/ui/ColumnOrExpression.jsx, src/firefly/js/charts/ui/CombineChart.jsx, src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/charts/ui/options/Errors.jsx, src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx, src/firefly/js/charts/ui/options/HeatmapOptions.jsx, src/firefly/js/charts/ui/options/NewTracePanel.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/charts/ui/options/SpectrumOptions.jsx, src/firefly/js/ui/AutoCompleteInput.jsx, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/CloseButton.jsx, src/firefly/js/ui/SwitchInputField.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx, src/firefly/js/visualize/ui/MultiItemViewerView.jsx
Fixes [FIREFLY-1401](https://jira.ipac.caltech.edu/browse/FIREFLY-1401) (mostly)
- Removed `type=switch` from CheckboxGroupInputField because it was buggy and switch is meant to be used as singleton (not in group)
- Created SwitchInputField to have a field group connected Joy-UI switch with tooltip and labels and used it in Error and other places using CheckboxGroupInputField type=switch
- Fixed wrong usage of switch in TAP panel and Edit ADQL
- Fixed bug in heatmap options colorscale field
- Used CollapsiblePanelGroup to group Chart and Trace options's collapsibles in different chart modes
- Converted ImageTableRowViewer to joyUI
- Fixed rubin chart#3  bug
Firefly: https://fireflydev.ipac.caltech.edu/firefly-1401-improve-chat-opts/firefly/
SphereX: …
=> FIREFLY-1401: UI Conversion: Improve chart options panel

src/firefly/html/test/test-coverage.html, src/firefly/js/tables/TableUtil.js, src/firefly/js/templates/fireflyslate/FireflySlate.jsx, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/ToolbarButton.jsx
- fixed: triview not checking store initLoadCompleted in api loads
- fixed: `TableUtil.js` not checking for bigint before calling isNan
- fixed: test had wrong naif id 2000002 instead of 20000002
- https://fireflydev.ipac.caltech.edu/firefly-1439-regression/firefly/test/tests-viewer.html
- load the hips or a table
- https://fireflydev.ipac.caltech.edu/firefly-1439-regression/firefly/test/test-coverage.html?test=MOST+Orbital+path+of+Pallas
- should load
=> Firefly-1439: fix regression issues

buildScript/tasks.gincl, src/firefly/js/core/AppDataReducers.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/core/core-typedefs.jsdoc, src/firefly/js/templates/hydra/HydraViewer.jsx, src/firefly/js/templates/router/RouteHelper.jsx, src/firefly/js/templates/router/RoutedApp.jsx, src/firefly/js/ui/App.jsx, src/firefly/js/ui/AppConfigDrawer.jsx, src/firefly/js/ui/Banner.jsx, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/SearchPanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1436
More changes here: https://github.com/IPAC-SW/irsa-ife/pull/312
- Add path support to Menu and SideBar
- Add multiple result paths
- Cleanup and add more documentation to RoutedApp
Used Euclid as an example.  
- No longer using SearchPanel
- Searches are defined as MenuItems
- Redefined paths with clear rendering components
- Added LandingPage
Should work like it suppose to.  Search will submit results to `Resutls` tab.  
Switch tabs to see path changes accordingly.  Backward and forward should work reasonably as well.
TODOs:
- Cleanup Spherex
- Add support for api mode
Tests:
https://fireflydev.ipac.caltech.edu/firefly-1436-routed-apps-joyui/firefly/
https://firefly-1436-routed-apps-joyui.irsakudev.ipac.caltech.edu/applications/euclid/ …
=> FIREFLY-1436: Route-based apps with the new Menu/SideBar features.

src/firefly/js/core/background/BackgroundUtil.js, src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-1447
As title suggested, table model were not updated when a background fetch failed.
To test, use this ADQL in TAP search
```sql
SELECT * FROM allwise_p3as_psd WHERE designation in ("J053432.33+220010.6","J053435.34+220146.0","J053434.31+220007.8")
```
Test: https://fireflydev.ipac.caltech.edu/firefly-1447-isfetching-onerror/firefly/
=> FIREFLY-1447: Table model isFetching failed to unset when background job failed

src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/CheckboxGroupInputField.jsx, src/firefly/js/ui/ListBoxInputField.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/RadioGroupInputField.jsx, src/firefly/js/ui/RadioGroupInputFieldView.jsx, src/firefly/js/ui/SwitchInputField.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx, src/firefly/js/ui/tap/Constraints.js, src/firefly/js/ui/tap/ObjectIDSearch.jsx, src/firefly/js/ui/tap/TableChooser.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/ExtraIpacSearches.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx, src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx, src/firefly/js/visualize/ui/MatchLockDropDown.jsx, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- [Firefly-1450](https://jira.ipac.caltech.edu/browse/FIREFLY-1450): object id search using select...in
- from: https://confluence.ipac.caltech.edu/pages/viewpage.action?spaceKey=IRSA&title=Testing+April+2024
- fix: 3
- fix: 4
- fix: 11
- fix: 12- tap: clicking twice on the tables menu for it to work
- fix: 13
- fix: 20 - 1 & 2
- fix: 21
@kpuriIpac :
-  the object Id feature is in `ObjectIDSearch.jsx` and small changes in `ColumnConstrainsPanel.jsx`, `Constraints.jsx`, `TapSearchRootPanel.jsx`
- the rest is just label changes and small bug fixes
- https://firefly-1450-object-id.irsakudev.ipac.caltech.edu/irsaviewer
- test select...in query
- test fixes
=> Firefly-1450: Multi fixes and object id feature

src/firefly/js/ui/WorkspaceSelectPane.jsx
Set File location option in download option panel to horizontal. 
To test in the dev build:
https://irsa-5895-ztf.irsakudev.ipac.caltech.edu/applications/ztf
Do a position search and try `Prepare Download` in the result page.
=> IRSA-5895 ZTF JoyUI conversion

src/firefly/js/ui/ColorPicker.jsx, src/firefly/js/ui/FitsDownloadDialog.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/PlotViewUtil.js, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/iv/ImageExpandedMode.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/ui/ColorTableDropDownView.jsx, src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx, src/firefly/js/visualize/ui/MultiItemViewerView.jsx
- Feature: scroll images - only available in expanded mode
- 26 - image highlighting
- 27 - save dialog sizing
- 28 - image filtering
- 29 - color lock icon updating
- 30 - color and overlays text
- 31 - color picker width
- https://firefly-1453-bugs.irsakudev.ipac.caltech.edu/irsaviewer/
- load many images into firefly and on toolbar click `Scroll images`
- test bugs: according to https://confluence.ipac.caltech.edu/display/IRSA/Testing+April+2024
=> Firefly-1453: fixes

src/firefly/js/templates/fireflyviewer/LandingPage.jsx, src/firefly/js/ui/AppConfigDrawer.jsx, src/firefly/js/ui/Menu.jsx
- updated according to the ticket
- irsa-ife PR: https://github.com/IPAC-SW/irsa-ife/pull/316
- https://firefly-1454-wording.irsakudev.ipac.caltech.edu/irsaviewer
- https://firefly-1454-wording.irsakudev.ipac.caltech.edu/irsaviewer/dce
- test according to the ticket
=> Firefly-1454: update landing page and menu

src/firefly/js/charts/ui/PlotlyChartArea.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/FireflyRoot.jsx, src/firefly/js/ui/JoyToMUIThemeWrapper.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx, src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
As part of this ticket: https://jira.ipac.caltech.edu/browse/IRSA-5926
- support dark/light mode changes
More changes here: https://github.com/IPAC-SW/irsa-ife/pull/317
Test: https://fireflydev.ipac.caltech.edu/irsa-5926-spherex-joyui/firefly/
=> IRSA-5926: Convert PlotlyChartArea into a functional component

docker/cleanup.sh, src/firefly/java/edu/caltech/ipac/firefly/server/ExternalTaskHandlerImpl.java, src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/GatorQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java, src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryIBE.java, src/firefly/java/edu/caltech/ipac/firefly/server/persistence/QueryVOTABLE.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/DataAccessException.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/ConcurrentSearchUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/WorkdspaceImageFileRetriever.java, src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java, src/firefly/js/core/JsonUtils.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/tables/reducer/TableDataReducer.js, src/firefly/js/tables/ui/AddOrUpdateColumn.jsx, src/firefly/js/tables/ui/TablePanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1445
Moved 'upload' to policy-managed directories with a set time of 1 day from last access. 
Also, use access time for the configurable directories rather than modification date.
Test: https://firefly-1445-upload-cleanup-tweak.irsakudev.ipac.caltech.edu/irsaviewer/
Instead of having @lrebull test this, I suggest we merge after a code review.  This is a minor adjustment and should not cause any undesirable operational issues.  She can submit new tickets if the problems persist.
=> FIREFLY-1445: adjust cleanup script to keep upload files for 1 day

src/firefly/js/core/AppDataReducers.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/visualize/MenuItemKeys.js
- [Firefly-1458](https://jira.ipac.caltech.edu/browse/FIREFLY-1458): fixed: crash when simbad search fails, reason: formatting error message
- https://firefly-1457-appoptions.irsakudev.ipac.caltech.edu
- do a search off of the main page
- menubar should be correct
- https://firefly-1457-appoptions.irsakudev.ipac.caltech.edu/irsaviewer
- try simbad on a point that fails
=> Firefly-1457, Firefly-1458: fixes

config/app.config, src/firefly/js/FFEntryPoint.js, src/firefly/js/api/webApiCommands/DatalinkUICommands.js, src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/FileUploadProcessor.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DLuiDecoration.jsx, src/firefly/js/ui/dynamic/DLuiRootSearchPanel.jsx, src/firefly/js/ui/dynamic/FetchDatalinkTable.js, src/firefly/js/visualize/iv/ImageViewer.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/ui/MultiImageViewer.jsx, src/firefly/js/visualize/ui/MultiImageViewerView.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/TargetHipsPanelToolbar.jsx, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- generalize for multiple projects
- clean up
- refactored parts into 3 files
- fixed upload panel issues when loading a datalink file directly into app
- fixed the url api for generic firefly app
- cleaned up TargetHipsPanel to use an embeded primary toolbar
-  https://firefly-1456-dl-panel.irsakudev.ipac.caltech.edu/irsaviewer/dce
- use DCE
- only obvious UI change - DCE hips toolbar
=> Firefly-1456: generalize and clean up DLGeneratedDropDown.js

src/firefly/js/templates/hydra/HydraViewer.jsx, src/firefly/js/visualize/ui/Buttons.jsx
**[IRSA-5960](https://jira.ipac.caltech.edu/browse/IRSA-5960)**: 
- IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/314
**Testing**: 
- Finder Chart: https://irsa-5960-finderchart-final-cleanup.irsakudev.ipac.caltech.edu/applications/finderchart
- do a search and see the toolbar icons, and notice the new PDF icon
=> IRSA-5960: Added PDF icon for use in FinderChart 

src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java, src/firefly/java/edu/caltech/ipac/table/ResourceInfo.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java, src/firefly/js/core/background/JobInfo.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/tables-typedefs.jsdoc, src/firefly/js/tables/ui/AddOrUpdateColumn.jsx, src/firefly/js/tables/ui/TableInfo.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/tables/ui/TablesContainer.jsx, src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx, src/firefly/js/ui/panel/TabPanel.jsx
The INFO tags inside the RESOURCE were not populated, which is why the overflowed TAP results were not marked. This was an oversight on my part. Please test again.
https://fireflydev.ipac.caltech.edu/firefly-1396-votable-overflow/firefly/
=> FIREFLY-1396: Display TAP overflow indicator when present in VOTable

src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java, src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliQuery.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/DaliUtil.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java, src/firefly/test/edu/caltech/ipac/firefly/server/query/AsyncTapQueryTest.java, src/firefly/test/edu/caltech/ipac/firefly/server/query/DaliUtilTest.java
- create base class DaliQuery to search DAL services
- update UwsProcessor and AsyncTapQuery to make use of these functions
Mostly new code with some unit testing.  I ran test and it passed.  I built SHEREx for regression testing.
https://firefly-1459-dali-processor.irsakudev.ipac.caltech.edu/applications/spherex/
- Spectrophotometry Tool first so the results tab is populated
- Then, try TAP upload to ensure it's still working
=> FIREFLY-1459: Create DALI utility functions to support standard parameters like UPLOAD and MAX_REC.

src/firefly/js/charts/ui/ChartSelectPanel.jsx, src/firefly/js/core/core-typedefs.jsdoc, src/firefly/js/templates/lightcurve/LcViewer.jsx, src/firefly/js/ui/CompleteButton.jsx, src/firefly/js/ui/DownloadDialog.jsx, src/firefly/js/ui/FileUploadDropdown.jsx, src/firefly/js/ui/FormPanel.jsx, src/firefly/js/ui/HiPSImageSelect.jsx, src/firefly/js/ui/ScriptDownloadDialog.jsx, src/firefly/js/ui/SearchPanel.jsx, src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/ui/TestQueriesPanel.jsx, src/firefly/js/ui/TestSearchPanel.jsx, src/firefly/js/ui/UploadTableChooser.js, src/firefly/js/ui/UploadTableSelector.jsx, src/firefly/js/ui/WorkspaceDropdown.jsx, src/firefly/js/ui/dynamic/DLuiRootSearchPanel.jsx, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/ObjectIDSearch.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/ExtraIpacSearches.jsx, src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx, src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1461
- Document the usage of this component
- Perform minor cleanup of CompleteButton
- Fix all usage of FormPanel to comply with new api
More changes here: https://github.com/IPAC-SW/irsa-ife/pull/321
See src/firefly/js/ui/FormPanel.jsx for changes made.  
Because there were lots of changes throughout, please help with regression testing.
Especially Upload, DynamicUI*, and DCE related usages.
Tests:
https://fireflydev.ipac.caltech.edu/firefly-1461-refactor-formpanel/firefly/
https://firefly-1461-refactor-formpanel.irsakudev.ipac.caltech.edu/
- irsaviewer/dce/timeseries/gator
- [finderchart](https://firefly-1461-refactor-formpanel.irsakudev.ipac.caltech.edu/applications/finderchart/)
- …
=> FIREFLY-1461: Refactor FormPanel and introduce slots

src/firefly/js/FFEntryPoint.js, src/firefly/js/ui/Banner.jsx, src/firefly/js/ui/Menu.jsx
- firefy: https://fireflydev.ipac.caltech.edu/firefly-1472-menu-large-font/firefly
- IrsaViewer: https://firefly-1472-menu-large-font.irsakudev.ipac.caltech.edu/irsaviewer
- using chrome, set preferences -> Appearance -> Font Size: set to `Large` or `Very Large`
- Looks at ops to see the problem: https://irsa.ipac.caltech.edu/irsaviewer/
- Menu bar should grow and shrink correctly
=> Firefly-1472: bug fix: menu should adjust with browser set fonts sizes

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/js/metaConvert/missions/WiseRequestList.js
Related tickets: [IRSA-4874](https://jira.ipac.caltech.edu/browse/IRSA-4874), [IRSA-5079](https://jira.ipac.caltech.edu/browse/IRSA-5079)
test build:
https://irsa-4874-5079-wise-bug-fix.irsakudev.ipac.caltech.edu/applications/wise
Please use the example in the ticket as test cases.
=> WISE bug fixes

src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- https://fireflydev.ipac.caltech.edu/firefly-1476-compression/firefly/
=> Firefly-1476: fixes: readout bug with compressed files

src/firefly/js/api/ApiHighlevelBuild.js, src/firefly/js/charts/ui/ChartsContainer.jsx, src/firefly/js/charts/ui/MultiChartToolbar.jsx, src/firefly/js/charts/ui/MultiChartViewer.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableChooser.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/ui/ApiFullImageDisplay.jsx, src/firefly/js/visualize/ui/ApiToolbarImageDisplay.jsx
- also - support noirlab's old version of tap
- API mode: bug fix: chart toolbar background now consistent with images and tables (variant: soft)
- https://fireflydev.ipac.caltech.edu/firefly-1478-3-4-6-7/firefly
- test according to ticket  3,4,6,7
- helpful notes
- choose IRSA - spitzer - popup the tables
- choose Gaia - gaiadr3 - popup the tables
=> Firefly-1478: fixes items: 3,4,6,7

src/firefly/js/metaConvert/DefaultConverter.js, src/firefly/js/ui/DefaultSearchActions.js, src/firefly/js/ui/UploadTableChooser.js, src/firefly/js/ui/UploadTableSelector.jsx
- Also fixed: second bug not in ticket: referencing a loaded table in upload should not add it again to the tables
- https://fireflydev.ipac.caltech.edu/firefly-1486-upload/firefly
=> Firefly-1486: Don't include hidden columns in column count

src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/ImagePager.jsx, src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
- https://firefly-1488-grid-icons.irsakudev.ipac.caltech.edu/applications/wise
- test according to ticket and notice new 3 color icons
=> Firefly-1488: grid icons cleanup and alignment

src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IbeFileRetrieve.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/ibe/IbeQueryArtifact.java, src/firefly/js/metaConvert/missions/WiseRequestList.js
View [Ticket](https://irsa-5500-wise.irsakudev.ipac.caltech.edu/applications/wise/).
To test:
https://irsa-5500-wise.irsakudev.ipac.caltech.edu/applications/wise/
open Scan ID search panel, using the example scan id, view image display layers by click the layer icon on the image display panel.
related  [Ife PR](https://github.com/IPAC-SW/irsa-ife/pull/328)
=> Irsa 5500 fix missing artifacts layer on wise scanid search result

src/firefly/js/core/background/BackgroundMonitor.jsx, src/firefly/js/drawingLayers/SearchSelectTool.js, src/firefly/js/ui/DownloadDialog.jsx, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
- https://firefly-1498-polygon.irsakudev.ipac.caltech.edu/irsaviewer/dce
- test according to ticket
=> Firefly-1498: fixed: polygon does not default on first click

src/firefly/js/templates/router/RouteHelper.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-5492
IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/326
- Keeping this firefly PR open for any other firefly changes that need to be made to accomodate the IFE Euclid PR (these firefly changes don't need to go into RC in my opinion) 
- this change allows Region Explorer to determine search type and customize additional search options (IBESearchType) when the `searchType === Polygon `
Test builds in the [IFE PR](https://github.com/IPAC-SW/irsa-ife/pull/326).
=> IRSA-5492: Cleanup and work related to current Euclid IFE ticket

src/firefly/js/charts/ui/PlotlyToolbar.jsx
- Update the filter and check button to be the same as images, supports dark mode
- Changed order of filter and select to be the same as images
- https://fireflydev.ipac.caltech.edu/firefly-1506-dark/firefly
- do a TAP search
- do a selection with the chart
- change to dark mode
- the buttons should show up and be the same as images
=> Firefly-1506: Update buttons to material icons

docs/release-notes.md
* Corrected FIREFLY-1345 to FIREFLY-1445 in 2024.1.0 release notes
* Add FIREFLY-1462, FIREFLY-1487, FIREFLY-1499, FIREFLY-1502 to 2024.2.0 release notes
=> Edits to 2024 release notes

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java
Minor firefly change. Logics are added in ife. 
View related [ife PR](https://github.com/IPAC-SW/irsa-ife/pull/331) for  testing steps.
=> IRSA-5367 fix sourceid extracted from image search.

src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/visualize/draw/ShapeDataObj.js, src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js, src/firefly/js/visualize/ui/ColorBandChooserPopup.jsx
- fixed ColorBandChooserPopup sizing and cleanup
- fixed recentering issue
- https://firefly-1505-euclid-bugs.irsakudev.ipac.caltech.edu/applications/euclid
=> Firefly-1505: Euclid issues

src/firefly/js/core/ComponentCntlr.js, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/DataProductsType.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/DatalinkProducts.js, src/firefly/js/metaConvert/vo/ServDescProducts.js, src/firefly/js/ui/CutoutSizeDialog.jsx, src/firefly/js/ui/ToolbarButton.jsx, src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/visualize/projection/ProjectionHeaderParser.js, src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx, src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx, src/firefly/js/voAnalyzer/VoConst.js, src/firefly/js/voAnalyzer/VoDataLinkServDef.js
euclid PR: https://github.com/IPAC-SW/irsa-ife/pull/336
- https://firefly-1491-cutout.irsakudev.ipac.caltech.edu/applications/euclid
- Do a search, you should see a cutout option on the far left on the image toolbar
- https://fireflydev.ipac.caltech.edu/firefly-1491-cutout/firefly
- to a obscore TAP search from CADC, choose the cutout option
=> Firefly-1491: add cutout support to data product viewer

buildScript/dependencies.gradle, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ModFileWriter.java, src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/FitsEvaluation.java, src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java, src/firefly/java/edu/caltech/ipac/util/FitsHDUUtil.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadFactory.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java, src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FlipXY.java
- related clean up
- https://fireflydev.ipac.caltech.edu/firefly-1512-fitslib/firefly
- upload any fits or do a image search
=> Firefly-1512: Update nom.tam.fits to 1.20.0

src/firefly/js/ui/PopupPanel.jsx
- https://fireflydev.ipac.caltech.edu/firefly-1514-popup-close/firefly/
- test according to ticket
=> Firefly-1514: fixed: popup not closing until second click

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/js/metaConvert/missions/WiseRequestList.js
View [Related Ife PR](https://github.com/IPAC-SW/irsa-ife/pull/341) for dev build and test instruction.
=> Irsa 6148 fix wise sourceid search

src/firefly/js/templates/hydra/HydraViewer.jsx
Fix used by https://github.com/IPAC-SW/irsa-ife/pull/344
=> IRSA-6248: fix bug in HydraLanding that prevent it from passing in slotProps

src/firefly/html/test/tests-table.html, src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java, src/firefly/js/tables/reducer/TableUiReducer.js, src/firefly/js/tables/ui/FilterEditor.jsx, src/firefly/js/tables/ui/TablePanel.jsx, src/firefly/js/tables/ui/TablesContainer.jsx
This enables the title to be updated by dispatchTableUiUpdate.
See test's source for example code.
Test: https://fireflydev.ipac.caltech.edu/firefly-1519-table-title/firefly/test/tests-table.html?test=Custom+Table+Title
=> FIREFLY-1519: add logic to pick up table title from table_ui table space

src/firefly/js/metaConvert/AnalysisUtils.js, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/DataProductsWatcher.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/UploadAndAnalysis.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/voAnalyzer/TableAnalysis.js, src/firefly/js/voAnalyzer/VoConst.js, src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- https://fireflydev.ipac.caltech.edu/firefly-1523-dl/firefly
- upload a datalink table
=> Support datalink tables as a primary product type

src/firefly/js/drawingLayers/Catalog.js, src/firefly/js/tables/ui/TableRenderer.js, src/firefly/js/tables/ui/TablesContainer.jsx, src/firefly/js/ui/ColorPicker.jsx, src/firefly/js/ui/RadioGroupInputField.jsx, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/ui/tap/ResultTitleDialog.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TapKnownServices.js, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/DrawLayerPanelView.jsx, src/firefly/js/visualize/ui/DrawLayerUIComponents.jsx
- Table use color swatch
- TAP includes button to set table title
- Small TAP panel clean up
- https://fireflydev.ipac.caltech.edu/firefly-1510-color/firefly
- load multiple catalog tables
- Color feedback in tabs
- You should see colors on each tab
- click color the change the color
- bring up drawing layer, change color of a layer, the the tab will change
- Search Title
- From TAP dialog click `Custom Search Title` button, set new title
- Experiment with the dialog after two or three searches
- Also test from Euclid: https://firefly-1510-color.irsakudev.ipac.caltech.edu/applications/euclid
=> Firefly-1510: Color shows in table tabs

src/firefly/java/edu/caltech/ipac/firefly/server/util/JsonToDataGroup.java, src/firefly/java/edu/caltech/ipac/table/TableUtil.java, src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java, src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java, src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java, src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java, src/firefly/js/metaConvert/PartAnalyzer.js
- https://fireflydev.ipac.caltech.edu/firefly-1529-gaia-datalink/firefly
=> Firefly-1529: fixed datalink issue with gaia

src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/charts/ui/options/SpectrumOptions.jsx, src/firefly/js/ui/panel/CollapsiblePanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-6084
When changing the x/y axis, the label does not update. This only happens when using the column search popup (magnifying glass icon).
Test: https://fireflydev.ipac.caltech.edu/dev/firefly/
- Load a chart
- Use column search popup to change x/y axis
- Make both label and values are updated.
=> IRSA-6084: changing x/y axis does not work when using column search popup

src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/DynamicDef.js, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- [Firefly-1549](https://jira.ipac.caltech.edu/browse/FIREFLY-1549): fixed
- [Firefly-1525](https://jira.ipac.caltech.edu/browse/FIREFLY-1525): support multiple MOCs in service descriptor
- some code clean up, some jsdoc clean up
- load url: https://firefly-1549-1525-dce.irsakudev.ipac.caltech.edu/irsaviewer/dce?api=dl&id=spitzer_m83m33&execute=true&sr=1500s&ra=23.4620417&dec=30.6602222
- it should do the proper search
- the moc ticket cannot be easily tested until the backend support them
=> Firefly-1525, Firefly-1549: two tickets

src/firefly/js/charts/ChartUtil.js, src/firefly/js/charts/TableStatsCntlr.js, src/firefly/js/charts/ui/ChartSelectPanel.jsx, src/firefly/js/charts/ui/CombineChart.jsx, src/firefly/js/charts/ui/options/BasicOptions.jsx, src/firefly/js/charts/ui/options/FireflyHistogramOptions.jsx, src/firefly/js/charts/ui/options/HeatmapOptions.jsx, src/firefly/js/charts/ui/options/ScatterOptions.jsx, src/firefly/js/charts/ui/options/SpectrumOptions.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1521
- Plot label not updating (already fixed)
- User-defined columns are not appearing as options in the chart options dialog
- Input fields in chart options dialog did not update after chart data has changed
Test:  https://fireflydev.ipac.caltech.edu/firefly-1521-chart-new-bugs/firefly
- Upload the sample test file in the ticket.
- Use the Chart Options dialog to change the x/y axis and ensure the chart data and axis labels are updated.
- Add a new column.  Make sure it is a numeric type.  Then, open the Chart Options dialog to verify that the new column is selectable.  
- Make additional updates to the chart, close the dialog, then reopen it to ensure the updates are reflected.
- This process should work with other tables as well.
=> FIREFLY-1521: a few chart related bugs

src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java
See https://github.com/IPAC-SW/irsa-ife/pull/353
=> IRSA-6308: pass along credential to IRSA backend services

src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java, src/firefly/java/edu/caltech/ipac/firefly/server/security/JOSSOAdapter.java, src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
See https://github.com/IPAC-SW/irsa-ife/pull/353
=> IRSA-6308: add logic to pass along basic-auth credential to IRSA backend services

src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java, src/firefly/java/edu/caltech/ipac/table/TableMeta.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java, src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java, src/firefly/java/edu/caltech/ipac/util/StringUtils.java, src/firefly/js/tables/ui/TableInfo.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-6331
- split and wrap description so that it does not exceed 80 characters per line.
Radar: https://irsa-6331-invalid-ipactable-created.irsakudev.ipac.caltech.edu/applications/Radar/
Timeseries: https://irsa-6331-invalid-ipactable-created.irsakudev.ipac.caltech.edu/irsaviewer/timeseries
Test: 
- do a radar search on anything (i did "sv sag")
- find the NEOWISE exposure photometry and send to IRSA Viewer
- save data table from there.
- load time series tool and upload that copy.
- try to do periodogram.
- periodogram fails.
=> IRSA-6331: change logic to convert VOTable's description into IPAC table comments

src/firefly/js/api/webApiCommands/ImageCommands.js
- The `api=hipsPanel' endpoint should be able to directly load a HiPS
-  https://fireflydev.ipac.caltech.edu/firefly-1541-hipspanel/firefly/?api=hipspanel
-  try the last two examples
-  https://fireflydev.ipac.caltech.edu/firefly-1541-hipspanel/firefly/?api=hipspanel&uri=https://web.ipac.caltech.edu/staff/desai/test/PilotHiPS
- should load HiPS
=> Firefly-1541: web api 'hipsPanel' url can setup hips services and load multiple hips

src/firefly/js/ui/DownloadDialog.jsx
Related to [ife PR ](https://github.com/IPAC-SW/irsa-ife/pull/357)
=> FIREFLY-1554 multi fixes address feedback in the test report.

src/firefly/js/ui/panel/TabPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1562
- Add scrollbarWidth='none' to ensure it's not visible even in firefox
- Decrease min-width to accommodate more tabs; setting it slightly bigger for removable tabs
- Introduce more advance logic to calculate the optimal tab size
Tests: 
https://firefly-1562-scrollbar-over-tab.irsakudev.ipac.caltech.edu/applications/sofia/
https://firefly-1562-scrollbar-over-tab.irsakudev.ipac.caltech.edu/irsaviewer/
In both IrsaViewer and Sofia, add multiple tabs to the results view to observe how it performs when there are more tabs than can fit. 
Also, even if the scrollbar is not visible, you can still scroll through the tabs using swipe gestures or by holding the Shift key while scrolling with the mouse.
=> FIREFLY-1562: scrollbar appears when there are more tabs than can fit within the available space

src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/ui/TimePanel.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapSearchSubmit.js, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/ui/tap/WavelengthPanel.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
See ife PR for details and test-build links: https://github.com/IPAC-SW/irsa-ife/pull/360
=> IRSA-6245: Add Search for LVF Images

src/firefly/js/metaConvert/missions/ShaRequestList.js
Related to [ife PR](https://github.com/IPAC-SW/irsa-ife/pull/363)
=> IRSA-5575 add "Depth of Coverage" in the the map title

docs/next-release-details.md, src/firefly/js/tables/ui/FilterEditor.jsx, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/SimpleComponent.jsx, src/firefly/js/ui/TimePanel.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchMethods.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapSearchSubmit.js, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TapViewType.jsx, src/firefly/js/ui/tap/WavelengthPanel.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1565
- fix clear `Current Constraints` stopped working
Test: https://fireflydev.ipac.caltech.edu/firefly-1565-copy-filter-refresh-screen/firefly
- Load a table
- Apply a column filter
- Bring up Table Option, then `Advanced Filter`
- Verify that 'Copy to clipboard' works and that it does not reload the the table(blink).
- Verify `Current Constraints: Clear` works.
=> FIREFLY-1565: Copy filters makes screen blink

src/firefly/js/ui/tap/AdvancedADQL.jsx, src/firefly/js/ui/tap/TapSearchRootPanel.jsx, src/firefly/js/ui/tap/TapSearchSubmit.js
Fixes [IRSA-6360](https://jira.ipac.caltech.edu/browse/IRSA-6360)
See IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/362
- Allow TAP request submit, to take additional clauses (like ORDER BY) and meta info (other than TAP meta info)
- Fix ORDER BY example
https://fireflydev.ipac.caltech.edu/irsa-6360-lvf-results/firefly
Check if firefly's TAP is working as before
=> IRSA-6360: LVF-search results UI

src/firefly/js/api/ApiBuild.js, src/firefly/js/metaConvert/AnalysisUtils.js, src/firefly/js/metaConvert/ImageDataProductsUtil.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/ui/BasicTableView.jsx, src/firefly/js/templates/common/ttFeatureWatchers.js, src/firefly/js/templates/fireflyviewer/FireflyViewer.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/MultiViewCntlr.js, src/firefly/js/visualize/PlotAttribute.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/task/PlotHipsTask.js
@loitly can you check the `TableUtil.js` changes?
- https://firefly-1571-image-sub-highlighting.irsakudev.ipac.caltech.edu/applications/spherex
- you should see the image sub-highlight like the table does
=> Firefly-1571: support image sub-highlighting

src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java, src/firefly/js/util/__tests__/VOAnalyzer-test.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1578
- create custom function nvl2 to support existing functionality
- remove outdated test that was failing
Test: https://fireflydev.ipac.caltech.edu/firefly-1578-nvl2-missing/firefly/ts.html
- Upload the sample test file attached in ticket
- Ensure it loads correctly without errors
=> FIREFLY-1578: nvl2 function does not exists in DuckDB

buildScript/webpack.config.js, package.json, src/firefly/js/templates/hydra/HydraViewer.jsx, src/firefly/js/templates/router/RoutedApp.jsx, src/firefly/js/ui/AppConfigDrawer.jsx, yarn.lock
Fixes [IRSA-6338](https://jira.ipac.caltech.edu/browse/IRSA-6338)
See ife PR for description and test-links: https://github.com/IPAC-SW/irsa-ife/pull/365
=> IRSA-6338: Use new icons for IRSA apps

docs/next-release-details.md, src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java, src/firefly/js/drawingLayers/hpx/HpxCatalog.js, src/firefly/js/metaConvert/vo/ServDescProducts.js, src/firefly/js/tables/HpxIndexCntlr.js, src/firefly/js/ui/VersionInfo.jsx, src/firefly/js/visualize/PlotAttribute.js, src/firefly/js/visualize/iv/ImageViewerDecorate.jsx, src/firefly/js/visualize/saga/CoverageUtil.jsx, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/visualize/ui/Buttons.jsx, src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
- [IRSA-5577](https://jira.ipac.caltech.edu/browse/IRSA-5577): fixed
- [IRSA-5779](https://jira.ipac.caltech.edu/browse/IRSA-5779): fixed
- [IRSA-5390](https://jira.ipac.caltech.edu/browse/IRSA-5390): fixed
- Added warning when BOX or REGION goes over limit (defaults to 30000), then show as catalog
- [IRSA-5897](https://jira.ipac.caltech.edu/browse/IRSA-5897): fixed
- https://irsa-5577-5779-5390.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
- Coverage should work better
- Warning when to many coverage Items (test: m16, .5 deg, PBCD, BCD)
=> IRSA-5xxx: multiple tickets: IRSA-5577, IRSA-5779, IRSA-5390

src/firefly/js/metaConvert/vo/ServDescProducts.js, src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx
- https://firefly-1581-cutout-def.irsakudev.ipac.caltech.edu/applications/spherex
- do search
- cutout default should be .5 degree (30 arcmin) which come from the server
=> Firefly-1581: recognize cutout default from service

src/firefly/java/edu/caltech/ipac/util/RegionFactory.java, src/firefly/js/drawingLayers/hpx/HpxDraw.js, src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx, src/firefly/js/tables/HpxIndexCntlr.js, src/firefly/js/visualize/draw/DrawObj.js, src/firefly/js/visualize/draw/ShapeToRegion.js
- include some catalog rendering tweeks for all sky with few points in each cell
- https://fireflydev.ipac.caltech.edu/firefly-1582-region/firefly/
- show a large catalog
- put in ellipse mode
- save as region layer
=> Firelfy-1582: fixed: region saving as ellipse

src/firefly/js/util/WebUtil.js, src/firefly/js/util/__tests__/WebUtil-test.js
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-6427
=> IRSA-6427: encodeUrlString() returning bad hash segment

src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java, src/firefly/java/edu/caltech/ipac/table/DataGroup.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1583
See ticket for testing instructions.
Test: Ticket: https://fireflydev.ipac.caltech.edu/firefly-1583-catalog-meta/firefly/
=> FIREFLY-1583: IpacTableFromSource fail to inject table meta when ingesting data directly from source

src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java, src/firefly/js/metaConvert/missions/ShaRequestList.js, src/firefly/js/visualize/FitsHeaderUtil.js, src/firefly/js/visualize/PlotAttribute.js, src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- https://firefly-1585-hdu-title.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
- The SHA DOC should show the channel
=> Firefly-1585: improved hdu title options, use by SHA

src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java, src/firefly/java/edu/caltech/ipac/firefly/data/WiseRequest.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/wise/QueryWise.java
Changes related to the NEOWISER year11 release. Can't test with year11 data yet, data will be available on the release data (soft release data 11/12).
=> IRSA-6168 neowiser year11 data release

src/firefly/js/drawingLayers/hpx/HpxCatalog.js, src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx, src/firefly/js/tables/HpxIndexCntlr.js, src/firefly/js/visualize/saga/CoverageWatcher.js
- Performance is OK but not great
- Will improve in future releases
- https://fireflydev.ipac.caltech.edu/firefly-1601-36mil/firefly
- load 36 million row table into firefly
=> Firefly-1601: coverage supports up to 36 million rows

src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java, src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java, src/firefly/js/Firefly.js, src/firefly/js/api/webApiCommands/ImageCommands.js, src/firefly/js/api/webApiCommands/TableCommands.js
- Also fixes [Firefly-1617](https://jira.ipac.caltech.edu/browse/FIREFLY-1617)
- url api examples changed to use https
- https://fireflydev.ipac.caltech.edu/firefly-1621-race/firefly/?api
- load am image via url api
=> Firefly-1621: fixed race condition when images loading

src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java, src/firefly/js/charts/dataTypes/FireflySpectrum.js
- recognize spectrum from next-sci
- spectrum plot will reverse the low spectrum if negative
- https://fireflydev.ipac.caltech.edu/firefly-1620-spec-types/firefly
- upload some of the files in the ticket (make sure to check `Attempt to interpret tables as spectra`)
=> Firefly-1620: more spectrum types for the guesser

src/firefly/js/tables/ui/PropertySheet.jsx
View [related ticket](https://jira.ipac.caltech.edu/browse/IRSA-6482) for details. 
Add a help anchor in propertysheet, requested in SOFIA test report. this change will affect all IRSA apps.
Test:
https://irsa-6482.irsakudev.ipac.caltech.edu/applications/sofia/
do a position search and go to Details tab, try help anchor.
=> Irsa 6482 sofia UI fixes by feedback

src/firefly/js/Firefly.js, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/tap/Constraints.js, src/firefly/js/ui/tap/ObjectIDSearch.jsx, src/firefly/js/ui/tap/ObsCore.jsx, src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx, src/firefly/js/ui/tap/SIASearchRootPanel.jsx, src/firefly/js/ui/tap/SiaUI.jsx, src/firefly/js/ui/tap/SiaUtil.js, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TableSearchHelpers.jsx, src/firefly/js/ui/tap/TapUtil.js, src/firefly/js/ui/tap/TemporalSearch.jsx, src/firefly/js/ui/tap/WavelengthPanel.jsx, src/firefly/js/voAnalyzer/VoCoreUtils.js
- https://fireflydev.ipac.caltech.edu/firefly-1622-siav2/firefly
- choose SIAv2 search panel and do a search
- Lock to service:  Try the `IRSA SIAv2` search
=> Firefly-1622: SIAv2 Implementation

src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java, src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java, src/firefly/test/edu/caltech/ipac/table/IpacTableFromSourceTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1632
See ticket for details.
Test: https://fireflydev.ipac.caltech.edu/firefly-1632-http-fetch-error/firefly
Using the new SIA2 search panel, fill out parameters that will trigger errors.
Also, see added test cases.
=> FIREFLY-1632: Enhance HTTP fetch error messages with response body details

src/firefly/js/visualize/saga/CatalogWatcher.js
- https://firefly-1612-cov-color.irsakudev.ipac.caltech.edu/applications/sofia
- test according to ticket
=> Firefly-1612: bug fix: table tab color wrong

src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
- https://firefly-1624-readout.irsakudev.ipac.caltech.edu/applications/sofia
=> Firefly-1624: improve bottom mouse readout layout

src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/ServiceDefTools.js, src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
- IFE  PR: https://github.com/IPAC-SW/irsa-ife/pull/377
- https://firefly-1646-moc-loading.irsakudev.ipac.caltech.edu/irsaviewer/dce
- load DCE
- should work like before: click around and make sure the MOCs load
=> Firefly 1646 moc loading

src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
Fixes [IRSA-6575](https://jira.ipac.caltech.edu/browse/IRSA-6575)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/381
=> IRSA-6575: Changes in Time Panel of LVF search form

src/firefly/html/firefly-dev.html, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/BaseGator.java, src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java, src/firefly/js/Firefly.js, src/firefly/js/data/MetaConst.js, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/DataProductsType.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/DatalinkProducts.js, src/firefly/js/metaConvert/vo/ObsCoreConverter.js, src/firefly/js/metaConvert/vo/ServDescConverter.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/ui/CatalogSearchMethodType.jsx, src/firefly/js/ui/DropDownContainer.jsx, src/firefly/js/ui/MultiSearchPanel.jsx, src/firefly/js/ui/PopupUtil.jsx, src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx, src/firefly/js/visualize/ui/GatorProtocolRootPanel.jsx, src/firefly/js/visualize/ui/GatorProtocolUtil.jsx, src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx, src/firefly/js/voAnalyzer/TableAnalysis.js
- Used with LSDB
- The Gator Protocol tab will only appears if searches are configured with the option `gatorProtocol.services`
- https://fireflydev.ipac.caltech.edu/firefly-1655-gator-proto/firefly/
- go to `LSDB Test Searches` tab.
- try a search
```
OP_gatorProtocol_title=LSDB Test Searches
OP_gatorProtocol_primary=true
OP_gatorProtocol_searchOptionsMask=cone,polygon,box
OP_gatorProtocol_services_0_serviceId=troyTest
OP_gatorProtocol_services_0_label=LSDB Raen Test
OP_gatorProtocol_services_0_value=https://troyraen.irsakudev.ipac.caltech.edu
OP_gatorProtocol_services_1_serviceId=IRSATEST
OP_gatorProtocol_services_1_label=Irsa Test (not LSDB)
OP_gatorProtocol_services_1_value=https://irsatest.ipac.caltech.edu
OP_gatorProtocol_services_1_showSqlSection=true …
```
=> Firefly-1655: Generalize IRSA Catalog Search for other services implementing the Gator protocol

src/firefly/js/util/WebUtil.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1616
- Add charset=UTF-8 to the Content-Type header to ensure the server correctly interprets the encoding.
Test: https://fireflydev.ipac.caltech.edu/firefly-1616-unicode-characters-columns/firefly/
Upload the sample table found in the ticket. It should be working now. Remember to test other functions as well, such as sorting and filtering. Since the modified function is a core function, perform a regression test to ensure everything else works as expected.
=> FIREFLY-1616: The Firefly table does not function correctly when a column contains non-ASCII characters.

src/firefly/js/metaConvert/missions/WiseRequestList.js
View Jira [ticket](https://jira.ipac.caltech.edu/browse/IRSA-6605).
Improv WISE image overlay for both position and none position searches.  For none position search image overlay the reference ra/dec (crval1, crval2).
test build:
https://irsa-6605-wise-overlay.irsakudev.ipac.caltech.edu/applications/wise/
1. test moving object search with full size image request
2. test none positions search with Scan ID and Coadd ID searches
=> IRSA-6605 WISE overlay issue

src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/HealpixProcessor.java, src/firefly/java/edu/caltech/ipac/table/DataGroup.java, src/firefly/js/drawingLayers/hpx/HpxCatalog.js, src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js, src/firefly/js/drawingLayers/hpx/HpxDraw.js, src/firefly/js/drawingLayers/hpx/TileDataMaker.jsx, src/firefly/js/metaConvert/DataProductConst.js, src/firefly/js/metaConvert/DataProductsCntlr.js, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/DataProductsWatcher.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js, src/firefly/js/metaConvert/vo/DatalinkFetch.js, src/firefly/js/metaConvert/vo/DatalinkProducts.js, src/firefly/js/metaConvert/vo/ObsCoreConverter.js, src/firefly/js/metaConvert/vo/ServDescProducts.js, src/firefly/js/tables/HpxIndexCntlr.js, src/firefly/js/tables/TableConnector.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js, src/firefly/js/ui/tap/Cutout.js, src/firefly/js/util/SynchronizeAsync.js, src/firefly/js/util/WebUtil.js, src/firefly/js/visualize/Point.js, src/firefly/js/visualize/VisUtil.js, src/firefly/js/visualize/saga/CoverageWatcher.js, src/firefly/js/voAnalyzer/TableAnalysis.js
- https://fireflydev.ipac.caltech.edu/firefly-1661-hpx-catalog/firefly
- Everything should work as before
=> Firefly-1661: hpx catalog using HealpixProcessor.java

src/firefly/js/ui/DefaultSearchActions.js, src/firefly/js/visualize/FitsHeaderUtil.js, src/firefly/js/visualize/iv/HiPSSingleTileRender.js, src/firefly/js/visualize/projection/ProjectionHeaderParser.js, src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx, src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- https://fireflydev.ipac.caltech.edu/irsa-6654-simbad-error/firefly
- bring up a HiPS
- zoom in deep and find an area with is pretty blank
- select a small area and use the ![Screenshot 2025-02-21 at 5 14 20 PM](https://github.com/user-attachments/assets/a0e9f5da-e157-4f17-baae-b782e46a64b1)
- from dropdown choose: `Search (cone) using simbad...`
- if there is an error it should be cleaner.
=> IRSA-6654: Nicer Simbad search error

src/firefly/js/drawingLayers/HiPSMOC.js, src/firefly/js/tables/HpxIndexCntlr.js, src/firefly/js/visualize/draw/DrawUtil.js, src/firefly/js/visualize/draw/Drawer.js, src/firefly/js/visualize/draw/MocObj.js
- MOC not redrawing properly when more than one MOC in on screen
- MOC now draws correctly even when tiles wrap
- MOC drawing is a little faster
- https://firefly-1663-moc-issues.irsakudev.ipac.caltech.edu/applications/euclid
- Euclid planned MOC should show correctly in both Spherical and Aitoff
=> Firefly-1663: fixed multiple MOC issues

src/firefly/js/templates/lightcurve/LcManager.js, src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx, src/firefly/js/templates/lightcurve/LcResult.jsx, src/firefly/js/templates/lightcurve/LcUtil.jsx, src/firefly/js/templates/lightcurve/wise/WiseMissionOptions.js
View [Ticket](https://jira.ipac.caltech.edu/browse/IRSA-4725) for details.
To test: 
Upload a time series table, click top Period Finder button. The Uploaded Filename should show in the period fineder option panel.
https://irsa-4725-ts.irsakudev.ipac.caltech.edu/irsaviewer/ts.html
=> IRSA-4725 misc time series issues

src/firefly/java/edu/caltech/ipac/firefly/resources/healpix-java.sql, src/firefly/test/edu/caltech/ipac/table/healpy/Dockerfile, src/firefly/test/edu/caltech/ipac/table/healpy/README.md, src/firefly/test/edu/caltech/ipac/table/healpy/compose.yaml, src/firefly/test/edu/caltech/ipac/table/healpy/run_healpy.py
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1672
- add validation test procedure
See ticket for details.
To test: https://fireflydev.ipac.caltech.edu/firefly-1672-healpix-index-bug/firefly/
- Upload sample table from URL: https://bacchus1.ipac.caltech.edu:9201/cover-whole-sky-1.87mil-rows.parquet
- Look for error in Chrome DevTool console.  There should not be any.
=> FIREFLY-1672: fix left-shift negative number error in HEALpix UDFs

src/firefly/js/charts/ui/PlotlyChartArea.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1675
See the ticket for the observed behavior and explanation.
Test: https://fireflydev.ipac.caltech.edu/firefly-1675-selection-lines-mode/firefly/
Go to `IRSA Catalogs`
- m31 -> 500 arcsecs -> Search
- Active Chart -> Settings
- Trace Style = lines -> Apply -> Close
- Select a rectangular area and notice that the `Select the enclosed points` and `Filter on the selected points` icons appear.
If you do this with the nightly builds, a `No points in the selection area` popup will appear.
=> FIREFLY-1675: Chart area selection does not work for scatter plot with 'lines' mode

docs/release-notes.md, src/firefly/js/visualize/ImViewFilterDisplay.js, src/firefly/js/visualize/iv/ExpandedTools.jsx, src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx, src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx, src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
- [Firefly-1688](https://jira.ipac.caltech.edu/browse/FIREFLY-1688): obs core crash
- [Firefly-1689](https://jira.ipac.caltech.edu/browse/FIREFLY-1689): fixed image filtering by checkbox
- https://fireflydev.ipac.caltech.edu/firefly-1688-obscore-crash/firefly
- Test according to the tickets
=> Firefly-1688, Firefly-1689: multi ticket

buildScript/next-pre-tag.sh, buildScript/next-release-tag.sh, src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java, src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/SpectrumMetaInspectorTest.java
- Now will build the spectral model for non-votables if they have the right column utypes
- Better documentation
- Improve guessing column names and units some for common Spitzer spectrum IPAC tables
- https://fireflydev.ipac.caltech.edu/firefly-1697-fits-spec/firefly
- load the spectrum in the ticket, they should all work
=> Firefly-1697: improve SpectrumMetaInspector

src/firefly/js/api/webApiCommands/DatalinkUICommands.js, src/firefly/js/drawingLayers/DistanceTool.js, src/firefly/js/templates/common/FireflyLayout.jsx, src/firefly/js/templates/common/InitArgsCtx.jsx, src/firefly/js/ui/dynamic/DLGeneratedDropDown.js, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/visualize/ImViewFilterDisplay.js, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- [Firefly-1681](https://jira.ipac.caltech.edu/browse/FIREFLY-1681): fixes: give more details that 1D images are loaded as tables
- [Firefly-1690](https://jira.ipac.caltech.edu/browse/FIREFLY-1690): fixed distance tool: image pixel offset is wrong on some images when wcs matched and in pixel mode
- https://firefly-1696-euclid-urlapi.irsakudev.ipac.caltech.edu/applications/euclid/
- Load example page: https://firefly-1696-euclid-urlapi.irsakudev.ipac.caltech.edu/applications/euclid/?api
- try the examples
- make variations
- https://fireflydev.ipac.caltech.edu/firefly-1696-euclid-urlapi/firefly
- Test according to the ticket.
=> Firefly-1696: changes for url api to work with a routed app and EmbededPositionSearchPanel

src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java, src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java, src/firefly/java/edu/caltech/ipac/util/FormatUtil.java, src/firefly/js/data/FileAnalysis.js, src/firefly/js/metaConvert/AnalysisUtils.js, src/firefly/js/metaConvert/UploadAndAnalysis.js, src/firefly/js/ui/FileUpload.jsx, src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/visualize/SearchRefinementTool.jsx, src/firefly/js/visualize/ui/ImageStatsPopup.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
- [Firefly-1195](https://jira.ipac.caltech.edu/browse/FIREFLY-1195): refine search region stays on when it shouldn't
- Search refinment: also fixes cone sizing is wrong which switch from polygon
- Search refinment: polygon will not reselect once it is selected once
- [Firefly-1706](https://jira.ipac.caltech.edu/browse/FIREFLY-1706): TAP search from selection tool is broken
- https://fireflydev.ipac.caltech.edu/firefly-1706-tap-search-selection/firefly
- Test according to the tickets
=> Firefly-1706, Firefly-1195: fixed two tickets

src/firefly/js/ui/WavelengthInputField.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/ui/tap/WavelengthPanel.jsx, src/firefly/js/visualize/ui/VisualSearchUtils.js
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/409
=> FIREFLY-1723,1726,IRSA-6891: SPHEREx LVF improvements

src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/js/core/background/JobHistory.jsx, src/firefly/js/core/background/JobInfo.jsx, src/firefly/js/tables/TableUtil.js, src/firefly/js/tables/TablesCntlr.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1735
- Add enumerated dropdown filters for the Service ID and Type columns
- Enable row highlighting and wire selection to show job info when available
Additional changes here: https://github.com/lsst/suit/pull/58
- Update LsstSSOAdapter to correctly extract a valid user ID from request headers
Test: https://fireflydev.ipac.caltech.edu/firefly-1735-job-monitor-related/firefly/
Submit a few TAP and/or IRSA Catalog searches, then go to the Job Monitor, you should see some history.
- The Service ID and Type columns now have dropdown filters.
- Click the Job Info (i-icon), then use your mouse or keyboard to move between rows. The Job Info popup will update to reflect the currently highlighted row.
=> FIREFLY-1735: Job Monitor related tasks

src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java, src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java, src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java, src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java, src/firefly/js/visualize/saga/CatalogWatcher.js, src/firefly/js/visualize/ui/IrsaCatalogSearch.jsx
- https://fireflydev.ipac.caltech.edu/firefly-1390-table-upload-ignore-overlay/firefly
- load some fits images
- create a file and upload the table below
- You should see some points in the bottom right and toward the middle
- add another image
- the points should be in the same place
Note - there will be no coverage since images point can's show up on HiPS
```
\CatalogOverlayType=IMAGE_PTS
\IMAGE_COLUMN=x;y
|     x|     y|index|what            |
|double|double| int | char           |
|      |      |     |                |
|  null|  null| null| null           |
2.0     3.0   1     zero-zero
5.5     6.0   2     half-zero
100.0    50    3     zero-quarter
88      150   4     half-half
```
=> Firefly-1390 table upload ignore overlay

src/firefly/js/Firefly.js, src/firefly/js/api/webApiCommands/ImageCommands.js, src/firefly/js/api/webApiCommands/TabCommands.js, src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js, src/firefly/js/tables/ui/TablePanelOptions.jsx, src/firefly/js/ui/Menu.jsx, src/firefly/js/ui/WebApiHelpInfoPage.jsx
- try: https://fireflydev.ipac.caltech.edu/firefly-1736-gourl/firefly/?api
- try: https://fireflydev.ipac.caltech.edu/firefly-1736-gourl/firefly/?api=go
- try: https://fireflydev.ipac.caltech.edu/firefly-1736-gourl/firefly/?api=go&to=mon
- try: https://fireflydev.ipac.caltech.edu/firefly-1736-gourl/firefly/?api=go&to=Upload
- try other stuff
=> Firefly-1736: URL API: add a go to tab

src/firefly/js/fieldGroup/FieldGroupCntlr.js, src/firefly/js/fieldGroup/FieldGroupUtils.js, src/firefly/js/metaConvert/AnalysisUtils.js, src/firefly/js/metaConvert/DataProductConst.js, src/firefly/js/metaConvert/DataProductsType.js, src/firefly/js/metaConvert/DataProductsWatcher.js, src/firefly/js/metaConvert/UploadAndAnalysis.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/DatalinkFetch.js, src/firefly/js/metaConvert/vo/DatalinkProducts.js, src/firefly/js/metaConvert/vo/ObsCoreConverter.js, src/firefly/js/metaConvert/vo/ServDescConverter.js, src/firefly/js/tables/TableUtil.js, src/firefly/js/ui/TargetPanel.jsx, src/firefly/js/ui/dynamic/DynComponents.jsx, src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx, src/firefly/js/visualize/ui/CoveraeViewer.jsx, src/firefly/js/visualize/ui/FileUploadViewPanel.jsx, src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx, src/firefly/js/voAnalyzer/VoDataLinkServDef.js, src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
- euclid: https://firefly-1743-related.irsakudev.ipac.caltech.edu/applications/euclid
- SPHEREx: https://firefly-1743-related.irsakudev.ipac.caltech.edu/applications/spherex
- Do a SPHEREx search and you should see related grid option.
=> Firefly-1743: Data product viewer: support related grid based on table filter

src/firefly/html/css/global.css, src/firefly/js/ui/panel/DockLayoutPanel.jsx, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
Fixes [IRSA-6898](https://jira.ipac.caltech.edu/browse/IRSA-6898)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/412
> Note: I've tried to generalize the collapsible split panel components used in spherex results but the still need more work to make the styling not specific to spherex use case - left those as TODOs in code.
=> IRSA-6898: SPHEREx: Reconcile LVF and Spectrophotometry Results

src/firefly/js/ui/UploadTableSelector.jsx, src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx, src/firefly/js/ui/tap/AdvancedADQL.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/IRSA-6794
See **IFE PR** for details: https://github.com/IPAC-SW/irsa-ife/pull/413
=> IRSA-6794: Add Search Type Options optionally inside Embed panel

src/firefly/js/Firefly.js, src/firefly/js/core/AppDataCntlr.js, src/firefly/js/core/background/BackgroundCntlr.js, src/firefly/js/core/background/BgMaskPanel.jsx, src/firefly/js/core/background/JobMonitor.jsx, src/firefly/js/ui/DropDownContainer.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1761
Updated the Job Monitor according to the ticket requests.
Test: https://firefly-1761-job-monitor-wording.irsakudev.ipac.caltech.edu/irsaviewer/
- Go to Job Monitor tab
- Added a help description next to the Notification Email field.
- Updated the 'Note' message as specified in the ticket.
=> FIREFLY-1761: Add help to Email Notification field

src/firefly/js/Firefly.js, src/firefly/js/core/LayoutCntlr.js, src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/TableDataProductUtils.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/metaConvert/vo/ServDescProducts.js, src/firefly/js/ui/CutoutSizeDialog.jsx, src/firefly/js/ui/TargetPanelWorker.js, src/firefly/js/ui/UploadTableSelector.jsx, src/firefly/js/ui/panel/TabPanel.jsx, src/firefly/js/ui/tap/Cutout.js, src/firefly/js/ui/tap/SpatialSearch.jsx, src/firefly/js/ui/tap/TapKnownServices.js, src/firefly/js/visualize/ImagePlotCntlr.js, src/firefly/js/visualize/ImageViewerLayout.jsx, src/firefly/js/visualize/PlotAttribute.js, src/firefly/js/visualize/reducer/HandlePlotChange.js, src/firefly/js/visualize/reducer/PlotView.js, src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js, src/firefly/js/visualize/task/PlotHipsTask.js, src/firefly/js/visualize/task/WcsMatchTask.js, src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx, src/firefly/js/visualize/ui/multiProduct/MetaDataMultiProductViewer.jsx, src/firefly/js/voAnalyzer/ColumnsModelInfo.js, src/firefly/js/voAnalyzer/TableAnalysis.js, src/firefly/js/voAnalyzer/VoConst.js
- Data product table should not loading when you show coverage
- WebPlotRequest: turning off ‘Pan by table Row’
- Recenter issue- Fix images scrolling off of the screen
- integrate cutout dialog
- [Firefly-1763](https://jira.ipac.caltech.edu/browse/FIREFLY-1763): support an xtype==='point' column for position
- [Firefly-1751](https://jira.ipac.caltech.edu/browse/FIREFLY-1751): "No results yet" when there are results
-  [Firefly-1758](https://jira.ipac.caltech.edu/browse/FIREFLY-1758): data collections tab claims MOC missing
- https://firefly-1760-spherex-issues.irsakudev.ipac.caltech.edu/applications/spherex
- The above should work
=> Firefly-1760: SPHEREx Issues

src/firefly/js/metaConvert/DataProductsFactory.js, src/firefly/js/metaConvert/TableDataProductUtils.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js, src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
- should not show the more dropdown in the Spectrophotometry tool
- fixed: when clicking off of the spectrum table to another tab then back the highlightedRow is set to 0
https://github.com/IPAC-SW/irsa-ife/pull/418
- https://firefly-1769-two-issues.irsakudev.ipac.caltech.edu/applications/spherex
- both issues should be fixed
=> Firefly-1769: SPHEREx: fix two issues

src/firefly/js/data/FileAnalysis.js, src/firefly/js/metaConvert/PartAnalyzer.js, src/firefly/js/metaConvert/TableDataProductUtils.js, src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- fixed test doc: Euclide - 12
- https://firefly-1772-table-state.irsakudev.ipac.caltech.edu/applications/euclid/
- load results spectra results, show a table, filter or select a row, click-off-and-on
- state should be maintained
=> Firefly-1772: data product tables maintain state
