Caltech-IPAC/firefly

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/ParamInfo.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
- src/firefly/java/edu/caltech/ipac/util/CollectionUtil.java
https://jira.ipac.caltech.edu/browse/IRSA-2271
test: 
https://irsawebdev9.ipac.caltech.edu/IRSA-2271_table_array_type/firefly/
https://irsawebdev9.ipac.caltech.edu/IRSA-2271_table_array_type/applications/sofia/
Sample file with array types:
${firefly_test_data}/FileUpload-samples/fits/imagetable/calexp-005882-i1-0406.fits
- adds support for array types
- use VOTable arraysize format
- display array values as `datatype [arraysize]`
- refactor VoTableReader and add support for reading specific table indices.
> IRSA-2271: Add support for array types to DataGroup

- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/js/charts/ui/FilterEditorWrapper.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/FilterEditor.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-340
Test deployment: https://irsawebdev9.ipac.caltech.edu/firefly-340_chartFilterEditor/firefly/
Filter Editor can be now invoked from the chart, the behavior is similar to the its behavior when it's invoked from a table. 
Bug fixes 
- Users should be able to update or remove expression filters set from the chart or ROW_IDX filters set from the image using Filter Editor's "Filters" box, which shows all filters.
- The number of filters on the badge on table toolbar should reflect the number of individual filters.
> FIREFLY-340: Filter Editor can not be invoked from a chart

- src/firefly/js/data/MetaConst.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/drawingLayers/DistanceTool.js
- src/firefly/js/drawingLayers/PointSelection.js
- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/draw/DrawingDef.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
Firefly-324: Fixed: when a catalog is reloaded from the background manager its color changes.
- Other bugs: not checking when tableMode.isFetching, table model was not complete
- Added a couple of more color so catalogs are less likely to duplicate
- Firefly-181: now can define DEFAULT_SYMBOL in table meta just like you can DEFAULT_COLOR
see issue described in  https://jira.ipac.caltech.edu/browse/FIREFLY-324 _or_
https://jira.lsstcorp.org/browse/DM-11426
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-324-redraw/firefly/
- do a catalog search long enough to take a few seconds e.g. wise/m31/400 arcsec
- send it to the background as soon as the message appears on the tab.
- load the table from the background monitor
- after everything come up, click on the background monitor again, …
> Firefly-324: Fixed: when a catalog is reloaded from the background manager its color changes.

- buildScript/tasks.gincl
- docker/base/Dockerfile
- docker/base/cleanup.sh
- docker/base/launchTomcat.sh
- docker/base/setenv.sh
- docker/base/start-examples.txt
- docker/k8s/firefly.yaml
- docs/firefly-docker.md
https://jira.ipac.caltech.edu/browse/FIREFLY-165
Test deployment: https://irsawebdev9.ipac.caltech.edu/firefly-165_docker/firefly/
> gradle :firefly:bAAD
> gradle :firefly:dockerImage
> docker run -p 8090:8080  --memory=1g --rm ipac/firefly
(If using mac docker, docker VM is limited by default to 2G, but it can be changed to a higher number using the Whale 🐳 icon in the task bar, then Preferences -> Advanced.)
To see which files were cleaned
> docker stats 
> docker exec -it `containerIdOrName` bash
The cleanup logs are in `/usr/local/tomcat-base/firefly-work/firefly/cleanup_logs`
> FIREFLY-165 Update the firefly docker with clean up and auto VM sizing

- docker/base/Dockerfile
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-364
As described in the ticket, link substitution uses relative index instead of an absolute one.  The returned value is wrong because it's taken from the first page.  
To test, simply compare this PR build to the one from nightly.  Use `file upload` with sample test file: `firefly_test_data/FileUpload-samples/VOTable/tabledata/multiTables_Ned.xml`
The first column(`Object Name`) has a reference to itself.  You will see in the nightly build that the referenced's value is no longer correct after the first page.  This is fixed in this PR build.
nightly:  https://irsawebdev9.ipac.caltech.edu/nightly/firefly/
PR test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-364_votable_link_substitution/firefly/
> FIREFLY-166: fix votable link using relative index instead of absolute

- buildScript/depends.gincl
see https://github.com/IPAC-SW/irsa-ife-env/pull/2
> FIREFLY-80: switch to Java 11 openJDK and Java 1.8 openJDK

- src/firefly/js/tables/TablesCntlr.js
https://jira.ipac.caltech.edu/browse/FIREFLY-360
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-360_revert_highlight_onsort/firefly/
As described in the ticket, highlighted row should be set to 0 after sorting.  This behavior should be for all tables, including `client` tables.
Some known client tables:
Images -> View HIPS Images -> Select Data Set
Then click the `i` icon on the image toolbar to bring up another client table.
> FIREFLY-360: revert changes made previously to onSort behavior

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/TableStatsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyHistogram.js
- src/firefly/js/drawingLayers/Artifact.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/HiPSListUtil.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-357
Test build: https://irsawebdev9.ipac.caltech.edu/firefly-357_filterbugs/firefly/
- Fixed a bug in EmbeddedDbProcessor:handleHighlightedRowRequest - when highlighted row is not in [filtered] table, it should be reset. (This was causing empty table when filtering from a chart when on last pages and with highlighted row not in filtered table.
- Since tableData.data can be undefined when no data available, we should handle this situation. When data are used as an array, use empty array.
- When filtering from image and no points are in the selection, "IN ( )" was causing database errors. Using ROW_IDX<0 instead.
- Catalog overlay should not show, when the connected table is empty after filtering.
- IRSA-3117 merge partially reverted …
> FIREFLY-357: after filtering decimated plot table crashes

- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BgMaskPanel.jsx
- src/firefly/js/ui/DownloadDialog.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-381
Add progress indicator and option to background prepare download jobs.  This should be implemented such that the behavior is consistent among all applications using Firefly.
See `Intended behavior: ` section of the ticket for more details.
To test, use Time Series:  https://irsawebdev9.ipac.caltech.edu/FIREFLY-381_download_dialog_mask/firefly/ts.html
- Upload a file
- Select all from the `Input Data` result table
- Click `Prepare Download` located top right corner.
PS.  
https://irsawebdev9.ipac.caltech.edu/FIREFLY-381_download_dialog_mask/applications/finderchart/
I built finderchart to see if the above changes would propagate down to finderchart, and it did not.  The reason is because finderchart is using a copy of the above dialog and …
> FIREFLY-381: Prepare download dialog updates

- buildScript/tasks.gincl
This ticket does:
1- Modifying gradle "dockerPublish" task to take multiple tags for a K8s build.
2- Adding new "dockerDelete" task to gradle tasks. This task deletes docker image form docker hub.
To test:
1- Use Jenkins's [snadbox](http://irsawebdev5:8100/job/sandbox/) job to build K8s build, and specify multiple tags for that build: 
2- Use Jenkins's [sandbox2](http://irsawebdev5:8100/job/sandbox2/) job to delete the K8s build. It should delete the image tag from docker hub too.
irsa-ife-env PR: https://github.com/IPAC-SW/irsa-ife-env/pull/4
> Firefly 342 improve jenkins to manage multiple tags

- src/firefly/js/util/WebUtil.js
Firefly Ticket :  https://jira.ipac.caltech.edu/browse/FIREFLY-159
There are five issues reported originally, please see the ticket above.  Two of the three issues (fileName and backgroundable) are fixed in Loi's two pull requests. The open dialog issue is 
an intended behavior in the updated DownloadDialog.  
In this pull request, two remaining issues, the non-stop spiny mask and check mark are fixed.
The fix is very trivial.   Please check the fix to see if it was fixed properly.  The test URL is
https://irsawebdev9.ipac.caltech.edu/firefly-159-Lijun/irsaviewer/ts.html
Thanks!
> firefly-159-The issues in "prepare download" that are seen in Time Series, Sofia etc.

- src/firefly/html/css/global.css
- src/firefly/java/edu/caltech/ipac/firefly/core/background/BackgroundStatus.java
- src/firefly/java/edu/caltech/ipac/firefly/data/DownloadRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/BackgroundInfoCacher.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackageMaster.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/Packager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/BackgroundEnv.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerParams.java
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundMonitor.css
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/core/background/BackgroundStatus.js
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/core/background/BgMaskPanel.jsx
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/templates/lightcurve/LcImageToolbarView.jsx
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/ptf/PTFMissionOptions.js
- src/firefly/js/templates/lightcurve/ztf/ZTFMissionOptions.js
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/DownloadOptionsDialog.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/ui/PopupUtil.jsx
- src/firefly/js/ui/WorkspaceSelectPane.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/util/Validate.js
https://jira.ipac.caltech.edu/browse/FIREFLY-384
additional changes here: https://github.com/IPAC-SW/irsa-ife/pull/90
- create new workspace selection panel as an example of how to write composable widgets
- add Title to dialog
- add SaveAs plus workspace support
- add show* props to allow for more flexibility when laying out fields.
- refactor LightCurve download dialogs.
To test:
https://irsawebdev9.ipac.caltech.edu/FIREFLY-384_update_download_dialog/irsaviewer/timeseries
https://irsawebdev9.ipac.caltech.edu/FIREFLY-384_update_download_dialog/applications/sofia/
PS:  Workspace selection UI and related selection data is added to the dialog and also to the download request.  But, the logic to `save to workspace` is not yet implemented.
If you wish for me to add that logic to the PR as …
> FIREFLY-384: update to download dialog

- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/Packager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingController.java
https://jira.ipac.caltech.edu/browse/FIREFLY-389
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-389_single_file_download/applications/sofia/
Additional changes: https://github.com/IPAC-SW/irsa-ife/pull/91
There are 2 issues:
1.  When download resulted in only 1 file, it does not save the file with the selected 'Save As' value. 
This can be duplicated in ZTF Time Series or SOFIA by selecting only 1 row.
2. When download resulted in only 1 file in which you do not have access or privilege to, it saves the error HTML page as the content of the file without any warnings. 
This can be duplicated using SOFIA -> 'M17', level 2 -> FORCAST -> select 1 row -> Prepare Download
Also: fixed `undefined` showing up in `Save As` in SOFIA download dialog.
> FIREFLY-389: fix single file package download

- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
- Firefly-264: FIXED: Marker, once uncheck will not recheck and become visible
- Firefly-58: FIXED: Draw distance disappears after zoom points too far out
- Firefly-145: changing hips will not change coordinate system
_To Test:_
https://irsawebdev9.ipac.caltech.edu/firefly-264-marker-58-distance/firefly/
- Firefly-58: load an image, use distance across the middle. Zoom until the endpoints are out of view. The line should still be visible.
-  Firefly-264: load an image, add a marker, bring up layer control.  Hide and then show the marker.  It should work.
- Firefly-145: show a 2mass HiPS, change coordinate sys to Galactic, change to another 2mass HiPS (there are 4 total)
>  Firefly-264,Firefly-58, Firefly-145: fixed bugs

- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/IbeTemplateProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/IrsaLightCurveHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lsst/LSSTMetaSearch.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/OidcAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ws/WsServerUtils.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
- src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
https://jira.ipac.caltech.edu/browse/IRSA-3179
Test: https://irsawebdev9.ipac.caltech.edu/IRSA-3179_sofia_proprietary_not_working/applications/sofia/
Additional changes:  https://github.com/IPAC-SW/irsa-ife/pull/93
SOFIA: proprietary queries/downloads not working.
When accessing proprietary data aware services, user's credential has to be explicitly requested when the connection is created.  This has not been done to any of IRSA's React based applications.  This PR added a few things to enable this feature and also ensure that SOFIA's server-side code implements it.
Also, refactor HttpServices to simplify its API.
To test:
Query SOFIA proprietary data.  (I use `m17` with Level 2,3,4)
This should return some FORECAST with pink(no access) rows.
Sign in as someone with access to SOFIA data. …
> IRSA-3179: implement proprietary data access for SOFIA

- src/firefly/html/test/template.html
- src/firefly/js/ui/FieldGroupConnector.jsx
- src/firefly/js/visualize/MenuItemKeys.js
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/MatchLockDropDown.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
Firefly-416: useFieldGroupConnector was not unmounting fields properly
- also enable wcs button to be turned off
- added line to demonstrate removing wcs lock in gator
- IRSA-3070 should use this example
https://jira.ipac.caltech.edu/browse/FIREFLY-416
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-416-bad-validation/firefly/
- The problem described in the ticket is fixed.
> Firefly-416: useFieldGroupConnector was not unmounting fields properly

- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
The error message for attempts to load 1D images is changed to avoid implying that 1D images are non-conformant; we just don't support them (yet!).
> Adjust error message produced when attempting to load 1D image

- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-414
- add followRedirect to HttpServices
- manually handle redirection from aync TAP queries
Test: https://lsst-lsp-int.ncsa.illinois.edu/portal/app/
Problem:
LSST TAP results endpoint redirect to AWS.  HttpClient from Apache includes the headers when follow redirect.  This causes the request to fail at AWS due to credential header being sent.
Solution:
Manually handle redirection.  Include credential info only when redirected back to ncsa.
> FIREFLY-414: Fail to retrieve results from LSST async TAP queries

- src/firefly/html/firefly-dev.html
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
IRSA-3272: Header popup panel was not updating as the FITS image changed
- Bug fix in `FitsHeaderView.jsx`
- Also fix a small URL substitution bug, (`firefly-dev.html`,`ImageSearchPanelV2.jsx`)
https://jira.ipac.caltech.edu/browse/IRSA-3272
_to test:_
https://irsawebdev9.ipac.caltech.edu/IRSA-3272-header-popup-bug/applications/sofia/
- Do an all sky sofia search
- switch to data tab
- bring up some images by switching tabs and clicking on rows
- bring up header view
- continue to switch images, the header panel should update.
> IRSA-3272: Header popup panel was not updating as the FITS image changed

- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
The following PR is about solving the problem explained in ticket [FIREFLY-443](https://jira.ipac.caltech.edu/browse/FIREFLY-443).
It expects to solve a problem found while testing [IRSA-2442](https://jira.ipac.caltech.edu/browse/IRSA-2442) in irsatest and need to be fixed for the upcoming IRSAViewer release in `rc-2019.3` and ultimately merged back to dev.
The image search is not responding, skipping any search where cubes of images are expected from IRSA/IBE searches.
Datasets are defined in a image master data config file and data type column is used to separate images from cubes to be able to avoid using cutout. Somehow this was changed and no longer working in the current `rc-2019.3` and in `dev` branches.
The code involved has changed a lot since this datatype usage was introduced …
> FIREFLY-443: put back cube images

- src/firefly/js/visualize/task/LSSTFootprintTask.js
Firefly-435: fixed a LSST footprint bug that was introduced by table changes churn
https://jira.ipac.caltech.edu/browse/FIREFLY-435
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-435-footprint-bug/firefly/
- Load an image and the related footprint.  It should overlay correctly as it did before.
> Firefly-435: fixed a LSST footprint bug that was introduced by table changes churn

- src/firefly/js/core/History.js
- src/firefly/js/tables/TablesCntlr.js
https://jira.ipac.caltech.edu/browse/FIREFLY-64
Additional changes here: https://github.com/IPAC-SW/irsa-ife/pull/99
Issue: Browser back button doesn't behaves as user expect.
This ticket was raised while testing SOFIA.  In SOFIA, a single search triggers multiple Firefly table's searches.  Firefly record history based on an action at a time.  This causes the problem reported in the ticket.
In this PR, I've created a new SOFIA_SEARCH action creator to capture the multiple searches logic.  This action creator is then `registered` to Firefly to make Firefly aware of the new action.
This should fix the `Back` button issue as well as the copy/paste of the URL.
Test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-64_back_button/applications/sofia/
> FIREFLY-64: Enable default history handling.

- src/firefly/js/drawingLayers/DistanceTool.js
- src/firefly/js/drawingLayers/DistanceToolUI.jsx
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/draw/DrawObj.js
- src/firefly/js/visualize/draw/DrawUtil.js
- src/firefly/js/visualize/draw/Drawer.js
- src/firefly/js/visualize/draw/DrawingDef.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- src/firefly/js/visualize/iv/HiPSSingleTileRender.js
The developement fixes the ruler tool behavior based on the following JIRA tickets, 
https://jira.ipac.caltech.edu/browse/FIREFLY-56
https://jira.ipac.caltech.edu/browse/FIREFLY-1
Here is the  summry of the fixing, 
- increase the line thickness and font size and style of the ruler tool
- display PA along angular distance without requiring the user to click in the layer dialog
--  PA angle and angular disatance are displayed in parallell, above and along the anglular distance vector 
-- PA angle is measured East from North, in unit 'degree'
- Add an arrow head at the end of angllar distance vector 
- Unit update including that on layer dialog, 
-- add unit 'pixel' to image with WCS case 
-- image without WCS has only unit 'pixel' option
-- HiPS has no 'pixel' unit
-  lines and the …
> FIREFLY-56 Change ruler tool behavior for image with or without WCS and HiPS

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/mapper/IpacTableExtractor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/table/DataObject.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
- src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/java/edu/caltech/ipac/visualize/draw/FixedObjectGroupUtils.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/IpacTableTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-150
General changes:
- `data type` is shown by default.  (most tables)
- `Text View` UI is updated to look more like an SQL client and not IPAC table.
- Data overflow in table cell will be appended with `...`(more indicator).
- By default, column width is set to the data’s length or 100 whichever is less.
- significant update to VoTableWriter - @cwang2016 please review and test to make sure it support all previous use-cases.
Data array:
- Display
- Full value of the array is displayed in the table cell as JSON string
- Column width is default to the length of the value or 30 whichever is less.
- Overflow values are hidden and replaced with `...`
- In `Text View`, the same JSON string value is shown in full 
- Save
- VOTable: data array is saved …
> FIREFLY-150: Handle data array type

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
Firefly-467: https://jira.ipac.caltech.edu/browse/FIREFLY-467
The wrong tbl_index bug was fixed in this pull request.  To validate it, please use the attached data that Dave gave me for testing WAVE-TAB.  Please run it in irsadev.ipac.caltch.edu and then run using the URL in this pull request, you can see the difference.  The fix is simple.  
Please note, the wavelength is always NAN.  It is caused by other bug firefly-469 (https://jira.ipac.caltech.edu/browse/FIREFLY-469).  Also the ra,dec are all 0.  There should be more bugs.  
URL: https://irsawebdev9.ipac.caltech.edu/firefly-467-readTable/firefly/
> firefly-467-Firefly can not read the binary table header correctly if the FITs has both Image HDU and BinaryTable HDU	

- src/firefly/js/drawingLayers/FootprintToolUI.jsx
- src/firefly/js/visualize/draw/MarkerFootprintObj.js
https://jira.ipac.caltech.edu/browse/FIREFLY-436
Update:
compute the outline box before rendering footprint text when the location corner is changed. 
test:
https://irsawebdev9.ipac.caltech.edu/FIREFLY-436_footprint_label_position/firefly/
do image search
select a footpint 
chage the footprint label corners from the overlay dialog. 
or check the build for Sofia, 
https://irsawebdev9.ipac.caltech.edu/FIREFLY-436_footprint_label_position/applications/sofia/
> FIREFLY-436 place the footprint label when the location corner is changed

- buildScript/tasks.gincl
- docker/base/cleanup.sh
- src/firefly/js/Firefly.js
- src/firefly/js/visualize/HiPSUtil.js
- After a reload all HiPS tile and property caching should be cleared
- new function Firefly.js: getFireflySessionId()
- Firefly-490: allow reload caching to happen in local mode
- Firefly-361: docker clean will cleanup hips cache over 90 days
https://irsawebdev9.ipac.caltech.edu/firefly-489-hips-cache/firefly/
You will need to bring up developer tools and watch the network tab. Watch for the message `(disk cache)` or `(memory cache)` when fits tiles are loading.
_First try_
1. Chose a target and HiPS selection, you will use this same one again and again.
1. make sure developer tools, network tab is up
1. load the HiPS and zoom down to around 5 degree FOV, and scroll around that area
1. you will see a lot of activity on the network tab, watch the size
1. as you scroll around you will see …
> Firefly-489: caching of HiPS properties and tiles should only last until a reload happens

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
https://jira.ipac.caltech.edu/browse/FIREFLY-487 
When the WAVE-TAB was implemented,  the validation process was ignore.  When the FITs has multiple HDUs, it can have more binary tables.  Thus, the validation is necessary to guarantee that the right table is used.  This pull request is to add WAVE-TAB WCS validation according to the paper " Representations of spectral coordinates in FITS by E. W. Greisen et al."   All changes are in sever side.  
What it does it to check all the binary tables and find the right one whose extver number, extlevel number and extname are the same as thePV3_i  (i=1, 2) and PS3_i  respectively.  Also the extname in the binary table should start with "WCS-". 
To test it, please use previously known working FITs files (in the ticket). 
URL: …
> firefly-487-Add validation to WAVE-TAB WCS implementation

- README.md
- docs/release-notes.md
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/ActiveRowCenterWatcher.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/task/WcsMatchTask.js
- src/firefly/js/visualize/task/ZoomTask.js
- src/firefly/js/visualize/ui/VisToolbar.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
Firefly-484: HiPS/Image WCS match rotate updates
- The actual fix to this bug was to make the image rotate to the FITS orientation
- Image rotating to the HiPS orientation on WCS match is actually a new feature that was requested in the past
When WCS matching:
- When FITS rotates the HiPS will change coordsys it if it EQJ2000 north or Galactic north
- When HiPS changes coordinateSys FITS will rotate to it.
- FITS will rotate when locking to a HIPS
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-484
https://irsawebdev9.ipac.caltech.edu/firefly-484-hips-rotate/firefly/
1. Attempt repeat the ticket, the problem should be fix.
1. Bring in a FITS and HiPS, wcs match lock
- switch coordinate system on the HiPS, the fits will rotate
- rotate the hips as you cross J2000 north or galactic …
> Firefly-484: HiPS/Image WCS match rotate updates

- buildScript/tasks.gincl
- buildScript/webpack.config.js
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
- src/firefly/js/Firefly.js
- src/firefly/js/rpc/SearchServicesJson.js
https://jira.ipac.caltech.edu/browse/FIREFLY-488
Implement new cache policy for table searches.
Table results are only saved for the duration of the page.  Upon reload, all table searches should refetch data and not use cached version.
Also in this PR, fix Gator master table processor (CatMasterTableQuery) so that it does not do any caching of its own.  It should follow the same caching policy mentioned above.  In doing so, the code is rewritten to parse the IPAC table directly from IO stream avoiding having to write out the IPAC table into `perm-files` first.  This is one step closer to removing `perm_files` directory.  This should also fix the exception encountered when `perm_files` directory is deleted during runtime.
Test:  https://irsawebdev9.ipac.caltech.edu/FIREFLY-488_table_cache_u …
> FIREFLY-488: enforce new cache policy

- src/firefly/html/test/test-coverage.html
- src/firefly/js/data/MetaConst.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
Added "OverlayPostion" table meta data that will place search target on coverage or catalog.
_to test:_
https://irsawebdev9.ipac.caltech.edu/firefly-518-overlay-pos/firefly/test/test-coverage.html
- go down to test #7 
- click on next search
- each time the overlay position should update
> Firefly-518: Added better method method of managing overlay position

- src/firefly/html/test/tests-table.html
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/GroupInfo.java
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/ResourceInfo.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/ObjectTree.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-461
Add VO resources into Firefly table.  Because we are flatten the VOTABLE hierarchy, this information will be lost when the table is exported or saved to disk.
Also:
- allow resources and links to be injected via API
To test:  https://irsawebdev9.ipac.caltech.edu/FIREFLY-461_table_resources/firefly/
- Append some sample RESOURCEs into a VO table them upload it to Firefly.
You should see it at the upload summary as well as when you load that table.
- A new test case added to show how it can be injected via API; case  number 6
https://irsawebdev9.ipac.caltech.edu/FIREFLY-461_table_resources/firefly/test/tests-table.html
> FIREFLY-461: add VO resources to Firefly table.

- src/firefly/js/ui/DownloadDialog.jsx
https://jira.ipac.caltech.edu/browse/IRSA-3411
Add "CancelText" property to DownloadDialog so that the property can be passed to the FormPanel.  
URL: https://irsawebdev9.ipac.caltech.edu/IRSA-3411-finderchart/applications/finderchart/
> IRSA-3411-download popup shouldn't have 'cancel'

- config/app.config
- docs/new-release-procedure.md
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TableRenderer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-523
When a column is fixed, empty and link cells are either fully or partially transparent, allow hidden contents to appear when scrolled under.
To test, use https://irsawebdev9.ipac.caltech.edu/FIREFLY-523-fixed-column-transparency/firefly/demo/table-api.html 
uncheck `use wise catalog`, paste the url into the `URL` field, then put `{"col.Frequency Targeted.fixed": true}` in the META-INFO input box to set the column to fixed.
Here are links to table with empty cells and table with links:
http://dev1.ned.ipac.caltech.edu/cgi-bin/datasearch?search_type=z_id&zv_breaker=30000.0&of=xml_main&objname=m31&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1&objid=58141
http://dev1.ned.ipac.caltech.edu/cgi-bin/datasearch?search_type=Diam_id&of=xml_main …
> FIREFLY-523: fix fixed column cell transparency issue

- src/firefly/js/Firefly.js
- src/firefly/js/metaConvert/DataProductsCntlr.js
- src/firefly/js/metaConvert/DataProductsFactory.js
- src/firefly/js/metaConvert/DataProductsType.js
- src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/visualize/saga/DataProductsWatcher.js
- src/firefly/js/visualize/ui/CoveraeViewer.jsx
- src/firefly/js/visualize/ui/MultiProductViewer.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
This PR includes the following changes to the Data Products Viewer
- Pull down entry: HDU #index (Type) Description/Extname
- Also show a show all images option
- Data that can be both images or table, has two entries
- When a user select the item in the list, by default the viewer should show a table first  not a chart.
- For 1-d image show chart first (seems to make more sense, because a image is made to be visualized)
- Switch buttons 'chart'/'table' _to_  'table'/'chart' 
- When chart is selected, the viewer would show X-Y plot only, no histogram
- In SOFIA, we don't need the grid multi-viewer around the file data product viewer, that can be disabled in the SOFIA context.
https://jira.ipac.caltech.edu/browse/FIREFLY-497
_sofia:_ 
- …
> Firefly-497: Updates for Data Products Viewer

- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/visualize/draw/MocObj.js
https://jira.ipac.caltech.edu/browse/FIREFLY-526
The development fixes the color of the round-up tiles when the color is changed from the color editor.
test: https://irsawebdev9.ipac.caltech.edu/FIREFLY-526_MOC_color/firefly/
* do HiPS image, ex. GALEX GR6 AIS (until March 2014)- Color composition
* zoom the image to fit entirely within the frame
* open the overlay dialog, turn on "MOC - CDS_P_GALEXGR6_AIS_color" layer
* check 'fill' to show MOC in 'fill' style, you will see majority tiles with higher opacity and the round-up tiles with lower opacity (half of high opacity)
* open the color panel to select a different color and check if the color of all tiles including round-up tiles changes accordingly.
> FIREFLY-526 update the fill color for round-up tiles when the color changes

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
https://jira.ipac.caltech.edu/browse/FIREFLY-502
Text comparison is suppose to be case insensitive.  This applies to `like` as well as other comparison operators, i.e. `=`, `>`, `!=`
This was broken.  It is now fixed.
To test: https://fireflydev.ipac.caltech.edu/firefly-502-table-filter-like/firefly/
Bring up a table with `char` data.  Try catalog search or table upload.
Test text filtering on a `char` column.
> FIREFLY-502: table filter text comparison is no longer case insensitive

- src/firefly/test/edu/caltech/ipac/visualize/plot/FitsReadTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-522
This pull request implemented FIREFLY-522.  The wavelength unit tests in the server side were removed since the wavelength calculation and unit tests are done in the front end now.  There is
not URL needed to test.  
To test it, 
1. check out this pr
2. run gradle :fi:test
The wavelength tests in java are gone.
> FIREFLY-522:Clean up wavelength unit test in the java side

- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
https://jira.ipac.caltech.edu/browse/FIREFLY-517
https://jira.ipac.caltech.edu/browse/IRSA-2590
Two tickets above were implemented in this PR. 
- Fixed  bugs in Wavelength calculation formula
- Changed the calculation for the case that has no index table and the coordinate table does not follow the standard
- Update the unit tests based on the new changes
The UI can be tested by combining with https://github.com/IPAC-SW/irsa-ife/pull/105. 
To test unit test, 
gradle :fi:jTest
URL: https://irsawebdev9.ipac.caltech.edu/IRSA-2590-sofia-FIFI-LS/irsaviewer/
> IRSA-2590-SOFIA FIFI-LS: missing information when displaying Level 3 from spectral images

- src/firefly/js/templates/fireflyviewer/ResultsPanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-533
Changed Firefly's tri-view layout as described in ticket.
images top-left, chart top-right, table bottom half.
Test with IRSAViewer:  https://irsakudevlb1.ipac.caltech.edu/firefly-533-triview-layout/
Enter `m51` into `Search for Source` (radar) then click `Search`
on first row, click `To IRSAViewer`
Or, go straight to IRSAViewer: https://irsakudevlb1.ipac.caltech.edu/firefly-533-triview-layout/irsaviewer/
Then do a Catalog search
> FIREFLY-533: Change tri-view layout

- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java
- src/firefly/js/data/FileAnalysis.js
- src/firefly/js/metaConvert/PartAnalyzer.js
Firefly-544: Fixed: now we can add a table to a report
- fixed the bug
- created an example
_to test_
https://fireflydev.ipac.caltech.edu/firefly-544-fa-add-table/firefly/
- upload: http://web.ipac.caltech.edu.s3-us-west-2.amazonaws.com/staff/roby/data-products-test/dp-test.tbl
- click on the 3rd row, one with code EM
- Example for how to add a table: https://github.com/Caltech-IPAC/firefly/blob/368aa15799f5e77016adbdb15d292026b432543e/src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java#L275
> Firefly-544: Fixed: now we can add a table to a report

- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/visualize/DrawLayerCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/RelatedDataUtil.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/region/RegionTask.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
- src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
The brief description about the issues the PR is dealing with:
In the irsaviewer toolbar, there are a few tool buttons whose actions are adding the overlays to the images.  There is a "Color and Overlay" lock button.  When this button is locked, all such overlay tools can add the layers to all the images.  In the layer dialog, when unselected or "Hide All"  such layers, the layers are reappearing unless the "Align and Lock" button is locked.  The other issue is that when the "Hide All" is clicked in the layer dialog, the selected image was hidden as well.   
This PR fixed two issues that affect all the overlay buttons such as Direction, Selection, Marker, Region and North-up as well as the layer Dialog. 
Please test it by comparing with how the irsaviewer in irsadev works.  So you can see …
> IRSA-2651:overlays keep reappearing

- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiUtil.js
- src/firefly/js/templates/fireflyslate/FireflySlate.jsx
- src/firefly/js/templates/fireflyslate/FireflySlateManager.js
- src/firefly/js/templates/fireflyslate/GridLayoutPanel.jsx
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/ui/MultiProductViewer.jsx
Firefly-552: Fixed: Jupyter lab start is broken.
- fixed: Lab cannot start firefly using `startAsAppFromApi`
- fixed: data products cell hangs in slate
https://jira.ipac.caltech.edu/browse/FIREFLY-552
_to test:_ bring up lab and start firefly using `FireflyClient.make_lab_client()`
https://fireflydev.ipac.caltech.edu/firefly-552-jl-open/firefly/
to set the firefly URL in `~/.jupyter/jupyter_notebook_config.json`
add entry:
```json
"Firefly": {
"url":  "https://fireflydev.ipac.caltech.edu/firefly-552-jl-open/firefly/"
}
```
> Firefly-552: Fixed: Jupyter lab start is broken.

- src/firefly/js/util/WebUtil.js
https://jira.ipac.caltech.edu/browse/IRSA-3526
Fixed the bug about parse an object (key, val) issue in WebUtil.js.  
To test:
Follow the steps in the bug report using https://irsakudevlb1.ipac.caltech.edu/front, and then after "send to finderchart", adding the "irsa-3526-finderchart" to the path before the "application/finderchart"
or
Just run 
servlet/api? https://irsakudevlb1.ipac.caltech.edu/irsa-3526-finderchart/applications/finderchart/servlet/api?mode=getResult&UserTargetWorldPt=148.88821;+69.06529;EQ_J2000&subsize=0.083&grid=true
URL
https://irsakudevlb1.ipac.caltech.edu/irsa-3526-finderchart/applications/finderchart/
> irsa-3526-sending to finderchart from gator is broken

- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/MouseReadout.css
- src/firefly/js/visualize/ui/MouseReadout.jsx
- src/firefly/js/visualize/ui/VisHeaderView.jsx
- lock by click cut off on bottom
- upload panel button cutoff on left
- mouse readout paused changed from 200 ms to 100 ms
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-561_
https://fireflydev.ipac.caltech.edu/firefly-561-layout-bugs/firefly/
- confirm the the lock by click is not cut off on the new chrome v83
- confirm that the right side of the upload button on the upload dialog is not cut off
- notice that the mouse readout show the value faster
> Firefly-561: fix small layout issues

- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/DataExtractUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/Sofia1DSpectraExtractor.java
- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java
- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/VOSpectraModel.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
- src/firefly/js/metaConvert/PartAnalyzer.js
The purpose of this PR is to add an DP analyzer that will be used for SOFIA data product purposes. See ticket here: [FIREFLY-465](https://jira.ipac.caltech.edu/browse/FIREFLY-465)
This PR has a counterpart PR for SOFIA in IFE [here](https://github.com/IPAC-SW/irsa-ife/pull/115).
The analyzer will trigger and add an extracted spectra to the report returned using a custom FITS HUD image extractor (also included) and a spectra model defined for SOFIA using VO UCDs and units as standard as possible.
Extracted and added spectra will depend on a couple of columns: instrument, product type and level.
The interesting code to look for and complete or update is here:
- The analyzer: `edu.caltech.ipac.firefly.server.dpanalyze.SofiaAnalyzer`
- The extractor: …
> FIREFLY-465: adding sofia analyzer and include spectra 1d extraction from FITS image data

- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
https://jira.ipac.caltech.edu/browse/FIREFLY-177
This PR is created based on the open PR: FIREFLY-465-sofia-analyzer.  The FIFI-LS FITs converter is used to convert the FIFI-LS wavelength FITS to the standard "WAVE-TAB" format.  I checked the Header and did not find any information about the unit.  
To test:
URL: https://irsakudevlb1.ipac.caltech.edu/firefly-177-sofia/applications/sofia/
In order to avoid longer loading time(testing took me a lot of time), please use:
Target: CasA
Instrument FIFI-LS
and then
filter the url column using "wavelength"
> FIREFLY-177:Add more generic parser/analyzer to support non standard FITS header

- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/DropDownContainer.jsx
1.  found be ned: it not buttons (commands) are set in the menu firefly crashes
2.  found in another PR. when table is saving an uploaded file, it show the name of ${filename}
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-573
_url:_  https://fireflydev.ipac.caltech.edu/firefly-573-2-bugs/firefly/
testing bug 1 - @cwang2016 has a test for it.
testing bug 2 - upload a file from catalog panel and then save it.  It should have a file name that is not ${filename}
> Firefly-573: fix two bugs

- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/Demo1Analyzer.java
- src/firefly/js/data/FileAnalysis.js
- src/firefly/js/metaConvert/DataProductsCntlr.js
- src/firefly/js/metaConvert/DataProductsType.js
- src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/MetaDataMultiProductViewer.jsx
- src/firefly/js/visualize/ui/MultiProductViewer.jsx
- add a setInterpreted to FileAnalysisPart
- indent and don't modify title if setInterpreted is true
- for certain images show image,table, and chart options as one button
- easier to add parts to FileAnalysis object
_Ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-524
- _url:_ https://fireflydev.ipac.caltech.edu/firefly-524-dp/firefly/
- _Upload_: http://web.ipac.caltech.edu.s3-us-west-2.amazonaws.com/staff/roby/data-products-test/dp-test.tbl
- computed products will be indented (line 3 of the table)
- now does image,table,chart toggle see line 21, "demo - image as table"
> Firefly-524: DataProducts viewer update

- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-347
This PR fixed the none responsive tickbox on top of catalog search column.  It is in Firefly, so I did not make an ife branch.  I did test it by switching long/short and individual selection, all seem working fine. I did not clean it up since my fix may not be the the best way.  
Here is the test URL:
https://fireflydev.ipac.caltech.edu/firelfy-347/firefly/
> firelfy-347:tickbox on top of catalog search column

- src/firefly/js/tables/TableUtil.js
This PR fixes bug report by [FIREFLY-580](https://jira.ipac.caltech.edu/browse/FIREFLY-580).
1. column width now taking null sting into consideration
2. when parsing data to IPAC table taking null string as is
Test url:
https://fireflydev.ipac.caltech.edu/firefly-580/firefly/ts.html
upload the the table in [FIREFLY-580](https://jira.ipac.caltech.edu/browse/FIREFLY-580) and follow the steps to produce phase-folded lc. Check the phase-folded table in both table view and text view,  you should note the column width in the text view is corrected and the "null" string is kept as is in the table view.
>  FIREFLY-580 Fixed bug that causes the phase-folded lc failed to load

- src/firefly/js/charts/dataTypes/FireflyGenericData.js
update for 
https://jira.ipac.caltech.edu/browse/FIREFLY-362
test:
https://fireflydev.ipac.caltech.edu/firefly-362-lowerlimits/firefly/test/tests-chart.html
please look at the 3rd chart with both upward and downward pointing arrows. 'Upper Limit' or 'Lower Limit' should be shown at the last line in the tooltip box respectively for downward or upward pointing arrows.
> FIREFLY-362-LowerLimits fix the text shown in the tooltip of upward pointing arrows for lower limit on Y axis values in scatter plots

- src/firefly_data/footprint/Footprint_SOFIA.reg
https://jira.ipac.caltech.edu/browse/FIREFLY-530
Fixed the footprints orientation issued reported in FIREFLY-530.
To test:
URL: https://fireflydev.ipac.caltech.edu/firefly-530-footprint/firefly/
click the URL above
search on M16, 500 arcsec, GLIMPSE and WSIE
when tool loads, pick one of the WISE images as current.
lock by wcs.
overlay SOFIA FOV (attached example has FIFI-LS and HAWC+)
the footprints are aligned
> firefly-530:More coordinate hiccups

- src/firefly/html/firefly-dev.html
- src/firefly/js/Firefly.js
- src/firefly/js/metaConvert/converterUtils.js
- src/firefly/js/visualize/WebPlotRequest.js
the app option is `image.defaultColorTable`
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-584
- https://fireflydev.ipac.caltech.edu/firefly-584-reverse/firefly/
- All image should come up in reverse gray scale.
> Firefly-584: set default color table to reverse grayscale and give app option and option to change it

- src/firefly/js/visualize/task/PlotAdminTask.js
- src/firefly/js/visualize/task/PlotChangeTask.js
https://jira.ipac.caltech.edu/browse/FIREFLY-590  
Fixed restore to default about the color issue.  
I did not change the behavior of the second button.  I don't know what is the expected behavior in the case below:
1.  color overlay lock is in lock position
2. change all plots to a different color (all image changed at the same time)
3.  unlock the color overlay lock, and lock the second lock (image alignment)
4. click "restore default",  all the image changed to the default color and the image
One issue I noticed, "restore to default" also changed to "North up".  Is this the requested behavior? 
Test URL:
https://firefly-590-colorissue.irsakudev.ipac.caltech.edu/irsaviewer/
> firefly-590:IRSA Viewer: return to defaults doesn't change color table back

- docs/release-notes.md
Lots of trailing parentheses missing around ticket names in recent releases.
> Correct markup in release notes

- src/firefly/js/visualize/ui/DrawLayerItemView.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-612
The lag reported is caused by the visibility property in two components.  This only happens when there are more images and layers because restoring them to default takes longer time.  In such situation, when the visibility is true, the component is drawn and displayed before the popup dialog is displayed.  In this PR, the visibility property was changed to default, inherit.  When the parent component is visible, these two components are visible as well.
To test:
URL: https://fireflydev.ipac.caltech.edu/firefly-612-layerpopup/firefly/
1. select at lease four sources to do the image search
2. lock the both overlay and position lock
3. change color 
4. change stretch
5. add many layers as many as 11 layers
6. click restore
7. click the layer …
> FIREFLY-612:weird lag in chrome/safari layers popup

- src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/IRSA-3638
This issue affected all instruments except FIFI-LS because FIFI-LS does not have one-dimension table.  The bug is a small logic issue in the PartAnalyzer.  Please see the attached images in the ticket https://jira.ipac.caltech.edu/browse/IRSA-3638. All the images were screenshots from running the nightly build. 
The issue first was notified in the GREAT instrument which I was adding an analyzer to.   I commented in the ticket that all the instruments have the same issue.  But I did not change the ticket title.
Please test it
URL: https://irsa-3638-analyzer.irsakudev.ipac.caltech.edu/applications/sofia/
If you prefer, you can run the nightly build to compare, thus, you can see the difference between this two build.  The image tag is shown in …
> irsa-3638:The analyzer for "GREAT" instrument image does not have the image tab

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/CropFile.java
- src/firefly/js/visualize/draw/ShapeDataObj.js
https://jira.ipac.caltech.edu/browse/IRSA-2624  
https://jira.ipac.caltech.edu/browse/FIREFLY-628
In this PR, several bugs in two tickets were detected and fixed.   
Please note:  This fix is only for FIFI-LS data.  Each instrument in sofia, the FITs are different.  There could be issues in other instruments.  
Test URL: https://irsa-2624-sofia-chop.irsakudev.ipac.caltech.edu/applications/sofia/
To test:
Search:
CasA
Select "FIFI-LS"  in instrument constrains
> IRSA-2624:FIFI-LS Level 3 "wavelength_resampled" cube fails to be cropped (reported by SMO)

- src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/FIREFLY-629  
This PR fixed issue that the image tab is present for 1D Image.
To test:
URL: https://lijun.irsakudev.ipac.caltech.edu/applications/sofia/
Target: CasA
Instrument: FIFI-LS
> FIREFLY-629:FIFI-LS: Image button shouldn't be present in HDU table type

- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/Sofia1DSpectraExtractor.java
- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaSpectraModel.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
This is a PR that should fix most of the problem seen lately and related to 1d spectra and SOFIA analyzer. In particular:
+ GREAT L1 1D image default shown as chart
+ GREAT L4 checked
+ FIFI-LS types other than L3 wavelength_resampled to be shown as table (binary table types)
+ FORCAST spectra 1D test/check that table extracted and VO model is aligned with data
+ FILTECAM L2 spec spectra 1D test/check that table extracted and VO model is aligned with data
+ EXES L3 'mrgordspec' spectra 1D test/check that table extracted and VO model is aligned with data
See ticket for more details [here FIREFLY-631](https://jira.ipac.caltech.edu/browse/FIREFLY-631).
Please test the different cases here and confirm:
https://firefly-631.irsakudev.ipac.caltech.edu/applications/sofia/
Thanks!
> FIREFLY-631: fixing spectra and other instrument data product viewer related issues

- src/firefly/js/ui/tap/AdvancedADQL.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-596
Test:    https://fireflydev.ipac.caltech.edu/firefly-596-tap-ui-updates/firefly/?__action=layout.showDropDown&view=TAPSearch
Changes:
- Insert "SELECT TOP 1000 * FROM <table>" only when `ADQL Query` field is empty, otherwise insert just the table name.
- Add checkbox `Insert fully-qualified column names`, defaults to checked.
- When checked, insert fully-qualified column names, which means table-name.column-name
- When unchecked, insert just the column name
> TAP UI: Enhance schema browser with qualified name column

- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
The development mainly fixes the disappearing of the circle, box, and ellipse regions. 
https://jira.ipac.caltech.edu/browse/FIREFLY-274
The development adds one more level testing to determine if rendering the following region shapes, 
- circle: 
before fixing, no circle is rendered in case the circle center is out of display area. 
after fixing, if the circle center is out of the display area, further checking if there is an intersection between the border of the circle and the display area. 
- box/ellipse: 
before fixing: no box or ellipse is rendered in case none of the corners of the box (or box enclosing the ellipse)  is inside the display area.
after fixing, if none of the box corners is inside the display area, further checking if there is an intersection between the borders of …
> FIREFLY-274: fix the disappearing of DS9 region

- src/firefly/js/metaConvert/PartAnalyzer.js
[FIREFLY-661](https://jira.ipac.caltech.edu/browse/FIREFLY-661) request is about changing the column name 'DataLine' for 1D image to be matching the title of the HDU or plot title.
Confirm that for GREAT L1, FIFI-Ls L3 and L4 specific product type (details in ticket) you see no more the 'DataLine' column name and the chart axis is also the same as the HDU title.
Test version available here:
https://firefly-661-dataline.irsakudev.ipac.caltech.edu/applications/sofia/
**Note**: I'm not sure what would happened if 1D image doesn't have HDU title.
> FIREFLY-661: replace DataLine generic column name with title HDU

- src/firefly/java/edu/caltech/ipac/firefly/data/sofia/SofiaFitsConverterUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
- src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
- src/firefly/js/metaConvert/PartAnalyzer.js
https://jira.ipac.caltech.edu/browse/IRSA-3726
This ticket is about the consistency of file content menu among instruments.  The FIFI-LS LEVEL4 has "All Image In File" in the file content but FIFI-LS LEVEL_3 does not.  The analysis is logged in the ticket above.  
This PR removed the dependency on added analyzer with convertedFileName set.  The WCS TAB's table column name is changed to wavelength instead of coords. 
To test:
URL: https://lijun-irsa-3276.irsakudev.ipac.caltech.edu/applications/sofia/
> irsa-3276:FIFI-LS level 3 file contents menu

- src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
While testing Bolocam: Galactic Plane Survey (GPS) dataset, we found that Firefly was displaying NaN flux value without units in the readout.
One of the discussion was about unit missing but actually what happened here is that the FITS file fetched from the search (Bolocam GPS, band 1.1 mm around 'ic1396' object) has BITPIX = 64 and bunit = Jy/Beam (see also file sample attached in https://jira.ipac.caltech.edu/browse/FIREFLY-651).
I've added the case of BITPIX = 64 in the code where the readout is getting the flux out of the FITS image.
To test, either:
- upload the file sample (in FIREFLY-651) and check that the readout is no longer NaN and missing the unit
https://fireflydev.ipac.caltech.edu/firefly-656-bitpix-64-support/firefly/?__action=layout.showDropDown&view=FileUploadDropDownCmd …
> Firefly 656 bitpix 64 support

- src/firefly/js/util/VOAnalyzer.js
When a user manually enters the URL of a TAP Service, Firefly runs a number of TAP_SCHEMA queries to the TAP service to gather the metadata. If the VOTable results of these queries contain null entries (i.e. Units, UCDs & UTypes) the Firefly UI crashes with the following JS Exception:
```
VOAnalyzer.js:1155 Uncaught TypeError: Cannot read property 'match' of null
at applyTokenSub (VOAnalyzer.js:1155)
at TableRenderer.js:675
at renderWithHooks (react-dom.development.js:16260)
at updateFunctionComponent (react-dom.development.js:18347)
at updateSimpleMemoComponent (react-dom.development.js:18285)
at updateMemoComponent (react-dom.development.js:18188)
at beginWork$1 (react-dom.development.js:20248)
at HTMLUnknownElement.callCallback (react-dom.development.js:336)
at …
```
> Null Check in VOAnalyzer.applyTokenSub function

- package-lock.json
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HealthCheck.java
https://jira.ipac.caltech.edu/browse/FIREFLY-667
Additional changes:  https://github.com/IPAC-SW/irsa-ife/pull/142
- Firefly 'dev' and 'gwt' need to be modified so that it take header ''X-Forwarded-*' header' when available.  This is because when Firefly is behind a reverse proxy, the proxied host information is stored in these headers.
- Add health check endpoint to all Firefly-based applications.  The check will perform a simple operation, like allocating a small amount of memory to ensure the JVM is healthy.  It will be mapped to `/healthz`.
I do not have a test build.  Please review code to ensure it does not break existing functionality.  More testing to come when IRSA UI apps are served by irsakudev.
> Firefly 667 Firefly related changes needed for irsakubernetes deployment

- src/firefly/html/test/template_loader.js
- src/firefly/html/test/tests-main.html
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
https://jira.ipac.caltech.edu/browse/FIREFLY-674
Allow API user to set custom location of Online-Help.  To test, goto `Test` URL below and scroll down to test #5.
Click on the Help icon(?) at upper right side of the table.  Click on `source: show` to see how it's done.
Test: https://fireflydev.ipac.caltech.edu/firefly-674-help-base-url-api/firefly/test/tests-main.html#test-5
> FIREFLY-674: Add custom Online-Help feature to API

- src/firefly/js/tables/ui/TablePanel.css
https://jira.ipac.caltech.edu/browse/FIREFLY-676
When 'No Data Found' is displayed in the table, the column filter input fox is partially blocked, making it hard to set focus.
Test: https://loi.irsakudev.ipac.caltech.edu/applications/sofia/
See ticket for details on how to duplicate bug.
> FIREFLY-676: Mouse focus blocked on column filter input field

- config/app.config
- docker/base/Dockerfile
- docker/base/customize-firefly.txt
- docker/base/launchTomcat.sh
- docker/base/setupFireflyExample.sh
- docker/base/start-examples.txt
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/java/edu/caltech/ipac/util/FileUtil.java
- remove unused variables
- predefine Firefly runtime directories, making it easier for user to mount into
- move statistics directory into logs/statistics
- VISUALIZE_FITS_SEARCH_PATH now defaults to blank.  Setting it will append to the '/external' set by default.
> Simplify Firefly dockerfile

- src/firefly/java/edu/caltech/ipac/firefly/server/query/UserCatalogQuery.java
- src/firefly/js/tables/TableRequestUtil.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableResultsReducer.js
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/test/edu/caltech/ipac/firefly/core/FileAnalysisTest.java
https://jira.ipac.caltech.edu/browse/IRSA-3851
https://jira.ipac.caltech.edu/browse/IRSA-3563
Also:
- remove multiple TableSearch called
- remove the use of ${filename} token
- fix failed test cause by https://jira.ipac.caltech.edu/browse/IRSA-3721
3851 test: https://irsa-3851-filename-as-title.irsakudev.ipac.caltech.edu/irsaviewer/
Upload multiple files using Catalog upload dialog.
3563 test: https://irsa-3851-filename-as-title.irsakudev.ipac.caltech.edu/applications/finderchart/
batch search, then overlay with same uploaded file.  open layer dialog to see overlay name.
> IRSA-3851: ${filename} appears in table title

- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
Fix the phase fold table column "phase" precision.  
To test on k8 dev build:
https://fireflydev.ipac.caltech.edu/wmi-firefly-693/firefly/ts.html
upload the attached ts table in [Jira ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-693), follow the phase fold steps.
> Firefly 693 ts phase precision too low

- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
https://jira.ipac.caltech.edu/browse/FIREFLY-707
Fixed a bug in the the display of images with WCS defined by PCi_j.  Rotation defined by PCi_j had no effect. (PCi_j is a linear transformation matrix without scale. When CDELT values are equal, the PCi_j matrix is a pure rotation. It is a FITS standard alternative to CROTA2 or CDi_j.)
Test at https://fireflydev.ipac.caltech.edu/firefly-707/firefly/
1. Load image from URL http://spherexdev1:8080/simulated/simulator_delivery1/outputs/SPHEREx_simulation_1_field_2_array_2.fits
2. Use E,N button and notice that the image orientation it is now matching DS9 screenshot. 
3. The catalog of the sources from the third extension now overlays exactly with the image.
> FIREFLY-707: coordinate transformation defined by PCi_j is not applied

- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/Firefly.js
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/InputAreaFieldView.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/Select.jsx
- src/firefly/js/ui/tap/TableColumnsConstraints.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.css
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- _Clean up_:  In "ADQL" mode, there are instructions that say "Schema Browser Usage". However, there's nothing labeled "Schema Browser".
- _Change_: For the column constraints, it's not at all clear what the checkboxes do.  "Column Constraints & Output Selection" maybe.
- _Change_: `1. TAP Service` --> `1. Select TAP Service`
- _Fixed_: FIREFLY-699 specifies a different order than I see at https://firefly-689-combine.irsakudev.ipac.caltech.edu/irsaviewer/
- _Fixed_: "Spatial Constraints", the "Try NED then SIMBAD" button is cut off.
- _Change_: `Single Table` _vs_ `ADQL` --> `Single Table (UI assisted)` _vs_ `Edit ADQL (advanced)`
- _Change_: Single Table" workflow, `Schema` --> `Table Collection (Schema)`
- _Clean up_: 3. Select Table section
- _Change_: `4. Select Constraints` --> `4. …
> Firefly-706: TAP Panel UI cleanup

- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/util/__tests__/VOAnalyzer-test.js
https://jira.ipac.caltech.edu/browse/FIREFLY-717
Instead of adding an option or an attribute to a votable LINK tag which will violate its xml schema, it's best to change the way these values are interpreted.
So, instead of taking the value as is, we will determine whether or not encoding is needed based on how it's used.
If it's used as tokens to construct a URL, then we will encode it.  If the value is intended to be a complete URL, then it's taken as is without any encoding
Test case added with two examples: src/firefly/js/util/tests/VOAnalyzer-test.js
Test deployment is here: https://fireflydev.ipac.caltech.edu/firefly-717-escape-link-url/firefly/
> FIREFLY-717: Auto escape values when used as part of a URL in a <LINK> tag

- src/firefly/js/util/VOAnalyzer.js
This PR has the solution regarding  the issue addressed in https://jira.ipac.caltech.edu/browse/FIREFLY-717 
In the case like  `<LINK href=“${columm_name}”>` where the assignment to 'href' is a single independent token, then the value from the relevant column is treated as a full URL, no escape is involved while resolving a tag with 'href' value.
Test: 
https://fireflydev.ipac.caltech.edu/firefly-717-full-url-token/firefly/
Please test two xml samples adapted from NED votables  attached in https://jira.ipac.caltech.edu/browse/FIREFLY-717.
> FIREFLY-717_full_url_token URL escape option for <LINK> parameters values for single complete token case

- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiUtilImage.jsx
- src/firefly/js/core/ExternalAccessCntlr.js
- src/firefly/js/data/form/PositionFieldDef.js
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/drawingLayers/SearchTarget.js
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/ui/ToolbarButton.css
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/ZoomOptionsPopup.jsx
- src/firefly/js/util/fetch.js
- src/firefly/js/visualize/CoordSys.js
- src/firefly/js/visualize/CoordUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/Point.js
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/iv/EventLayer.jsx
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/task/ZoomTask.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/CoveraeViewer.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- Firefly-678: coverage now supports HMS coordinate strings in the table
- Firefly-380: coverage now updates when a table is filtered to empty
- Firefly-727: coverage now updates correctly when a empty table is loaded
- Firefly-731: keyboard shortcuts now supported when adding extensions from python/remote API
- Firefly-735: reverse the scroll wheel zoom dir
- Firefly-720: fixed: document scroll with mouse wheel zoom
- Firefly-736: only a partial fix to work around safari bugs, we might work on it more later
- `dispatchRecenter` now supports `updateFixedTarget` parameter
- Cleaned up CoordUtil.js - removed options we don't and will probably never use
- Added KOA to TAP list
- https://jira.ipac.caltech.edu/browse/FIREFLY-678
- https://jira.ipac.caltech.edu/browse/FIREFLY-380
- …
> Firefly: multiple tickets:  Firefly-678,  Firefly-380,  Firefly-727, Firefly-731

- src/firefly/java/edu/caltech/ipac/astro/net/NedNameResolver.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
Fixes issue with calling NED passing `Content-Type: application/json`
testing:
https://fireflydev.ipac.caltech.edu/firefly-742-ned-call/firefly/
Use target panel and try : `SSTSL2 J140258.51+542318.3`
> Firefly-742: fixes issue calling NED with a '+'

- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-643
Set the minimum width of the table's column to 5px.  This prevents it from resizing to zero.
Also,
- Reset button in the Table option panel will also reset all columns back to theirs default width
- Adjust row height for several tables with input fields, i.e.  TAP constraint table, IRSA catalog constraint table, and Table Option panel
- Only show More Actions (...) icon when the column has a default text based renderer
Test URL: https://fireflydev.ipac.caltech.edu/firefly-643-col-resize-min/firefly/
> FIREFLY-643: Resizing a column to zero makes it disappear forever

- src/firefly/js/ui/tap/TableSearchMethods.jsx
The change here is to fix how we get the panel prefix id to be used as HelpId when ObsCore is enabled.
It should be picking up the 'location' prefix instead of always 'spatial'.
Please, make sure that the change in 'ObsCore''s case doesn't affect the fieldgroup or other UI bindings and kept the difference between Spatial and Location panel.
This PR include minor label change - FIREFLY-773
> FIREFLY-722: helpid to point to location instead

- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/ui/tap/TableColumnsConstraints.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Table name changes were being properly dispatched, so building queries was being done on stale table names. This fixes that.
This also adds some newline breaking to generated ADQL text when the list of column names is very long, while also breaking on FROM and WHERE keywords.
_To test:_ https://fireflydev.ipac.caltech.edu/brian-fix-table/firefly/
> Fix ADQL query generation

- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
As requested in [IRSA-3871](https://jira.ipac.caltech.edu/browse/IRSA-3871), this PR will only trying to add a case to display the VRAD value and units (m/s is the default) for each plane in the FITs cube. The handling of the generic spectral coordinates translation will be added later. 
To test, use k8s URL: https://fireflydev.ipac.caltech.edu/irsa-3871/firefly/ 
click  "Select Image Souces" -> "Use my image" and upload the test file [IRSA-3871](https://jira.ipac.caltech.edu/browse/IRSA-3871). Also test the wavelength case using [FIFI-LS level 4 data](https://irsa.ipac.caltech.edu/data/SOFIA/FIFI-LS/L4/p3991/data/g12/F0314_FI_IFS_04004934_RED_WXY_100872-100887.fits)
> Irsa 3871 display plane with value and unit in the cube

- src/firefly/js/ui/DownloadDialog.jsx
This PR is a change to add a message above the Title of the download dialog.
This is needed for SOFIA/Spitzer who wants to add some warning depending of the table/file to be downloaded to give the user more info about what they are downloading (IRSA-3944).
No build for testing here, see an example to test in IRSA-3944 PR: https://github.com/IPAC-SW/irsa-ife/pull/154
> FIREFLY-723: adding a pre message above Title for SOFIA/Spitzer need

- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/HiPSPropertyView.jsx
- src/firefly/js/visualize/ui/ImageStatsPopup.jsx
- src/firefly/js/visualize/ui/VisToolbarView.jsx
I've tried to update the help anchors id where it says 'edit' in the ticket [IRSA-3498](https://jira.ipac.caltech.edu/browse/IRSA-3498).
The build of Firefly and IRSAViewer are here for testing:
https://irsa-3498-update-helpid.irsakudev.ipac.caltech.edu/irsaviewer/
https://fireflydev.ipac.caltech.edu/irsa-3498-update-helpid/firefly/
I think that some helpId will point to IRSAViewer content but not in Firefly. Example: '#visualization.selectregion'.
Please check, and let me know. Thanks.
Upload helpid is different in IRSAViewer . this needs an IFE change, see here:https://github.com/IPAC-SW/irsa-ife/pull/158
> IRSA-3498: update help anchors

- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
https://jira.ipac.caltech.edu/browse/IRSA-4111
https://jira.ipac.caltech.edu/browse/IRSA-4113
These 2 tickets are duplicates.
- remove the use of `referer` header because it leads to false info in API case
Test: https://irsa-4111-fc-api-bad-redirect.irsakudev.ipac.caltech.edu/
Taken from IRSA-4113:
> if i go to Radar and search (example around 'arp220') and then if i click on ‘FinderChart’ logo at the bottom in the banner to send it to FinderChart , it displays an empty webapge ‘forbidden’.
@cwang2016 I am not sure you want to test this.  It may requires a lot of setup on your ends.
> IRSA-4111: Finderchart access from NED stopped working

- src/firefly/js/charts/ui/HistogramOptions.jsx
- src/firefly/js/core/BootstrapRegistry.js
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/fieldGroup/FieldGroupUtils.js
- src/firefly/js/templates/hydra/SampleHydra.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/ExampleDialog.jsx
- src/firefly/js/ui/FieldGroup.jsx
- src/firefly/js/ui/FieldGroupConnector.jsx
- src/firefly/js/ui/HiPSSurveyListDisplay.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/SimpleComponent.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/ui/TestSearchPanel.jsx
- src/firefly/js/visualize/ui/ActivateMenu.jsx
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
- src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
- src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Do the following with FieldGroup:
Change Field group to a function component
play with the FieldGroupConnector Effect for the component still works like before.
remove all sorts of functionality that was put into FieldGroup but not used or barely used.
related actions - Monitoring actions with a saga or watch
simplify `keepState` remove initValues functionality (never used)
Removed a lot of `validatorFunc`  properties from field group, I am not sure how this every got in there.
https://fireflydev.ipac.caltech.edu/firefly/
> Firefly 785 fieldgroup

- src/firefly/js/charts/dataTypes/FireflyHeatmap.js
- src/firefly/js/tables/TablesCntlr.js
https://jira.ipac.caltech.edu/browse/IRSA-3841
---
**UPDATED:**
fixed https://jira.ipac.caltech.edu/browse/IRSA-4133
- previous plot vanishes after a long search is sent to background 
---
Heatmap: failed when an expression filter is applied in expanded mode, then close(collapse) and clear filter.
Test: https://irsa-3841-heatmap-fail-clear-filter.irsakudev.ipac.caltech.edu/irsaviewer/
Follow instructions in ticket to reproduce. Or,
- Images -> m31 -> cutout = 2500" -> WISE -> WISE ALLWISE Atlas - Search
- Catalogs -> Search Method = Polygon -> Search
- expand chart -> setttings (gears icon)
- x: w1mpro-w4mpro -> y: w1mpro -> Apply
- select a small area on the chart, then click filter(funnel icon)
- collapse the chart(close icon)
- clear filters (crossed-out funnel icon)
Also:
- I noticed …
> IRSA-3841: chart plots failing when filters are cancelled

- src/firefly/html/test/tests-main.html
- src/firefly/js/Firefly.js
https://jira.ipac.caltech.edu/browse/FIREFLY-789
From ticket: The test for custom URL to go to a different  online help than the default is not working.
This is a case of user's error due to bad documentation.  I fixed the test page to clarify on its usage.  I also added a description to `help.base.url` appOption.
Test: https://fireflydev.ipac.caltech.edu/firefly-789-custom-help-base-url/firefly/test/tests-main.html?test=Custom+Online-Help+URL
- click on `source: show` to see how it's used
- click on table's help icon to see it go to irsaviewer's help instead of firefly's.
> FIREFLY-789: fix custom base.help.url override test page

- docs/release-notes.md
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
Ensure that errors in both the initial retrieval and in the retrieval of a
redirected error document are handled correctly.  Previous version was
incorrectly still reporting an error after a successful redirect.
> Improve nested error handling in retrieval of TAP error documents

- docs/release-notes.md
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/hips/HiPSMasterList.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
- src/firefly/js/data/ServerParams.js
- src/firefly/js/util/Color.js
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/RelatedDataUtil.js
- src/firefly/js/visualize/rawData/ManageRawDataThread.js
- src/firefly/js/visualize/rawData/RawDataCommon.js
- src/firefly/js/visualize/rawData/RawDataOps.js
- src/firefly/js/visualize/rawData/RawDataThreadActionCreators.js
- src/firefly/js/visualize/rawData/RawFloatData.js
- src/firefly/js/visualize/rawData/RawImageTilesGPU.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/task/ImageOverlayTask.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
- src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
- Change mask to use local data
- Mask should be faster with smaller memory load, mask data compress to bits
- Added transparency to the color palette of the color change dialog
- Fixed: Firefly-819 (simple one line fix)
- Fixed: Bias sliders not working in 3-color mode
https://fireflydev.ipac.caltech.edu/firefly-810-mask/firefly/
1. Load a fits file with mask
2. Enable the mask and zoom up and down
https://jira.ipac.caltech.edu/browse/FIREFLY-810
https://jira.ipac.caltech.edu/browse/FIREFLY-819
> Firefly-810: Fixed mask not loading correctly when zooming

- src/firefly/js/ui/ImageSelect.css
- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-800
Make Sections 1-4 of the **Image Search** form scroll together.
In addition to the ticket (need approval?) :
- `4. Select Data Set` toolbar will remain visible when scrolled out of view.
- `Filter by:` and `Selection:` moved to toolbar so that it does not get scrolled off the top.
Also:
- convert to functional component
Test: https://fireflydev.ipac.caltech.edu/firefly-800-image-search-scroll/firefly/
> FIREFLY-800:Make image search sections scroll all together

- src/firefly/js/charts/ui/PlotlySaveDialog.jsx
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/drawingLayers/ComputeWebGridData.js
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/util/fetch.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- standard is referenced in the ticket
- created a utility function for the standard: makeDefaultDownloadFileName in fetch.js
_Test build_: https://fireflydev.ipac.caltech.edu/firefly-823-save-files/firefly/
_Ticket_: https://jira.ipac.caltech.edu/browse/FIREFLY-823
_It is very important to look at the ticket first to understand what was implemented_
Save the following types of files:
Charts
- save a file from chart using the default
- save a file from chart using another name
- add a title and save a chart
Tables
- save a file from table using the defaults
- change the type and save
- edit the name then change the type and save
Images
- save a image or region or png using the default
- change the default then change the type and save
- save a three color
- save a three color but change …
> Firefly-823: Implement the file saving standard

- src/firefly/html/firefly-dev.html
- src/firefly/js/Firefly.js
- src/firefly/js/ui/TargetFeedback.jsx
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- target panel is now settable by two appOptions targetPanelExampleRow1, targetPanelExampleRow2, you can see this in `firefly-dev.html`
- TAP panel examples are now settable by service, You can see this in `Firefly.js`
_test build:_ https://fireflydev.ipac.caltech.edu/firefly-827-examples/firefly/
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-827
1. TAP panel adql - there are specific examples when the service is IRSA or Gaia otherwise it is the default example.
2. https://fireflydev.ipac.caltech.edu/firefly-827-examples/firefly/firefly-dev.html - notice that the target panel examples are different.
> Firefly-827: add example for TargetPanel and Tap Panel to appOptions

- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/ui/ImageSelect.css
- src/firefly/js/ui/tap/TableColumnsConstraints.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.css
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-829
- Input fields inside a table fail to re-render due to bad comparator
- fix Image Search not rendering correctly in Safari
- fix HiPS table not rendering correctly when pop-up in Safari
- fix Image Search 3-color not rendering correctly in Safari
Also:
- auto-size TAP column constraints
Test:
https://fireflydev.ipac.caltech.edu/firefly-829-client-table-bug/firefly/
Make sure to test all 4 bug fixes in all browsers.
Also, I changed the TAP `Column Selection` table to auto-size the column's width.  In my opinion, it looks a lot better.  But, if CCB does not like it, it's easy to undo.
> FIREFLY-829: Input fields inside a table is not being re-rendered correctly

- src/firefly/js/ui/tap/ObsCore.jsx
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
Fixes validation issues in TAP panel, both the error messages themselves and the bubbling up of those errors.
This adds the following logic to the UI when switching between tables:
• If ra/dec columns are identified in a table, ~and the table is NOT an ObsCore table~ or the table is an ObsCore table, then preselect the Spatial dropdown requiring a target in the TAP panel
• If you switch to a table without ra/dec, deselect Spatial dropdown when switching tables.
~• If you switch to ObsCore table (which does have an ra/dec), deselect "Spatial" Dropdown (same widget but it has a different title)~
The last case exists because we don't necessarily expect ra/dec to be the primary way to search an ObsCore table.
> Default Spatial Target with proper Errors validation

- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
This makes a number of changes to improve ivoa.obscore detection and handling:
1. Rewrite query to go by table name 'ivoa.ObsCore' or 'ivoa.obscore' instead of columns, which also makes it so that the obscore-like tables are no longer considered for the radio button UI ( MAST in particular was not happy with column detection query). It seems like the two hardcoded names are most reliable (rather than relying on a lower casing function in ADQL to be implemented, which isn't guaranteed).
2. This pulls up async detection logic out of BasicUI to the parent component so that the radio button works better when advanced ADQL editor is selected (and also helps with a complicated timing issue).
> DM-30780: Fix ivoa.ObsCore detection

- package.json
- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/JsonUtils.js
- src/firefly/js/rpc/SearchServicesJson.js
- yarn.lock
ticket: 
- https://jira.ipac.caltech.edu/browse/FIREFLY-732
test: 
- https://fireflydev.ipac.caltech.edu/firefly-732-custom-json-parser/firefly/
- https://firefly-732-custom-json-parser.irsakudev.ipac.caltech.edu/applications/sofia/
- fork json-bigint to fix its inability to handle scientific notation and long decimal.
- add flag to allow JSON with bigint support only if requested.
- rollback chart's support for bigint as it's not applicable
JSON parsing with BigInt support is limited to only a few Table's calls where it expects original table data with BigInt.
Although, JSON.stringify with BigInt support is available, it need to explicitly request it.
Fork of json-bigint is here: https://github.com/Caltech-IPAC/json-bigint
> FIREFLY-732_custom_JSON_parser

- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
- src/firefly/js/templates/lightcurve/LcPhaseTable.js
Ticket:  https://jira.ipac.caltech.edu/browse/IRSA-4223
Test   :  https://irsa-4223-timeseries-accept-period.irsakudev.ipac.caltech.edu/irsaviewer/timeseries
Phase folded table was originally written as formatted strings.  It did not get converted into real values when we moved to client-side formatting.  This PR fixes this problem by converting the client phase folded table into real values.
Follow instructions in the ticket to test.
> IRSA-4223: 'accept period' doesn't work in new build

- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/FitsUpload.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/FitsCacher.java
https://jira.ipac.caltech.edu/browse/IRSA-4233
When the concept of `shared.work.directory` was introduced in 2018, it was not implemented in GWT.  As a result, GWT based applications are writing all of the 'shared' work files into its local filesystem and are not accessible by other instances of the same app.
Also:
- init stats.log.dir on start up as needed
@robyww  This is more like a FYI.  I don't expect you test it.
> IRSA-4233: Add shared.work.directory concept to GWT codebase

- src/firefly/js/drawingLayers/ExtractLineTool.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
- src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
- src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
Firefly-841: UI improvements
- Expose more zoom buttons to the image embedded zoom menu
- Enabled options to control and turn off the active tool on the image (distance, extract, area select)
- Shift key will always allow for only scrolling
_ticket:_
https://jira.ipac.caltech.edu/browse/FIREFLY-879
_testing_
- Firefly: https://fireflydev.ipac.caltech.edu/firefly-879-ui-improve/firefly/
- ZTF: https://firefly-879-ui-improve.irsakudev.ipac.caltech.edu/applications/ztf/
- FinderChart:  https://firefly-879-ui-improve.irsakudev.ipac.caltech.edu/applications/finderchart/
> Firefly-841: UI improvements

- src/firefly/java/edu/caltech/ipac/astro/ibe/BaseIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/AtlasIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/TwoMassIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/WiseIbeDataSource.java
- src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/ZtfIbeDataSource.java
ticket: https://jira.ipac.caltech.edu/browse/IRSA-4355
test: https://irsa-4355-multiposition-ztf.irsakudev.ipac.caltech.edu/applications/ztf/
- changes include fixes to all missions: atlas, ptf, 2mass, wise, ztf
`makeQueryParam` failed to detect Multi-Object Search parameters because `UserTargetWorldPt` parameter is null.  Add logic to include `filename` as well.
After changes, Multi-Object works fine when Search Region is involved.  When `Image contains target` or `Any pixel overlaps search region`  is select, `Science Exposure` timed out.  This is the same behavior found in OPS.  @wmiipac , you should report this to back-end.
> IRSA-4355: Fix Firefly common IBE processing for multi-position search

- src/firefly/html/css/global.css
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/DialogRootContainer.jsx
- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-855
Test: https://fireflydev.ipac.caltech.edu/firefly-855-improved-tabpanel/firefly/
- Add 'Search open tabs' button  option to TabPanel.jsx
This is modeled after the Chrome browser 'Search Tabs' feature.  When this option is enabled, a `down-arrow` will appears on the right side of the tab panel.  The drop down panel consist of only a single column containing the Tab's title.  
From this dropdown, you can: 
- select the active tab
- sort and filter
`Allow the user to edit the name of a tab` is not implemented, yet.  It requires the tab panel to maintain states, which was not in the original design.  May need to refactor/rewrite `TabPanel.jsx` to accommodate more advance features in the future.
Things to consider:
- This feature is only …
> FIREFLY-855: Improve the firefly tab bar to handle large number of tabs

- buildScript/global.gincl
- buildScript/tasks.gincl
- config/common.prop
- src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/ui/DropDownContainer.jsx
- gets the firefly tag 
- show it in the version dialog
- use the tag to make a user agent for net work calls
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-886
- add a tag to the branch such as `release-2033.44.33` (that you will delete later)
- build the branch
- You should be the tag in the about dialog and any network call will log the user agent as `firefly/2033.44.33`
> Firefly-886: add user agent based on tag to firefly network calls

- src/firefly/js/ui/panel/TabPanel.css
- src/firefly/js/ui/panel/TabPanel.jsx
More changes in irsa-ife:  https://github.com/IPAC-SW/irsa-ife/pull/186
https://jira.ipac.caltech.edu/browse/FIREFLY-891
- Table's text-view off alignment
https://jira.ipac.caltech.edu/browse/FIREFLY-895
- ztf: location of x's to close tabs are now too close to the edge of the tab
- `Open Tabs` search button(down-arrow)  is hidden/cut off when there are many tabs
Test: https://firefly-891-895-tab-text-issues.irsakudev.ipac.caltech.edu/applications/ztf/
> FIREFLY-891-895: ZTF tab and table bugs

- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/BaseHttpServlet.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-888
To duplicate:
Change this line: src/firefly/html/test/template.html:148
to, then rebuild firefly:
`    <script src="https://fireflydev.ipac.caltech.edu/firefly/firefly_loader.js"></script>`
then, goto http://localhost:8080/firefly/test/tests-table.html
- click 'Save' table on any table on that page.
You should noticed the saved file is 'undefined.txt'
Now, change that line: src/firefly/html/test/template.html:148
to, then rebuild firefly:
`    <script src="https://fireflydev.ipac.caltech.edu/firefly-888-cors-exposed-headers/firefly/firefly_loader.js"></script>`
then, goto http://localhost:8080/firefly/test/tests-table.html
- click 'Save' table, again.
You should see that the bug is fixed.
> FIREFLY-888_CORS: Allow CORS access to Content-Disposition response header

- buildScript/global.gincl
- buildScript/tasks.gincl
- config/app.config
- config/common.prop
- docs/new-release-procedure.md
- docs/pre-release-procedure.md
- docs/tags-and-branches.md
- src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/ui/DropDownContainer.css
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/VersionInfo.css
- src/firefly/js/ui/VersionInfo.jsx
- Two new concepts
- pre-release tagging
- dev cycle tagging, including branch
- We now support 3 types of tags
- `release-<version>` - just as before, marks a formal release - ie `release-2022.1.0`
-  `pre-#-<version>` - a prerelease - version is in the form of development cycle - number, ie `pre-5-2022.1`
- `cycle-<version>` - a development cycle, tag is added to the next commit after a release, ie. `cycle-2022.1`
- Updated Gradle build to support finding the current tag, current branch, and last tag to fit a description
- Docs updated
- Firefly library not longer uses the following properties: BuildMajor, BuildMinor,BuildRev, BuildNumber 
- Only applications built against Firefly uses the properties. 
- Version dialog updated substantially  
- Version React code broken out to its own …
> Firefly-915: redo the versioning

- src/firefly/js/drawingLayers/ExtractLineTool.js
- src/firefly/js/drawingLayers/ExtractPointsTool.js
- src/firefly/js/drawingLayers/PointSelection.js
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-908
- **Firefly Library Version:** 2022.1-DEV:firefly-908-extract_6a82
- **Firefly**
- https://fireflydev.ipac.caltech.edu/firefly-908-extract/firefly/
- Load a couple of images, do extract line or point,  go back to the image dialog load some more
- Load a image, do extract line or point, delete it, go back to the image dialog load more images
- **ZTF** 
- https://firefly-908-extract.irsakudev.ipac.caltech.edu/applications/ztf/
- do search, show the images, turn on line or point extraction, change images back click on the table
> Firefly-908: Allow extraction to stay on when new images are added

- src/firefly/js/tables/TableUtil.js
https://jira.ipac.caltech.edu/browse/FIREFLY-931
A simple fix.  Follow ticket description to test:
https://fireflydev.ipac.caltech.edu/firefly-931-save-filtered-table/firefly/
```
After doing a catalog search try to filter the table.
Saving the table to file doesn't work anymore.
Log about promises error appeared in browser console (can be reproduced in any Firefox, Chrome or Safari).
```
> FIREFLY-931: Saving filtered table is broken

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-883
The `Data Type` column in Radar table results no longer have an enumerated filter choices to pick from.
Test: https://firefly-883-choiced-column-fix.irsakudev.ipac.caltech.edu/frontpage/
Do any Radar search -> turn on filter to see the drop-down option under `Data Type` column.
> FIREFLY-883: "Data Type" column in Radar results no longer have filter choices

- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/util/ObsCoreSRegionParser.js
- check table and columns using regular expressions
- also fixed small bug in ObsCoreSRegionParser
_ticket:_ [FIREFLY-935](https://jira.ipac.caltech.edu/browse/FIREFLY-935)
- Version: 2022.1-DEV:firefly-935-quotes_0d46
- URL: https://fireflydev.ipac.caltech.edu/firefly-935-quotes/firefly/
- Do a VizieR Search
- @lrebull Search: VizieR, collections: J_ApJ, table: 752/127  (no other constraints)
- try various searches with the advance panel
> Firefly-935: Add quotes to table or columns where needed

- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- fixed bug
- added support for "OR"
- column constrains and now be entered >1 AND <4
- fixed a 1 pixel layout error with "close button"
_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-847
- Version: 2022.1-DEV:firefly-847-col-parse-err_958e
- URL: https://fireflydev.ipac.caltech.edu/firefly-847-col-parse-err/firefly/
- On the tap panel 
- `IRSA` / `wise_allwise` / `allwise_p3as_psd` / target - `m1` / `400 arcsec`
- on the column constrains  column `nb`: `=1 or =3`, column `w1mpro`: `>10 and < 16`
- click `Populate and edit ADQL` is should look right
- do a search
- try other combinations and look at them in the ADQL panel
> firefly-847: fixed: TAP Panel Bug in "populate" ADQL from the SingleTable input panel

- src/firefly/js/tables/TablesCntlr.js
https://jira.ipac.caltech.edu/browse/FIREFLY-939
```
In certain cases for small searches the table search results are not showing up, 
it just is a blank area instead with not message and no results.
```
This explains it.  This PR fixed the case when an async job returns immediately with `COMPLETED` status, table failed to retrieve the data.
Test: https://fireflydev.ipac.caltech.edu/firefly-939-blank-table/firefly/
> FIREFLY-939: Table search sometime do not return results

- src/firefly/html/test/test-image.html
- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/visualize/MenuItemKeys.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/draw/DrawSymbol.js
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- src/firefly/js/visualize/ui/ZoomButton.jsx
- [Firefly-45](https://jira.ipac.caltech.edu/browse/FIREFLY-45): api option to hide image toolbar
- [Firefly-543](https://jira.ipac.caltech.edu/browse/FIREFLY-543): better computation of  minimum size for coverage
- [Firefly-633](https://jira.ipac.caltech.edu/browse/FIREFLY-633): Improve terminology for zoom max
Testing:
- Version: 2022.1-DEV:firefly-45_543_633_e575
- URL: https://fireflydev.ipac.caltech.edu/firefly-45-543-633/firefly/
- [Firefly-543](https://jira.ipac.caltech.edu/browse/FIREFLY-543)
- do any search and then sort down to 1 object
- now sort down to 3 to 5 objects that are fairly close together
- The image size should be the same.
- [Firefly-633](https://jira.ipac.caltech.edu/browse/FIREFLY-633)
- zoom all the way to make the image as big as possible. 
- Clicking the zoom …
> firefly-45,firefly-543,Firefly-633: Multiple tickets

- src/firefly/js/tables/ui/TablePanel.jsx
Move ZTF Prepare download button into the table's toolbar
https://jira.ipac.caltech.edu/browse/FIREFLY-911
Test: https://firefly-911-ztf-download-location.irsakudev.ipac.caltech.edu/applications/ztf/
Also fixes FIREFLY-948: Table mask pane is loaded outside of Table's div
https://jira.ipac.caltech.edu/browse/FIREFLY-948
Test: https://fireflydev.ipac.caltech.edu/firefly-911-ztf-download-location/firefly/
@cwang2016  Please test.
> FIREFLY-911: Move ZTF Prepare download button into the table's toolbar

- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/InputFieldView.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-960
FIREFLY-960: cancel filters from table doesn't work
- fixed.  regression bug.
https://jira.ipac.caltech.edu/browse/FIREFLY-962
FIREFLY-962: can't turn on filters in catalogs if they're loaded from the background
- fixed.  regression bug.
https://jira.ipac.caltech.edu/browse/FIREFLY-963
FIREFLY-963: strange behavior of tab keys to navigate among filters
- I noticed this behavior in OPS as well.  The table re-render after applying the filter then focus is lost.  I thought it was expected
- But, I went ahead and add the code needed to keep focus after re-rendering.
- Also, I don't understand the "lock by click" test case.  Please test to see if my fix also fixes that.
Test: https://fireflydev.ipac.caltech.edu/firefly-960-962-963-table-filters/f …
> Multiple tickets PR(FIREFLY-960, FIREFLY-962, FIREFLY-963)

- docs/firefly-api-overview.md
- src/firefly/html/demo/table-api.html
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/ui/HiPSImageSelect.jsx
Changes to irsa-ife as well.   https://github.com/IPAC-SW/irsa-ife/pull/204
FIREFLY-969: Set maximum number of values supported in auto-detected category-column filtering to 32
- fixed as requested
FIREFLY-961: ZTF: details tab changes if you click on the gears
- fixed as requested
FIREFLY-970: Display units if table contains units information by default
- ticket updated based on conversation with @ejoliet and @robyww
- please read ticket to determine the impact of this change
Tests: 
https://firefly-969-961-ztf-details.irsakudev.ipac.caltech.edu/applications/ztf/
https://firefly-969-961-ztf-details.irsakudev.ipac.caltech.edu/irsaviewer/
https://firefly-969-961-ztf-details.irsakudev.ipac.caltech.edu/applications/finderchart/
> FIREFLY-969-970-961: Multiple tickets PR

- config/app.config
- config/common.prop
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/Logger.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/StopWatch.java
- src/firefly/java/edu/caltech/ipac/firefly/tools/FitsHeaderTool.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/DataObject.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableDef.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/PrimitiveList.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/util/cache/CacheManager.java
- src/firefly/test/edu/caltech/ipac/firefly/ConfigTest.java
- src/firefly/test/edu/caltech/ipac/firefly/TestUtil.java
- src/firefly/test/edu/caltech/ipac/firefly/core/FileAnalysisTest.java
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
- src/firefly/test/edu/caltech/ipac/table/VoTableReaderTest.java
ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-978
test: https://fireflydev.ipac.caltech.edu/firefly-978-big-table-performance/firefly/
Improve reading IPAC table
- Replace the use of DataGroup and DataObject with indexed values when reading IPAC table to DataGroup
- Greatly reduces read time for large table. (~30%)
- The sample file used to take over 7s now takes around 4.5s to read.
Improve loading IPAC table info DB
- turn off DB logging.  reduce DB ingestion time from 6s to 3s
Lower memory requirement
A sample 1 million rows WISE catalog is around 360mb file; requiring 550mb of RAM in memory.
To ingest the table into the DB requires 3 copies in memory; DataGroup, PrepareStatement, and the DB tables in memory.
- Instead of loading the full table in one batch commit, separate the …
> Firefly 978 big table performance

- docker/launchTomcat.sh
https://jira.ipac.caltech.edu/browse/IRSA-4562
See Tim's comment.  It's not related to original ticket.
Fixed by adding additional `--add-opens` startup parameters.
test: https://irsa-4562-finderchart-api-broken.irsakudev.ipac.caltech.edu/applications/finderchart/servlet/api?locstr=146.22351+22.88512&subsetsize=1.0&reproject=true
> IRSA-4562: finderchart API broken

- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/ui/SimpleComponent.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-756
Test: https://fireflydev.ipac.caltech.edu/firefly-756-string-filter/firefly/
To test, follow the steps provided in the ticket.  
**Note**:  After the fix, the 'first two' values referred in the ticket are no longer first two.  After trimming, they fall under their natural order.
StarTable return string values without trimming.  Trim before saving.
Also:
- add property for JobManager max packaging queue
- small fix to useStoreConnector
> FIREFLY-756: A string filter bug

- docs/firefly-api-overview.md
- src/firefly/html/demo/table-api.html
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-971
Turn on the showFilters by default for all tables except for client table.  Ticket updated to reflect this change.
Test: 
https://fireflydev.ipac.caltech.edu/firefly-971-catalog-filter-on/firefly/
> FIREFLY-971: showFilters defaults to true for all tables except client tables

- src/firefly/html/test/tests-table.html
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/RequestOwner.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ResourceProcessor.java
- src/firefly/js/api/ApiUtilTable.jsx
- src/firefly/js/tables/TableRequestUtil.js
- src/firefly/test/edu/caltech/ipac/firefly/server/query/ResourceProcessorTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-982
This is taken from ticket under implementation notes.
```
Resources are persistent data taken from a unique Table Request. Uniqueness is based on getUniqueID.
Once a resource is created, it will remain unchanged until deleted.
firefly.util.table.makeResourceRequest is created to help work with resources.
See "Table as a Resource" in tests-table.html for sample usage.
Resource comes with basic security features. This info is saved as a .acl file next to the database files.
scope: This control the visibility of a resource. It can be 'global', 'user', or 'protected'.
global is public. Anyone can access it. If this resource is created with a secret, then that secret is needed to delete it.
user is visible to only the user who created it. User …
```
> FIREFLY-982: Add the capability to a create persistent resource from a table request

- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/projection/__tests__/WaveTab-test.js
- src/firefly/js/visualize/projection/__tests__/Wavelength-test.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-989
Test build: https://fireflydev.ipac.caltech.edu/firefly-989-wavetab-1d/firefly/
WAVE-TAB algorithm is described in Section 6 of the second WCS paper: [Representation of spectral coordinates in FITS](https://www.aanda.org/articles/aa/pdf/2006/05/aa3818-05.pdf)
Verified and fixed the WAVE-TAB algorithm for 1d case that was already implemented in Firefly. Tested using the examples in the ticket and Cycle6_GR_OT_06_0112_JJackson_Nessie-A_OI.lmv.fits referenced in "Example MEF, Cube, Spectral Image FITS Files" confluence page. 
- applyDefaultValues in WavelengthHeaderParser.js was wrongly changing all 0 values in PC matrix to the default values.
- TAB algorithm was producing incorrect or misleading results in the cases described in the …
> [FIREFLY-989] WAVE-TAB: The algorithm is producing incorrect results

- docker-compose.yml
- docker/README.md
- docker/launchTomcat.sh
- docker/start-examples.txt
- firefly-docker.env
- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/JsonUtils.js
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/CoreServices.js
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/InputAreaFieldView.jsx
- src/firefly/js/ui/PopupPanel.jsx
- src/firefly/js/ui/PopupPanelHelper.js
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TapKnownServices.js
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- The property java `FIREFLY_OPTIONS` can contain a json string equivalent  `firefly.options` on the client. 
- This json object will be merge with what is running on the client at startup time.
- Also fixes a bug I introduced in my last PR that breaks the advanced TAP panel. Related to converting `InputAreaFieldView` to a functional component
- use docker to test
- define an environment variable from bash
- `export PROPS_FIREFLY_OPTIONS=$'\'{ "tap" : { "additional":{ "services": [ { "label": "I-internal", "value": "https://irsasearchops.ipac.caltech.edu/TAP" } ] } } }\''`
- `docker compose up firefly`
- The tap option should show a new tap service labeled 'I-internal'
- To override the IRSA server try: 
- `export PROPS_FIREFLY_OPTIONS=$'\'{ "tap" : { "additional":{ "services": [ { …
> Firefly-995: support defining then passing firefly options from server to client

- config/web.xml
- docker/launchTomcat.sh
- firefly-docker.env
- src/firefly/js/ui/Banner.css
- src/firefly/js/ui/Banner.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-599
- move user-info to the right of Background Monitor
https://jira.ipac.caltech.edu/browse/FIREFLY-1002
- add docker support to change basic auth path, including the ability to disable it
Manually added `USE_ADMIN_AUTH` override after deployed:
```
kubectl edit deploy firefly-599-1002-userinfo-loc-admin-path-suit
- env:
- name: USE_ADMIN_AUTH
value: false
```
Test: https://firefly-599-1002-userinfo-loc-admin-path.irsakudev.ipac.caltech.edu/suit/
- check user-info is on the right of Background Monitor
- user's name is limited to 150px.  mouse-over to see the complete text
- suit/admin/status does not require user-id/password
> FIREFLY-599_1002: Multi tickets changes

- docker/java.security.override
- docker/launchTomcat.sh
- src/firefly/html/css/global.css
- src/firefly/html/firefly.html
- src/firefly/js/Firefly.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/ChartPanel.css
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/ChartSelectPanel.jsx
- src/firefly/js/charts/ui/ChartWorkArea.jsx
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/MultiChartToolbar.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/ui/TextButton.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/MultiProductViewer.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-994
Test: https://fireflydev.ipac.caltech.edu/firefly-994-multi-table-chart-view/firefly/
Basic description of the added features, copied from ticket.
When useChartWorkArea is enabled,
- Chart Viewer may contains Active Charts and Pinned Charts
- Displayed as tabs or side-by-side
- Top toolbar added with help anchor
- Pin Chart button is available with Active Chart is visible
- When pinning chart
- Ask for title if one does not exist
- Default to table's title if exists otherwise blank
- Not allowed after max number of pinned charts is reached (set at 6)
- On first pin, switch to side-by-side view so the user can visually see a new chart is added to Pinned Charts tab
- When a table is deleted or removed, remove all pinned charts …
> FIREFLY-994: Create chart view that support multiple charts from different tables

- src/firefly/js/charts/ui/ChartWorkArea.jsx
- src/firefly/js/charts/ui/MultiChartToolbar.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1017
https://jira.ipac.caltech.edu/browse/FIREFLY-1018
- FIREFLY-1017: cannot scroll through pinned plots
- FIREFLY-1018: plot title in expanded mode is wrong
- 'Show Table' button not appearing for Histogram charts
See tickets for testing instructions.
https://fireflydev.ipac.caltech.edu/firefly-1017-1018-pin-chart-bugs/firefly/
> FIREFLY-1017-1018 multi tickets commit

- src/firefly/html/css/global.css
- src/firefly/js/charts/ui/ChartPanel.css
- src/firefly/js/charts/ui/ChartWorkArea.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/ui/panel/DockLayoutPanel.jsx
Test: https://firefly-1020-1021-1022-chart-ui-changes.irsakudev.ipac.caltech.edu/irsaviewer/
https://jira.ipac.caltech.edu/browse/FIREFLY-1020
persistent split pane position  
https://jira.ipac.caltech.edu/browse/FIREFLY-1021
plural/singular pinned chart label
https://jira.ipac.caltech.edu/browse/FIREFLY-1022
location of 'pin chart' button
Beside the requested changes, I've also added these:
- Increase max pinned charts to 12 so you can see how crowded it can get.  If you want me to remove the limit completely, I can do that as well.
- Decreased the gap between split panels.  This is a global change.  All split panels will look like this.
- Change Active and Pinned Charts panel UI.  They look like separate tabs now.
I am open to changes.  Just leave comments below.
> FIREFLY-1020-1021-1022: Chart multi-ticket UI changes

- buildScript/gwt_webapp.gincl
- docker/Dockerfile
- docker/README.md
- docker/launchTomcat.sh
- src/firefly/build.gradle
- it's not needed
- it intermittently hangs on npm install, causing a long delay during build
> Remove build_client from GWT builds

- src/firefly/js/core/background/BgMaskPanel.jsx
- src/firefly/js/metaConvert/DataLinkProcessor.js
- src/firefly/js/metaConvert/ServDescConverter.js
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/ConnectionCtx.js
- src/firefly/js/ui/FieldGroup.jsx
- src/firefly/js/ui/InputAreaFieldView.jsx
- src/firefly/js/ui/InputFieldView.css
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/ui/dynamic/DynamicDef.js
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/iv/HiPSTileDrawer.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/task/PlotHipsTask.js
- src/firefly/js/visualize/ui/MultiProductViewer.jsx
- src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
- src/firefly/js/visualize/ui/ServiceDescriptorPanel.jsx
- src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- Visual target selection
- make fields yellow that are being editied
- set FOV smarter
- add help text at top of visual selection, and help icon
- show s_region
- Other stuff:
- revamp aitoff coverage so if AITOFF if always comes up at 0,0 gal
- add a 0,0, galactic button if showing aitoff
- if coverage start with aitoff have option of different image
- fixed: distance tool turn off button sometime shows when it should not
- fixed: remove distributed data” from tool tip
- image will show EXTNAME or EXTTYPE
- Also Fixes: [Firefly-1025](https://jira.ipac.caltech.edu/browse/FIREFLY-1025): improve visual target selection
- https://fireflydev.ipac.caltech.edu/firefly-1030-map-selection/firefly/
- TAP:
- Goto tap dialog and select an area
- do a search with CADC, ivoa/ivoa.obscore - target m1, …
> Firefly-1030: improve visual target selection, (Also Firefly-1025)

- docker/Dockerfile
- docker/launchTomcat.sh
- src/firefly/java/edu/caltech/ipac/firefly/server/security/PersonalAccessToken.java
- src/firefly/java/edu/caltech/ipac/firefly/server/security/SsoAdapter.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1040
- Implements a PersonalAccessToken `SsoAdapter`
- Define property used by PersonalAccessToken to set token at startup
To test:
https://jira.lsstcorp.org/browse/DM-35788
git fetch &&  git checkout FIREFLY-1040_personal_access_token
Add these properties into `./firefly-docker.env`
PROPS_sso__framework__name=PAT
PROPS_sso__req__auth__hosts=.ncsa.illinois.edu,.lsst.cloud
PROPS_sso__access__token=[secret-token]
docker compose up firefly --build
Goto http://localhost:8080/firefly/?__action=layout.showDropDown&view=MultiTableSearchCmd
Enter 'https://data.lsst.cloud/api/tap' into `Select TAP Service` field then [Return]
You should see Schema and Tables loaded.
> FIREFLY-1040: Allow Firefly to startup with a predefined access token

- firefly-docker.env
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HiPSRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/Firefly.js
- src/firefly/js/api/webApiCommands/TapCommands.js
- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/metaConvert/DataProductsFactory.js
- src/firefly/js/metaConvert/ImageDataProductsUtil.js
- src/firefly/js/metaConvert/ObsCoreConverter.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/ui/PopupPanelHelper.js
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/visualize/HiPSMocUtil.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/PlotGroup.js
- src/firefly/js/visualize/RangeValues.js
- src/firefly/js/visualize/WebPlotRequest.js
- src/firefly/js/visualize/reducer/HandlePlotChange.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/ui/DrawLayerPanel.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/PlotInfoPopup.js
- src/firefly/js/visualize/ui/StretchDropDownView.jsx
- src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- Fixed: Expanding/restoring an image in MultiProductViewer causes a reload stretch and color are reset
- Fixed: Exceptions happening when FItsHeaderView is up
- Fixed: Exceptions happening with StretchDropDownView
- Fixed: draw layer panel is hidden at times (zIndex was not correct)
- Fixed: on resize or when popping up mouse readout displayed zoomed to fix when it should not have
- Fixed: Moc validation was not accepting a valid FITs TFORM header
- Fixed: Better support for authorization in URLDownload.java
- Fixed: Expose MOC in Target Hips Panel
- Fixed: double load of web api
- Fixed: TAP search api did not init table correctly, also- fixed some bugs in examples
- Stretch should be sticky on MultiProductViewer
- Stretch should be stick for multi HDU images, if the same extension type …
> Firefly-1045: Fixed several bugs

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1049
Taken from ticket:
This is a regression bug created by [FIREFLY-978](https://jira.ipac.caltech.edu/browse/FIREFLY-978).  In an attempt to save memory, table ingest is separated into batches of 10,000 rows.  However, it failed to increment `ROW_IDX` between batches causing `ROW_IDX` to repeat on large table that requires multiple batches.
Test:  https://fireflydev.ipac.caltech.edu/firefly-1049-filter-by-selected-row/firefly/
- Load a large table (more than 10k rows)
- Select 1 row, then filter by selected row
- Verify that there's only 1 row left
- Clear filter
- bring up Table Options -> Advanced Filter
- enter `ROW_IDX = 0 or (ROW_IDX > 9998 and ROW_IDX < 10002)` into constraints field, then apply
- There should be 4 rows remaining (0, …
> FIREFLY-1049: Table: Filter by selected row returned more than it should

- src/firefly/js/tables/__tests__/TableUtil-test.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/test/edu/caltech/ipac/util/StringUtilsTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1046
Taken from ticket:
StringUtilsTest is a JUnit test for StringUtils.  Most of the functions are not used anymore.  But, we still use a lot of the getters functions, i.e. getInt, getLong, getDouble, getFloat.
Added tests to verify it works as intended as well as to demonstrate its behaviors.
TableUtil-test.js is a JavaScript(Jest) test for TableUtil.js.  Added additional conditions to 'formatValue' test to capture Column's precision use cases (HMS, DMS, F, E, G).
> Firefly 1046: Add additional tests to StringUtilsTest.java and TableUtil-test.js

- src/firefly/js/util/PositionParser.js
- Added a check for latitude/longitude (dec/ra) being out of bounds
- If either ra or dec is out of bounds, setting their value to NaN because the **positionValidateInternal** function in PositionFieldDef.js expects ra/dec to be NaN in order to throw an error message 
-  https://fireflydev.ipac.caltech.edu/firefly-1056-coordinates-validation/firefly/
-  go to Select Target -> Coordinates or Object Name -> Enter valid coordinates for longitude [0,359] and latitude [-90, 90], enter out of bounds coordinates to test error message (error message should specifically say whether longitude or latitude is out of bounds)
- Finally, also enter all other coordinate/position types (name, DB_ID, HMS/DMS to make sure they work as expected)
> Firefly 1056 Coordinates validation for latitude and longitude 

- src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java
- fixed code so that an input like "2020 AA" doesn't return multiple unrelated results (formerly it was querying the API with just "AA", for which we were getting multiple results)
-  https://firefly-1065-naif-resolver-filter.irsakudev.ipac.caltech.edu/applications/wise/
-  Search by Solar System Object/Orbit -> Object Name -> 2020 AA 
- Other Object Names you should test with: 2020, 599994 (2011 EN), 2011 E, 599994, 2011 EN
- 2011 E will return multiple results, and you should be able to scroll through all of them in the dropdown (previously, you were not able to scroll through the last few items for multiple results returned)
- Note: If you search with the input "2020 Ukko" you will get no results (this was formerly supported). The reason is that querying the horizons lookup API with …
> Firefly 1065 naif resolver (multiple results unrelated to input showing up)

- src/firefly/js/metaConvert/PartAnalyzer.js
Replaces and closes #1261 , which was filed against `dev`.
Relevant to processing of results from service descriptor calls.
Please consider for deployment with the bug fix FIREFLY-1066, in 2022.2.3.
> FIREFLY-1068: Recognize and permit default display of flux-based time series

- src/firefly/js/ui/PointShapeSizePicker.jsx
- Converted the ShapePickerWrapper class to a functional component (ShapePicker) 
- The **if** condition inside **componentDidUpdate** in the class component was never being reached (none of the 3 conditions were true for any of the cases I tested: size, symbol and width were always equal to their previous values), so I did not convert that using **useEffect** and only did so for **componentDidMount** and **componentWillUnmount**.  
- The second **if** condition (dlColor !== drawingDef.color) inside the **storeUpdate** (which is called using useStoreConnector) is also never reached, but I have kept this code in place for now. It may come in handy if we modify a shape that is not using the draw layers DrawingDef (but I couldn't figure out how to test that). 
- …
> Firefly 1063 PointShapeSizePicker class to functional component

- src/firefly/js/ui/tap/ObsCore.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- added a call to onChangeDateTimePicker which now shows feedback under user input when selecting date/time from the calendar dialog
- there was an issue with timeOptions.value not being updated to 'mjd' when the 'mjd' radio button was selected by the user. This resulted in the input field also changing its value to 'iso' format when using the calendar dialog to pick a date/time with the 'mjd' radio button selected. I manually set timeOptions.value = timeMode (which reflects the correctly selected radio button). There might be a better way to do this in the future (timeOptions.value should have already been updated to reflect the correct radio button selected). 
- When doing temporal search and selecting 'mjd', the calendar icon was removed. I re-added it, allowing the user to use the …
> Firefly 1075 obs tap date update calendar dialog

- src/firefly/js/ui/DownloadOptionsDialog.jsx
- src/firefly/js/ui/PointShapeSizePicker.jsx
- converted DownloadOptionsDialog to a functional component 
- used useStoreConnector instead of flux.addListener directly 
- made changes to PointShapeSizePicker.jsx's ShapePicker functional component to update state in useEffect instead of (incorrectly) in useStoreConnector itself 
-  https://firefly-1084-downloadoptionsdialog-functional.irsakudev.ipac.caltech.edu/irsaviewer/
- go to Catalogs -> NED -> m1 -> Radius: 100 
- Click on the "Save" icon for the image and for the table (chart save does not use this Download Options Dialog box) 
- For image, try switching between FITS Image, PNG File and Region File and change the file name
- For table, try changing the file format and file name
- Click on "Save" to make sure it downloads the image/table in the selected format 
- Switch between …
> FIREFLY-1084: converting Download Options Dialog to a functional component

- buildScript/webpack.config.js
- docker/Dockerfile
- docker/devMode.sh
- src/firefly/html/demo/table-api.html
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/js/api/ApiHighlevelBuild.js
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/chart-typedefs.jsdoc
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
- src/firefly/js/charts/ui/ChartPanel.css
- src/firefly/js/charts/ui/ChartSelectPanel.jsx
- src/firefly/js/charts/ui/ChartWorkArea.jsx
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/SpectrumOptions.jsx
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/TablePanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1041
Add the ability to combine multiple charts.  Limited to spectra with same axis unit.
Sample data added to the ticket.
To test: https://fireflydev.ipac.caltech.edu/firefly-1041-combine-spectrum/firefly/
Upload 2 or more spectra, then pin them.
Select a spectrum to combine, then click on `Combine Chart`.
A list of 'suitable' charts will appear.  Select 1 or more to continue.
If none show up, then there are no suitable charts to combine with the one you selected.  To test the ability to combine any chart(experimental), check the box `Show All Charts`.
Also added these small changes:
- create source map for both local and dev env
- Docker DevMode get verbose log
- update Table API doc to reflect showInfoButton now default to true
- move and …
> FIREFLY-1041: add feature to combine charts(spectra)

- src/firefly/js/ui/DownloadOptionsDialog.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- Took a bit longer than I expected, but got rid of a lot of code and encountered a couple of bugs and partially fixed them (see below) 
- Got rid of the reducer and and used useFieldGroupValue to get the file type, name and location and then monitor changes in any of those via a useEffect (which basically sets a new filename when the user changes the file name or extension/file type or picks a new filename from the workspace) 
- made MakeFileOptions a react component
-  https://firefly-1085-fitsdownloaddialog-remove-reducer.irsakudev.ipac.caltech.edu/irsaviewer/
- go to TAP -> service: IRSA/NED -> Coordinates or Object Name: m1 -> Radius: 100 
- open the fits download dialog by clicking on the **save** icon
- ensure this works as expected. try changing file type, file name, and file …
> FIREFLY-1085: removing reducer from fitsDownloadDialog

- config/app.config
- docs/server-settings-for-fits-files.md
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisContext.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- fix the `TableUtil.guessFormat()` so it only looks ahead 1k
- work with longs for the file offset header `SPOT_OFF`
- change property to increate the max fits file size
This is a small PR. You can really test it unless you start you server at about 20G and have a 14G fits file. So, just look at the code.
> firefly-1103: Fix firefly fITS reader so it can read Multiple large HDUs for a 14G file

- src/firefly/js/visualize/ui/MatchLockDropDown.jsx
- Related design ticket: [Firefly-275](https://jira.ipac.caltech.edu/browse/FIREFLY-275)
- in MatchLockDropDown.jsx, added a warning when user tries to align by WCS or Target and if one or more images don't have WCS
- Warning shows the plot titles for all of the image(s) without WCS 
- If multiple images don't have WCS, the warning popup looks a bit messy. Tried to clean it by adding some letter-spacing and line-height with CSS, but taking recommendations on how to make it look even better. 
-   https://fireflydev.ipac.caltech.edu/firefly-1092-no-wcs-warning/firefly/
-  add/upload some FITS images with and without WCS
- Try aligning by WCS/Target with an image with WCS selected 
- Also try aligning by pixel origins and by pixel at image centers to make sure those work as expected
> Firefly-1092 no WCS warning when trying to align by WCS

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSExtractToTable.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/visualize/FitsHeaderUtil.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
- Also added some features mentioned in firefly-1059, combinations types average, add and bitwise OR
- Some general clean up, refactored some code around to make it cleaner
- new files: `FitsExtract.java` and `FITSExtractToTable.java`
- https://fireflydev.ipac.caltech.edu/firefly-1060-extract/firefly/
- Do an extraction and pin a table - notice the unit type should be correct with you FITS
- For a over `1x1` size you have access to `average`, `add`, or `OR` (`OR` only available to int or long HDUs)
> Firefly-1060: Support datatype and other features in extract

- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/options/BasicOptions.jsx
- src/firefly/js/charts/ui/options/SpectrumOptions.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1095
Test deployment: https://fireflydev.ipac.caltech.edu/firefly-1095-combinedunits/firefly/
- On combined chart creation, the units are converted to the unit of the base trace for all traces with compatible units
- On combined chart update, the units are applied to all traces with compatible units 
- Errors in non-active traces are preserved.
> [FIREFLY-1095] Combine Spectra with unit conversion

- src/firefly/js/drawingLayers/ImageRoot.js
Design ticket:   [Firefly-758](https://jira.ipac.caltech.edu/browse/FIREFLY-758)
- changed HiPS and FITS text in layers popup to "Image (HiPS)" and "Image (FITS)" respectively
- in the code, I've hardcoded `showSize` to `false` and commented out the code next to it that determines if `showSize's` value. This is in case we ever decide to go back and show "Search Size" next to "Image (FITS)" in the layers popup as we previously did. I can get rid of this code if this is not needed. 
**Testing**: https://fireflydev.ipac.caltech.edu/firefly-1091-layers-popup-text/firefly
- Search for something that'll have both FITS / HiPS. From "TAP/Table Searches", under "IRSA Catalogs", I selected "Spitzer" and searched for "m1". 
- Then with "FITS" selected, open the layers popup, and you should see …
> FIREFLY-1091: changed layers popup text to be consistent

- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
- src/firefly/js/ui/FitsRotationDialog.jsx
- src/firefly/js/ui/RangeSlider.jsx
- src/firefly/js/ui/RangeSliderView.jsx
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
Fixes [FIREFLY-1119](https://jira.ipac.caltech.edu/browse/FIREFLY-1119)
- This component doesn't really require state, so removed that and made it a pure functional component.
- Cleaned up code and removed unused `value` prop
- Replaced `wrapperStyle` with `style`
https://fireflydev.ipac.caltech.edu/firefly-1119-range-slider-func/firefly/
Go to Table Search > IRSA Catalogs > Search. Now on Image toolbar, go to:
- Color dropdown for testing all 3 sliders
- Tools > Rotate Image for testing rotation slider 
Go to Time Series tool, then:
- In the images panel (bottom), go to the toolbar and select stretch dropdown (4th icon) and then color stretch option (1st option). Make sure "Asinh" stretch type is selected, for testing the slider for setting Q
- Click the period finder button, test the …
> Firefly 1119: Converted RangeSliderView to functional component

- src/firefly/js/charts/ui/PlotlyChartArea.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1096
Test deployment: https://fireflydev.ipac.caltech.edu/firefly-1096-chart-selection/firefly/
1. Clicking to highlight a data point of an inactive trace now switches the active trace and highlight.
2. Selecting an area from an inactive trace changes the active trace unless some active trace points are also selected. Clicking Select or Filter button at this point will act on currently active trace. This works for scatter chart only. For heatmap-like chart, the warning is issued if no active trace points are included into selection.
> FIREFLY-1096 Selection on multi-trace chart

- src/firefly/js/drawingLayers/ImageRoot.js
- Increased max width of the layers popup to compensate for longer file names 
- https://fireflydev.ipac.caltech.edu/firefly-1091-layerswidth/firefly
- go to the Upload panel and upload a fits file (ideally one with multiple images) and select all images. Select the default option "All images in one window" and load all images. 
- Go back to the upload panel, and load just one or two images this time. 
- Then bring up the layers popup and switch between the images and notice how the width of the layers popup changes (increases for the one with multiple images because of the current naming convention - this will be changed in my other ticket **Firefly-1104**, but for now this serves as a good way to test long file names - the other option is to just use a file with a really long name). …
> FIREFLY-1091 increased maxWidth of layers popup

- src/firefly/js/ui/FieldGroup.jsx
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
**Updates** **(11/9)**: 
- Fixed code post PR comments
- moved FieldGroup over to FileUploadDropdown. 
- showing the upload panel as a dialog from the "Add MOC" dialog by calling showUploadDialog() with acceptMoc = true. FileAnalysis in FileUploadViewPanel checks if the file **isMoc** and if acceptMoc = true, if it's not moc, display a warning (although right now the warning is displayed even before you try and upload a file - need to fix this). 
- After loading MOC from the upload panel, the upload panel still stays in place (showUploadDialog's onSubmit would ideally call dispatchHideDialog - but I've commented it out for now since that was interfering with resultSuccess's request object being undefined for some reason - looking into this as well). 
- ImageDisplayOption's selectedImages …
> Firefly 1104 file upload view panel reusability

- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- added upload panel as a FieldGroupTab (alongside "Search" / "Featured MOC") in the HiPS/MOC **Add MOC Layer** dialog 
- keepState for this FieldGroup is currently set to true. Should I change it to false? (it was false when we were launching the upload dialog separately from the HiPS/MOC **Add MOC Layer** dialog)
- https://fireflydev.ipac.caltech.edu/firefly-1124-hips-tabs/firefly
- open a HiPS image (search for m1, choose image type "View HiPS Image") 
- From the **HiPS/MOC** dropdown, select **Add MOC Layer**. Toggle between "Search" and "Use my MOC" tabs. 
- In the "Use my MOC" tab, attempt to upload a non-MOC file (should give you warning), and if you attempt to load it, you should get a popup error/warning. Now attempt to upload a moc fits file, this should work as expected. Make …
> Firefly-1124 hips tabs

- src/firefly/java/edu/caltech/ipac/firefly/data/Version.java
- src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/VersionUtil.java
Fixes [FIREFLY-1116](https://jira.ipac.caltech.edu/browse/FIREFLY-1116)
TODOs:
https://firefly-1116-echo-version.irsakudev.ipac.caltech.edu/irsaviewer/admin/status
https://fireflydev.ipac.caltech.edu/firefly-1116-echo-version/firefly/admin/status
I couldn't find them on jenkins build console, hence attachin console logs at my local machine (see last 6 lines of each):
```
==> /Users/jsinghal/dev/server/tomcat/logs/irsaviewer.log <==
12/08 17:51:40  INFO   Thread: Catalina-utility-1  cache.EhcacheProvider#log:315
shared cache manager config file: /Users/jsinghal/dev/server/tomcat/webapps/irsaviewer/WEB-INF/config/shared_ehcache.xml
12/08 17:51:40  INFO   Thread: Catalina-utility-1  server.ServerContext#log:315
CACHE_PROVIDER : edu.caltech.ipac.firefly.server.cache.EhcacheProvider
WORK_DIR …
```
> FIREFLY-1116: Echo version information to console log and /admin/status panel

- docker/Dockerfile
- docker/launchTomcat.sh
- firefly-docker.env
https://jira.ipac.caltech.edu/browse/FIREFLY-1121
Add Firefly docker support for setting a base deployed path(baseURL).
`baseURL` is passed into the container as an environment variable.  It will be picked up on first start and cannot be changed for the duration of the container's lifetime.
To test, 
- checkout this branch
- uncomment `#baseURL=/my/version/` at firefly-docker.env:6
```bash
cd ./firefly
docker compose up firefly --build
```
Then, goto http://localhost:8080/my/version/firefly/ to see Firefly deployed at the defined baseURL.
> add base path settings to Firefly docker

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/PinnedChartPanel.jsx
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
- the major changes are in ChartUtil.js. Added an ActionWatcher to watch for chart updates
- the callback of this action watcher then ensures that the chart is fully loaded before calling pinChart to pin the chart 
- temporarily commented out the call to DefaultChartsContainer in ChartsContainer.jsx and calling PinnedChartPanel directly, so that you can test pinning charts from both the extraction dialog and the pin chart button to ensure both work as expected 
- some ESLint suggested cleanup in PlotlyChartArea.jsx 
**Updates 12/20**
- When allowPinnedCharts() is set to true, the extraction dialog button will read "Pin Chart/Table", otherwise it will just read "Pin Table" 
- Better code segmentation and separation of concern based on @loitly's feedback and code 
**Updates 12/21 - 1.0**
- …
> FIREFLY-1024: Pinning charts from extraction dialog 

- config/app.config
- config/common.prop
- docker/Dockerfile
- docker/devMode.sh
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/tables/ui/AddColumn.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1138
`help.base.url` used to be compiled into JavaScripted.   Make it an application property so that it can be overridden by environment variable.
Additional changes here: 
https://github.com/lsst/suit/pull/46
https://github.com/IPAC-SW/irsa-ife/pull/239
Also:
- set add-column helpId
- cleanup work-dir init and logging
- change how tomcat is install in dev-mode
Test: https://firefly-1138-base-help-url.irsakudev.ipac.caltech.edu/suit
*** Manually added to `env` after deployed via `kubectl`.
```yaml
- name: PROPS_help__base__url
value: https://irsa.ipac.caltech.edu/onlinehelp/wise
```
When clicking on help icon(?), it will go to IRSA WISE help.
** NOTE:  @robyww pay attention to how this is added to `FIREFLY_OPTIONS` in `AppServerCommands.java`. …
> FIREFLY-1138: Make help base URL a runtime configuratable property

- firefly-docker.env
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ResourceProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1136
- define cleanup parameters as props
- fine tune cleanup policy
- added better visibility via /admin/status
Not much to test.  Review policy and cleanup parameters to make sure it's sensible.
`1 million max memory rows for every 1GB of memory at startup.` is a conservative default setting.  The idea is to use custom props for special use case.
> FIREFLY-1136: embedded DB customization via props

- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/fireflyslate/FireflySlate.jsx
- src/firefly/js/ui/DefaultSearchActions.js
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- added more parameter checking in TAP
- Fixed a small bug in ServerContext with choosing working directory
- added "click-to-search" masking to control which features are avilable.
- Test on https://data-int.lsst.cloud/
- search a table 
- Use click to search feature
- try searching the truth table or obscore from image after selecting an area
- try searching the truth table or obscore  from table
> Firefly-1144: add better support tap search params for click-to-action

- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/FileUploadUtil.js
- src/firefly/js/ui/HiPSImageSelect.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- really a draft PR, more work needs to be done but wanted to check if it looks okay so far
- most of the work that's left is for **FileUploadProcessor** (**FileAnalysis** in **FileUploadViewPanel** takes care of giving users warnings for file types not allowed - but they're still able to load files of types not in acceptList - that'll need to be taken care of in the **resultSuccess** function of **FileUpoadProcessor**)
- added checks in **ImageDisplayOption** and **TableDisplayOption** to show appropriate checkboxes (for spectra, moc, images, etc.) based on what's in acceptList 
- Currently in **FileUploadViewPanel's** **getLoadButtonText** function, I added warnings for when the user attempts to select tables and images (when either one is not present in the acceptList) 
- this is not …
> Firefly 1130 Modify FileUploadViewPanel to take an accept list

- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- added a new prop in FileUploadViewPanel: acceptOneItem (when it's true, we only allow user to select and load with one entry) 
- Default value of acceptOneItem is false (so we accept any number of entries) but FileUploadDropdown can be called with acceptOneItem set to true 
- some small changes to in FileUploadViewPanel and FileUploadProcessor to accommodate for acceptOneItem being true
- To hide checkboxes, I call TabelPanel with selectable={false} when acceptOneItem is true
- https://fireflydev.ipac.caltech.edu/firefly-1147-acceptonlyoneitem/firefly/firefly-dev.html
-  Go to Test Searches -> Uploads
- All of the buttons here call the upload panel with acceptOneItem set to true 
- Click on "Tables Only" or "All Tables" upload, and upload a FITS file with both tables and images
- ensure …
> Firefly-1147: Modify upload panel to accept/allow one item

- package.json
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TablePref.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/util/BrowserCache.js
- src/firefly/js/visualize/ui/CatalogSelectViewPanel.jsx
- yarn.lock
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-613
Test: https://fireflydev.ipac.caltech.edu/firefly-613-table-col-sticky/firefly/
Remember user's selection from Table Options, then apply the same settings to the same table.  This includes columns, showUnits, showFilters, and showTypes.
`same` is defined with a `tbl_pref_key` tableMeta key, or the uniqueness of the combined column names in the same order.  
When previous settings(preferences) are applied to a table, show an option to clear it.
What is the difference between `Reset` and `clear preferences`.  Both will clear preferences and reset columns, showUnits, showFilters, and showTypes to default settings.  `Reset` also reset the `Page Size` and any filters added to the table.
Things to consider:
- Is there another way of …
> FIREFLY-613: remember table options selection

- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
Fixes [FIREFLY-1146](https://jira.ipac.caltech.edu/browse/FIREFLY-1146)
Since FIREFLY-250 was fixed, target is stored in its own field group. So updated the group key where target is set through intiArgs (by search actions)
https://fireflydev.ipac.caltech.edu/firefly-1146-image-search-selection-fix/firefly/
when you: show an image -> select an area -> click on binoculars dropdown -> Search FITS/HiPS at region center, it should bring up ImageSearchPanel with target set to the coordinates of the center of my selection (as shown in the dropdown in bold)
> FIREFLY-1146: Fix target field not updating when searching at selected region in image viewer

- src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonFromExternalTask.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/JsonStringProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/ui/TimePanel.jsx
- src/firefly/js/ui/TimeUIUtil.js
- src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
- src/firefly/js/ui/tap/TemportalSearch.jsx
- src/firefly/js/ui/tap/TimeRangePanel.jsx
Changes in firefly as per https://github.com/IPAC-SW/irsa-ife/pull/241
-  @loitly added JSON String Search Processor to simplify simple JSON requests - was needed to query suggestion list of observers for SHA "search by observers" panel
- Made changes in TimeRangePanel component so that it can be used in SHA "search by date":
- time mode can now be specified as fixed (no radio group selection)
- time panel feedback is shown as per fixed or unfixed time mode 
- labels, examples, and styles are customizable
In context of SHA: https://irsa-3143-sha-search-by-program.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
In general: https://fireflydev.ipac.caltech.edu/irsa-3143-sha-search-by-program/firefly
> IRSA-3143: SHA migration: Add search by Program, Campaign, Observer, and Observation Date

- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysisReport.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/java/edu/caltech/ipac/firefly/util/Ref.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/data/FileAnalysis.js
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/FileUploadUtil.js
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.css
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- added support for upload of UWS job files via the upload panel
- added a button to allow user to "Show UWS Job Info" after a successful upload 
- **Updates 2/16**:
- changes in resultSuccess (in FileUploadProcessor) to allow user to "Load" the UWS job and get back table(s) 
- changed uws job info from "Show UWS Job Info" button to just showing it directly in the upload panel after uploading a UWS job url 
- the 'query' value for uws job info is really long, so I added some css to reel it in (see class 'FileUpload__uws' in FileUploadViewPanel.css)...there may be a better way to do this
- **Updates 2/21**:
- improved error message when trying to upload a uws xml file (not from the "upload from URL" option)
- also disabled loading in this case, giving an error dialog instead 
- made css …
> FIREFLY-1129: Support UWS job file uploads via the upload panel

- src/firefly/js/api/webApiCommands/DatalinkUICommands.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/TargetFeedback.jsx
- src/firefly/js/ui/dynamic/DLGeneratedDropDown.css
- src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
- src/firefly/js/ui/dynamic/FetchDatalinkTable.js
- src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
- src/firefly/js/visualize/task/PlotHipsTask.js
- Add side bar using table
- Any data set can be select
- These are URL's that can be used to launch IrsaViewer from atlas type web pages.
- Try different URLs:
- https://firefly-1140-atlas-sidebar.irsakudev.ipac.caltech.edu/irsaviewer/?api=dl&id=iras_issa
- https://firefly-1140-atlas-sidebar.irsakudev.ipac.caltech.edu/irsaviewer/?api=dl&id=wise_z0mgs
- https://firefly-1140-atlas-sidebar.irsakudev.ipac.caltech.edu/irsaviewer/?api=dl&id=herschel_phpdp&showChooser
- https://firefly-1140-atlas-sidebar.irsakudev.ipac.caltech.edu/irsaviewer/?api=dl&id=msx&showChooser=true
- look at the URL doc
- https://firefly-1140-atlas-sidebar.irsakudev.ipac.caltech.edu/irsaviewer/?api=dl
> Firefly-1140: Add side bar that list the whole registry

- src/firefly/java/edu/caltech/ipac/firefly/server/catquery/CatMasterTableQuery.java
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/IRSA-5077
`info` and `ColumnDef` links are broken in IRSA ops.
- Also fixed broken 'Table Selection' links under `name` column
This happens on first load as well as when `Column Def` does not exists
Test URL: https://irsa-5077-info-link.irsakudev.ipac.caltech.edu/irsaviewer/
This is built with `ops` env and uses IRSA ops backend.  It should appear as if it's in ops.
To test when there's no `ColumnDef`, select project = `IRAS`.
> IRSA-5077: Broken 'info' and 'Column Def' links under catalog listing

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
- src/firefly/js/ui/NaifidPanel.jsx
- src/firefly/js/ui/NaifidPanelWorker.js
Added naifIdFormat to NaifIdPanel component and server-side NaifIdresolver to be able to resolve naif IDs in 7 digit (old) format if specified.
1. https://irsa-5027-search-by-naifid-fix.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
In search by moving object, typing Gaspra (an asteroid) should lead to naif Id = `2000951` instead of `20000951` 
2. https://irsa-5027-search-by-naifid-fix.irsakudev.ipac.caltech.edu/applications/sofia/
In precovery, typing Gaspra should lead to `20000951` (original 8-digit format naif ID returned by horizons)
> IRSA-5027: Fixed search-by-naifID not working when using name over id field

- src/firefly/js/core/background/BgMonitorButton.jsx
- Investigated the bug causing the crash, eventually a one character fix in BgMonitorButton.jsx checking if "**info**" exists before accessing its **jobInfo** attribute. 
- the irsa-ife PR (which most likely needs to be deleted now): https://github.com/IPAC-SW/irsa-ife/pull/247 
**Updates 3/16**
- Removed fits and hips options from the click to search (binocular) tool for finderchart
- https://firefly-1155-finderchart-tap-bug.irsakudev.ipac.caltech.edu/applications/finderchart
- @lrebull I didn't test this extensively, but I tested tap search from the binocular/click on search (cone/rectangular) tool and from catalogs as well. I believe this fixes the crash issue. 
- See Luisa's video on [Firefly-1155](https://jira.ipac.caltech.edu/browse/FIREFLY-1155) 
- Go to the "Multiple Positions" …
> FIREFLY-1155: fixed crash on tap search in finderchart

- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- created a new tab "Loaded Tables" in the upload table chooser dialog next to the "Upload Table" tab
- this "Loaded Tables" tab displays all existing tables
- user can select and load one of these into the tap panel
- **Updates 3/14**
- made some small changes per @loitly's comments, including a small cleanup in FileUploadDropdown.jsx as well. Test build is also updated. 
- **Updates 3/20**
- added 2 new columns (number of columns, number of rows) and changed title of "Loaded Tables" to "Table Title" 
- using 'use' column to filter in ADQL query in TapSearchPanel 
- fixed the issue where I was grabbing tables from "getTableGroup().tables". Now filtering should work and still grab the correct currently selected table and load it into the tap panel. @loitly 
- test build below is updated
- …
> FIREFLY-1148: table chooser to load existing table into tap panel

- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- see video on ticket link for description of the bug
- took some time to track this down, but I think this fixes the issue with doing stuff like **1/col_name** (if col_name has any zero values - that would result in infinity) 
- if you want to track down the issue on the client: see, for example, line 141 in FireflyHeatmap.js
- Here, **decimateKey** (from the tableMeta) results in **yUnit/dy** = **infinity** (for the example provided in the ticket video, where the Y axis is set to 1/parallax) 
- and subsequently, all calls to **getCenter(xval, yval)** (line 162) result in the **y** value = **infinity** 
- So, added a check to skip any rows in **doDecimation** function where xval or yval is infinite 
- https://fireflydev.ipac.caltech.edu/firefly-1089-nan-plot-err/firefly
- load a table, …
> Firefly-1089: fix for nan/inf plot errors 

- src/firefly/js/ui/rc-slider.css
There was -4px margin-left set on handle that was causing this problem.
Also, I noticed this problem was in all other instances of range slider like color band panel too so this fix is for all.
https://fireflydev.ipac.caltech.edu/firefly-669-rotate-slider-offset/firefly
Image search -> FITS Image, m81, WISE All -> toolbar in Image Grid:
1. Tools dropdown -> Rotate/flip -> enter 180 deg, the slider handle's center and marker's center should be on same vertical line (imaginary)
2. Color dropdown -> set color bar slider to 3, it should again vertically aligned with marker (which it wasn't earlier - [test here](https://fireflydev.ipac.caltech.edu/firefly/))
> FIREFLY-669: Fix offset in rotate image slider's handle 

- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/templates/lightcurve/LcManager.js
Fixes [FIREFLY-1061](https://jira.ipac.caltech.edu/browse/FIREFLY-1061)
- ~Simply removed the Page size element~ remove page element when it is equal to max rows
https://fireflydev.ipac.caltech.edu/firefly-1061-remove-page-size/firefly/?__action=layout.showDropDown&
Go to TAP, click gear icon in "Output Column Selection and Constraints" table, there shouldn't be any page size in top right and everything else should work as expected.
Do a catalog search, the page size should appear on clicking gear icon
> FIREFLY-1061: Fix "Page size" appearing in client-table gears dialogs

- src/firefly/java/edu/caltech/ipac/firefly/server/RequestAgent.java
- should use 'X-Forwarded-Host' header first
> FIREFLY-1188: Firefly picks up the wrong host requested header when behind a reverse proxy

- config/app.config
- config/common.prop
- src/firefly/js/core/AppDataCntlr.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1218
More changes here:
https://github.com/IPAC-SW/irsa-ife/pull/254
https://github.com/lsst/suit/pull/48
Moved server-side declaration to global_vars(__$HELP_BASE_URL) so that it can be overridden as a firefly option on the client.  Everything should work as it did before.
Test:
https://fireflydev.ipac.caltech.edu/firefly-1218-help-base-url/firefly/
https://firefly-1218-help-base-url.irsakudev.ipac.caltech.edu/applications/sofia/
https://firefly-1218-help-base-url.irsakudev.ipac.caltech.edu/suit/
> FIREFLY-1218: Allow onlinehelp base URL to be overridden as firefly options on the client

- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
- src/firefly/java/edu/caltech/ipac/table/io/SpectrumMetaInspector.java
- src/firefly/js/util/VOAnalyzer.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1166
Test: https://fireflydev.ipac.caltech.edu/firefly-1166-spectral-dm-1-2/firefly
The ticket is to recognize Spectral order and SED proposed in SDM V1.2.  We are already doing it.
In this PR, I added the proposed relative order(RelOrder) as one of the meta we can recognize even though we have no use for it, yet.  I also did minor code cleanup.
To test, replace utype `ipac:Spectrum.Data.SpectralAxis.Order` with `spec:Spectrum.Data.SpectralAxis.Order` in your spectrum table, then upload into Firefly.  Firefly should display it as spectral order.
> FIREFLY-1166: Recognize Spectral order and SED proposed in SDM V1.2

- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-712
- IPAC table requires column type to be lower case.  Convert types to lower case when reading in.
Test: https://fireflydev.ipac.caltech.edu/firefly-712-ipac-type/firefly
Upload the attached sample table file from the ticket.  All column types appeared in lower case and recognized as it should.
> FIREFLY-712: Table upload not accepting compliant IPAC tables

- src/firefly/java/edu/caltech/ipac/firefly/visualize/ClientFitsHeader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageHeader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/Zscale.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/ImageStretch.java
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
This is one line bug fix for incorrect `NaN` values in place of zeros in pixel value display.
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1222
Test URL: https://fireflydev.ipac.caltech.edu/firefly-1222-zero-val/firefly
To test, upload the FITS image attached to the ticket. Note, that zero values for both float and integer values are now displayed correctly. (They are displayed as `NaN` in https://fireflydev.ipac.caltech.edu/firefly)
> FIREFLY-1222 Bug fix in the readout of pixels with value 0.

- src/firefly/js/ui/DefaultSearchActions.js
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- the  first bug/issue: if you did a whole table search with a TAP service selected that does not support upload, you would still see the table you just did a whole table search with on the TAP panel, leading to all sorts of issues. 
- This fixes that bug, by checking if this TAP service supports uploads or not, if it does not - don't show the table on the TAP panel for this service
- instead, display a warning message. 
- **Updates 4/19** 
- updated the warning message to be displayed after you do a click to action (whole table) search and switch to a service such as NED that does not support uploads
- fixed the Position Column (from the uploaded table) bugs, see testing instructions below 
- **Updates 4/21** 
- addressed PR comments, small fixes and using serviceLabel in the warning …
> Firefly-1198:whole table search fix for TAP services not supporting uploads 

- src/firefly/java/edu/caltech/ipac/firefly/data/SortInfo.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/js/tables/SortInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TableRenderer.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1125
- trim column names when reading in csv files
- fix sorting when column namne contains comma
Test: https://fireflydev.ipac.caltech.edu/firefly-1125-fix-csv-table/firefly
Upload attached imperfect_u.csv file from ticket.
Follow instructions in ticket to confirm that the reported issues are fixed.
> FIREFLY-1125: fixed csv file with bad colum names

- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/js/ui/DefaultSearchActions.js
- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- for a table upload, filtered down user selected columns in the upload table 
- @robyww I wasn't sure how to use the "INCL_COLUMNS" attribute of a TableServerRequest properly for this, but managed to get it working by editing the DataGroup object, let me know if this approach looks okay. 
- **Updates 4/24**
- updated code in AsyncTapQuery per @loitly's suggestions 
- if you upload table/load table, or do a click to action whole table search, the selected columns by default will only be the same as position columns 
- and if user changes position columns, any of these changes will be reflected by being selected in the columns (and therefore, also in the ADQL) 
- confirmed table filtering works
- confirmed **dg.removeDataDefinition** works as expected 
- the small bug with selecting some …
> Firefly-1212: filter upload tbl columns down to user selected cols

- src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
- We were writing` <DESCRIPTION> `after `<FIELD>` tags, but as per IVOA convention for VO tables, `<DESCRIPTION>` needs to come before `<FIELD>` tags (see: https://ivoa.net/documents/VOTable/20191021/REC-VOTable-1.4-20191021.html#ToC46) 
- I wanted to make sure I got this right, and it looks correct, but since this is something that could potentially break searches, let me know if anything looks off, I suggest looking at the temp file created as well (I tested it plenty - but could still use feedback)  
- Code explanation: 
- earlier, we were calling VOSerializer's writePreDataXML
- writePreDataXML attempts to write the `<TABLE>, <DESCRIPTION> and <PARAMS> and <FIELD>` tags. But for some reason, it did not get and hence did not write the description tag. 
- I wrote a helper function …
> Firefly-1228: fix position of desc tag when writing to VOTable

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/PinnedChartContainer.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-5175
```
When IRSAViewer is in DCE mode and Coverage appears on the right-hand side of the tri-view, 
it creates a tab-in-tab look which is wrong.  We need to fix it so that Coverage and Charts can coexist in that area.
```
Test: https://fireflydev.ipac.caltech.edu/irsa-5175-triview-top-right/firefly
The feature allowing Coverage to be moved to Chart area is now enabled for Firefly, not just DCE.
To test, search or load a table.  Then, toggle `Coverage: Left/Right/Coverage w/Charts`.  Pin Chart should work as it did before as well.
> IRSA-5175: Fix the right-side of the tri-view to accommodate both Charts and Coverage

- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/DownloadOptionsDialog.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1236
Rendering is fixed.  Not sure why workspace is not working.
Test: https://firefly-1236-save-table-render.irsakudev.ipac.caltech.edu/irsaviewer/
See ticket for testing instruction.
@lrebull Please test at your convenience.
> FIREFLY-1236: fixed Save table dialog badly rendered when Workspace is chosen

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
- src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1156
Test: https://fireflydev.ipac.caltech.edu/firefly-1156-sql-errors/firefly
Load table, then try to make 'Add Column' fail to see error message.  One way is to reference a bad column name in the expression field.  Or, create a type mismatch by picking a data type that's inconsistent with the results of the expression.
You can also look at tests to see several different type of messages.
https://github.com/Caltech-IPAC/firefly/blob/FIREFLY-1156_sql_errors/src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java#L239
https://github.com/Caltech-IPAC/firefly/blob/FIREFLY-1156_sql_errors/src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java#L270
@lrebull It takes a lot of work to construct a precise error message.  And …
> FIREFLY-1156: better SQL error message for added column failure

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/tables/ui/TableRenderer.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1240
Test:  https://firefly-1240-pinchart-flipy.irsakudev.ipac.caltech.edu/irsaviewer/
Also fix  #10 from Bugs found in 2023.1 RC to ticket: 
https://confluence.ipac.caltech.edu/display/IRSA/Bugs+found+in+2023.1+RC+%3A+IV%2C+DCE+testing+April+2023
> When you use the preset function to add a column, it appears in the newly created column as true and false. But when you go to try to filter on that newly created column from the filter pulldown at the top of the new column, it says true and <NULL>, not true and false. If you filter on <NULL>, it does what you expect it to do, e.g., just gives you the 'false' values
> FIREFLY-1240: flipped y axis doesn't persist in chart thumbnail view

- src/firefly/js/ui/DefaultSearchActions.js
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- also: improved center column guessing columns such as `ra_obj` and `dec_obj` (common in irsa moving target tables)
- https://firefly-1241-coverage-replace.irsakudev.ipac.caltech.edu/irsaviewer
> Firefly-1241: Fix: Search search showing fits in wrong viewer

- src/firefly/java/edu/caltech/ipac/firefly/data/RelatedData.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/Wavelength.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/task/PlotImageTask.js
XXXX-TAB algorithm for computing spectral coordinates requires that the combination of EXTNAME, EXTVERSION, and EXTLEVEL is used to identify the extensions with lookup tables. This PR makes sure that the values of these 3 headers are passed with the WAVELENGTH_TABLE related data to the client.
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-987
Test deployment: https://fireflydev.ipac.caltech.edu/firefly-987-extid/firefly
To test, check that the displayed wavelength is not NaN for the test files from https://jira.ipac.caltech.edu/browse/FIREFLY-989
> FIREFLY-987 Identify tables by EXTNAME, EXTVERSION, EXTLEVEL 

- src/firefly/js/ui/DownloadDialog.jsx
Completes an outstanding task in https://github.com/IPAC-SW/irsa-ife/pull/252
In SHA, options for data files (checkbox group) can't be empty. And unlike field level validation, this requires validation on submit. So added prop validateOnSubmit in DownloadDialog and added a validator function in SHA.
1. SHA: https://irsa-3356-download-validator.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/ - see instructions at https://github.com/IPAC-SW/irsa-ife/pull/257
2. Other apps: https://irsa-3356-download-validator.irsakudev.ipac.caltech.edu/applications/sofia/ 
Make  a search, then select a row in "FORCAST" table and click prepare download, uncheck file type options and submit. Because there wasn't any validator passed in props, it should submit download options form as it used to.
> IRSA-3356: Added validator in download dialog for SHA

- src/firefly/html/test/tests-table.html
- src/firefly/js/drawingLayers/Artifact.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/__tests__/TableUtil-test.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1245
```js
var wrapperReq = firefly.util.table.makeTblRequest( 
'IpacTableFromSource', 
'NED SED', 
{searchRequest: tblReq}, 
{filters: '"NED Units" = \'Jy\''}, 
{pageSize: 50} 
);
```
Normally, Firefly is able to handle undefined pageSize.  However, when it's used in this way(wrapper request with bad pageSize), it defaults to -1 which break paging and cause unexpected exceptions.
Test: https://firefly-1245-handle-undefined-pagesize.irsakudev.ipac.caltech.edu/
Follow instructions in ticket to test.  Or,
TLDR:
`Search for Source` -> m101 -> Search
switch table tab to `NED NED`, then select a different row.
> FIREFLY-1245: handle undefined pageSize

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/drawingLayers/SearchSelectTool.js
- src/firefly/js/metaConvert/DataLinkProcessor.js
- src/firefly/js/metaConvert/MultiProductFileAnalyzer.js
- src/firefly/js/metaConvert/ObsCoreConverter.js
- src/firefly/js/metaConvert/ServDescConverter.js
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/visualize/draw/PointDataObj.js
- src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
- new using same approach in datalink table as will normal access_url type tables
- averaging em_min and em_max for table of loaded images
- fixed: magnitude of conversion
- fixed: dropdown menu not showing in service descriptor error case
- fixed: added small shadown to target selection marker
- https://firefly-1246.irsakudev.ipac.caltech.edu/irsaviewer/dce
- pin a few images and look at look at TLI dialog, The microns should be correct
- The `obs_title` support is very hard to test outside of the LSST environment
- Most of this PR work is related to `obs_title` and titling obscore with datalink images correctly
> Firefly-1246: Fixed: obs_title not showing up for datalink. wavelength wrong my order of magnitude

- src/firefly/js/ui/PositionFieldDef.js
- in the Target Panel feedback, show EQJ2000 coordinates for any non-EQJ2000 coordinates entered. See design ticket for more info: https://jira.ipac.caltech.edu/browse/FIREFLY-1184
Testing: 
- https://fireflydev.ipac.caltech.edu/firefly-1234-equatorial-coords/firefly
- in the target panel, enter any non-EQJ2000 coordinates. E.g.: "250, 5 Gal", "105, 5 B1950", "200, 80 ECL", etc. 
- ensure that the resulting EQJ2000 coordinates on a new line look correct. I used NED's calculator to cross check as well:  https://ned.ipac.caltech.edu/coordinate_calculator
> Firefly-1234: Convert all non EQJ2000 coords to EQJ2000 coords

- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServiceInput.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/HttpServices.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/test/edu/caltech/ipac/firefly/server/network/HttpServicesTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1253
This is a little harder to test because we don't have authenticated TAP services that redirect its `/error` endpoint.  The code is fixed to handle all generic `GET` endpoints.  A test is also written to ensure redirecting is handled properly.
Test: https://fireflydev.ipac.caltech.edu/firefly-1253-tap-query-mishandle-redirects/firefly
Please test for regression bugs.
> FIREFLY-1253: TAP Query mishandled redirects originating from an "/error" status

- src/firefly/js/ui/NaifidPanel.jsx
Fixes [FIREFLY-1266](https://jira.ipac.caltech.edu/browse/FIREFLY-1266)
- Made searchHistory aware of naifIdFormat by converting it to an object with keys for each format
https://firefly-1266-naifid-conflict.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
- Go to search by moving object, search Gaspra - check that naif ID is in 7-digit format, now go to Precovery, search Gaspra again and check that ID is in 8-digit (default) format (instead of 7 digit -- earlier behaviour)
- Go to precovery, search karin, check ID should be in 8-digit format. Now go to moving object, search karin, check ID should be in 7-digit format (instead of 8 digit -- earlier behaviour)
https://firefly-1266-naifid-conflict.irsakudev.ipac.caltech.edu/applications/sofia
Make sure this change didn't affect how solar …
> FIREFLY-1266: Fix Naif ID resolution conflicts for different formats

- src/firefly/js/util/ObsCoreSRegionParser.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/CoveraeViewer.jsx
- This ticket addresses a few small issues (also see related ticket https://jira.ipac.caltech.edu/browse/IRSA-4866) 
- Treating **POINT** type s_regions the same as **POSITION** type s_regions fixes this specific issue, and the coverage map loads as expected (see changes in ObsCoreSRegionParser's `parseObsCoreRegion` function).  
- If s_region wasn't parsed correctly in **ObsCoreSRegionParser.js** (the switch statement on line 132 leads to the default case), then the coverage would fail and the app would crash. Reason for this is that when s_region exists but is parsed as invalid, then the **isCoverageFail** function of **CoveraeViewer.jsx** gets a **covState** value that is a string ('_No coverage available_') instead of an array, which is why `covState.find` fails. Adding a check fixed …
> FIREFLY 1073: Support for 'POINT' type s_region and prevent coverage from failing

- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/ui/tap/ObjectIDSearch.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TemporalSearch.jsx
- src/firefly/js/ui/tap/TemportalSearch.jsx
- Added a new Search Helper (ObjectID Search) to the TAP panel under services that support uploads 
- allow user to upload a table and select a column from their uploaded table, and a column from the selected table on the right. This will lead to a new ADQL constraints of the format '`ut.objectID = a.objectID`' (ut = uploaded table, a = first char of the selected table in this case) 
- This is a draft PR because I need to fix one small style issue and at possibly this bug below:
- Bug Description 
- This is a regression bug. Switching back from **multi-object** to **Single Shape** leads to some incorrect ADQL. For a service, like GAIA (and table is "public.hipparcos"), if under **Spatial** you select **Multi-object** and upload a table. Now if you select **Single Shape** and enter in, …
> Firefly 1150 object id tap

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DsvTableIO.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableWriter.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableWriter.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1285
- complete TODO item in DataType that maps the remaining VoTable types to Firefly
- remove useShortDesc in DataType.
- add round trip support for VoTable to IPAC to VoTable when VoTable contains types not supported by IPAC table.
From ticket:
> Due to incomplete mappings, it was mapping the missing types to String which causes the Type mismatch exception.  I fixed that as well as cleaning up some old code.  I also added round-trip support for VoTable -> IPAC table -> VoTable even though IPAC table do not support these types.  To do this, I added the type mappings info into the IPAC Table's meta
Test: https://fireflydev.ipac.caltech.edu/firefly-1285-spherex-table-load-fail/firefly
See ticket for link to test table.
-> Upload test table.  It …
> FIREFLY-1285: SPHEREx photometry table sample fails to load

- src/firefly/js/util/ObsCoreSRegionParser.js
- see the ticket for details of the issue
- see comment in the code for the fix 
Testing: 
- https://fireflydev.ipac.caltech.edu/firefly-1281-sregion-err/firefly
- use the table from the ticket above, upload it. From the tri-view, click on Coverage above the image and then click on the layers icon. The error that you see in the screenshot in the ticket should not be seen now, as all 0.0 and -0.0 values are read correctly as expected now.
> Firefly-1281: Fixing error in processing s_region values containing zeros 

- src/firefly/js/ui/tap/TemporalSearch.jsx
- fixes a bug causing a crash on irsaviewer when selecting the `TAP_SCHEMA` project with IRSA selected as the TAP service (presumably because the default table that shows up with `TAP_SCHEMA`: `TAP_SCHEMA.schemas` is empty - and that's a different issue that may need looking into as well). 
Testing: 
- Firefly: https://fireflydev.ipac.caltech.edu/firefly-1292-crash/firefly, IRSAViewer: https://firefly-1292-crash.irsakudev.ipac.caltech.edu/irsaviewer
- You can test using any of the 2 links above (firefly directly or irsaviewer) 
- go to the TAP UI from either 
- With IRSA selected as the TAP service, from `Project`, select `TAP_SCHEMA`. The default table that shows up here (`TAP_SCHEMA.schemas`) is empty (cause of the crash before the fix). Now you should just see this empty table, but the …
> Firefly-1292: TAP UI Crashes when selecting TAP_SCHEMA table

- src/firefly/js/Firefly.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/PropertySheet.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
Since #1404 got merged, irsaviewer is unable to load likely due to circular dependencies in accessing `PROP_SHEET` constant.
Moved it from `TableUtil.js` to `PropertySheet.jsx` to fix this. Also `PROP_SHEET` belongs to that module so it seems like a better place to put it.
Testing instructions in linked PR
IRSAViewer: https://firefly-1256-prop-sheet.irsakudev.ipac.caltech.edu/irsaviewer/
Also test if everything else is working as expected:
- IFE apps: 
- https://firefly-1256-prop-sheet.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/ 
- https://firefly-1256-prop-sheet.irsakudev.ipac.caltech.edu/applications/sofia/
- API mode: https://fireflydev.ipac.caltech.edu/firefly-1256-prop-sheet/firefly/test/tests-main.html
> FIREFLY-1256: Fix property sheet causing error in loading IrsaViewer

- src/firefly/js/charts/ui/ColSelectView.jsx
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/ui/tap/ObjectIDSearch.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- for the main table (selected table on the right), the Object ID column is populated with  `meta.id;meta.main` if available, or with the first `meta.id` if `meta.main` is not available. If both are not available, the column remains empty. 
- _Note_: if a valid column name is found (say a UCD with `meta.id;meta.main` exists), then the `Object ID Search` helper is auto-selected by default. Is this behavior okay? **_Done_**. 
- Added the helpful text (from the ticket) right under the `Object ID Search` helper title (side note: we may also need to update the onlinehelp link next to the title for the Object ID, as this is a new feature so users may want to click on it to learn more about it). 
_Pending tasks_ (as time permits before release): 
- filtering the columns with all that have UCD …
> Firefly-1279: TAP Object ID Search Cleanup

- src/firefly/html/test/tests-viewer.html
- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/api/WebApi.js
- src/firefly/js/api/webApiCommands/ImageCommands.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/fieldGroup/FieldGroupCntlr.js
- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/WebPlot.js
- the `firefly.getViewer()` now can be use to pass url api parameters to a running firefly
- DCE Test Page: https://firefly-1295-dce-multiload.irsakudev.ipac.caltech.edu/irsaviewer/test-dce-api.html
- click on links on test page to launch DCE
- Test Page: https://fireflydev.ipac.caltech.edu/firefly-1295-dce-multiload/firefly/test/tests-viewer.html?test=TriView%3A+URL+API+External+viewer+to+load+image+with+title
- click on link to see image load via url api using `getViewer()`
> Firefly-1295: calling the URL API via firefly's getViewer() in the javascript api

- src/firefly/js/drawingLayers/Catalog.js
- src/firefly/js/metaConvert/ImageDataProductsUtil.js
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/util/VOAnalyzer.js
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/saga/DataProductsWatcher.js
- coverage and catalog watcher shoutld not compete
- catalog will not add overlays on coverage anymore
- coverage only adds overlays on coverage
- this approach is a deoptimzation for large tables, both will have to load the table
- https://firefly-1296-urlapi-searchpanel.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/?api
- build against `IRSA-5419-sha-web-api`
- try second option in SHA API help page
> Firefly-1296: SearchPanel.jsx api updates & coverage vs catalog updates

- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
- src/firefly/js/ui/NaifidPanel.jsx
Fixes [FIREFLY-1299](https://jira.ipac.caltech.edu/browse/FIREFLY-1299)
Additionally, fixed excessive server calls - even when value was present in client-side searchHistory/cache (identified this problem from network inspector)
https://firefly-1299-pluto-naifid-fix.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
Go to Moving object search:
- type pluto: 3 suggestions should appear in dropdown, including 999 (two suggestions with same name)
- type Europa: again check that in suggestions, two suggestions can have same name but different IDs
https://firefly-1299-pluto-naifid-fix.irsakudev.ipac.caltech.edu/applications/sofia/
Check if everything is working as before.
> Firefly-1299: Fix pluto not resolving to 999 NAIF ID

- src/firefly/java/edu/caltech/ipac/firefly/core/background/Job.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagedEmail.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
- src/firefly/js/core/background/JobInfo.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1282
Generalize Firefly's UWS support  to accommodate multiple results being returned.
In this case, it should return an ObsCore-like table.
Currently, there isn't an existing UWS service with results like this.  Therefore, I added a mock-tap service that can return tap result at `/results/result`, but multiple results at the `/results` endpoint.  
This mock service has been deployed to https://nightly.irsakudev.ipac.caltech.edu/mock-tap
To test, go to: https://fireflydev.ipac.caltech.edu/firefly-1282-uws-multi-results/firefly
- Upload -> Upload from URL
- Enter URL:  https://nightly.irsakudev.ipac.caltech.edu/mock-tap/async/45
- Click Upload and then Load
You can use any integer instead of 45.  The mock service provides two sets of …
> FIREFLY-1282: Add multi-results support for UWS jobs

- src/firefly/js/visualize/task/PlotChangeTask.js
Fixes [FIREFLY-1118](https://jira.ipac.caltech.edu/browse/FIREFLY-1118)
`recenterActionCreator` expects `centrePt` field in payload to be a `WorldPtObj` for `WorldPt` type. This works as long as payload is coming from the UI (because things are in the same JS world) but it will fail if payload comes through `WebSocketListener` i.e. used when calling it from FF python client.
Using `makeWorldPt` also encouraged me to use `CoordSys.parse` which is smart enough to parse any `cSys` string in the payload, giving more flexibility overall.
Make sure this doesn't break existing recenter option in image toolbar
Testing instruction for firefly python client in https://github.com/Caltech-IPAC/firefly_client/pull/53
> FIREFLY-1118: Update recenter action to allow coordinate system to be a string

- src/firefly/js/metaConvert/ShaRequestList.js
Take out `sha.ipac.caltech.edu` in the servlet url construction for Precovery image viewing.
To test:
https://sha-fix.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
do Precovery search with Karin and using the example time range, view images in Data View tab.
> Minor sha fix, take out "sha.ipac.caltech.edu"

- src/firefly/js/visualize/iv/HiPSRenderer.js
- src/firefly/js/visualize/iv/HiPSSingleTileRender.js
- src/firefly/js/visualize/iv/HiPSTileDrawer.js
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
- [Firefly-1312](https://jira.ipac.caltech.edu/browse/FIREFLY-1312)
- clean of HiPS render to remove artifacts
-  [FIREFLY-1315](https://jira.ipac.caltech.edu/browse/FIREFLY-1315)
- Bug Fix: default the values of CD matrix to cdelt1/2 if defined
- https://github.com/Caltech-IPAC/firefly/issues/1430
- https://fireflydev.ipac.caltech.edu/firefly-1312-hips-render/firefly
- Test according to the tickets.
> Firefly-1312,1315: hips render & Bug Fix: FITS GnomicProjection using cd matrix

- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- this change is to return an empty string for obs core title if app options specifies a an empty tapObsCore.productTitleTemplate as discussed (aimed at euclid - but generic and can apply to other apps as well) 
**Testing**: 
- tested it locally and it works ('`Euclid, `' is taken out from the cutouts title), don't have a test build available for this as I'm still working on other irsa-ife changes for euclid. once I push  a commit for that, I can create a test build as well. 
- actually, pushed the irsa-ife change and created a test build here: https://irsa-5479-cutouts-title.irsakudev.ipac.caltech.edu/applications/euclid/search
- you should be able to do a region explorer search and see that '`Euclid, `' is now taken out of the title.
> IRSA-5479: return empty string is app options specifies empty productTitleTemplate string

- src/firefly/js/externalSource/prismLive/prism-live.js
Fixes [FIREFLY-1072](https://jira.ipac.caltech.edu/browse/FIREFLY-1072)
This is a problem with [PrismJS Live](https://github.com/PrismJS/live) we're using. Made a patch to them as well: https://github.com/PrismJS/live/pull/38
On some `keydown` events like characters which need auto-completing pairs (like ', ",  (, \`, etc.), prism-live does custom handling. They prevent default browser handling of the `keydown` event at the end which is necessary for window switching. So fixed the condition to make sure it only happens if `keydown` of such pair characters was not in combination of `keydown` of `superKey` (which is "Cmd" in case of Mac).
> Why this bug is only in safari? Chrome didn't have this problem with "Cmd + \`" shortcut because it doesn't allow JS running in browser to catch "\`" …
> FIREFLY-1072: Fix ADQL text-entry field swallowing "(Command)-`"

- src/firefly/html/css/global.css
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/FileUploadDropdown.jsx
- src/firefly/js/ui/RadioGroupInputField.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- a simple drag drop UI for file uploads - probably just the first iteration of many, would like to iterate based on UI feedback received 
- We need to consider how big to make the space for drag & drop, and what happens to it after a user uploads a file, since we immediately display the file analysis results 
- potentially make the entire window draggable/droppable for files? 
**Updates 10/10**
- The entire window is draggable/droppable for files now 
- added text that indicates you can choose a file from your OS's file explorer _or_ drag and drop a file
- You can switch to **_Upload from URL_** and upload files from there too (this should switch the window back to **_Upload from file_** as well). 
- To swtich the radio buttons back to **_Upload from file_**, I call **fireValueChange** …
> FIREFLY-1310: Prototype of Drag Drop UI for file uploads 

- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/data/FileAnalysis.js
- src/firefly/js/drawingLayers/HiPSGrid.js
- src/firefly/js/metaConvert/AnalysisUtils.js
- src/firefly/js/metaConvert/DataProductsFactory.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/metaConvert/TableDataProductUtils.js
- src/firefly/js/metaConvert/UploadAndAnalysis.js
- src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/metaConvert/vo/ServDescConverter.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/templates/router/RouteHelper.jsx
- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/iv/HiPSCellFinder.js
- src/firefly/js/visualize/ui/MultiItemViewerView.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
- src/firefly/js/voAnalyzer/VoConst.js
- src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- support recognizing and show multiple spectrum
- Note: this PR is based on `dev` the build has the same code but is based on PR https://github.com/Caltech-IPAC/firefly/pull/1438
- https://fireflydev.ipac.caltech.edu/test-spherex-multi-spectrum/firefly
- unzip the folder below and upload `multi-spec.vot` into firefly
- each click on the table will try to show two spectra and the two related table. Unfortunately the is some bug and one of the tables will not load. However, you can get the idea.
[multi-spec-folder.zip](https://github.com/Caltech-IPAC/firefly/files/13182248/multi-spec-folder.zip)
> Firefly-1324: Update multi product view to handle multiple spectrum at once

- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1340
`noChartToolbar` parameter stopped working.
To test:  https://fireflydev.ipac.caltech.edu/firefly-1340-nocharttoolbar/firefly/test/tests-main.html?test=Table+group+with+default+charts
The chart should non-interactive without toolbar.
> FIREFLY-1340: noChartToolbar parameter for showChart not working

- src/firefly/js/charts/dataTypes/FireflySpectrum.js
- src/firefly/js/charts/dataTypes/SpectrumUnitConversion.js
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/options/SpectrumOptions.jsx
- src/firefly/js/voAnalyzer/SpectrumDM.js
- src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
Implements [FIREFLY-1304](https://jira.ipac.caltech.edu/browse/FIREFLY-1304)
On a high-level:
- Made spectral frame data in the table available to the chart data as `fireflyData`
- Added UI for spectral frame and redshift input in Spectrum options
-  Also updated it based on early feedback from scientists
- Made changes in spectral frame UI inputs trigger changes in X ColumnOrExpression and X Label - aka redshift correction
- Also apply those changes to other traces of the chart
https://fireflydev.ipac.caltech.edu/firefly-1304-redshift-correction/firefly/
Created test files for each of the following 3 case available at https://github.com/jaladh-singhal/z-correction-data/
1. TOPOCENTER - Download [Spitzer_IRS_SL_PBCD-topocenter.vot](https://github.com/jaladh-singhal/z-correction-data/blob/m …
> FIREFLY-1304: Implement spectral redshift correction

- src/firefly/java/edu/caltech/ipac/table/PrimitiveList.java
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1297
Fixed: Firefly incorrectly interprets null values as 'false' when a column is specified as a Boolean.
This also expand NULL support to all data types. 
Test: https://firefly-1297-table-support-null-primitives.irsakudev.ipac.caltech.edu/irsaviewer/dce
- Select Facility: MSX
- Search on any covered area with 300 arcsec radius.
In the result table, `environment_photometric` column should be all NULLs instead of `false`.
> FIREFLY-1297: Add support for null values to all table's data types.

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/CheckboxGroupInputField.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1333
Table column filter by dropdown list failed to handle values with comma(s) in them.
Test: https://firefly-1333-filter-enumeration-comma.irsakudev.ipac.caltech.edu/irsaviewer/dce
Trying filtering `Bands` and `Inst.` using the dropdown list.  They should work now.
> FIREFLY-1333: Add support for enumerated column's values with comma.

- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/SearchPanel.jsx
- irsa-ife PR: https://github.com/IPAC-SW/irsa-ife/pull/294
- React Router's `useNavigate()` may be used only in the context of a <Router> component which is why I had to separate the `SearchPanel` component into a new `SearchPanelRoutes` component (if I tried to use `useNavigate()` in the existing `SearchPanel` component, things would be fine for euclid and spherex apps, but would break for wise and other apps
- SearchPanelRoutes now works with the euclid app, which means we would have had two submit and two cancel buttons on the search page (since SearchPanel internally calls FormPanel, but the euclid search components - RegionExplorer, Source Inspector also call FormPanel)
- So I had to add a conditional in FormPanel component whose default value is always true to display the …
> Firefly 1320: Search Panel routes for Euclid SphereX

- src/firefly/html/demo/table-api.html
- src/firefly/js/Firefly.js
- src/firefly/js/tables/FilterInfo.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/PropertySheet.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1347
Also, 
- fixes property sheet popup in API mode
- fixes a bug in FIREFLY-1307 in which the Details table crashes when filtering on the Value column.
- Note:  Value column is type 'char'.  The values are converted to string during the comparison process.
More changes here: https://github.com/IPAC-SW/irsa-ife/pull/297
Test: https://fireflydev.ipac.caltech.edu/firefly-1347-propertysheet/firefly/
and:  https://firefly-1347-propertysheet.irsakudev.ipac.caltech.edu/irsaviewer/
Ensure 'Details' tab in tri-view still works as expected.
Test: https://fireflydev.ipac.caltech.edu/firefly-1347-propertysheet/firefly/test/ 
Ensure popup button 'Show details for the selected row' work as expected.  It should show the content of the current …
> FIREFLY-1347: showPropertySheetButton option should be consistent with other table's options

- src/firefly/js/Firefly.js
- src/firefly/js/tables/TableConnector.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/PropertySheet.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
Fixes [FIREFLY-1352](https://jira.ipac.caltech.edu/browse/FIREFLY-1352)
5,8 doesn't seem to have any to-do for this PR 
https://fireflydev.ipac.caltech.edu/firefly-1307-propsheet-fixes/firefly/
Do Table search -> IRSA Catalogs -> m81, 100 arcsec. Go to details tab and confirm that:
- type appears in columns
- table options dialog show option to hide/show type
- format is respected: 1st row, w1rchi2 column: `4.873E+1` - same value appears in property sheet instead of `48.73`; 1st row,  w3sat column: `0.000` - same appears in property sheet instead of `0`
- null string shows up: 4th row, w4sigmpro column: `null` - same appears in property sheet instead of empty cell
Select some rows in property sheet table, and filter - changing row selection in source table should preserve the filter in …
> FIREFLY-1352: Implement property sheet feedback

- src/firefly/js/Firefly.js
- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/drawingLayers/HiPSMOCUI.jsx
- src/firefly/js/util/Color.js
- src/firefly/js/visualize/draw/Drawer.js
- src/firefly/js/visualize/draw/DrawingDef.js
- src/firefly/js/visualize/draw/MocObj.js
- src/firefly/js/visualize/draw/ShapeDataObj.js
- Do outline with MOC
- put in the right opacity
- Moc default style
- moc max depth to 5 with an appOption
Testing:
- https://firefly-1350-moc-outline.irsakudev.ipac.caltech.edu/irsaviewer/dce
- click around on display, all the MOCs should come up as outlines
- choose the drawing layers to change to other modes
- _note:_ sometime moc outlines seem like they are double for certain ones. This is really the best we can do.
> Firefly-1350: Add MOC outline style

- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/HttpServCommands.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/RegionTableWriter.java
- src/firefly/js/tables/ui/TableSave.jsx
- adds option of file format for region file to table save when position columns are available 
- downloads region file if selected 
- @robyww as I mentioned in the standup, not a lot of changes here, I'll still work on some cleanup but if you could take a quick look at the code to make sure it makes sense overall (or point out if something stands out as incorrect)
**Updates 12/1**
- added support for saving files with one column array entry of ra,dec values (assuming entry arrays are always going to be type `double`), test build updated. 
**Updates 11/29**
- Please see my comment in `TableAnalysis.js` line 34. Is there a table I can use to test and write code for single column entries for center columns? 
- What should the behavior look like when users filter out the center columns (one …
> Firefly-1235: Adding region file format to table save when position columns are available

- package.json
- src/firefly/html/css/global.css
- src/firefly/js/api/ApiUtil.js
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/core/background/BgMaskPanel.jsx
- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/CheckboxGroupInputField.jsx
- src/firefly/js/ui/CompleteButton.jsx
- src/firefly/js/ui/FireflyRoot.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/RadioGroupInputFieldView.jsx
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/ui/ThemeSetup.js
- src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
- src/firefly/js/ui/tap/TableColumnsConstraints.jsx
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- yarn.lock
https://jira.ipac.caltech.edu/browse/FIREFLY-1356
Also:
- Add theme to API mode
- Scale down theme's font-size to our preferred size to avoid customizing every component's size.
What is converted…
- table and table toolbar
- table save dialog
- Add a column dialog
- Including Expression Creator (search icon in Expression field)
- Table Info dialog
- Table Options dialog
- both Column Options and Advanced Filter
What is not converted..
- TabPanel
- InputAreaField (Advanced Filter Dialog)
- CollapsiblePanel
Issues need resolving…
- Need to establish what is the default non-primary button should be
- the current default is  too light, it bleeds into the background.
- I suggest using ‘solid’ for dialog (ok/cancel) and ‘outlined’ for all others
- RadioGroupInputField label’s uses wrong …
> FIREFLY-1356: UI Conversion: convert TableView to Joy UI

- package.json
- src/firefly/js/visualize/ui/ImageTableRowViewer.css
- src/firefly/js/visualize/ui/ImageTableRowViewer.jsx
- src/firefly/js/visualize/ui/MultiItemViewerView.jsx
- yarn.lock
Fixes [FIREFLY-1353](https://jira.ipac.caltech.edu/browse/FIREFLY-1353)
- Added react-slick slider to use in ImageTableRowViewer. slick-carousel package is also added for the css needed for react-slick
- Expose layout/container creating function in MultiItemViewerView so that items (images) can be rendered inside slider
- Synchronized changes in slide with change in highlighted row and vice versa (note: this is where logic gets bit complicated because we have to prevent it from looping)
- Created a custom slider arrow button for above purpose and to cancel the event when slider is hitting the left edge or right edge (so that it doesn't slide and active image moves to center)
- Made change in active plot through UI, change the highlighted row 
- Make height of slider (and inner components) …
> FIREFLY-1353: Add arrow buttons for image scrolling in ImageTableRowViewer

- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/ui/DialogRootContainer.jsx
- src/firefly/js/ui/MultiSearchPanel.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/visualize/ui/CoveraeViewer.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1355
- added scrolling to tabs.
- convert table content overflow drop-down (...)
Test: https://fireflydev.ipac.caltech.edu/firefly-1355-joyui-tabpanel/firefly/
Test wherever tabs are used.  
Keep in mind these features of TabPanel:
- Tab may be removable
- Tab will resize itself as more tabs are added.  It will also resizes as more spaces are mad available
Added Feature:
- A `min-width=100` is set on the tabs.  When there are too many to fit, it will overflow.  They become scrollable at this point.  To scroll, hover over the tab headers, press the Shift key, and then use the scroll wheel.
> FIREFLY-1355: Convert TabPanel to Joy UI

- src/firefly/html/firefly.html
- src/firefly/js/Firefly.js
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/ui/FireflyRoot.jsx
- src/firefly/js/ui/Menu.css
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/ThemeSetup.js
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- Provide a way for application to override Firefly's default theme.
- Package google font as part of Firefly to avoid external linking of google font.
- Use device's colorMode as default.  Provide option to set colorMode as well as document how to enable mode switching in the future.
Read comments in FireflyRoot.jsx for details.  Please provide feedbacks if you see issues.
- Use CssBaseline
I enabled `ScopedCssBaseline`.  See https://mui.com/joy-ui/react-css-baseline/ for more details.
This is a good idea going forward.  However, because it changes box-sizing model, it may breaks places where we use offset to fix alignment where we should have set box-sizing to 'border-box'.  I saw and fixed a couple.  I don't know how many more places this may affect.  I am ok reverting this change. …
> FIREFLY-1387: UI Conversion: Additional core functionalities

- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/data/MetaConst.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/templates/hydra/HydraManager.js
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/ui/UploadTableSelector.jsx
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/ui/dynamic/DynamicDef.js
- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/tap/Constraints.js
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/visualize/ui/CommonUIKeys.js
**[Firefly-1341](https://jira.ipac.caltech.edu/browse/FIREFLY-1341)**: 
**IRSA-IFE PR for Euclid**: https://github.com/IPAC-SW/irsa-ife/pull/303
- `UploadTableChooser` shows up and works with `EmbeddedPositionSearchPanel` (conditionally, because all components using EmbeddedPositionSearchPanel may not want an upload option, like Source Inspector in Euclid or some DCE tables)
- removed column selector for Euclid by passing in `uploadTable` flag (should change this name) to `UploadTableSelector` 
- the flag enables showing column selector for an uploaded table on TAP, but not for Euclid (or other apps that call `UploadTableSelector` with this flag set to true) 
**Updates 1/31**:
- doing `dispatchTableSearch` on all table uploads and not going to results view directly. Made this work using …
> Firefly-1341: Enhanced EmeddedPositionSearchPanel for upload

- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/ui/PopupPanel.jsx
- src/firefly/js/ui/PositionFieldDef.js
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/ui/tap/TableSelectViewPanel.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/ui/CatalogTableListField.css
- src/firefly/js/visualize/ui/CatalogTableListField.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- from: https://confluence.ipac.caltech.edu/display/IRSA/Testing+Feb+2024+-+Joy+UI%2C+mostly
- fixes three color tab infinate loop
- add pipes between tabs
- tab panel fixes
- https://firefly-1406-fixes.irsakudev.ipac.caltech.edu/irsaviewer
- https://firefly-1406-fixes.irsakudev.ipac.caltech.edu/irsaviewer/dce
- https://fireflydev.ipac.caltech.edu/firefly-1406-fixes/firefly
- image borders and some table border are round
- tabs have pipes between 
check when confirmed:
> Firefly-1406: fixes 1, 29, 54 (partial, not all tables), 62, 64

- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/FireflyRoot.jsx
- src/firefly/js/ui/tap/ColumnConstraintsPanel.jsx
- src/firefly/js/visualize/ui/CatalogConstraintsPanel.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1402
Fixed so far:
Table UI:
Apply full borders to table cells, set the font size to 12px, reduce the row height to 20px(back to pre-Joy's height), and unset font smoothing.
13.5: 
VO TAP search, look at "Output Column Selection and Constraints" part of the screen. Scroll left and right. The part of the "Name" column that is not occupied by text is transparent! you can see the contents of the rest of the table as you scroll left/right.
18:
when in dark mode, the text color used for links is unreadable
(found in: iv image results, when many images loaded, list of images pop up)
Test: https://fireflydev.ipac.caltech.edu/firefly-1402-more-chart-conversion/firefly/
> FIREFLY-1402: more chart related UI conversion changes

- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/visualize/ZoomUtil.js
- src/firefly/js/visualize/reducer/HandlePlotCreation.js
- src/firefly/js/visualize/task/PlotImageTask.js
- [IRSA-5700](https://jira.ipac.caltech.edu/browse/IRSA-5700) : packaging uses filename
- [Firefly-1289](https://jira.ipac.caltech.edu/browse/FIREFLY-1289): better zoom level
- [Firefly-1375](https://jira.ipac.caltech.edu/browse/FIREFLY-1375): TAP can have a per service preferred hips for coverage
- https://irsa-5700-firefly-1289.irsakudev.ipac.caltech.edu/irsaviewer/dce
- The only thing that can really be tested is dce packaging.
> IRSA-5700 & FIREFLY-1289: packaging and zoom

- src/firefly/js/charts/ui/PlotlySaveDialog.jsx
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/DownloadOptionsDialog.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
UI-conversion [FIREFLY-1364](https://jira.ipac.caltech.edu/browse/FIREFLY-1364).
Updated following popup dialogs:
- FitsDownloadDialog.jsx
- TableSave.jsx
- DownloadOptionsDialog.jsx
- PlotlySaveDialog.jsx
There are more cleanups needed in the DownloadOptionsDialog related to workspaces, which will be done in Firefly-1400.
To test: https://fireflydev.ipac.caltech.edu/firefly-1364/firefly/
1. do  a image search with wise and make 3 color image, and go to download image/3-color image
2. try a catalog search and in the table panel click save table
p.s `ZoomOptionsPopup` has been refactored already
Check when confirmed
> FIREFLY-1364 more updates and cleanup

- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/ColSelectView.jsx
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/MultiChartToolbar.jsx
- src/firefly/js/charts/ui/PlotlySaveDialog.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/ui/AutoCompleteInput.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/CloseButton.jsx
- src/firefly/js/ui/InputAreaField.jsx
- src/firefly/js/ui/InputAreaFieldView.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/ObjectIDSearch.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1412
Converted the listed files to JoyUI.
One significant piece is the addition of `AutoCompleteInput` to replace `SuggestBoxInputField`.  `SuggestBoxInputField` is still in used by other component.  The behavior may not be exactly the same.  But, using JoyUI's Autocomplete will allow us to add more features moving forward.
https://fireflydev.ipac.caltech.edu/firefly-1412-more-chart-ui/firefly/
Things to test:
> FIREFLY-1412: Finish Charts conversion left over from FIREFLY-1408

- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TableRenderer.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1415
Test: https://fireflydev.ipac.caltech.edu/firefly-1415-tableoptions/firefly
> FIREFLY-1415: Table options default size is too small

- src/firefly/js/Firefly.js
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/templates/common/FireflyLayout.jsx
- src/firefly/js/templates/fireflyslate/FireflySlate.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/App.jsx
- src/firefly/js/ui/AppConfigDrawer.jsx
- src/firefly/js/ui/DialogRootContainer.jsx
- src/firefly/js/ui/DropDownDirContext.js
- src/firefly/js/ui/DropDownMenu.jsx
- src/firefly/js/ui/DropDownToolbarButton.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/UploadTableSelector.jsx
- src/firefly/js/ui/dynamic/ServiceDefTools.js
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/ui/tap/TapViewType.jsx
- src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
- dropdown should go up if no room down
- tap
-  general tap: show services by default
- clean up layout for different modes
- menu: small tweeks to make it look better
- AppConfigDrawer will close when you click the app icon
- https://firefly-1418-ui-cleanup.irsakudev.ipac.caltech.edu/irsaviewer
- other tap stuff is mostly better spacing
- do tap search, make table area small, click on microscope
- close draw by clicking on app icon
- There should be a little line under the results tab when it is not selected (like the other tabs)
- the side bar result item is better aligned
> Firefly-1418: UI cleanup

- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundMonitor.jsx
- src/firefly/js/tables/SortInfo.js
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/dynamic/ServiceDefTools.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1419
Also, allow quotes and commas in table sortInfo.  This allow DCE to use 
```table_sort_order=ASC,substring("dataproduct_subtype",2)```
Test: https://firefly-1419-download-broken.irsakudev.ipac.caltech.edu/irsaviewer/dce
To test download probem:
- load DCE
- pick DeepDrill from menu on left
- search on anything where there is data (i used the example target
- pick any data to download (I used one or two of the science mosaics)
- click on “prepare download”
- wait for it to finish packaging
- click on “Download now”
To test sortInfo problem:
- load DCE
- search on anything where this is data
In the results column `dataproduct_subtype`, `science` should be on top.
> FIREFLY-1419: Package download is no longer working

- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/ui/DialogRootContainer.jsx
- src/firefly/js/ui/ImageSelect.jsx
- src/firefly/js/ui/SimpleComponent.jsx
- src/firefly/js/ui/Stacker.jsx
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/Buttons.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1420
Converted DialogRootContainer.DropDown to JoyUI Dropdown.
Converted `View As Text`  popup
Added Stacker container
Also worked on issues from: https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199
Test: https://fireflydev.ipac.caltech.edu/firefly-1420-cleanup-items/firefly
> Firefly 1420 cleanup items

- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/PinnedChartContainer.jsx
- src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
- src/firefly/js/tables/ui/FilterEditor.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanelOptions.jsx
- src/firefly/js/tables/ui/TableRenderer.js
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/ui/DialogRootContainer.jsx
- src/firefly/js/ui/DownloadOptionsDialog.jsx
- src/firefly/js/ui/ExampleDialog.jsx
- src/firefly/js/ui/FitsDownloadDialog.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/MultiSearchPanel.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/TestQueriesPanel.jsx
- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/ImageSearchPanelV2.jsx
- src/firefly/js/visualize/ui/ImageStatsPopup.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1424
From doc: https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199
From doc: https://confluence.lsstcorp.org/pages/viewpage.action?pageId=250480825
Also:
- Refactor and cleanup TabPanel
- Fix sizing issues with table and image save dialog
- There should not be empty white area unless the user resize the dialog in workspace mode.
- Set TabPanel's default borderRadius to 5px.  Can be overridden by `sx={{borderRadius}}`
Test: 
https://firefly-1424-more-ui-conversion-fix.irsakudev.ipac.caltech.edu/irsaviewer/
https://fireflydev.ipac.caltech.edu/firefly-1424-more-ui-conversion-fix/firefly/
> Firefly 1424 more UI conversion fix

- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/js/charts/ui/ColSelectView.jsx
- src/firefly/js/charts/ui/ColumnOrExpression.jsx
- src/firefly/js/charts/ui/MultiChartToolbar.jsx
- src/firefly/js/charts/ui/PlotlyToolbar.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/UploadTableSelector.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TableColumnsConstraints.jsx
- src/firefly/js/ui/tap/TemporalSearch.jsx
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- src/firefly/js/visualize/iv/ImageViewerDecorate.jsx
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- src/firefly/js/visualize/ui/Buttons.jsx
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
- src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- rubin chart 1: images and charts: arrows icon now material icon
- rubin chart:2: images and charts: grouping display modes
- irsa testing round 2: 9 - tap quoting
- feedback: image viewer only show highlights when there is more then one showing
- [Firefly-1435](https://jira.ipac.caltech.edu/browse/FIREFLY-1435): bug fix: reading an empty FITS table
- https://fireflydev.ipac.caltech.edu/firefly-1434-several-fixes/firefly
- fixes from feedback rubin chart 1 & 2, irsa testing round 2: 9
- Upload a fits with an empty table HDU (example attached to ticket)
- Image view will not show highlight when only on image or HiPS on screen
> Firefly-1434: fixes: irsa 9, rubin-chart 2,3, empty FITS table

- src/firefly/html/css/global.css
- src/firefly/js/FFEntryPoint.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/AppDataReducers.js
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/templates/common/FireflyLayout.jsx
- src/firefly/js/templates/fireflyslate/FireflySlate.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/LandingPage.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/templates/hydra/HydraViewer.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/App.jsx
- src/firefly/js/ui/AppConfigDrawer.jsx
- src/firefly/js/ui/Banner.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/MultiSearchPanel.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/SimpleComponent.jsx
- src/firefly/js/ui/Stacker.jsx
- src/firefly/js/ui/ThemeSetup.js
- src/firefly/js/ui/panel/TabPanel.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/ui/FitsHeaderView.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1427
More changes here: 
https://github.com/IPAC-SW/irsa-ife/pull/311
https://github.com/lsst/suit/pull/51
Provide option for HydraViewer apps to use Menu instead of search panel.
- To enable, call dispatchLoadSearches with renderAsMenuItems=true.
- Add 'primary: true|false’ to SearchItem; this is then passed to MenuItem.
**Also:**
- Fix TabPanel's inconsistent usage of onTabSelect.
- Add slots/slotProps to the application-level component, e.g., FireflyLayout. The three slots are: drawer, banner, and dropdown. 
- Maybe we should move landingPage into a slot as well, but not in this PR.
- Add meaningful slots to Banner. This makes it cleaner and more robust.
- Moved and cleaned up many app-level props, e.g., banner*Style, …
> FIREFLY-1427: Provide option for HydraViewer apps to use Menu instead of search panel.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/mos/QueryMOS.java
Fix WISE MOS search. Allow blank ObsDate for MOS time range. 
To test enter a moving object, leave observation time range blank:
https://wise-fix.irsakudev.ipac.caltech.edu/applications/wise/
> Wise hotfix allow null ObsDate string

- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
**[FIREFLY-1452](https://jira.ipac.caltech.edu/browse/FIREFLY-1452)**: 
- fixed the bugs (`Loaded Tables `width increasing) and styling issue in UploadTableChooser (`Load` button is now at the bottom by default - set height of `Box` equal to the `minHeight` we have for resizing - that was the issue, but took some time to make it work as expected). 
- ~~got rid of the Cancel buttons. Do we want them here?t~~   
**Testing**: 
- https://fireflydev.ipac.caltech.edu/firefly-1452-upload-popup/firefly
- Test the upload table chooser popup by clicking on `Multi-Object` under Spatial Search on TAP. 
- After uploading a table, click on the Loaded Tables tab and make sure it looks okay (by default, without resizing the popup).
> FIREFLY-1452: fix bugs in UploadTableChooser popup

- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
**[IRSA-5925](https://jira.ipac.caltech.edu/browse/IRSA-5925)**: 
- IRSA PR: https://github.com/IPAC-SW/irsa-ife/pull/313
- small changes to the `EmbeddedPositionSearchPanel's` position (to make it look not stuck to the bottom left of the screen for Euclid). 
- test DCE to ensure the EmbeddedPositionSearchPanel looks good, if not, I can revert these changes. 
Testing: 
- Euclid: https://irsa-5925-euclid-joyui.irsakudev.ipac.caltech.edu/applications/euclid
- IRSAViewer (DCE): https://irsa-5925-euclid-joyui.irsakudev.ipac.caltech.edu/irsaviewer
> IRSA-5925: Convert Euclid to JoyUI 

- src/firefly/js/charts/ui/ChartsContainer.jsx
- src/firefly/js/charts/ui/MultiChartToolbar.jsx
- src/firefly/js/charts/ui/MultiChartViewer.jsx
- src/firefly/js/charts/ui/PinnedChartContainer.jsx
- src/firefly/js/charts/ui/options/HeatmapOptions.jsx
Fixes [FIREFLY-1449](https://jira.ipac.caltech.edu/browse/FIREFLY-1449)
- Made PinChart to not show up when viewer is Data Product Viewer 
- because current pinning functionality is designed to handle only charts that have their data tables in store (DP viewer's chart data gets replaced each time row is changed). To pin chart shown in DP Viewer, first pin its table and then from active charts, pin it.
- this was also a bug in ops and the two pin buttons should have never existed until chart pinning can handle DP viewer - @lrebull agrees to remove it
- Exposed showAddChart as a prop in MultiChartViewer and set it false by default, and true only for ActiveChartsPanel
- Moved x, y mappings from first call of reducer to initial state of components to prevent it setting x, y axes options as …
> FIREFLY-1449: Fix 2 pushpin in DCE and other chart bugs

- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/Stacker.jsx
https://jira.ipac.caltech.edu/browse/FIREFLY-1396
Although ticket said 'TAP', it can be applied to any VOTABLE with a QUERY_STATUS of OVERFLOW.
Test: https://fireflydev.ipac.caltech.edu/firefly-1396-votable-overflow/firefly/demo/table-api.html
Since there aren't any services providing this status, use this test page to mimic its return. 
Include this JSON value in the META_INFO field.
```json
{
"QUERY_STATUS" : "OVERFLOW",
"backgroundable": true
}
```
Or, edit a VOTABLE with this status, then upload.
> FIREFLY-1396: Display overflow indicator when present in VOTable.

- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileUpload.java
- src/firefly/java/edu/caltech/ipac/util/download/ResponseMessage.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/tables/SelectInfo.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/tap/ObjectIDSearch.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/ImViewFilterDisplay.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/iv/ExpandedTools.jsx
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
- src/firefly/js/visualize/projection/WavelengthHeaderParser.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
- src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
- src/firefly/js/visualize/ui/MultiImageViewer.jsx
- src/firefly/js/visualize/ui/MultiImageViewerView.jsx
- src/firefly/js/visualize/ui/MultiViewStandardToolbar.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- src/firefly/js/voAnalyzer/TableAnalysis.js
1. [FIREFLY-1448](https://jira.ipac.caltech.edu/browse/FIREFLY-1448):  image sorting/filtering clean up and refactor
- sorting/filtering syncs when moving between expanded and collapsed mode
- images stay sorted when new ones are add or removed
- Images don't stay filtered but button gives an alert to revisit and reset filtering
1. [FIREFLY-1462](https://jira.ipac.caltech.edu/browse/FIREFLY-1462): fixed: obscore download buttons showing up when no products
1. Small fixes
- Toolbar separators do not have top/bottom margin
- `Scroll Images` now available in `Pinned Images` tab
- TAP Object Id search shows warning color when column is marked `unset`
- a little JS Doc clean up
- improve error message (response code) on hips loading and file upload
-  fixed file upload mask issue
- …
> Firefly-1448 & Firefly-1462: multiple fixes

- src/firefly/java/edu/caltech/ipac/table/JsonTableUtil.java
- src/firefly/js/core/background/BackgroundMonitor.css
- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/tables/ui/ObjectTree.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/ui/PopupUtil.jsx
Fixes [FIREFLY-1464](https://jira.ipac.caltech.edu/browse/FIREFLY-1464)
- Made font sizes same, aligned their baselines (note: everything is sm now, key value pairs have different font-weights to disambiguate)
- Replace "show more" link by chip "show"
- Made metadata info popup resizable
- Removed css styles and cleaned up redundant code & layout a bit
https://fireflydev.ipac.caltech.edu/firefly-1464-metadata/firefly/
Go to TAP -> m81, 100 arcsec -> table info.
- compare font sizes and alignment with nightly build in both Job info and metadata tab 
- click on "show" chip button in "table metadata" tab
- the popup should be resizable 
- when popup size is reduced below content dimensions, the content should be scrollable
- click on "show" button in "job info" tab, the popup should be as …
> FIREFLY-1464: Cleanup Table Info dialog, metadata

- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/visualize/ui/ExtraIpacSearches.jsx
This PR address the `Search ` button on the SearchPanel, it should be preserved at the bottom while resizing the search panel. 
Related [IFE PR](https://github.com/IPAC-SW/irsa-ife/pull/325)
To test, try resize the search panel for the apps:
https://irsa-6032-wise.irsakudev.ipac.caltech.edu/applications/wise
https://irsa-6032-finderchart.irsakudev.ipac.caltech.edu/applications/finderchart
https://irsa-6032-ztf.irsakudev.ipac.caltech.edu/applications/ztf
> IRSA-6032: Make SearchPanel  preserving the search button at the bottom

- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/ui/PositionFieldDef.js
- src/firefly/js/visualize/ChangePrime.js
- src/firefly/js/visualize/CoordSys.js
- src/firefly/js/visualize/CsysConverter.js
- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/projection/Projection.js
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
- src/firefly/js/visualize/reducer/PlotView.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/task/WcsMatchTask.js
- src/firefly/js/visualize/ui/MatchLockDropDown.jsx
- src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
- src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
- src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- src/firefly/js/visualize/ui/ThumbnailView.jsx
[Jira ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-1468)
Build: https://fireflydev.ipac.caltech.edu/firefly-1468-coordreadout/firefly
- Separated readout options for celestial and non-celestial images
- Added units to projection information
- Added handling for non-degree units when displaying pixel scale
- Added convenience methods to separate all images with projection info into celestial and non-celestial
- For non-celestial coordinates the readout is displayed as `<CTYPE1>, <CTYPE2>: val1, val2 <CUNIT1>`
> FIREFLY-1468 Non-celestial coordinate readout.

- src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
**[FIREFLY-1451](https://jira.ipac.caltech.edu/browse/FIREFLY-1451)**: 
- see ticket details
- made header as small as possible when search panel is open, and when collapsed, display a search summary. 
- reduced opacity of search panel on mouse click anywhere outside the search panel, but hover/mouseover the search panel brings it back to 100% opacity
- corresponding irsa-ife PR: https://github.com/IPAC-SW/irsa-ife/pull/323
**Testing**: 
- Euclid: https://firefly-1451-embed-panel-enhanced.irsakudev.ipac.caltech.edu/applications/euclid
- Play around with the searches, collapse the panel for cone and multi-object (before and uploading a file - should work in both cases). 
- DCE: https://firefly-1451-embed-panel-enhanced.irsakudev.ipac.caltech.edu/irsaviewer/dce
- the search panel will be a …
> Firefly-1451: Embedded Position Search Panel Enhancements

- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCoreMetadataQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
- src/firefly/js/ui/AutoCompleteInput.jsx
- src/firefly/js/ui/tap/ObsCore.jsx
- src/firefly/js/ui/tap/TableSearchMethods.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/ui/tap/TapViewType.jsx
Fixes [FIREFLY-1187](https://jira.ipac.caltech.edu/browse/FIREFLY-1187)
- For ObsCore Instrument, Collection, and SubType, created a `ObsCoreInputField` that can render as ValidationField or multi-select AutocompleteInput, depending on the options supplied from AppOptions
- Updated ADQL generation code to allow parsing of options from ListBoxInput 
- Added a search processor `ObsCoreMetadataQuery` that fires queries for different obscore columns in parallel to retrieve metadata 
- Added client-side code in TAP root panel to fire the above query for each obscore capable service when selected, and then passes the resulting table metadata table to ObsCore panel. Also caches the results in same way as schema, tables, & columns 
- Enabled multiple mode in Autocomplete. Note: this requires …
> FIREFLY-1187: Update TAP ObsCore.jsx to support more options

- src/firefly/js/Firefly.js
- src/firefly/js/api/ApiExpandedView.jsx
- src/firefly/js/api/ApiViewer.js
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/PinnedChartContainer.jsx
- src/firefly/js/core/LayoutCntlr.js
- src/firefly/js/metaConvert/DataProductsType.js
- src/firefly/js/metaConvert/DataProductsWatcher.js
- src/firefly/js/metaConvert/DefaultConverter.js
- src/firefly/js/metaConvert/UploadAndAnalysis.js
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/FireflyViewerManager.js
- src/firefly/js/templates/fireflyviewer/LayoutChoice.jsx
- src/firefly/js/templates/fireflyviewer/TriViewPanel.jsx
- src/firefly/js/visualize/MultiViewCntlr.js
- src/firefly/js/visualize/task/PlotChangeTask.js
- src/firefly/js/visualize/ui/MultiImageViewerView.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- src/firefly/js/voAnalyzer/TableAnalysis.js
see [firefly_client PR](https://github.com/Caltech-IPAC/firefly_client/pull/58)
see [jupyter_firefly_extension PR](https://github.com/Caltech-IPAC/jupyter_firefly_extensions/pull/29)
- added a api view mode landing page
- improved ApiExpandedView to handle pinned charts
- TriViewPanel now better handles display modes
- removed many uses of renderTreeId
- js api viewer supports triview or slate
- https://fireflydev.ipac.caltech.edu/firefly-1483-triview/firefly
- see the [firefly_client PR](https://github.com/Caltech-IPAC/firefly_client/pull/58)
> Firefly-1483: change firefly_client to better support triview and plan to deprecate slate

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/PlotlySaveDialog.jsx
Fixes [FIREFLY-1480](https://jira.ipac.caltech.edu/browse/FIREFLY-1480)
Three bugs in ticket:
1. no longer reproducible
2. when an expression is given to X, Y to heatmap options it was closing the dialog after "apply". It was requesting table stats even when they were already available - which takes time and was causing isNonNumColumn() to throw errors.
3. Plot saving wasn't working because CompleteButton wasn't connected to FieldGroup (this got taken out during joy-ui refactor)
https://fireflydev.ipac.caltech.edu/firefly-1480-binned-plot-bugs/firefly/
Select 2MASS catalog, do m81, 1deg -> open heatmap options -> change x: j_m-h_m, y: h_m-k_m -> apply. Chart should update without closing. 
[For regression testing] Do another search, 2MASS, m81, 1arcmin -> open scatter options -> change …
> FIREFLY-1480: Fix binned plot and chart-saving bugs

- src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/visualize/ui/VisualSearchUtils.js
**[IRSA-5492](https://jira.ipac.caltech.edu/browse/IRSA-5492)** 
- Enabling no comma Polygon pairs to be accepted now (while comma separated pairs will still work)
- adjusted the error and help text accordingly, to indicate the use of comma is optional 
- IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/326
Testing: 
- DCE:  https://irsa-5492-euclid-upload-source.irsakudev.ipac.caltech.edu/irsaviewer/dce
- Euclid: https://irsa-5492-euclid-upload-source.irsakudev.ipac.caltech.edu/applications/euclid
- test polygon inputs, with and without comma, and less than 3 pairs, etc.
> IRSA-5492: Change Polygon input accept no comma pairs 

- src/firefly/html/css/global.css
- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/PlotlyChartArea.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.css
- src/firefly/js/tables/ui/TablePanel.jsx
Fixes [FIREFLY-1485](https://jira.ipac.caltech.edu/browse/FIREFLY-1485)
Note: This is a minimal cleanup of highly notable dark mode problems - we can do more nuanced cleanup in future.
Made following colors theme based:
- Chart fonts
- Additional: cleaned up `lineColor` not being used becuase the plotly prop for it is called `linecolor`
- Table border
- Table fonts
- Table scrollbars (background as well as track/face)
https://fireflydev.ipac.caltech.edu/firefly-1485-dark-mode-cleanup/firefly/
Open any tiview search results in dark mode, it will be best to compare it side by side with a [nightly firefly build](https://fireflydev.ipac.caltech.edu/firefly/)
Also check light mode should look mostly same (there are only minor notable changes, instead of fixed-table css grey colors, we now are …
> FIREFLY-1485: Clean up dark mode

- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
- src/firefly/java/edu/caltech/ipac/firefly/data/table/MetaConst.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
- src/firefly/js/data/MetaConst.js
- src/firefly/js/metaConvert/AnalysisUtils.js
- src/firefly/js/metaConvert/DataProductsCntlr.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/metaConvert/TableDataProductUtils.js
- src/firefly/js/metaConvert/UploadAndAnalysis.js
- src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- src/firefly/js/metaConvert/vo/DatalinkProducts.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/metaConvert/vo/ServDescConverter.js
- src/firefly/js/metaConvert/vo/VORequest.js
- src/firefly/js/ui/ColorPicker.jsx
- src/firefly/js/visualize/ImageViewerLayout.jsx
- src/firefly/js/visualize/ui/Buttons.jsx
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
- src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
- src/firefly/js/voAnalyzer/TableAnalysis.js
- src/firefly/js/voAnalyzer/VoConst.js
- src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- src/firefly/js/voAnalyzer/VoTableRecognizer.js
- Improve service descriptor parsing for the following complex case 
- data has data product
- table has non-datalink service descriptor 
- table also has datalink service descriptor
- Improve error handling
- Improve SSA data recognition: recognize DataID.Title utype
- Fix "Center Plot / Recenter" for large 1xN fits data
- For 1xN data give a line extract option to extract whole line
- fix color color picker close but
- fix finder chart 3C button
- finder chart: https://firefly-1495-sd-parsing.irsakudev.ipac.caltech.edu/applications/finderchart
- Three color button updated
- close works on the color panel
- Firefly: https://fireflydev.ipac.caltech.edu/firefly-1495-sd-parsing/firefly
- use file: [text.xml.zip](https://github.com/user-attachments/files/15571218/text.xml.zip)
- Upload the …
> Firefly-1495: sd parsing and extraction fixes

- src/firefly/js/drawingLayers/ExtractLineTool.js
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/visualize/iv/PlotTitle.jsx
- src/firefly/js/visualize/ui/ExtractionDialog.jsx
- src/firefly/js/visualize/ui/TriViewImageSection.jsx
- src/firefly/js/visualize/ui/VisCtxToolbarView.jsx
- [Firefly-1500](https://jira.ipac.caltech.edu/browse/FIREFLY-1500): Fixed: Data product view appears when changing hips
- [Firefly-1501](https://jira.ipac.caltech.edu/browse/FIREFLY-1501): Fixed: Some components of double tooltips on safari
- Bug fix: line extraction does not work if you click first outside of the image
- https://fireflydev.ipac.caltech.edu/firefly-1500-multi-tickets/firefly
- [Firefly-1500](https://jira.ipac.caltech.edu/browse/FIREFLY-1500): test according to ticket
- [Firefly-1501](https://jira.ipac.caltech.edu/browse/FIREFLY-1501): use safari and put mouse over plot title of image
- Use line extraction on an image and start outside of the image
> Firefly-1500,1501: Fixes multiple tickets

- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/templates/common/FireflyLayout.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/fireflyviewer/LandingPage.jsx
- src/firefly/js/templates/hydra/HydraViewer.jsx
Fixes [IRSA-6134](https://jira.ipac.caltech.edu/browse/IRSA-6134)
When a FireflyViewer or HydraViewer app gets ready (for the first time) with a tab other than Results view, we don't need to show hint about choose tabs.
> Note: working more on it, I think a long-term cleaner solution will be to lift up `AppHint` in component tree to `App` level (instead of `LandingPage`) - making it possible to show on any tab an app starts with for first time 
https://irsa-6134-blinking-hint-fix.irsakudev.ipac.caltech.edu/applications/finderchart/ - switch to results tab, hint shouldn't appear
https://irsa-6134-blinking-hint-fix.irsakudev.ipac.caltech.edu/irsaviewer/ - hint should appear
Clean browser local storage and then go to https://irsa-6134-blinking-hint-fix.irsakudev.ipac.caltech.edu/irsaviewer/?_ …
> IRSA-6134: Fix blinking "choose tab" hint in finder chart and other apps

- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- src/firefly/js/metaConvert/vo/DatalinkProducts.js
- src/firefly/js/templates/router/RoutedApp.jsx
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapViewType.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- https://firefly-1490-lock-tap-schema.irsakudev.ipac.caltech.edu/applications/euclid/
- bring up euclid choose the sidebar option for Euclid catalogs
- it will show only wise catalogs but can be changed to euclid in the future when we have some
> Firelfy-1490: TAP catalogs can now be locked to a schema

- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/tables/ui/BasicTableView.jsx
- src/firefly/js/tables/ui/TablePanel.jsx
- src/firefly/js/tables/ui/TablesContainer.jsx
- src/firefly/js/templates/fireflyviewer/FireflyViewer.js
- src/firefly/js/templates/hydra/HydraViewer.jsx
- src/firefly/js/templates/lightcurve/LcImageViewerContainer.jsx
- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
- src/firefly/js/ui/AutoCompleteInput.jsx
- src/firefly/js/ui/ChartSelectDropdown.jsx
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/ui/FileUpload.jsx
- src/firefly/js/ui/InputAreaField.jsx
- src/firefly/js/ui/InputField.jsx
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/PagingBar.jsx
- src/firefly/js/ui/SizeInputField.jsx
- src/firefly/js/ui/SuggestBoxInputField.jsx
- src/firefly/js/ui/WorkspaceViewer.jsx
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- removed `defaultProps` from functional components
- removed calls to `findDOMNode`
- https://fireflydev.ipac.caltech.edu/firefly-1515-prepare-for-19/firefly
- Everything should work as before
- Look closely at the table related components
> Firefly-1515: fix deprecations to prepare for react 19

- src/firefly/js/ui/UploadTableSelectorPosCol.jsx
- src/firefly/js/ui/UploadTableSelectorSingleCol.jsx
- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/tap/ObjectIDSearch.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1507
**IFE PR**: https://github.com/IPAC-SW/irsa-ife/pull/340
- I added a `search by radius` option to multi-object uploads, as the API takes this as a param. 
- did some refactoring, so now we have `UploadTableSelectorSingleCol` (user uploads a file, and we let them pick one column from the file - this is used by `Object ID Search` and `Search by ID` in Euclid) and `UploadTableSelectorPosCol` (this is the old and original `UploadTableSelector`, just renamed it to indicate selecting position columns - ra and dec - from the uploaded file as opposed to a single column) 
**Testing**:
- https://firefly-1507-search-processor-euclid.irsakudev.ipac.caltech.edu/applications/euclid
- In Inspect Sources, test by changing the size/radius for …
> Firefly-1507: Adding search radius to multi object uploads

- compose.yml
- docker/launchTomcat.sh
- src/firefly/java/edu/caltech/ipac/firefly/data/DecimateInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/data/TableServerRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/java/edu/caltech/ipac/util/decimate/DecimateKey.java
- src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1517
Optimizes the memory usage of `DecimationProcessor`. It should work the same as before with one key difference: the represented point (highlighted row) is now taken from the first row of an `SQL GROUP BY` statement instead of a random row determined by Java logic. This change should not impact functionality. Open to feedback.
This approach eliminates the need to load the entire table into JVM memory, which previously could consume gigabytes of memory. It also significantly speeds up processing for larger tables for the same reason.
Test: https://fireflydev.ipac.caltech.edu/firefly-1517-decimation/firefly/
Load bigger tables, at least 5000 rows to trigger decimation.
> FIREFLY-1517: use SQL to create decimate data

- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/ui/TablesContainer.jsx
A patch to previous Pull Request: https://github.com/Caltech-IPAC/firefly/pull/1594
- fix table tab switcher not showing table title as a string
> FIREFLY-1519: fix table tab switcher not showing table title as a string

- src/firefly/js/tables/TableUtil.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1516
I added a test file to the ticket to show that the chart will recognize `short` as a numeric type. 
The test table also includes an `unsignedByte` column to address the question raised in the ticket.
Test: https://fireflydev.ipac.caltech.edu/firefly-1516-chart-numeric-columns/firefly/
> FIREFLY-1516: The chart is not recognizing short as a numeric type

- __jest__/jest.base.config.js
- src/firefly/jest.config.js
- src/firefly/package.json
Fixes [FIREFLY-1522](https://jira.ipac.caltech.edu/browse/FIREFLY-1522)
Related PRs: https://github.com/IPAC-SW/irsa-ife/pull/346, https://github.com/lsst/suit/pull/53
- Moved jest config from the inline declaration in package.json to a dedicated file in `__jest__/jest.base.config` (gradle is setup already to copy everything under `__jest__` so it will become available to ife apps.
- Created a `jest.config.js` on same level as `package.json` to:
- override base config if needed (firefly doesn't do it but ife apps do)
- automatically get picked by jest command
Ran `gradle app:test` for all apps: firefly, euclid, irsaviewer, etc. - tests are able to run successfully
> FIREFLY-1522: Extract jest config from firefly for reusing it in all ife apps

- src/firefly/js/metaConvert/DataProductsWatcher.js
- src/firefly/js/tables/TableUtil.js
**Ticket**: https://jira.ipac.caltech.edu/browse/IRSA-6112
**IFE PR**: https://github.com/IPAC-SW/irsa-ife/pull/348
- added support for removing and re-adding tables to Euclid results view when user selects only Explore Regions ***_or_*** Inspect Sources tables (catalog results will always show) 
**Testing**:
- Euclid: https://irsa-6112-euclid-combine-results.irsakudev.ipac.caltech.edu/applications/euclid
- test selecting ***All Results***, ***Explore Regions***, and ***Inspect Sources*** after performing a search in Euclid
- Firefly: https://fireflydev.ipac.caltech.edu/irsa-6112-euclid-combine-results/firefly
- this is just to do a few searches to make sure nothing broke on firefly
> IRSA-6112: Support Euclid combine results

- src/firefly/js/metaConvert/PartAnalyzer.js
One char bug fix for spectra not loading in Euclid.
Testing:
- ~~for some reason my test build is not getting built (I think jenkins or branch name issue), but I tested locally and this resolves the bug~~
- Never mind, here's the test build (I forgot to keep IFE branch as `dev`): https://firefly-bug-fix-spectra.irsakudev.ipac.caltech.edu/applications/euclid
- Try these IDs for a Search by ID (Object ID) search: 2360606233404805332
> Hotfix: one char bug fix for spectra in euclid

- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/ui/PlotlyWrapper.jsx
- src/firefly/js/templates/lightcurve/LcViewer.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1535
- changes are very small, but this is my first time working with plotly, so took some time to figure out the workflow and the issue.
- So we currently update the chart when user applies one of 4 options (grid, top/right, reverse and log) using `Plotly.relayout`, and we send it a `layoutUpdate` (or `layoutDelta` object), which is just the difference of the current and old layout based on user selection instead of the entire layout context (which is the `layout` object)
- from my research and understanding of this topic: `Plotly.relayout` is great for updates like grid, log, etc. but not for complex stuff like axes reversal. 
- To fix this, I considered using `Plotly.react`, which re-renders the entire plot though. 
- After some …
> FIREFLT-1535: Timeseries bug fix

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ui/ChartPanel.jsx
- src/firefly/js/charts/ui/CombineChart.jsx
- src/firefly/js/charts/ui/CompareRowCharts.jsx
- src/firefly/js/charts/ui/PinnedChartContainer.jsx
- src/firefly/js/metaConvert/vo/ServDescConverter.js
Fixes [IRSA-6111](https://jira.ipac.caltech.edu/browse/IRSA-6111)
Also see: https://github.com/IPAC-SW/irsa-ife/pull/351
- Refactored CombineChart to make it:
- independent of PinnedChartsContainer, and accept `chartIds` instead
- handle promises of chartIds (because async fetching of charts is required in Euclid) as well as the loading and error states
- generic overall and more meaningful names of variables
- Created two specific HOCs of CombineChart:
1. `CombinePinnedCharts` - to allow existing functionality
2. `CombineRowCharts` - to allow fetching charts from the selected rows in active table (Euclid's compare sources functionality)
- Bonus: Improved trace titles creation in combined chart - added chart title to trace titles. Old titles that just rely on trace numbering were …
> IRSA-6111: Make a compare sources tab in Euclid

- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/TablePanel.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1536
**IFE-PR**: https://github.com/IPAC-SW/irsa-ife/pull/352
- This PR enables calling `dispatchTblResultsAdded` by itself, indirectly enabling re ordering tables 
- by removing table from results view by calling `dispatchTblResultsRemove` and then by calling `dispatchTblResultsAdded` when you need to re-add this table in the order you want
**Testing**: 
- Euclid: https://firefly-1536-euclid-reorder-tbls.irsakudev.ipac.caltech.edu/applications/euclid
- Start by doing an Explore Regions search, Inspect Sources search & catalog searches 
- Click on the `Show Results` toggle buttons, if tables are being removed and added back to the results view as expected, then this is working.
> FIREFLY-1536: Support for standalone dispatchTblResultsAdded to support reordering of tables

- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
- https://fireflydev.ipac.caltech.edu/firefly-1547-color/firefly
- load any images
- show the color dropdown
- it should look the same in dark mode or light mode
> Firefly-1547: fixed: color table not inverting

- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/templates/hydra/HydraManager.js
- src/firefly/js/ui/Menu.jsx
View [ ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-1548) for details.
By adding checks for none app searches from: `IRSA search tabs` and `External archive search tabs`, the previous search results are cleaned out for new app search only.
To test:
https://firefly-1548-sofia.irsakudev.ipac.caltech.edu/applications/sofia
https://firefly-1548-wiseirsakudev.ipac.caltech.edu/applications/wise
https://firefly-1548-ztf.ipac.caltech.edu/applications/ztf
https://firefly-1548-sha.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
https://firefly-1548-euclid.irsakudev.ipac.caltech.edu/applications/euclid/
go to any of above IRSA app, ie. sofia, wise, ztf,
* make a position search (or any app search)
* navigate to a different search (without submit search), then go do a Catalog search (or …
> FIREFLY-1548 fix-irsa-app-search-cleanup-issue

- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/network/IpacTableHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/UwsJobProcessor.java
- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/ui/PopupPanel.jsx
- src/firefly/js/ui/tap/TapKnownServices.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1533
- attaching a RUNID to the submission when TAP service supports it.
- save information local for display
- filling it in with the user-specified value
- displaying it in the job-status dialog
- displaying it in the table-info dialog
Test: https://fireflydev.ipac.caltech.edu/firefly-1533-runid-jobname/firefly/
- do a TAP search
- [optional] enter a custom title.  (bottom of form next to Search and Row Limit)
- while in progress, click on 'i' icon to see Job Information, then 'Show' to see UWS Job info.
- once table results returned, click on 'i' table info to see 'Job Info', then 'Show' to see UWS Job info.
Notes:
- most of the predefined TAP services do not properly support this.
- RUNID is limited to 64 chars.  If more than 64, …
> Firefly 1533 runid jobname

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/test/edu/caltech/ipac/table/DuckDbAdapterTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1552
IpacTableFromSource was fetching data from the URL again, even though the database for this request already exists. This can be observed through network activity in Chrome DevTools or by checking the logs.
Test: https://firefly-1552-ipacfromsource-cache.irsakudev.ipac.caltech.edu/irsaviewer/dce
- Select a position, then click Submit.
> FIREFLY-1552: IpacTableFromSource processor unnecessarily re-fetches data

- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1553
- The changes are very small, but they fix some existing issues mentioned in the ticket, a quick summary:   
- When you upload a `moc fits` file via the `UploadTableChooser` popup (Multi-object search), the `Load/Cancel` buttons were not visible unless you resized the dialog to make it bigger. 
- Also, the `Details` model table on the right was either not visible or just barely visible in the `UploadTableChooser` popup. 
- This PR fixes both issues. 
- **_Note_**: The styling is applied directly within `FileUploadViewPanel`, so this affects the `Upload` tab as well. I chose to do it this way because it makes the `Upload` tab cleaner as well. 
- it makes the summary model (the table on the left when you upload a file like `moc …
> FIREFLY-1553: Upload table chooser popup UI bug fixes

- src/firefly/html/test/test-hips-mocs.html
- src/firefly/java/edu/caltech/ipac/firefly/server/Counters.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/VosiCapabilityRetrieve.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/js/drawingLayers/HiPSMOC.js
- src/firefly/js/drawingLayers/WebGrid.js
- src/firefly/js/drawingLayers/hpx/HpxCatalog.js
- src/firefly/js/tables/HpxIndexCntlr.js
- src/firefly/js/ui/tap/AdvancedADQL.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/ui/tap/TapViewType.jsx
- src/firefly/js/util/WebUtil.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/saga/CoverageWatcher.js
- saved via api
- saved with "enter my URL" option
- save as a preference
- The option should remain through reloads until the user removes it.
- improve bad server error handling
- https://fireflydev.ipac.caltech.edu/firefly-1558-tap-service/firefly
- enter a alternate tap server (such as: https://irsadev.ipac.caltech.edu/TAP) 
- reload, it should still be in the list
- enter a bad one  (such as: https://abcdefg.edu/TAP) 
- The error handling has improved
- reload and they both should still be in the list. You can select them just like before.
- try out the `x` on the servers you entered
- _open_ developer tools
- _on top choose_: Application
- _on left choose_:  Local Storage -> the url
- _on right highlight_: `APP_PREFERENCES`
- click on the `X`
> Firelfy-1558: Save user add TAP servers as a preference and show it in the list.

- README.md
- buildScript/app.gincl
- buildScript/dependencies.gradle
- buildScript/tasks.gincl
- docker/Dockerfile
- src/firefly/build.gradle
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1559
- main purpose is to avoid JVM crashing when loading big FITS images.
- required upgrading Gradle from v7.4 to v8.10
- upgrade Tomcat v9 on openjre17 to v9 on openjre21-jammy
- required upgrading Java and Gradle for firefly-help as well
- fix Gradle build scripts as part of upgrading Gradle
- update document to reflect changes
More changes here: 
https://github.com/IPAC-SW/irsa-ife/pull/358
https://github.com/Caltech-IPAC/firefly-help/pull/40
https://github.com/lsst/suit/pull/54
After merging firefly-help, I will also update irsa-ui-help and suit-help.
Requires regression testing.
Test builds:
https://fireflydev.ipac.caltech.edu/firefly-1559-java-21-upgrade/firefly/
https://firefly-1559-java-21-upgrade.irsakudev.ipac.caltech.edu/irs …
> FIREFLY-1559: Upgrade Java from version 17 to 21

- src/firefly/js/charts/ui/PlotlyWrapper.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1535
- The fix is just one line, but this will require some explanation of my findings. 
- Prerequisite to understanding the below is to understand what `autorange` and `range` represent within the `layout` object  in Plotly. 
- Simply put, if you have a valid `range` entry, then `autorange` **_must_** be set to false. and if there is no valid range, `autorange` is either set to `true` (meaning plotly dynamically calculates axis range) or set to `reversed` (when reversing the axis). 
- Issues arise when `autorange` is set to `true` while still having a valid `range`. 
- My initial suspect was the logic inside `evalChangesFromFields` in `BasicOptions.jsx` (which determines changes to the layout). Specifically, for this ticket, I was …
> FIREFLY-1535: Chart fix for reversal of axes bug

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/SrvParam.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ExtractFromImage.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSExtractToTable.java
- src/firefly/java/edu/caltech/ipac/table/io/FITSTableReader.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsExtract.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/js/Firefly.js
- src/firefly/js/data/ServerParams.js
- src/firefly/js/drawingLayers/ExtractLineTool.js
- src/firefly/js/rpc/PlotServicesJson.js
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/tap/TapKnownServices.js
- src/firefly/js/visualize/FitsHeaderUtil.js
- src/firefly/js/visualize/projection/ProjectionHeaderParser.js
- src/firefly/js/visualize/saga/CatalogWatcher.js
- src/firefly/js/visualize/ui/Buttons.jsx
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- src/firefly/js/visualize/ui/extraction/ExtractionChart.jsx
- src/firefly/js/visualize/ui/extraction/ExtractionDialog.jsx
- src/firefly/js/visualize/ui/extraction/ExtractionTable.jsx
- improve 1D image to table handling
- [Firefly-1560](https://jira.ipac.caltech.edu/browse/FIREFLY-1560): add support of line or column to extraction
- Improved chart line combine pixels extraction (1xn or nx1)
- https://fireflydev.ipac.caltech.edu/firefly-1180-extract/firefly
- [Firefly-1180](https://jira.ipac.caltech.edu/browse/FIREFLY-1180)
- upload panel `->` choose url `->` https://data.desi.lbl.gov/public/epo/example_files/coadd-0-100-thru20210505.fits
- load one of the nx1 tables. The results has been updated according to the ticket
- [Firefly-1560](https://jira.ipac.caltech.edu/browse/FIREFLY-1560)
- load a fits
- choose line extract
- try to new option to choose only a line or column
> Firefly-1180: improve table from fits image HDU uploads

- src/firefly/js/charts/ChartUtil.js
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/charts/dataTypes/FireflyGenericData.js
- src/firefly/js/charts/dataTypes/FireflySpectrum.js
- src/firefly/js/tables/SelectInfo.js
- src/firefly/js/tables/TablesCntlr.js
Alternative solution to PR https://github.com/Caltech-IPAC/firefly/pull/1629
[Firefly-1545](https://jira.ipac.caltech.edu/browse/FIREFLY-1545): charts better handle large selections
The first commit addresses two issues:
- Lodash's `_.isEqual` is slow when comparing large sets or arrays.
- Firefly should skip unnecessary selection updates.
These changes enable Firefly to handle scatter plots with up to 1 million rows, instead of crashing at a much smaller datasets. 
However, performance is noticeably slow beyond this point.  It turns out updating the highlighted row rather than selection updates that's slow.
The second commit attempt to optimizes chart highlighting:
- Reduced code execution time from 160ms to around 60ms.
- Unfortunately, the remaining execution time is due to Plotly.js, …
> Firefly-1545: charts better handle large selections (alternative)

- src/firefly/java/edu/caltech/ipac/firefly/core/FileAnalysis.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/H2DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/HsqlDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/SqliteDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ResourceProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SharedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/java/edu/caltech/ipac/table/DataType.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/js/tables/ui/TableSave.jsx
- src/firefly/test/edu/caltech/ipac/table/DuckDbAdapterTest.java
- src/firefly/test/edu/caltech/ipac/table/EmbeddedDbUtilTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1550
Add support for saving a Firefly table in Parquet format. 
The file will be saved as a `parquet.votable` file, which is a Parquet file with  VOTable metadata. This will allow users to store table data in a highly efficient, columnar storage format while preserving the rich metadata associated with VOTables.
More details about the standard here: https://github.com/astropy/astropy/pull/16375
Sample files here: https://vizcat.cds.unistra.fr/hats:n=1000000/
While testing, I noticed Firefly fails to write out RESOURCES when they are present.  I file this as a bug [FIREFLY-1563](https://jira.ipac.caltech.edu/browse/FIREFLY-1563)
Also, I noticed many sample files with `unit=[]`.  Is this something Firefly need to interpret as empty string …
> FIREFLY-1550: Save table in Parquet format

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/fitseval/SpectralCubeEval.java
- src/firefly/js/drawingLayers/WebGridUI.jsx
- src/firefly/js/metaConvert/DataProductsType.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/ui/CutoutSizeDialog.jsx
- src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
- src/firefly/js/ui/dynamic/ServiceDefTools.js
- src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
- src/firefly/js/ui/tap/TapViewType.jsx
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
- src/firefly/js/visualize/ui/ImageMetaDataToolbar.jsx
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
- src/firefly/js/voAnalyzer/VoConst.js
- redundant adds of related data HDUs in SpectralCubeEval.java (found during sphereX testing)
- PlotImageTask.js improved logging of RelatedData errors (found during sphereX testing with  @alaity47)
- WebGridUI.js showing empty options (found by NED)
- MultiProductViewer
- Better naming cutout services (found by @alaity47)
- Better job in recognizing cutout services (found during sphereX testing a datalink table with  @alaity47)
- Support pixel cutout service  (found during sphereX testing with  @alaity47)
- Color dropdown in hips mode, empty image for default color option, should be none (found during testing)
- https://fireflydev.ipac.caltech.edu/firefly-1564-bugs/firefly
- Hips colors: 
- show any HiPS image (Images -> View HiPS image)
- The color dropdown, `Default Color Map` should …
> Firefly-1564: fix some bug found durring testing

- docs/next-release-details.md
- src/firefly/java/edu/caltech/ipac/visualize/plot/Histogram.java
- src/firefly/js/drawingLayers/ExtractLineTool.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/metaConvert/UploadAndAnalysis.js
- src/firefly/js/ui/InputFieldView.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapUtil.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/ui/extraction/ExtractionDialog.jsx
- src/firefly/js/visualize/ui/multiProduct/MPMessages.jsx
- line 7,41
- can't choose free initially
- flip between column and line lock, it moves the line but doesn't refresh the plot. and it doesn't go back to the line i had before.
- random clicking (as i'm frustrated and trying to sort it out) makes it behave strangely. ideally give an error message. but at least don't behave like point extraction
- name selection options more clearly
- line 10 - removing user added TAP service
- line 17 - loading datalink xml file
- clean up release notes per @lrebull 's sugestions
- https://fireflydev.ipac.caltech.edu/firefly-1570-7-10-17/firefly
> Firefly-1570: fix 7(41),10,17

- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/tables/tables-typedefs.jsdoc
- src/firefly/js/voAnalyzer/SpectrumDM.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1534
> should work like this:
> 
> If the table has a Utype, use it.
> If the table does not have a Utype, search "outwards" in the enclosing elements in the XML and use the first one you find.  Thus, in the typical nesting:` <VOTABLE><RESOURCE><TABLE></TABLE></RESOURCE></VOTABLE>` , you would start with the TABLE, and then check the RESOURCE containing it.
Test: https://fireflydev.ipac.caltech.edu/firefly-1534-spectrum-utype/firefly/
- Load a spectrum where `utype` is not from `<TABLE>` but from `<RESOURCE>`
> FIREFLY-1534: Check for utype in the table's resources if one does not exist in the table.

- src/firefly/js/ui/HiPSImageSelect.jsx
**Ticket**: [FIREFLY-1567](https://jira.ipac.caltech.edu/browse/FIREFLY-1567)
- fix for a regression bug, caused by my previous PR: https://github.com/Caltech-IPAC/firefly/pull/1624
- that PR didn't take into account the HiPS `Add MOC Layer` upload popup calling `FileUploadViewPanel` directly
**Testing**
Firefly: https://fireflydev.ipac.caltech.edu/firefly-1567-upload-bug/firefly
- do any TAP search (for instance `m81` on `IRSA` & `wise_allwise`)
- In `Coverage`, under the `HiPS / FITS / MOC` dropdown, click on `Add MOC Layer`
- go to the `Use my MOC` tab. 
- Upload a MOC fits file here. You should be able to see the details clearly (as opposed to it being squished, like in the screenshot below). Try this in both a small and large browser size.  
- here's a screenshot of what it looked …
> FIREFLY-1567: Fix upload popup style for HiPS MOC dialog

- src/firefly/js/templates/lightcurve/LCPanels.css
- src/firefly/js/templates/lightcurve/LcPeriodPlotly.jsx
**Ticket**: [FIREFLY-1492](https://jira.ipac.caltech.edu/browse/FIREFLY-1492)
- see screenshot in ticket for a quick summary existing layout issues
- a lot of these issues occur due to resizing browser size, if you opened the browser with a small enough size and didn't resize, you may not even notice these 
- There are 4 major components on the page, tried to make them equally spaced out 
- The `LcPFOptionsBox` (the box on the top left) looked awkward when browser size is large enough, leaving whitespace between itself and the table below
- I essentially used `flexGrow: 1` here to make it expand into and take up the whitespace
- This may look a little awkward, but I tried to make the component internally spaced out as well. Open to better suggestions. 
- Made the top-right chart expand to …
> FIREFLY-1492: Timeseries Period Finder Layout Issues

- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/table/DataGroup.java
- src/firefly/java/edu/caltech/ipac/table/IpacTableUtil.java
- src/firefly/java/edu/caltech/ipac/table/TableUtil.java
- src/firefly/java/edu/caltech/ipac/table/io/DataGroupStarTable.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1575
- The column names only differ in terms of case sensitivity (uppercase vs. lowercase).
- Add support for VOTable and Parquet formats.
- For other formats, duplicate column names will have '_idx' appended to ensure uniqueness.
Solution:
When a duplicate column is detected, we will append an index to the column name (e.g., col_a becomes col_a_1). 
The original name (col_a) will be saved as `column.label`, which will be displayed in the UI. If the column's `ID` doesn't already exist, we will assign the modified name (col_a_1) as the column's ID to indicate the uniqueness of the column.
These information will be used to accurately write back the file in its original format.
Test: https://fireflydev.ipac.caltech.edu/firefly-1575-simbad-dulicate- …
> FIREFLY-1575: Simbad query returns duplicate columns

- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
- When you upload a multi-HDU FITS then upload a table the details to do render
- https://fireflydev.ipac.caltech.edu/firefly-1586-upload/firefly
- test according to ticket
> Firefly-1584: Upload not showing table summary after multi extension FITS

- src/firefly/js/templates/lightcurve/LcPeriodogram.jsx
**Ticket**: [FIREFLY-1568](https://jira.ipac.caltech.edu/browse/FIREFLY-1568)
- see ticket for bug description
- Fix: just set `mounted: true` when calling `dispatchChartAdd`. 
- That fixes the bug in the ticket, but there may need to be further discussion (or new ticket) to clean up our general mounting/unmounting logic. 
- ~~Fix: when recalculating periodogram, the `chartId: 'periodogram'` is the same as before, but to mount a chart, we rely on a useEffect in `ChartPanelView` (`ChartPanel.jsx` line 22) that's triggered by a `chartId`. 
this is the reason why changing table tabs (to `peaks table` and back to `periodogram` makes the chart show up)
therefore, when recalculating periodogram, I appended a counter to the `chartId` so that it's changed and triggers this `useEffect`~~
- ~~I'm …
> FIREFLY-1568: Periodogram Render bug fix

- docs/release-notes.md
- src/firefly/js/drawingLayers/FixedPtControl.jsx
- src/firefly/js/drawingLayers/FootprintTool.js
- src/firefly/js/drawingLayers/MarkerTool.js
- src/firefly/js/drawingLayers/WebGrid.js
- src/firefly/js/drawingLayers/WebGridUI.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/visualize/draw/DrawLayer.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/task/PlotImageTask.js
- src/firefly/js/visualize/ui/DrawLayerPanelView.jsx
- src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- src/firefly/js/visualize/ui/SelectAreaDropDownView.jsx
- src/firefly/js/visualize/ui/SimpleLayerOnOffButton.jsx
- src/firefly/js/visualize/ui/VisMiniToolbar.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
- src/firefly/js/voAnalyzer/VoTableRecognizer.js
- [Firefly-1589](https://jira.ipac.caltech.edu/browse/FIREFLY-1589): add scroll bar to MultiProduct jpg viewer
- [Firefly-1584](https://jira.ipac.caltech.edu/browse/FIREFLY-1584): options consistent
- Fixed bug in draw layer end button
- Grid overlay: can be turned on and off, sticky when on
- Footprint overlay:can be turned on and off, sticky when on
- Mouse readout "Lock by Click" will support choosing a point and then shift-clicking on other image and keeping the same point
- When looking for center ra/dec columns in a table, if more than one column has the same UCD, the parser will prefer a floating column over a string
- Firefly: https://fireflydev.ipac.caltech.edu/firefly-1587-overlays/firefly
- irsaViewer: https://firefly-1587-overlays.irsakudev.ipac.caltech.edu/irsaviewer/dce
- …
> Firefly-1587: improving overlays

- src/firefly/html/test/tests-table.html
- src/firefly/js/tables/ui/TablesContainer.jsx
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-6431
When multiple `tbl_groups` were used, tables in the second group were unable to switch tabs in expanded mode.
Test: https://fireflydev.ipac.caltech.edu/irsa-6431-switch-tabs-expanded-mode/firefly/test/tests-table.html?test=Custom+Table+Title
- Expand the second table tabs
- Ensure you are able to switch tabs
- The drop-down Open Tabs selector should also work
@cwang2016 It would be nice if you can try and test this version to see that it actually fixes the bug you found.
> IRSA-6431: Firefly tables in expanded mode was unable to switch tabs.

- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/visualize/ui/TargetHiPSPanel.jsx
- https://firefly-1596-radius.irsakudev.ipac.caltech.edu/applications/euclid/search-region-pos
- when you choose `image contains target` you should not see a radius on the HiPS image
- The build was against the irsa-ife branch `tmp-test-for-FIREFLY-1596`
> Firefly-1596: disable showing radius

- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableHandler.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1591
Changes include:
- Direct import of VOTable data into the database
- Refactoring of VoTable reading code
Optimizations for VOTable Ingestion:
- Switched from MEMORY-only to ADAPTIVE parsing, offloading excess data to disk.
- Enabled direct VOTable import, eliminating the Firefly table conversion.
Performance Summary:
Loading a 300MB VOTable file now requires less memory and time:
- Initially: 3.07s, JVM 1.1GB → Optimized: 2.67s, JVM 250MB
Database Ingestion now requires a tiny amount of memory because it does not need to load the full table.
- Initially: 6.76s, JVM 1.1GB → Optimized 5.25s with only **32MB** memory
https://fireflydev.ipac.caltech.edu/firefly-1591-votable-direct-ingest/firefly/
To test it out:
- Run a small IRSA …
> FIREFLY-1591: Directly import VOTable data into the database.

- src/firefly/js/util/WebUtil.js
- src/firefly/js/util/__tests__/WebUtil-test.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1606
Just a small fix. As mentioned in the ticket, after the links in the table are resolved, the port portion of the URL is missing.
Run WebUtil-test.js to test.
> FIREFLY-1606-links-missing-port

- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbDataIngestor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/table/io/IpacTableReader.java
- src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/test/edu/caltech/ipac/firefly/server/util/tables/DataGroupReadTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1592
See ticket for details.
In the past, handling large tables required more memory. This PR should improve that.
Test: https://fireflydev.ipac.caltech.edu/firefly-1592-ipactable-direct-ingest/firefly/
- Upload a large IPAC table
If you need a test file, you can use this one: a 3 million row, 25 column, 1.2GB IPAC table file. https://irsadev.ipac.caltech.edu:9201/test/3mil.tbl  (Upload via URL)
From DevTools, I see that my PR build takes 21.4s, compared to 28.2s for nightly. On the nightly build, it seems to crash (or possibly fails to load) on hips coverage, as it sometimes doesn't show up. Both PR and nightly are running with 4GB of memory.
> FIREFLY-1592: Directly import IPAC table data into the database

- src/firefly/java/edu/caltech/ipac/firefly/resources/healpix-java.sql
- src/firefly/java/edu/caltech/ipac/firefly/server/ServCommand.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbInstance.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbUDF.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/spring/JdbcFactory.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/HealpixProcessor.java
- src/firefly/java/edu/caltech/ipac/util/StringUtils.java
- src/firefly/js/charts/ChartsCntlr.js
- src/firefly/js/tables/ui/AddOrUpdateColumn.jsx
- src/firefly/test/edu/caltech/ipac/table/HealpixProcessorTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1607
- create deg2pix UDF
- create HealpixProcessor
- create HealpixProcessorTest
- enable json error log for better duckdb error message
> FIREFLY-1607: Server-side implementation of Healpix index

- src/firefly/java/edu/caltech/ipac/firefly/server/dpanalyze/SofiaAnalyzer.java
View [tickedt](https://jira.ipac.caltech.edu/browse/IRSA-4877) for details.
Added logic for SOFIA Forcast grism product type "combined_spectrum" to be treated as spectra.
To test:
https://irsa-4877-sofia.irsakudev.ipac.caltech.edu/applications/sofia
1. pick All-Sky search, in Instrument Constraints select FORCAST, and Data Product Constraints pick Level3
2. in FORCAST result tab, filter on column "Product Type" with "combined_spectrum" and "combspec"
3. navigate product Type and view Data tab with Spectrum
> IRSA-4877 SOFIA FORCAST GRISM product

- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/ui/MouseReadoutOptionPopups.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
Fixes [FIREFLY-1572](https://jira.ipac.caltech.edu/browse/FIREFLY-1572)
- Removed extra leading whitespace in copy string of hms readouts
- Added Python SkyCoord readout option
- Created a separate radio group for radio options since independent from readout options
- Copy options appear specifically when click lock is on and options are WorldPt compatible
- For celestial case (fits with WCS), SkyCoord option becomes disabled for Image pixel options - this is done on purpose to prevent layout from jumping 
- ~Show it selectively when firefly is being interfaced by python~
https://fireflydev.ipac.caltech.edu/firefly-1572-coord-copy/firefly/
Load a fits image, turn click lock on, copy coords - they shouldn't have leading whitespace
Click on the chip and change copy options to "SkyCoord" …
> FIREFLY-1572: Improve copying of coordinates from image panel

- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/js/tables/HpxIndexCntlr.js
- also fixed: [Firefly-1614](https://jira.ipac.caltech.edu/browse/FIREFLY-1614): coverage map zoom issues (again. still.)
- [Firefly-1597](https://jira.ipac.caltech.edu/browse/FIREFLY-1597)
- https://fireflydev.ipac.caltech.edu/firefly-1597-null/firefly
-  load file from ticket
- [Firefly-1614](https://jira.ipac.caltech.edu/browse/FIREFLY-1614): 
- https://firefly-1597-null.irsakudev.ipac.caltech.edu/applications/Gator/
- do a small tap search- wise,m31, 10 arcsec
> Firelfy-1597: fixes: things with null ra/dec shouldn't be plotted on coverage map

- src/firefly/js/charts/ui/ChartPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1627
https://firefly-1627-filter-order-plot.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
To test, follow the description in the ticket.
> FIREFLY-1627: filtering on spectral plots with >1 order causes chaos

- buildScript/tasks.gincl
- src/firefly/java/edu/caltech/ipac/firefly/server/query/StatisticsProcessor.java
- src/firefly/js/charts/ui/CombineChart.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1599
- there were NaNs in the data which is a max value for stats.
- replaced NaNs with null so that it is not counted when collecting stats.
To test: https://fireflydev.ipac.caltech.edu/firefly-1599-comgine-cascade-spectra/firefly/
- upload sample fits file from the ticket -> Load Image
- using `Extract Z-axis from cube` tool to pin a few charts
- switch to `Pinned Charts` tab, then combine them
- remember to select `Apply cascading` option
> FIREFLY-1599: cascade combining spectra is broken

- src/firefly/js/templates/common/ttFeatureWatchers.js
**Ticket**: [FIREFLY-1635](https://jira.ipac.caltech.edu/browse/FIREFLY-1635)
- there's a regression bug in `ttFeatureWatchers.js`, in some cases the request object does not have a `source` entry, but will have a `serviceUrl` entry instead (from TAP). 
- this fix uses that value when `source` is undefined, fixing the `Prepare Download` not working for CADC bug 
**Testing**: 
Firefly: https://fireflydev.ipac.caltech.edu/firefly-1635-prepare-download-bug/firefly
DCE: https://firefly-1635-prepare-download-bug.irsakudev.ipac.caltech.edu/irsaviewer/dce
- do a CADC search and select one or more rows, click on `Prepare Download` to make sure it works 
-  the search i do is: select IVOA from the CADC tables, and search for 'm81', 10 rows.
- do a DCE search and repeat the same step (click on …
> FIREFLY-1635: bug fix for CADC prepare download

- src/firefly/java/edu/caltech/ipac/firefly/data/ServerParams.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerCommandAccess.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
- src/firefly/js/core/background/BackgroundCntlr.js
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/data/ServerParams.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/ui/DownloadDialog.jsx
**Ticket**: [IRSA-6468](https://jira.ipac.caltech.edu/browse/IRSA-6468)
- [**IFE PR**](https://github.com/IPAC-SW/irsa-ife/pull/375)
- Based on feedback, created a `DownloadSciptWorker` based on our existing `PackagingWorker` with changes to write out the URLs to a script made available for download (instead of zipped files of products) 
- Client can specify the script type (`curl`, `wget` or plain list of urls) 
- Removed cutout option from the UI (a new [ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-1639) will address this item). 
- Modified `DownloadScript.java` to support better filename generation from the given URL 
- Made some changes in the `DownloadButton` and `DownloadOptionPanel` components to accept the download button text (instead of `Prepare Download`)
- …
> IRSA-6468: Support for Packager Script of URLs (Euclid, SphereX, Rubin, etc.) 

- firefly-docker.env
- src/firefly/java/edu/caltech/ipac/firefly/messaging/JsonHelper.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/util/AppProperties.java
- every value will be a separate property
- set a path with an underscore divider
- example- PROPS_OP_coverage_hipsSourceURL=ivo://CDS/P/allWISE/W4
- checkout branch
- modify firefly-docker.env to set any properties
- use `docker-compose` to build and run
> Firefly-1641: new FIREFLY_OPTIONS aproach

- src/firefly/js/data/MetaConst.js
- src/firefly/js/metaConvert/TableDataProductUtils.js
- src/firefly/js/metaConvert/vo/DataLinkStandAloneConverter.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/ui/CutoutSizeDialog.jsx
- src/firefly/js/ui/ToolbarButton.jsx
- src/firefly/js/ui/panel/CollapsiblePanel.jsx
- src/firefly/js/ui/tap/ObsCoreOptions.js
- src/firefly/js/ui/tap/SIASearchRootPanel.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TapSearchSubmit.js
- src/firefly/js/visualize/VisUtil.js
- src/firefly/js/visualize/projection/Projection.js
- src/firefly/js/visualize/ui/ImageMetaDataToolbarView.jsx
- src/firefly/js/visualize/ui/VisInlineToolbarView.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
- src/firefly/js/voAnalyzer/TableAnalysis.js
- src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- src/firefly/js/voAnalyzer/vo-typedefs.jsdoc
- add support of types of cutout - user, search position, row position
- improve UI for better selection and feedback
- ife PR: https://github.com/IPAC-SW/irsa-ife/pull/376
- https://firefly-1643-improve-cutouts.irsakudev.ipac.caltech.edu/applications/euclid
- do a search of `Images`, and play with different types of cutouts
- I did 3h54m50.91s -50d42m08.0s Equ J2000
- for radius 5400
- choose table (magnifier) options `Show table of all Euclid products for this row`
- the cutout will work for the row that support them otherwise it will show full images
- cutouts work for `#this`, `#cutout`, `#counterpart`
- note- this is the full datalink table of everything
> Firefly-1643: improve cutouts

- src/firefly/java/edu/caltech/ipac/astro/ibe/IBE.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/URLFileInfoProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/LockingVisNetwork.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/AllSkyRetriever.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/URLFileRetriever.java
- src/firefly/java/edu/caltech/ipac/util/FileUtil.java
- src/firefly/java/edu/caltech/ipac/visualize/net/AnyUrlParams.java
- src/firefly/js/Firefly.js
- src/firefly/js/api/webApiCommands/TableCommands.js
- src/firefly/js/ui/PositionFieldDef.js
- src/firefly/js/ui/TargetFeedback.jsx
- src/firefly/js/ui/TargetPanel.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/util/PositionParser.js
- `TargetPanel` example settable from appOptions, tapObsCore and tapObsCore[source]
- use  `targetPanelExampleRow1`, `targetPanelExampleRow2`
- `TargetPanel` examples now clickable
- https://fireflydev.ipac.caltech.edu/firefly-441-examples/firefly/
- Demonstrates the clickable examples
- Examples are configured in options as described below
- To test
- go to images target panel, it should have the default examples, click on any example
- go to the IRSA tap target panel, it will show examples as described below  
-  go to the NED tap target panel, it will show examples as described below  
- go to a  non-IRSA, non-NED tap target panel, it will show examples as described below
The following options will
- use the default for the images panel (or any non-tap panel)
- set tap panel (except …
> Firefly-441: provide target panel example config and make example clickable

- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/tap/WavelengthPanel.jsx
Fixes [IRSA-6536](https://jira.ipac.caltech.edu/browse/IRSA-6536)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/372
- Generalize wavelength options in a new component that can be used outside obsCore TAP context
- Also tried to standardize names among field keys and slotProps for different subcomponents
- Made EmbeddedPositionSearchPanel to work when only cone and upload is on
- refactored the toggle options generation code since the logic didn't use to account for that case
Do regression testing if Wavelength Panel in ObsCore TAP searches is working as before: https://fireflydev.ipac.caltech.edu/irsa-6536-specphoto-ui/firefly
Do regression testing of EmbeddedSearchPosition Panel in:
- DCE: https://irsa-6536-specphoto-ui.irsakudev.ipac.caltech.edu/irsaviewer
- Euclid: …
> IRSA-6536: SPHEREx Photometry tool job submission UI

- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1652
Reported by NEXSci.
Test: https://fireflydev.ipac.caltech.edu/firefly-1652-heatmap-filtering/firefly/
-> IRSA Catalogs Search -> m31 -> 2000 asec
-> Add a chart(+ icon) -> heatmap -> x=ra y=dec -> Ok
Filter a small section of the heatmap to return fewer than 5000 points. This works correctly in the PR build but fails on irsatest/irsaviewer.
> FIREFLY-1652: Heatmap fails to display data after filtering

- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1649
Reported by Rubin
Test: https://fireflydev.ipac.caltech.edu/firefly-1649-heatmap-nan/firefly/
Upload the sample data file attached in the ticket and observe that NaNs are no longer displayed on the heatmap.
> FIREFLY-1649: NaNs values should not show up in Heatmap

- docker/Dockerfile
- docker/devMode.sh
- docker/entrypoint.py
- docker/entrypoint_test.py
- firefly-docker.env
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1648
This PR addresses several issues and improvements related to environment variable parsing.
The key changes are:
- Resolved issues with escaping special characters during Dockerfile parsing of environment variables.
- Rewritten the old launchTomcat.sh launch script into entrypoint.py, which is now the primary entrypoint for launching Tomcat.
- Add unit test entrypoint_test.py to make testing easier when modifying entrypoint.py
- Expose System Properties in ServerStatus
- Updated Jenkinsscripts to ensure that special characters in env variables are properly escaped
Test via Jenkins + Helm:  https://firefly-1648-envvars-parsing.irsakudev.ipac.caltech.edu/irsaviewer/
This is built with FIREFLY_PROPS=
``` …
```
> FIREFLY-1648: fix Dockerfile parsing envVars bugs

- src/firefly/java/edu/caltech/ipac/firefly/core/RedisService.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/QueryUtil.java
- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/test/edu/caltech/ipac/firefly/core/RedisServiceTest.java
- src/firefly/test/edu/caltech/ipac/firefly/messaging/MessengerTest.java
- src/firefly/test/edu/caltech/ipac/util/cache/CachePeerProviderFactoryTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1654
- Ensure the temp directory exists before returning it.  This was causing download to fail.
- Update Redis to reconnect if not already connected on every use, since it is now a mandatory runtime dependency.
Test: https://firefly-1654-euclid-download-failed.irsakudev.ipac.caltech.edu/applications/euclid/
-> Images Tab -> 1st example coordinate -> Submit
-> Select all rows, then click "Generate Download Script" -> click "Download Script"
The script should successfully download.
> Firefly 1654 euclid download failed

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Fixes [FIREFLY-1511](https://jira.ipac.caltech.edu/browse/FIREFLY-1511)
See rendered version of these 2 markdown docs here: 
- [Code of conduct](https://github.com/Caltech-IPAC/firefly/blob/FIREFLY-1511-coc-guidelines/CODE_OF_CONDUCT.md)
- [Contribution Guidelines](https://github.com/Caltech-IPAC/firefly/blob/FIREFLY-1511-coc-guidelines/CONTRIBUTING.md)
Firefly Code of Conduct (CoC) is adapted from Astropy since every other project seems to be reusing Astropy's CoC. But these projects differ on Contribution guidelines - I adapted those of TARDIS for Firefly, given that we wanted to keep it high-level without delving into technical details which needs a lot more time.
All options that I considered (for inspiration) are:
- Astropy: [CoC](https://www.astropy.org/code_of_conduct.html), …
> FIREFLY-1511: Add Code of conduct and Contribution guidelines

- src/firefly/java/edu/caltech/ipac/firefly/visualize/DirectFitsAccessData.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/PixelValue.java
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- src/firefly/js/visualize/ui/MultiImageViewerView.jsx
Fixes [FIREFLY-1644](https://jira.ipac.caltech.edu/browse/FIREFLY-1644)
- Made server side code treat integer values different than double when formatting base 10 string
- Created getFluxRadix() and fixed MultiImageViewerView.jsx calling primePlot twice
https://firefly-1644-flag-readout-bug.irsakudev.ipac.caltech.edu/applications/spherex
Make a LVF search (without any constraints) -> LVF image result, make sure it's full image -> change HDU to #2(FLAGS):
1. hovering over image should show values in integer (without `.0`)
2. turn on click lock -> click on "Value" -> Radix dialog -> change floating point radix to hexadecimal that shouldn't change value being displayed, but changing integer radix should change it
- also make sure same applies to with click-lock off, and mouse readout popout …
> FIREFLY-1644: Fix Readout values in Flags-extension of the LVF Images

- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/DownloadScriptWorker.java
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/tap/TapSearchSubmit.js
Fixes [IRSA-6572](https://jira.ipac.caltech.edu/browse/IRSA-6572)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/382
- Generalized common code as ScriptTypeOptions component
- Made DataSource in DownloadScriptWorker to be accepted as a param
- Exposed table options in onTapSearchSubmit needed for adding download button in LVF results
https://irsa-6572-download-lvf.irsakudev.ipac.caltech.edu/applications/euclid
Just do regression testing on Euclid downloads
> IRSA-6572: Add "Prepare Download" to download LVF images

- src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- src/firefly/js/voAnalyzer/TableAnalysis.js
Fixes [IRSA-6574](https://jira.ipac.caltech.edu/browse/IRSA-6574)
- search target was not getting extracted from ADQL QUERY string in request for `POINT()` case. Changed regex to capture both `CIRCLE()` and `POINT()`
https://irsa-6574-crosshair-bug.irsakudev.ipac.caltech.edu/applications/spherex
Go to LVF image search, enter coords in ticket: `10:22:19 +41:29:58` and "observation boundary contains point" -> search. In "Data" tab, change view to multi image view and align and lock by WCS. The crosshairs should land on searched coordinates.
Go back to LVF search tab, change to "observation bounary interesects shape", cone shape: 1 degree radius -> search. Again the crosshairs should be on the searched target. 
NOTE: If you go back to LVF search tab, and change to polygon shape and search. …
> IRSA-6574: Misleading crosshairs and positions on images

- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
Fixes [IRSA-6701](https://jira.ipac.caltech.edu/browse/IRSA-6701)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/385
Refactored `SearchSummary` to:
- replace hardcoded strings `{'Cone', 'Polygon', 'Multi-Object'}` with `*_CHOICE_KEY`
- get search type label to display from toggleOptions (in default case)
- accept `getSearchType` in place of `getSummaryInfo` because `searchType.value` and `searchType.label` are the only things that need to be customized (in LVF case), rest all follows default logic to generate key value pairs from these two variables 
- simplify redundant logic and overall cleanup
https://irsa-6701-spherex-search-summary.irsakudev.ipac.caltech.edu/applications/euclid/
Do regression testing in Euclid searches to see if search summary is working as before
> IRSA-6701: LVF image search minimized dialog incorrectly shows polygon search

- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/AnyFileDownload.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
- src/firefly/js/metaConvert/vo/DatalinkFetch.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/ui/dynamic/ServiceDefTools.js
- src/firefly/js/ui/tap/Cutout.js
**Ticket**: [FIREFLY-1662](https://jira.ipac.caltech.edu/browse/FIREFLY-1662)
[IFE PR](https://github.com/IPAC-SW/irsa-ife/pull/383)
- I am mostly looking for feedback in `ObsCorePackager.java`, where support for Cutout Service Descriptors has been added 
- `CutoutServiceDescriptor` logic supports both kinds of service descriptors for cutouts we have come to expect
- 1. Service Descriptors containing an `x-type=circle` entry
- 2. Service Descriptors containing separate input params (ra, dec, size) like the current Euclid ones
- The logic for finding the correct service descriptor (corresponding to the current cutout) among several service descriptors flows largely from our conversations @loitly & @robyww 
- But I have been able to simplify the logic a bit: 
- I am **_not_** explicitly …
> FIREFLY-1662: Support for Cutout Service Descriptor URL generation

- buildScript/webpack.config.js
- src/firefly/js/templates/fireflyviewer/LandingPage.jsx
- src/firefly/js/templates/hydra/HydraViewer.jsx
- src/firefly/js/util/Color.js
Fixes [IRSA-6706](https://jira.ipac.caltech.edu/browse/IRSA-6706), [IRSA-6571](https://jira.ipac.caltech.edu/browse/IRSA-6571)
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/388
- HydraLanding styles change if `bgImage` is supplied by consumers (ife apps) and changes in LandingPage to support that
- Edit webpack config to support `.webp` files (SPHEREx image is available as webp) and to switch to `asset/resource` for large files (background images are large, we don't want them inline)
- Several cleanups:
- `topSection` now accepts `title` (to distinguish from `appTitle`), and `desc` that are used by Hydra apps
- `icon` prop of HydraLanding is never used by `topSection` in any apps but `bottomSection` uses it, so moved it there to avoid confusion and make it easier for consumers to …
> IRSA-6706, IRSA-6571: Add Image on background of Results tab

- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DbMonitor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1683
It turned out this was part of an interval-based cleanup process. As part of that process, we collected statistics from all active databases to determine if cleanup was needed. Although each call was fast, running them sequentially became time-consuming because of the large number of databases. When we switched to parallel processing, an unbounded thread pool was used, which resulted in spawning too many threads.
Solution:
Since cleanup is no longer required with our current database system, I removed that process. However, our admin status page still needs database statistics. I've updated the code so that it only performs the check when needed and limits the process to at most 5 parallel threads.
Test:
- Checkout this PR branch, …
> FIREFLY-1683: prevent excessive thread use

- src/firefly/js/ui/CutoutSizeDialog.jsx
**Euclid test build**: https://euclid-bugfixes.irsakudev.ipac.caltech.edu/applications/euclid
- do any search, then from cutout dialog click on the help icon -> the online help may not be fully updated yet, but the link you go to should end with: `onlinehelp/euclid/#id=visualization.cutout`
> Fix Cutout Dialog Help ID

- src/firefly/js/templates/lightcurve/LcConverterFactory.js
- src/firefly/js/templates/lightcurve/LcManager.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/lightcurve/LcUtil.jsx
View [ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-281) for details. The default time series slider range is set per mission request. 
WISE/NEOWISE: 0.1 - 2
PTF/ZTF:   0.001 - 100 
Other:       0.001 - 365
To test:
https://firefly-281-ts.irsakudev.ipac.caltech.edu/irsaviewer/ts.html
upload attached time series files for WISE, ZTF and Other (attached in [ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-281) ),  do `Period Finder`, inspect slider range setting.
> Firefly-281 set mission slide range value.

- config/app.config
- src/firefly/java/edu/caltech/ipac/astro/net/HorizonsEphPairs.java
- src/firefly/java/edu/caltech/ipac/astro/net/TargetNetwork.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/ResolveServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/rpc/VisServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/ImagePlotCreator.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisJsonSerializer.java
- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/VisServerOps.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebFitsData.java
- src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotResult.java
- src/firefly/java/edu/caltech/ipac/util/CollectionUtil.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/Histogram.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImageData.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/ImagePlot.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsRead.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadFactory.java
- src/firefly/java/edu/caltech/ipac/visualize/plot/plotdata/FitsReadUtil.java
- src/firefly/js/metaConvert/ImageDataProductsUtil.js
- src/firefly/js/visualize/WebPlot.js
- src/firefly/js/visualize/rawData/RawDataOps.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/task/CreateTaskUtil.js
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/extraction/ExtractionChart.jsx
- src/firefly/js/visualize/ui/extraction/ExtractionTable.jsx
- src/firefly/test/edu/caltech/ipac/firefly/server/rpc/ResolveNaifidNameTest.java
- Flip the image in place without memory allocation, this also means the interation is cut in half
- Read fits data during render process, this way the data does not have to be cached. Makes for better GC.
- build large data histogram with threads
- getByteStretchArray now only allows one call at a time per session using semaphores
- radically improving memory managment and not really affecting performance
- Only cache image on second image read.
- This indicates the user is changing stretch or the user has gone back to this image.
- Stretch changes often happen in groups.
- If the user is not changing stretch more moving back and forth then there is not reason to cache the data
- https://firefly-1680-optimize-fits.irsakudev.ipac.caltech.edu/applications/euclid/
- Everything should work …
> Firefly-1680: FITS image optimizations

- src/firefly/js/ui/WavelengthInputField.jsx
- src/firefly/js/ui/tap/WavelengthPanel.jsx
- src/firefly/js/util/Validate.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/VisUtil.js
Fixes [FIREFLY-1653](https://jira.ipac.caltech.edu/browse/FIREFLY-1653)
- Added `WavelengthInputField` and `WavelengthRangeInput` components that can handle units changes and validation
- Updated ObsTAP `WavelengthPanel` to use these components (cleaned up TAP/SIA constraints generation logic because these component handle that already)
- Made floatRange validator accept custom error message
- Now SPHEREx instances can define min max bounds on wavelength as well as initial value and initial unit and the component will handle input validation
See IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/396
https://firefly-1653-wvl-input-component.irsakudev.ipac.caltech.edu/applications/spherex/
Go to LVF search -> **_Uncheck "Location"_** -> "Spectral Coverage" -> select:
- "By Wavelength" and …
> FIREFLY-1653: Create a WavelengthInputField component to handle trailing units

- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/saga/MouseReadoutWatch.js
- src/firefly/js/visualize/ui/MouseReadPopoutAll.jsx
- src/firefly/js/visualize/ui/MouseReadoutBottomLine.jsx
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- https://firefly-1482-bandwidth.irsakudev.ipac.caltech.edu/applications/spherex
- Band width will should up in the bottom mouse readout and the popout mouse readout
- I need feedback as to the most concise, reasonable way to display wavelength and bandwidth. Notice the difference between the popout and the bottom line readout.
> Firefly-1482: implement bandwidth in readout

- src/firefly/html/firefly-dev.html
- src/firefly/js/Firefly.js
- src/firefly/js/api/WebApi.js
- src/firefly/js/api/webApiCommands/LsdbCommands.js
- src/firefly/js/api/webApiCommands/ViewerWebApiCommands.js
- src/firefly/js/ui/DropDownContainer.jsx
- src/firefly/js/visualize/ui/GatorProtocolRootPanel.jsx
- src/firefly/js/visualize/ui/GatorProtocolUtil.jsx
- enter url: https://fireflydev.ipac.caltech.edu/firefly-1702-lsdb/firefly/?api
- You should see the lsdb option towards the bottom.
- enter url: https://fireflydev.ipac.caltech.edu/firefly-1702-lsdb/firefly/?api=lsdb&enable
- the lsdb panel should be enabled
- on the lsdb panel enter the url: https://troyraen.irsakudev.ipac.caltech.edu
- It should populate
- a search should work as well
- enter url: https://fireflydev.ipac.caltech.edu/firefly-1702-lsdb/firefly/
- panel should not be there
> Firefly-1702: Experimental LSDB panel is enabled behind url api option

- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
- src/firefly/js/ui/tap/TimeRangePanel.jsx
- src/firefly/js/ui/tap/WavelengthPanel.jsx
- src/firefly/js/visualize/MouseReadoutCntlr.js
- src/firefly/js/visualize/ui/MouseReadoutUIUtil.js
- src/firefly/js/visualize/ui/WorldPtFormat.jsx
Fixes [IRSA-6747](https://jira.ipac.caltech.edu/browse/IRSA-6747)
See IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/401
- Mostly wording changes
- Make WavelengthOptions more customizable - fixed vs selectable range type, filter definitions label can be changed
- Major change in Search Summary of EmbeddedSearchPositionPanel: instead of key value pairs, it appears as a much shorter string now (no resolver name, and hms or dcm is chosen from HiPS readout preference)
https://irsa-6747-specphot-updates.irsakudev.ipac.caltech.edu/applications/spherex
- Check if all wordings have been changed as per ticket
- Check Spectrophotometry form's wavelength options
- Try all 3 cases (Cone, polygon, multi-object) in LVF search form and collapse the form to check search summary. Similarly check 2 …
> IRSA-6747: Changes in the job-submission UI

- src/firefly/java/edu/caltech/ipac/firefly/server/db/EmbeddedDbUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/PackagingWorker.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/Firefly.js
- src/firefly/js/metaConvert/vo/DatalinkFetch.js
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/ui/DownloadDialog.jsx
**Tickets**: [Firefly-1693](https://jira.ipac.caltech.edu/browse/FIREFLY-1693) and [Firefly-1692](https://jira.ipac.caltech.edu/browse/FIREFLY-1692)
IFE PR: https://github.com/IPAC-SW/irsa-ife/pull/400
- Cleaning up the logic in ObsCorePackager to **_remove_** all custom file naming logic, as this will be handled by both the Download Script and the Zipped Packager, by first looking at Content-Disposition header, and then at the URL path as a fallback
- this keeps our code generic, and lets the service set the name. 
- @robyww suggested maybe keeping some of the file naming convention, @loitly is making a strong case for not doing that with which I agree. We can discuss this further if needed. For now, I am only setting file name (from the `file` column, if available) for cutouts. But we …
> FIREFLY-1693: ObsCore improvements 

- src/firefly/js/api/webApiCommands/LsdbCommands.js
- src/firefly/js/metaConvert/AnalysisUtils.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/ui/Menu.jsx
- src/firefly/js/ui/TargetFeedback.jsx
- src/firefly/js/ui/dynamic/DLGenAnalyzeSearch.js
- src/firefly/js/ui/dynamic/DLGeneratedDropDown.js
- src/firefly/js/ui/dynamic/DLuiServDescPanel.jsx
- src/firefly/js/ui/dynamic/DynComponents.jsx
- src/firefly/js/ui/dynamic/DynamicDef.js
- src/firefly/js/ui/dynamic/DynamicUISearchPanel.jsx
- src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
- src/firefly/js/ui/dynamic/ServiceDefTools.js
- src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
- src/firefly/js/ui/tap/ObsCore.jsx
- src/firefly/js/ui/tap/SiaUI.jsx
- src/firefly/js/ui/tap/SiaUtil.js
- src/firefly/js/ui/tap/WavelengthPanel.jsx
- src/firefly/js/visualize/HiPSUtil.js
- src/firefly/js/visualize/ImagePlotCntlr.js
- src/firefly/js/visualize/ui/multiProduct/MultiProductViewer.jsx
- support sia wavelength
- support dataServiceId
- clean up
- support sia obscore options using ObsCore panel
- improve UI layout
- refactor some of DynComponents
- included ServiceDescriptorPanel in the improvements
- https://rc-2025-3.irsakudev.ipac.caltech.edu/suit/
- get the xml file below
- upload it into the SUIT portal
- The Collection Search tab will open 
- this is an DCE testing tab
- this is only good for one search, to go back you will have to go the the upload panel first
- click on a target in the HiPS
- choose some wavelength bands
- do the search
- 
[more-sia.xml.zip](https://github.com/user-attachments/files/19801386/more-sia.xml.zip)
> Firefly-1469: Update DCE to support rubin needs

- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/db/DuckDbReadable.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/java/edu/caltech/ipac/util/FormatUtil.java
- src/firefly/test/edu/caltech/ipac/util/FormatUtilTest.java
https://jira.ipac.caltech.edu/browse/FIREFLY-1715
- Add better error handling to the status page to ensure it continues rendering even if an error occurs.
- Added unit tests to show what it can detect.
**Note:** Unfortunately, this might produce false positives, since single-column CSV files are easy to match.
We should talk about this to narrow down the number of false positives.
Test:  https://fireflydev.ipac.caltech.edu/firefly-1715-single-col-table/firefly
Try uploading various file types to confirm the issue is resolved and everything still works as expected.
> FIREFLY-1715: Failed to recognize single column CSV file

- src/firefly/js/data/MetaConst.js
- src/firefly/js/drawingLayers/CatalogUI.jsx
- src/firefly/js/ui/CutoutSizeDialog.jsx
- src/firefly/js/ui/DefaultSearchActions.js
- src/firefly/js/ui/tap/DataServicesOptions.js
- [Firefly-1722](https://jira.ipac.caltech.edu/browse/FIREFLY-1722): cutout feedback message in dialog 
- https://firefly-1676-dl-seach-action.irsakudev.ipac.caltech.edu/applications/euclid
- do a search the from the table click on the ![Screenshot 2025-04-25 at 1 15 51 PM](https://github.com/user-attachments/assets/bb905ccd-8e24-40a9-87a8-9bdae58c2b0b)
- The option will be at the top
- for images is should say `'Show table of all Euclid products for Tile ID: <id>`
- for objects it should say `'Show table of all Euclid products for ID: <id>`
> Firefly-1676: improve the titling and position for the 'Show table with all data products' option

- src/firefly/js/drawingLayers/hpx/HpxCatalog.js
- src/firefly/js/metaConvert/ImageDataProductsUtil.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/visualize/PlotAttribute.js
- src/firefly/js/visualize/saga/ActiveRowToImageWatcher.js
- src/firefly/js/visualize/ui/ImageCenterDropDown.jsx
- https://firefly-1725-recenter.irsakudev.ipac.caltech.edu/applications/euclid
- https://firefly-1725-recenter.irsakudev.ipac.caltech.edu/applications/spherex
- do a cutout grid with either application, cutout should not longer scroll off the screen
> Firefly-1725: improve center on selected table row so the data products images are never scrolled off screen

- src/firefly/java/edu/caltech/ipac/firefly/core/background/EmailNotification.java
- src/firefly/java/edu/caltech/ipac/firefly/data/DownloadRequest.java
- src/firefly/java/edu/caltech/ipac/firefly/data/FileInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/data/HttpResultInfo.java
- src/firefly/java/edu/caltech/ipac/firefly/server/packagedata/ZipHandler.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/util/DownloadScript.java
- src/firefly/java/edu/caltech/ipac/util/FileUtil.java
- src/firefly/java/edu/caltech/ipac/util/download/URLDownload.java
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/templates/lightcurve/LcResult.jsx
- src/firefly/js/templates/router/RouteHelper.jsx
- src/firefly/js/ui/DownloadDialog.jsx
- src/firefly/js/ui/WorkspaceSelectPane.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1704
**IFE PR**: https://github.com/IPAC-SW/irsa-ife/pull/403
- Changes to download dialog (merging `Title` and `File Name` fields into one in the UI, and using this value as `BaseFileName` on the backend)
- Added getter/setter for suffix in `FileInfo` (currently used only for cutouts as `-cutout` at the end of a filename before the extension, but could be anything)
- Modified Download Script to handle duplicate file names (especially for curl, as wget does it internally) by roughly using the logic/algorithm described in the ticket
**Testing**: 
-  **CADC** on **Firefly**: https://fireflydev.ipac.caltech.edu/firefly-1704-download-script/firefly
- **Euclid**: https://firefly-1704-download-script.irsakudev.ipac.caltech.edu/applications …
> FIREFLY-1704: Download Script Enhancement

- src/firefly/java/edu/caltech/ipac/firefly/server/query/DecimationProcessor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1686
A regression bug has been identified where Firefly generates an invalid SQL statement when expressions are used in charts that require decimation. This bug was introduced in ticket [FIREFLY-1649](https://jira.ipac.caltech.edu/browse/FIREFLY-1649).
Test: https://fireflydev.ipac.caltech.edu/firefly-1686-invalid-sql-chart/firefly/
Steps to reproduce in Firefly:
Load a table with more than 10,000 rows.
Open the heatmap setting, change X and Y axes to use an expression, such as `log(x)` and `log(y)`
Click Apply
@lrebull At your convenience, please verify that the fix is working.
> FIREFLY-1686: Invalid SQL statement generated when expressions are used in charts requiring decimation.

- src/firefly/java/edu/caltech/ipac/firefly/server/query/ObsCorePackager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/PtfFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/WiseLightCurveFileGroupsProcessor.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/lc/ZtfLCFileGroupsProcessor.java
- src/firefly/js/templates/common/ttFeatureWatchers.js
- src/firefly/js/ui/DownloadDialog.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1731
**IFE PR**:  https://github.com/IPAC-SW/irsa-ife/pull/407 
- The download dialog now only has one checkbox option: `Flattened File Structure`, 
- When selected, we flatten downloaded files , else we default to 'structured' (`folder`) 
- for IFE apps not using ObsCorePackager, their downloads should look the same as before when flattened is selected and when it's turned off (defaulting to structured)
- the logical changes in this PR only affect Obs Core files, for these:
-  flattened will flatten the files, even if you have multiple rows selected
- for 'structured' (folder), which is the default, we only create folders when there's more than one entry in the datalink, if there's only 1 entry per row, we still flatten files 
- I …
> FIREFLY-1731: Download Dialog UI Improvement

- src/firefly/js/metaConvert/AnalysisUtils.js
- src/firefly/js/metaConvert/DataProductsFactory.js
- src/firefly/js/metaConvert/DataProductsType.js
- src/firefly/js/metaConvert/PartAnalyzer.js
- src/firefly/js/metaConvert/UploadAndAnalysis.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/metaConvert/vo/ServDescConverter.js
- src/firefly/js/metaConvert/vo/ServDescProducts.js
- src/firefly/js/ui/dynamic/ServiceDescriptorPanel.jsx
- src/firefly/js/visualize/ui/Buttons.jsx
- src/firefly/js/visualize/ui/multiProduct/DPDropdown.jsx
- src/firefly/js/visualize/ui/multiProduct/MultiProductChoice.jsx
- Make the MultiProductViewer more aggressively call service descriptors if
- is it a non-obscore / catalog table
- call the first one by default
- Clean up the service descriptor panel
- Clean up the service descriptor  toolbar
- Firefly: https://fireflydev.ipac.caltech.edu/firefly-1730-sd-calling/firefly
- goto tap
- choose project `ztf` with the first (default) table
-  results should include a table in the Data Products area
- Rubin portal: https://tag-rc-2025-3.irsakudev.ipac.caltech.edu/suit
- search DP0.2 or DP0.3 catalogs
- results should include a table in the Data Products area
- click ![Screenshot 2025-04-29 at 5 09 31 PM](https://github.com/user-attachments/assets/6d0232b0-b4ab-49c9-8d4b-593c0c3e2d3c) to redo the search, change the band
> Firelfly-1730: MultiProductViewer: more aggressively call Service Descriptors

- src/firefly/java/edu/caltech/ipac/table/io/TableParseHandler.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1711
- Table ingestion create indexes starting from 1 when it should have been from 0
Test: https://firefly-1711-table-ingestion-index-bug.irsakudev.ipac.caltech.edu/irsaviewer
Steps to recreate: 
- goto DCE and choose DIGIT
- 20h23m46.89s +42d12m43.0s Equ J2000
- 200 arcsec
- select first 3 rows and download - 2 results in zip
- select second and third row and download - 2 results in zip (same as above)
- select only first row and download - no results
> FIREFLY-1711: Table ingestion bug

- src/firefly/java/edu/caltech/ipac/firefly/core/RedisService.java
- src/firefly/java/edu/caltech/ipac/firefly/messaging/Messenger.java
- src/firefly/java/edu/caltech/ipac/firefly/server/AppServerCommands.java
- src/firefly/java/edu/caltech/ipac/firefly/server/ServerContext.java
- src/firefly/java/edu/caltech/ipac/firefly/server/events/ServerEventManager.java
- src/firefly/java/edu/caltech/ipac/firefly/server/servlets/ServerStatus.java
- src/firefly/js/Firefly.js
- src/firefly/js/core/AppDataCntlr.js
- src/firefly/js/core/AppDataReducers.js
- src/firefly/js/core/messaging/WebSocketClient.js
- src/firefly/js/templates/common/FireflyLayout.jsx
- src/firefly/js/ui/LostConnection.jsx
- src/firefly/test/edu/caltech/ipac/firefly/core/RedisServiceTest.java
- src/firefly/test/edu/caltech/ipac/firefly/messaging/MessengerTest.java
- src/firefly/test/edu/caltech/ipac/util/cache/CachePeerProviderFactoryTest.java
- src/firefly/test/edu/caltech/ipac/util/cache/CacheTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1727
- Try to reconnect until Redis is back online
- Show error status to client
- Show status in ServerStatus page
- Refactor LostConnection.jsx component to use JoyUI
Test:  https://fireflydev.ipac.caltech.edu/firefly-1727-handle-redis-failure/firefly/
It's a bit harder to test.  To simulate Redis down, I've deployed this instance with 2 replicas.  
- You can find and delete the Redis pod to see that Firefly can recover from a redis restart.
- You can find and edit the Redis deployment so that i cannot start back up to see what happen when it's down for a long time.
- Both requires kubectl access.
Locally: 
- You can see the LostConnection.jsx when you shutdown tomcat
- Find redis process, then kill it and you will see it's got …
> FIREFLY-1727: Handle Redis failure

- src/firefly/java/edu/caltech/ipac/table/io/VoTableReader.java
- src/firefly/js/ui/FileUploadProcessor.jsx
- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
Fixes [FIREFLY-1695](https://jira.ipac.caltech.edu/browse/FIREFLY-1695)
- onSubmit of UploadTableChooser (used in Multi-object fields) now uses `determineValidity` like FileUploadPanel's onSubmit, that shows an error popup if invalid
- FileUploadPanel was maintaining a `message` state besides `report` but wasn't using it in generating invalidation popup, now made it do so by registering in `request.additionalParams` and passing it to `determineValidity`.
- Made `message` state to read `FileAnalysis.ErrorResponse` description from server-side for showing more specific error messages.
https://fireflydev.ipac.caltech.edu/firefly-1695-upload-error-msg/firefly/
Go to "Upload" tab -> Upload the bad table file in ticket -> click "load" button, the error popup should show VOTable parsing error …
> FIREFLY-1695: Display error message when upload table can't be read

- src/firefly/js/tables/TablesCntlr.js
- src/firefly/js/tables/reducer/TableUiReducer.js
- src/firefly/js/tables/ui/BasicTableView.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1729
- should behave the same for both client and server backed table.
Test: https://fireflydev.ipac.caltech.edu/firefly-1729-table-reload-column-resize/firefly/
- Images -> M81; WISE -> Search
- Image Toolbar -> Show FITS header 'i' icon
- Scroll to the bottom of the table, then resize a column.  Scroll position should remain the same.
> FIREFLY-1729: Client tables reset scroll on column width change

- src/firefly/js/drawingLayers/SelectArea.js
- src/firefly/js/drawingLayers/hpx/HpxCatalog.js
- src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
- [Firefly-1734](https://jira.ipac.caltech.edu/browse/FIREFLY-1734): fixed: filtering not working for some very small selections
- [Firefly-1164](https://jira.ipac.caltech.edu/browse/FIREFLY-1164): turn off selection when projection changes
- [IRSA-6890](https://jira.ipac.caltech.edu/browse/IRSA-6890): catalog scrolling on center change
- https://fireflydev.ipac.caltech.edu/firefly-1734-filtering/firefly
- Test [Firefly-1734](https://jira.ipac.caltech.edu/browse/FIREFLY-1734) according to the ticket.
- Test [Firefly-1164](https://jira.ipac.caltech.edu/browse/FIREFLY-1164): selection will turn off when HiPS is flipped between galactic and eq 
- Test [IRSA-6890](https://jira.ipac.caltech.edu/browse/IRSA-6890) according to the ticket.
> Firefly-1164,1734: multiple tickets

- src/firefly/java/edu/caltech/ipac/firefly/server/db/BaseDbAdapter.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/EmbeddedDbProcessor.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1721
- remove use of backgrounding enumeratedValuesCheck to avoid race condition
Test:  https://fireflydev.ipac.caltech.edu/firefly-1721-added-col-go-away/firefly/
- load any table
- add a column (a -> 1)
- impose a filter to any column, e.g. "> 0"
- add another column (b -> 2)
- cancel the filters
2nd column **SHOULD NOT** goes away.
Also fixed drop-down column filter not appearing for large tables.
- TAP => CACD => choose Use Image Search (ObsTAP) => m81 -> Search
Drop-down filter option should appear for `dataproduct_type` column
> FIREFLY-1721: fixed added columns go away

- src/firefly/java/edu/caltech/ipac/firefly/server/visualize/DirectStretchUtils.java
- src/firefly/js/metaConvert/vo/DataLinkProcessor.js
- src/firefly/js/metaConvert/vo/DatalinkProducts.js
- src/firefly/js/metaConvert/vo/ObsCoreConverter.js
- src/firefly/js/visualize/PlotViewUtil.js
- src/firefly/js/visualize/ui/ColorBandPanel.jsx
- src/firefly/js/visualize/ui/ColorDialog.jsx
- src/firefly/js/visualize/ui/ColorPanelReducer.js
- src/firefly/js/visualize/ui/ColorRGBHuePreservingPanel.jsx
- src/firefly/js/visualize/ui/ColorTableDropDownView.jsx
- src/firefly/js/visualize/ui/StretchDropDownView.jsx
- src/firefly/js/voAnalyzer/VoDataLinkServDef.js
- [Firefly-1740](https://jira.ipac.caltech.edu/browse/FIREFLY-1740): done
- [Firefly-48](https://jira.ipac.caltech.edu/browse/FIREFLY-48): done
- Fixes bug: an issue `Hue preserving stretch`. Scaling coefficients not working
- Changes `Hue preserving stretch` change  to only work with refresh button like the rest of the panel
- A little clean on datalink related processing
- https://fireflydev.ipac.caltech.edu/firefly-1740-color/firefly
- [Firefly-1740](https://jira.ipac.caltech.edu/browse/FIREFLY-1740): `color,strech,and otherlay` lock button is in both color and stretch dropdown. And it color and stretch dialog
- [Firefly-48](https://jira.ipac.caltech.edu/browse/FIREFLY-48): no bounds checking on lower/upper range in data mode
- `Hue preserving stretch` Scaling coefficients now work: …
> Firefly-1740,48: clean up the color,strech,and otherlay sync button and add to other places

- src/firefly/js/core/background/BackgroundUtil.js
- src/firefly/js/core/background/JobInfo.jsx
- src/firefly/js/core/core-typedefs.jsdoc
- src/firefly/js/tables/ui/TableInfo.jsx
- src/firefly/js/ui/CssStrThemeWrapper.jsx
- src/firefly/js/ui/tap/AdvancedADQL.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1327
Implemented as described in the ticket, with two exceptions:
- Owner has been moved to the bottom section to provide a clearer separation between the top and bottom.
- The default proportional font is used, so the dates are not perfectly aligned as shown in the ticket. Would you like me to switch all values to a monospaced font for better alignment?  But, this will cause the dialog's font to deviate from the rest of the application.
Test: https://fireflydev.ipac.caltech.edu/firefly-1327-jobinfo-dialog/firefly/
Submit a few TAP or IRSA Catalog searches, then go to `Job Monitor` and click the Job Info (i-icon) to view details.
> FIREFLY-1327: Update job info dialog

- src/firefly/js/drawingLayers/hpx/HpxCatalogUtil.js
- https://fireflydev.ipac.caltech.edu/firefly-1739-filtering/firefly
- search two or three catalogs
- do a selection that does not include any - you should get a warning
- do a selection that just covers some
- you should get a warning
- the covered tables will be filtered
- the non-covered tables will be filtered to zero rows
> Firefly-1739: better handle table filtering when nothing is selected

- src/firefly/js/core/background/JobInfo.jsx
- Also added a `Box` around the ADQL display
- https://fireflydev.ipac.caltech.edu/firefly-1745-job-info/firefly
- make 2 or three jobs
- go to Job Monitor
- click on `i` and move/resize the dialog
- click on other rows. the dialog should stay in place.
> Firefly-1745: Job info size and position stays the same as the use clicks around

- src/firefly/java/edu/caltech/ipac/firefly/server/query/tables/IpacTableFromSource.java
- src/firefly/java/edu/caltech/ipac/table/TableMeta.java
- src/firefly/js/tables/TableUtil.js
- src/firefly/js/tables/ui/TableRenderer.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1749
The recently added HTML sanitizer is removing features that are currently supported
**Solution**
Introduce a `data_origin` in the table metadata to indicate whether a table is externally sourced.
Apply HTML sanitization only to externally sourced table data.
Internally generated tables will bypass the sanitizer, retaining all supported features.
Test: https://firefly-1749-sanitize-external-table.irsakudev.ipac.caltech.edu/
- Search for Source: enter 'm31' -> click Search
Click on both `To IRSAViewer` and `To WISE Image Service` should open a new browser tab/window.
> FIREFLY-1749: HTML sanitizer removes supported features

- src/firefly/js/tables/FilterInfo.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1265
- added support for NOT IN as well.
From ticket:
> There's a bug in table's column filtering.  Using NOT LIKE just results in the 'not' being dropped. i.e. "NOT LIKE Kepler" , after hitting enter, becomes "like '%Kepler%'".
> 
> NOT LIKE is standard SQL and should be supported.  The bug is probably a result of 'auto correct' in FilterInfo.
> 
To test:  https://fireflydev.ipac.caltech.edu/firefly-1265-filter-not-like/firefly
- Load any table
- In a string column, enter 'not like [anything]', then 'Enter' or tab away
- It should work and not report an error.
> FIREFLY-1265: Table column filter misinterpret 'NOT LIKE'.

- src/firefly/js/charts/ui/options/BasicOptions.jsx
View [ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-1753) for details.
To test:
Euclid: https://firefly-1753-euclid-xyratio.irsakudev.ipac.caltech.edu/applications/euclid
- do Search by ID = -606624697489151697
- in spectrum view, click on option gear and expand Chart Options, enter an X/Y ratio, the Stretch to: height and width selection will appear below the X/Y ration input
SHA: https://firefly-1753-sha-xyration.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
- do position search for PBCD, m51
- in the result table apply filter with `File Type` as "Table", in spectrum view, try enter X/Y ratio.
> FIREFLY-1753: Fix Charts X/Y Ratio ui cutting off problem

- src/firefly/js/core/background/BgMaskPanel.jsx
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1752
To reproduce: see ticket
Solution: disable button until JobInfo is available to avoid race condition
To test: 
https://firefly-1752-sendto-background-click-twice.irsakudev.ipac.caltech.edu/irsaviewer/
- Catalogs Search -> Send to background 
https://firefly-1752-sendto-background-click-twice.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
- Search by Position -> select first AOR -> Prepare Download 
- Select Level 2 -> click Prepare Download -> Send to background
In both cases, it should work as expected.
> FIREFLY-1752: Send to background requires 2 clicks

- src/firefly/js/api/WebApi.js
- src/firefly/js/api/webApiCommands/TapCommands.js
- src/firefly/js/ui/CatalogSearchMethodType.jsx
- src/firefly/js/ui/CompleteButton.jsx
- src/firefly/js/ui/SearchPanel.jsx
- src/firefly/js/ui/tap/ObsCoreExposureDuration.jsx
- src/firefly/js/ui/tap/SpatialSearch.jsx
- src/firefly/js/ui/tap/TableSearchHelpers.jsx
- src/firefly/js/ui/tap/TapSearchRootPanel.jsx
- src/firefly/js/ui/tap/TapSearchSubmit.js
- src/firefly/js/ui/tap/WavelengthPanel.jsx
Fixes [FIREFLY-1703](https://jira.ipac.caltech.edu/browse/FIREFLY-1703)
* Exposed polygon input as `polygon` parameter and updated `PolygonDataArea` component to accept an `initValue`
* Exposed spatial region operations in ObsTAP (`contains_point`, `intersects`, etc.) as `spatialRegionOperation` parameter 
* Made it possible for url api to control panel active states - needed when executing the search but the constraint panel doesn't expand and get checked
* Deprecated the `obsCoreWavelengthUnits` parameter, defaulting it to a base unit because `WavelengthInputField` has evolved since its URL api was written
See ife PR: https://github.com/IPAC-SW/irsa-ife/pull/415
* Added url API for SPHEREx LVF, **reusing** TAP's API wherever possible
* Added a one-time auto-search logic to automatically …
> FIREFLY-1703: SPHEREx: support URL API

- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobManager.java
- src/firefly/java/edu/caltech/ipac/firefly/core/background/JobUtil.java
- src/firefly/java/edu/caltech/ipac/firefly/server/query/SearchServerCommands.java
- src/firefly/js/core/background/JobMonitor.jsx
- src/firefly/js/rpc/SearchServicesJson.js
- src/firefly/js/tables/TableRequestUtil.js
- src/firefly/js/templates/router/RouteHelper.jsx
- src/firefly/js/templates/router/RoutedApp.jsx
- src/firefly/js/ui/FormPanel.jsx
- src/firefly/js/ui/tap/TapSearchSubmit.js
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1757
**Additional changes here**:  https://github.com/IPAC-SW/irsa-ife/pull/419
- Fixed: Load Euclid and SPHEREx results from Job Monitor
- Fixed: Job Monitor tab not always working correctly
- Minor: Refactored RoutedApp
- Fixed: Job deletion not persisting as expected
**Euclid:** https://firefly-1757-routed-load-results.irsakudev.ipac.caltech.edu/applications/euclid/
_** Note: Only background-able searches are saved as jobs; for Euclid, this means "Euclid Catalogs" only._
@robyww @kpuriIpac Should we make Euclid primary searches 'background-able' so that it becomes `jobs`?
- Go to `Euclid Catalogs` -> 267 65 -> click `Search`
- Open the `Job Monitor` tab; confirm your job appears and is marked `COMPLETED`.
- Reload the browser — you …
> FIREFLY-1757: Load Euclid and SPHEREx results from Job Monitor

- src/firefly/js/visualize/task/PlotHipsTask.js
####[ Firefly-1667](https://jira.ipac.caltech.edu/browse/FIREFLY-1667): when HiPS is changed, the associated MOC is added to the drawing layers
- _Note:_ MOCs are always added not replaced
- https://fireflydev.ipac.caltech.edu/firefly-1667-moc-adding/firefly
- Be aware the the MOCs are only added not replaced.  The user can always delete a MOC
> Firefly-1667: when HiPS is changed, the associated MOC is added

- src/firefly/js/ui/UploadTableChooser.js
- src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
**Ticket**: https://jira.ipac.caltech.edu/browse/FIREFLY-1771
- fixes the above ticket
- add a loading animation for bigger tables (similar to the one on the upload tab) 
**Testing**: 
**Euclid**: https://firefly-1771-row-mismatch.irsakudev.ipac.caltech.edu/applications/euclid
- test Euclid Catalogs according to ticket
- here's what I did: 
- Select the following catalog & search: `euclid_q1_spectro_zcatalog_spe_galaxy_candidates`
- Back on Euclid Catalogs, now select: `euclid_q1_phz_photo_z`, but don't click on Search
- Now under `Object ID search`, select `Load object IDs from a table` and select the first table you searched for from the `Loaded Tables` tab
- For both the ID columns, select `object_id`
- Do a search. You should get back several thousand rows (50,000  if you never …
> FIREFLY-1771: Fix Existing Table Load missing rows

- src/firefly/java/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessor.java
- src/firefly/java/edu/caltech/ipac/table/ResourceInfo.java
- src/firefly/test/edu/caltech/ipac/firefly/server/persistence/MultiSpectrumProcessorTest.java
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1765
Support Non-Array columns and service descriptor conversion in MultiSpectrum array-data files.
Test:  https://fireflydev.ipac.caltech.edu/firefly-1765-multispectrum-extract/firefly/
- Upload the test table attached in the ticket.  It has the added `ra/dec` columns.
- Verify that columns ra and dec appear in the extracted table under the Data Product tab.
- Note: The service descriptor is not visible in the UI. This is a known issue (see FIREFLY-1563).
However, the code to copy over the service descriptor is added and working.
You can verify this by running the MultiSpectrumProcessorTest, which checks that the RESOURCE is properly copied over.
> FIREFLY-1765: Allow non-array type columns
